const barugChapters = [

{
book: 'Barug',
chapter: '1',
content: [

"	1 EN dit is die woorde van die Boekrol wat Barug, die seun van NeriJaH, die seun van MagséJaH, die seun van SedekiJaHûW, die seun van HasádJaH, die seun van HilkíJaH[ûW], in Babel geskryf het.	",
"	2 In die vyfde jaar, op die sewende dag van dieselfde maand waarin die Chaldeërs Jerusalem ingeneem en deur vuur verbrand het,	",
"	3 het Barug die woorde van hierdie Boekrol voorgelees ten aanhore van JekónJaH, die seun van JeHôWjakim, die koning van JeHûWdah, en ten aanhore van al die volk wat na die lees van die Boekrol gekom het,	",
"	4 en ten aanhore van die vorste en die owerstes en die oudstes en van die hele volk, groot en klein, wat in Babel by die Soedrivier woon.	",
"	5 En hulle het geween en gevas en gebid voor die Aangesig van JaHWeH,	",
"	6 en ooreenkomstig elkeen se vermoë het hulle geld versamel	",
"	7 en dit na Jerusalem gestuur - na die priester JeHôWjakim, die seun van HilkíJaH[ûW], die seun van Sallum, en na die priesters en al die volk wat saam met hom in Jerusalem gewoon het.	",
"	8 Hulle het dit gegee, nadat hy die toerusting wat uit die Huis van JaHWeH geroof is, op die tiende dag van die maand Siwan ontvang het, om dit na die Aarde van JeHûWdah terug te bring - dit is die silwer toerusting wat SedekíJaHûW, die seun van koning JoshiJaHûW van JeHûWdah, gemaak het,	",
"	9 nadat Nebukadnésar, die koning van Babel, JekónJaH en die vorste en die smede en die magtiges en die hele bevolking van die Aarde uit Jerusalem weggeneem en na Babel weggevoer het.	",
"	10 En hulle het gesê: Kyk, ons stuur geld na julle; koop vir die geld brandoffers en versoeningsbydraes en wierook, en berei spysbydraes; en slag op die altaar van JaHWeH onse Elohey.	",
"	11 Bid vir die welsyn van Nebukadnésar, die koning van Babel, en vir die welsyn van sy seun Béltsasar, dat hulle dae op Aarde so lank mag wees soos die dae van die Hemele.	",
"	12 Dat JaHWeH ons Krag mag gee en Lig aan ons oë, sodat ons kan lewe in die skaduwee van Nebukadnésar, die koning van Babel, en in die skaduwee van sy seun Bélsasar; dat ons hulle in lengte van dae sal dien, en dat ons barmhartigheid sal vind voor hulle aangesig.	",
"	13 Bid vir ons ook tot JaHWeH onse Elohey, omdat ons teen JaHWeH onse Elohey oortree het en Sy Woede en Grimmigheid tot vandag nie van ons afgewend is nie.	",
"	14 En lees hierdie Boekrol, wat ons na julle stuur om haar in die Huis van JaHWeH voor te lees op die feesdag en op geskikte dae.	",
		
		
"	15 JULLE sal sê: Aan JaHWeH onse Elohey kom die Geregtigheid toe maar aan ons die beskaming van die aangesig, soos dit vandag is aan die hele JeHûWdah en aan die inwoners van Jerusalem	",
"	16 en aan ons konings, ons owerstes, ons priesters, ons profete en ons vaders.	",
"	17 Ons het oortree teenoor JaHWeH onse Elohey.	",
"	18 Ons het Hom nie gehoorsaam nie, en ons het nie geluister na die Stem van JaHWeH onse Elohey om te handel in die Wet wat Hy ons gegee het nie.	",
"	19 Vanaf die dag waarop JaHWeH ons vaders uit die Aarde van Egipte gelei het, tot vandag toe was ons voortdurend ongehoorsaam aan JaHWeH onse Elohey en het ons ligsinnig afgewyk om nie Sy Stem te hoor nie.	",
"	20 Aan ons kleef die besoedeling en die vloek wat JaHWeH deur Sy dienskneg Moshè verorden het op die dag waarop Hy ons vaders uit die Aarde van Egipte gelei het, om ons ‘n Adamah [die adamiet se Aarde] te gee wat oorloop van melk en heuning soos sy vandag is.	",
"	21 Maar ons het nie geluister na die Stem van JaHWeH onse Elohey, ondanks al die woorde van die profete wat Hy na ons gestuur het nie.	",
"	22 En ons het afgewyk, elkeen ooreenkomstig die gesindheid van sy besoedelde hart, om gode van vermenging te dien en te oortree voor die Aangesig van JaHWeH onse Elohey.	",

]
},
{
book: 'Barug',
chapter: '2',
content: [
	
"	1 DAAROM het JaHWeH Sy Woord in vervulling laat gaan wat Hy oor ons gespreek het en oor ons rigters, wat JisraEl geregeer het, en oor ons konings, ons vorste en die hele JisraEl en JeHûWdah:	",
"	2 Dat Hy groot besoedeling oor ons bring wat onder die ganse Hemele nie gebeur het soos in Jerusalem nie; dat, soos in die Wet van Moshè geskryf is,	",
"	3 elkeen van ons die vlees van sy seun en die vlees van sy dogter sal eet.	",
"	4 Hy het hulle oorgelewer in die mag van al die koninkryke wat ons omring, om ‘n voorwerp van spot en vervloeking te wees by al die omringende nasies, waaronder JaHWeH hulle verstrooi het.	",
"	5 Hulle het laer afgesak en nie hoër opgeklim nie, omdat ons oortree het teen JaHWeH onse Elohey deur nie te luister na Sy Stem nie.	",
"	6 Aan JaHWeH onse Elohey kom die Geregtigheid toe maar aan ons en aan ons vaders die beskaming van die aangesigte, soos dit vandag is.	",
"	7 JaHWeH het ons gedreig met al daardie besoedeling wat oor ons gekom het.	",
"	8 En ons het die Aangesig van JaHWeH nie gesoek deur ons almal te bekeer van die neigings van ons besoedelde hart nie.	",
"	9 Daarom was JaHWeH wakker oor die besoedeling om dit oor ons te bring; want JaHWeH is regverdig by al Sy werke wat Hy ons gebied.	",
"	10 Maar ons het nie na Sy Stem geluister om te wandel in die Wet van JaHWeH, wat Hy ons voorgehou het nie.	",
		
		
"	11 NOU dan, JaHWeH, die Elohey van JisraEl, wat U volk uit die Aarde van Egipte gelei het met ‘n Sterke Hand en met tekens, wonders en ‘n groot Krag en met ‘n Uitgestrekte Arm; wat vir Uself ‘n Naam gevestig het soos Hy vandag is! [Profesie van Barug 3:5]	",
"	12 Ons het oortree, ons was wetteloos, ons het verkeerd gedoen, JaHWeH onse Elohey, teen al U Gebooie.	",
"	13 Laat U Woede afgewend word van ons, want min van ons het oorgebly onder die nasies waarheen U ons verstrooi het.	",
"	14 Luister, JaHWeH, na ons gebed en ons smeking: lei ons uit om U ontwil, en laat ons Barmhartigheid vind voor die aangesig van diegene wat ons weggevoer het;	",
"	15 sodat die hele Aarde sal weet dat U JaHWeH onse Elohey is, en dat U Naam uitgeroep is oor JisraEl en sy nageslag.	",
"	16 JaHWeH, kyk neer van U Woning van U Apartheid, en gedenk ons. Neig U oor, JaHWeH, en hoor!	",
"	17 Open U Oë, o JaHWeH, en aanskou! Want nie die gestorwenes in die Doderyk/Sheol, wie se gees uit hulle binnenste weggeneem is, sal JaHWeH loof en verhoog nie,	",
"	18 maar die siel wat diep bedroef is; hy wat neergebuig gaan en swak is; die oë wat smag; die siel wat honger. Hulle loof en verhoog U, JaHWeH.	",
"	19 En ons, ons smeek U nie om U oor ons te ontferm vanweë die Geregtigheid van ons vaders en ons konings nie, JaHWeH onse Elohey,	",
"	20 maar vanweë U Woede en U Grimmigheid oor ons, ooreenkomstig die woorde wat U deur U diensknegte, die profete, gespreek het:	",
"	21 So spreek JaHWeH: Buig julle skouers, en dien die koning van Babel; dan sal julle in die Adamah [die adamiet se Aarde] bly wat Ek aan julle vaders gegee het;	",
"	22 maar as julle nie luister na die Stem van JaHWeH om die koning van Babel te dien nie,	",
"	23 dan laat Ek uit die stede van JeHûWdah en uit die omgewing van Jerusalem verdwyn die stem van Vreugde en die stem van Blydskap, die stem van die bruidegom en die stem van die bruid; en die hele Aarde sal ‘n woesteny sonder bewoners wees.	",
"	24 Maar ons het nie geluister na U Stem om die koning van Babel te dien nie; en U het U woorde in vervulling laat gaan, wat U deur U diensknegte die profete gespreek het: dat die bene van ons konings en die bene van ons vaders uit hulle grafte sou uitgehaal word.	",
"	25 En kyk, hulle is blootgestel aan die warmte van die dag en aan die koue van die nag. En hulle het gesterf in die vreeslikste smarte, deur die honger, deur die swaard en die pes.	",
"	26 En die Huis waaroor U Naam uitgeroep is, het U gemaak soos Hy vandag is vanweë die skuld van ongeregtigheid van die huis van JisraEl en van die huis van JeHûWdah.	",
"	27 U het met ons gemaak, JaHWeH onse Elohey, ooreenkomstig die volheid van U Geregtigheid en die volheid van U groot Medelye,	",
"	28 soos U gespreek het deur U dienskneg Moshè op die dag toe U hom gebied het om U Wet op te skryf voor die kinders van JisraEl:	",
"	29 Wanneer julle nie na My Stem luister nie, sal hierdie groot en talryke menigte, die minste word van die volke waaronder Ek hulle sal verstrooi;	",
"	30 want Ek weet dat hulle nie na My sal luister nie, omdat die volk se nek verhard is. Maar in die Aarde van hulle ballingskap sal hulle tot bekering kom,	",
"	31 en hulle sal erken dat Ek JaHWeH, hulle Elohey is. Dan sal Ek hulle ‘n hart gee en ore wat verstaan,	",
"	32 en hulle sal My loof in die Aarde van hulle ballingskap en My Naam indagtig wees.	",
"	33 Hulle sal hulle bekeer van hulle hardnekkigheid en van hulle besoedelde werke, want hulle sal dink aan die pad van hulle vaders, wat teen JaHWeH oortree het.	",
"	34 Dan sal Ek hulle laat terugkeer na die Adamah [die adamiet se Aarde] wat Ek met ‘n eed beloof het aan hulle vaders Abraham, Isak en Jakob, en hulle sal haar besit. En Ek sal hulle vermeerder, en hulle sal nooit minder word nie.	",
"	35 Ook sal Ek ‘n ewige Verbond met hulle sluit, sodat Ek hulle Elohey en hulle My volk sal wees; en Ek sal My volk JisraEl nie meer wegvoer uit die Adamah [die adamiet se Aarde] wat Ek aan hulle gegee het nie.	",

]
},
{
book: 'Barug',
chapter: '3',
content: [
		
"	1 ALMAGTIGE JaHWeH, die Elohey van JisraEl, ‘n gebroke gees en ‘n verslae siel roep U aan.	",
"	2 Hoor, JaHWeH, en ontferm U, want ons het oortree teen U.	",
"	3 Omdat U sit tot in ewigheid, sal ons dan verwerp wees tot in ewigheid?	",
"	4 Almagtige JaHWeH, die Elohey van JisraEl, hoor die smeekbede van die gestorwenes van JisraEl en van die kinders van hulle wat teen U oortree het en wat nie na die Stem van JaHWeH hulle Elohey geluister het nie. Die besoedeling kleef aan ons.	",
"	5 Wees nie die oortredinge van ons vaders indagtig nie, maar dink in hierdie tyd aan U Mag en U Naam. [Profesie van Barug 2:11]	",
"	6 U is JaHWeH onse Elohey, en ons sal U loof, JaHWeH.	",
"	7 Want U het juis daarom die Vrees vir U in ons hart gelê dat ons U Naam sou aanroep; en ons prys U in ons ballingskap, omdat ons ons afgewend het van die ongeregtigheid van ons vaders, wat teen U oortree het.	",
"	8 Kyk, vandag is ons in die ballingskap waarin U ons verstrooi het tot ‘n skande en vloek en boete vanweë al die oortredinge van ons vaders, wat afgewyk het van JaHWeH onse Elohey.	",
		
		
"	9 HOOR, JisraEl, die Gebooie van die lewe; luister om die Wysheid te ken.	",
"	10 Waarom is dit, JisraEl, dat jy in die Aarde van die vyande is? Dat jy oud geword het in ‘n vreemde deel van die Aarde?	",
"	11 Waarom is jy besoedel soos lyke? Waarom word jy gereken onder hulle wat neergedaal het in die Doderyk/Sheol?	",
"	12 Jy het die Fontein van die Wysheid verlaat.	",
"	13 Wanneer jy sou gewandel het op die Weg van Elohim, dan sou jy in Vrede gewoon het tot in ewigheid. [Psalm 18:30]	",
"	14 Leer waar Wysheid is en waar Krag is en waar tegelyk die Verstand is om te weet waar lengte van lewe en lewensonderhoud is, en waar Lig van die Oë en Vrede is.	",
"	15 Wie het die Wysheid se plek gevind? En wie het in Haar skatkamers binne gegaan? [Job 28:12]	",
"	16 Waar is die vorste van die nasies, en waar is die wat oor die wilde diere van die Aarde heers?	",
"	17 Waar is die wat met die voëls van die Hemele speel? Waar is die wat die goud en silwer waarop die mense vertrou, opspaar en wat nie ophou met soek na besit nie?	",
"	18 Waar is die wat die silwer smeed en met sorg bewerk, en wie se werkstukke onnavolgbaar is?	",
"	19 Hulle het verdwyn en neergedaal in die Doderyk/Sheol; en ander het hulle plekke ingeneem.	",
"	20 ‘n Jonger geslag het die Lig gesien en op die Aarde gewoon, maar hulle het die Weg van die Wysheid nie geken nie;	",
"	21 hulle was ook nie op Haar Paaie nie en het Haar nie gekry nie; en hulle kinders het ver gebly van die Weg. [Psalm 18:30]	",
"	22 In Kanaän hoor ‘n mens nie van Haar nie, en in Teman is Sy ook nie gesien nie.	",
"	23 Die seuns van Hagar wat die Kennis op die Aarde soek, en die koopmans van Merra en Teman, en die fabeldigters en die soekers van Insig - hulle het die Weg van die Wysheid nie geken nie, en hulle het geen wete gehad van Haar Paaie nie.	",
"	24 o JisraEl, hoe groot is die Huis van Elohim en hoe wyd die plek van Sy besit!	",
"	25 Hy is groot en Hy het geen einde nie; Hy is hoog en onmeetbaar.	",
"	26 Daar was die reuse, die manne van naam van die ou tyd, wat baie groot was en ervare in die stryd.	",
"	27 Maar JaHWeH het hulle nie uitverkies nie en aan hulle nie die Weg van die Wysheid gegee nie;	",
"	28 en hulle het omgekom, omdat hulle nie die Wysheid besit het nie; hulle het omgekom vanweë hulle onbedagsaamheid.	",
		
		
"	29 WIE het opgeklim na die Hemele en Haar gekry en saamgebring uit die Wolkkolom?	",
"	30 Wie het oorgevaar na die ander kant van die see en Haar gevind en Haar vir uitgesoekte goud gekoop?	",
"	31 Daar is niemand wat die Weg van die Wysheid ken of wete het van Haar Paaie nie.	",
"	32 Maar Hy wat alles weet, ken Haar; Hy het Haar gevind deur Sy eie Insig. Hy wat die Aarde in die eindelose tyd toeberei het, Hy het haar ook volgemaak met viervoetige diere.	",
"	33 Hy stuur die Lig, en Sy gaan; Hy roep Haar, en Sy gehoorsaam en sidder vir Hom.	",
"	34 Die Sterre straal op hulle wagposte en jubel;	",
"	35 Hy roep Hulle, en Hulle sê: Hier is Ons. En met vreugde straal Hulle vir Hulle Maker.	",
"	36 Hy is Onse Elohey; geen ander is aan Hom gelyk nie.	",
"	37 Hy het die hele Weg van die Wysheid ontdek, en Hy het Haar meegedeel aan Sy dienskneg Jakob en aan JisraEl, wat Hy liefhet.	",
"	38 Daarna is Sy gesien op die Aarde, en Sy het met die adamiete omgegaan. [Wysheid van Sirah 24:8]	",

]
},
{
book: 'Barug',
chapter: '4',
content: [
		
"	1 DIT is die Boekrol van JaHWeH se Gebooie en die Wet wat tot in ewigheid is. Almal wat Haar aanneem, sal lewe; maar die wat Haar verlaat, sal sterf.	",
"	2 Bekeer jou, Jakob, en aanvaar Haar; wandel in die Glans van Haar Lig.	",
"	3 Moenie jou Glansrykheid aan ‘n verbasterde gee nie; en moenie Haar wat vir jou voordelig is, aan ‘n ander nasie gee nie.	",
"	4 Welgeseënd is ons, JisraEl, dat die dinge wat aan JaHWeH welgevallig is, aan ons bekend is.	",
		
		
"	5 HOU goeie moed, My volk! JisraEl, onthou!	",
"	6 Julle is verkoop aan die nasies, maar julle sal nie omkom nie, want julle is aan die vyande uitgelewer omdat julle Elohey vertoorn het.	",
"	7 Want julle het julle Maker verbitter deurdat julle aan duiwels bydraes gebring het en nie aan Elohim nie.	",
"	8 Julle het die Ewige El vergeet wat julle gevoed het; julle het Jerusalem, wat julle gevoed het, bedroef gemaak. [Hooglied van Salomo 1:5]	",
"	9 Want Sy het die Woede van Elohim oor julle sien kom en gesê: Hoor, inwoners van Sion, want JaHWeH het groot rou oor My gebring.	",
"	10 Ek het die gevangenskap aanskou van My seuns en dogters, en die Ewige het dit aan hulle gedoen.	",
"	11 Met Vreugde het Ek hulle gevoed; met geween en rou het Ek hulle laat gaan.	",
"	12 Laat niemand hom vrolik maak oor My, die Weduwee wat deur baie verlaat is; Ek is eensaam vanweë die oortredinge van My kinders, want hulle het afgewyk van die Wet van JaHWeH, [Psalm 60:1; 2 Ezra 2:2]	",
"	13 Hulle het Sy regte misken en nie gewandel op die Weg van JaHWeH se Gebooie nie en nie in Geregtigheid die Paaie van Sy Onderrig gevolg nie.	",
"	14 Inwoners van Sion, kom en gedenk die gevangenskap van My seuns en dogters, wat die Ewige oor hulle gebring het.	",
"	15 Van ver af het Hy oor hulle ‘n nasie laat kom - ‘n onbarmhartige nasie met ‘n vreemde taal, wat nie ‘n grysaard en ‘n seuntjie ontsien nie.	",
"	16 Hulle het die geliefde seuns van die Weduwee weggevoer en die Eensame van Haar dogters beroof.	",
"	17 Maar Ek, hoe kan Ek julle help?	",
"	18 Want Hy wat die besoedeling oor julle gebring het, kan julle verlos uit die hand van julle vyande.	",
"	19 Trek weg, kinders, trek weg; want Ek bly eensaam agter.	",
"	20 Ek het die kleed van die Vrede afgelê en die roukleed van die Smeking aangetrek; Ek sal die Ewige aanroep in My dae. [Profesie van Barug 5:1]	",
		
		
"	21 HOU goeie moed, kinders! Roep na JaHWeH, en Hy sal julle uitlei uit die oorheersing en uit die mag van die vyande.	",
"	22 Ek het My hoop gestel op die Ewige dat Hy julle uitred; en Vreugde het van die Aparte Een oor My gekom vanweë die Medelye wat met spoed na julle kom van die Ewige, julle Losser.	",
"	23 Want Ek het julle laat gaan met smart en jammerklagte, maar JaHWeH sal julle aan My teruggee met Vreugde en Blydskap vir altyd.	",
"	24 Want net soos die inwoners van Sion nou julle gevangenskap aanskou, so sal hulle spoedig ook julle Lossing deur Elohim sien, wanneer Hy vir julle kom met groot Glansrykheid. [JeségiEl 43]	",
"	25 Kinders, verdra met geduld die Woede wat van JaHWeH oor julle gekom het; die vyand het jou vervolg, maar spoedig sal jy sy ondergang sien, en dan sal jy jou voet op sy nek sit.	",
"	26 My teergevoelige kinders het op skurwe paaie gewandel; hulle is weggevoer soos ‘n trop vee wat deur vyande gesteel is.	",
"	27 Hou goeie moed, kinders! Roep na JaHWeH, want Hy wat julle weggevoer het, sal aan julle dink.	",
"	28 Want soos dit julle gesindheid gewees het om van Elohim af weg te dwaal, so sal julle tienmaal meer na Hom terugkeer en soek.	",
"	29 En Hy wat die besoedeling oor julle gebring het, sal ewige Vreugde oor julle bring saam met julle Lossing.	",
		
		
"	30 Hou goeie moed, Jerusalem! Hy wat jou ‘n naam gegee het, nooi jou uit.	",
"	31 Wee hulle wat jou gekwel het en hulle verheug het oor jou val!	",
"	32 Wee die stede waar jou kinders diensbaar was! Wee die koninkryk wat jou seuns geneem het!	",
"	33 Want soos sy haar oor jou ondergang verheug het en oor jou val gejubel het, so sal sy jammer oor haar eie verwoesting.	",
"	34 Ek sal ‘n einde stel aan haar vreugde oor haar menigtes, en haar trots sal in droefheid verander.	",
"	35 Want vanaf die Ewige sal Vuur oor haar kom in lengte van dae, en vir ‘n lang tyd sal duiwels in haar woon.	",
"	36 Slaan jou oë op na die ooste, Jerusalem, en aanskou die Vreugde wat vir jou van Elohim af kom.	",
"	37 Kyk, jou kinders kom wat jy laat gaan het; hulle kom, van die ooste tot die weste versamel deur die Woord van die Aparte Een, en hulle jubel oor die Glansrykheid van JaHWeH.	",

]
},
{
book: 'Barug',
chapter: '5',
content: [
	
"	1 LÊ af, Jerusalem, die kleed van jou rou en verdrukking, en beklee jou vir altyd met die prag van JaHWeH se Glansrykheid. [Profesie van Barug 4:20]	",
"	2 Slaan die mantel om van die Geregtigheid wat uit Elohim is, en sit op jou hoof die hoofversiersel van die Glansrykheid van die Ewige. [Exodus 28:36]	",
"	3 Want JaHWeH sal aan die hele gebied onder die Hemele jou glans openbaar.	",
"	4 JaHWeH sal jou vir ewig by die naam noem: Vrede van Geregtigheid en Roem van Gehoorsaamheid. [JeshaJaH 60:14 - 17]	",
"	5 Staan op, Jerusalem, en klim op ‘n hoogte. Slaan jou oë op na die ooste, en aanskou jou kinders wat van die weste af deur die Woord van die Aparte Een versamel is, en wat jubel omdat JaHWeH aan hulle gedink het. [Psalm 147]	",
"	6 Hulle het te voet van jou weggegaan, toe hulle deur die vyande weggevoer is; maar JaHWeH lei hulle na jou, terwyl hulle met eer gedra word soos ‘n koningstroon.	",
"	7 Want JaHWeH het bepaal dat elke hoë berg en die ewige heuwels laag gemaak word en dat die klowe gevul word totdat die Aarde gelyk is, sodat JisraEl veilig kan wandel in die Glansrykheid van JaHWeH.	",
"	8 En die bosse en al die geurige bome sal aan JisraEl skaduwee gee op die bevel van JaHWeH.	",
"	9 Want JaHWeH lei JisraEl met Vreugde deur die Lig van Sy Glansrykheid saam met Sy Medelye en Geregtigheid.	",

]
},
{
book: 'Barug',
chapter: '6',
content: [
		
"	0 AFSKRIF van die brief wat JirmeJaH gestuur het na die gevangenes toe hulle op die punt staan om deur die koning van die Babeliete na Babel weggevoer te word, om hulle te meld wat JaHWeH aan hom beveel het.	",
"	1 Vanweë die oortredinge wat julle teen JaHWeH gedoen het, sal julle as gevangenes na Babel weggevoer word deur Nebukadnésar, die koning van die Babeliete.	",
"	2 Wanneer julle in Babel aankom, sal julle daar baie jare bly - ‘n lang tyd, so lank soos sewe geslagte. Daarna sal Ek julle van haar uitlei in Vrede.	",
"	3 Nou sal julle in Babel gode van silwer en goud en hout sien, wat op die skouers rondgedra word en Vrees by die nasies aanjaag.	",
"	4 Neem julle in ag dat julle die vreemdelinge nie navolg en daardeur aan hulle gelyk word nie, sodat die Vrees vir hulle ook julle aangryp,	",
"	5 wanneer julle die menigte voor en agter hulle sien neerkniel, sê dan in julle harte: U behoort aanbid te word, JaHWeH.	",
"	6 Want My Boodskapper is onder julle om self julle geeste te ondersoek.	",
"	7 Die gode se tong is deur ‘n ambagsman gepolys, en hulle is met goud en silwer bedek, maar tog is hulle bedrog en kan nie praat nie.	",
"	8 En soos vir ‘n dogter wat van ornamente hou, neem hulle goud en maak krone vir die hoofde van hulle gode;	",
"	9 tensy die priesters die goud en silwer van hulle gode weghaal, om dit vir hulleself te gebruik en daarvan te gee aan die hoere in die bordele.	",
"	10 Hulle versier die gode van silwer en goud en hout ook soos mense met klere; maar hulle is nie gevrywaar teen roes en bederf nie.	",
"	11 En ook, al is hulle beklee met ‘n koningsblou gewaad, tog word hulle gesigte skoongemaak vanweë die stof van die gebou wat dik op hulle lê.	",
"	12 Ook het hy ‘n septer, soos ‘n regter, van die platteland wat aan diegene wat hom aanrand nie die doodstraf kan oplê nie.	",
"	13 Hy hou ook wel ‘n swaard in sy regterhand, of ‘n byl; maar hy kan hom nie self help teen oorlog of diewe nie.	",
"	14 Daaruit blyk dat hulle nie elohim is nie; vrees hulle derhalwe nie?	",
"	15 Want soos ‘n mens se gebreekte gereedskap onbruikbaar is, so is ook die gode van hulle wat daar in die tempels neergesit is.	",
"	16 Hulle oë is vol stof van die voete van die wat inkom.	",
"	17 En ewenas vir iemand wat die koning beledig het, rondom die Poorte toegesluit is soos vir ‘n ter dood veroordeelde, so sluit die priesters hulle tempels met deur en grendels en sluitbalke, sodat hulle nie deur die diewe gesteel kan word nie.	",
"	18 Hulle brand lampe - en selfs baie vir hulle, maar hulle kan nie een daarvan sien nie.	",
"	19 Hulle is soos een van die balke van die Tempel, waarvan gesê word dat die hart weggevreet word: hulle bemerk dit nie dat die wurms uit die Aarde hulleself en hulle klere wegknaag nie.	",
"	20 Hulle gesigte is swart van die rook in die Tempel.	",
"	21 Vlermuise en swawels en ander voëls fladder op hulle lyf en hulle hoof; en ook is daar nog katte.	",
"	22 Julle weet daaruit dat hulle nie elohim is nie; vrees hulle daarom nie!	",
"	23 En die goud waarmee hulle vir versiering beklee is - as daar nie iemand is om die roes weg te neem nie, dan het dit geen glans nie; hulle bemerk selfs nie dat hulle gegiet word nie.	",
"	24 Vir die hoogste prys word hulle gekoop, en tog is daar in hulle nie ‘n siel nie.	",
"	25 Omdat hulle nie voete het nie, word hulle op die skouers rondgedra en toon so hulle eie skande aan die mense. Maar ook die wat hulle vereer, behoort hulle daaroor te skaam dat die gode nie uit hulleself kan opstaan, as hulle val nie.	",
"	26 En as iemand een regop sit, beweeg hy nie vanself nie; en as een oorhang, sal hy nie opkom nie. En tog word daar vir hulle slagdiere neergesit soos vir gestorwenes.	",
"	27 Die priesters verkoop van die slagdiere vir hulle eie voordeel, en hulle vroue sout ook wel daarvan in; maar hulle deel nie uit aan ‘n arme of ‘n gebreklike nie. Die slagdiere word trouens aangeraak deur vroue wat ‘n vloeiing het of onlangs gebaar het.	",
"	28 Daaraan sien julle dat hulle nie elohim is nie; vrees hulle nie!	",
"	29 Waarom sal hulle elohim genoem word? Want vroue bedien die gode van silwer en goud en hout.	",
"	30 En die priesters loop in hulle tempels rond met geskeurde klere en met geskeerde hare en baarde, terwyl hulle hoofde onbedek is.	",
"	31 Hulle huil en skreeu voor hulle gode soos sommige mense by ‘n dodemaal.	",
"	32 Die priesters neem ook van die klere van hul gode om hulle vroue en kinders aan te klee.	",
"	33 En of die gode nou kwaad of goed van iemand ondervind, hulle kan dit nie vergeld nie; hulle kan nie ‘n koning aanstel of afsit nie;	",
"	34 ewenas hulle nie rykdom of brons kan gee nie; en as iemand aan hulle ‘n gelofte doen wat hy nie hou nie, kan hulle nie wreek nie.	",
"	35 Hulle kan nie ‘n adamiet uit die Dood red nie, en hulle kan ‘n swakke nie uit die mag van ‘n sterke bevry nie.	",
"	36 Aan ‘n blinde kan hulle nie sy gesigsvermoë teruggee nie; en ‘n adamiet wat in nood is, kan hulle nie uitred nie.	",
"	37 Hulle ontferm hulle nie oor ‘n weduwee nie, en hulle sal ‘n weeskind nie goeddoen nie.	",
"	38 Hulle is gelyk aan die klippe van ‘n berg - daardie hout en vergulde en versilwerde maaksels; en die wat hulle vereer, behoort hulle te skaam.	",
"	39 Hoe is dit dan moontlik om te meen of te beweer dat hulle elohim is?	",
"	40 Ook selfs sommige Chaldeërs onteer die elohim: wanneer hulle ‘n stomme sien, wat dus nie kan praat nie, dan haal hulle Bel en vra hom om die spraak, asof hy dit kan verneem.	",
"	41 En ofskoon hulle weet, tog hou hulle nie daarmee op nie, omdat hulle geen verstand het nie.	",
"	42 Die vroue sit met linte wat hulle omgebind het by die paaie en brand semels;	",
"	43 wanneer een van hulle deur een van die verbygangers saamgeneem word en sy met hom gemeenskap gehad het, dan verwyt sy die vrou naasaan dat sy nie geëer is soos syself nie en dat haar lint nie stukkend geskeur is nie.	",
"	44 Bedrog is alles wat daar vir hulle gebeur; hoe is dit dan moontlik om te meen of te beweer dat hulle elohim is?	",
"	45 Deur ambagsmanne en goudsmede is hulle gemaak, en hulle kan dus niks anders wees as wat die handwerksmanne wil nie.	",
"	46 Die wat hulle maak, word self nie oud nie; hoe kan dan die dinge wat deur hulle gemaak is, elohim wees?	",
"	47 So laat hulle bedrog en skande agter vir die wat na hulle kom.	",
"	48 Want wanneer daar ‘n oorlog en besoedeling oor hulle kom, dan beraadslaag die priesters met mekaar waar hulle met die gode sal wegskuil.	",
"	49 Hoe is dit dan moontlik om nie in te sien dat hulle nie elohim is nie, as hulle hulleself nie kan vrywaar teen ‘n oorlog en teen besoedeling nie?	",
"	50 Omdat dit hout en vergulde en versilwerde maaksels is, sal later ingesien word dat hulle bedrog is: vir al die nasies en konings sal dit duidelik wees dat hulle nie elohim is nie maar die werke van mensehande, en dat daar geen werk van Elohim onder hulle is nie.	",
"	51 Wie moet dan nog insien dat hulle nie elohim is nie?	",
"	52 Hulle stel nie ‘n koning oor die Aarde aan nie, en ook gee hulle aan die mense geen reën nie;	",
"	53 hulle kan hulleself ook geen Reg verskaf nie, en hulle is onmagtig om teen onreg te vrywaar; hulle is soos valke tussen die Hemele en die Aarde.	",
"	54 Want as die Tempel van die hout of vergulde of versilwerde gode deur vuur getref word, dan vlug wel hulle priesters en red hulleself, maar die gode brand dwarsdeur soos balke.	",
"	55 Ook aan ‘n koning en aan vyande kan hulle nie weerstand bied nie.	",
"	56 Hoe kan ‘n mens dan aanneem en glo dat hulle elohim is?	",
"	57 Ook teen diewe en rowers kan die hout en versilwerde en vergulde gode hulle nie vrywaar nie; en omdat hulle sterker as die gode is, neem hulle die goud en die silwer en die klere wat hulle bedek van hulle af en loop daarmee weg, sonder dat die gode hulleself kan help.	",
"	58 Daarom is dit beter om ‘n koning te wees wat sy mag kan toon, of ‘n nuttige werktuig waarmee die eienaar kan werk, as om die valse gode te wees; of selfs ‘n huisdeur wat beskerming bied aan al wat binnekant is, as die valse gode; of ‘n houtpilaar in ‘n koninklike paleis as die valse gode.	",
"	59 Want die son en die maan en die Sterre is ligte, wat tot nut gestuur word en gehoorsaam is.	",
"	60 Eweso die weerlig, wat goed sigbaar is, wanneer dit verskyn; net so waai die wind op die hele Aarde.	",
"	61 En as die Wolkkolom deur Elohim gebied word om oor die hele Aarde te trek, dan volbring hulle die bevel; en die vuur wat van omhoog gestuur word om die berge en die bosse te verteer, vervul sy opdrag.	",
"	62 Maar die maaksels is nòg in uiterlik nog in krag daaraan gelyk.	",
"	63 Daarom moet nie gemeen of beweer word dat hulle elohim is nie, want hulle het nie die regsmag om ‘n uitspraak te doen nie, en hulle kan die mense nie goeddoen nie.	",
"	64 Julle weet dus dat hulle nie elohim is nie; vrees hulle nie!	",
"	65 Want hulle kan ook nie ‘n vervloeking of seën oor konings uitspreek nie,	",
"	66 Aan die nasies kan hulle nie tekens in die Hemele gee nie, en hulle kan nie straal soos die son nie, en nie lig gee soos die maan nie.	",
"	67 Die diere is nog beter as hulle: die kan wegvlug in ‘n skuilplek en hulleself help.	",
"	68 Op geen enkele wyse is dit ons derhalwe duidelik dat hulle elohim is nie; vrees hulle dus nie?	",
"	69 Want soos ‘n voëlverskrikker in ‘n komkommerland nie waghou nie, so is die hout en vergulde en versilwerde gode van hulle nie ‘n beveiliging nie.	",
"	70 Eweso is hulle gelyk aan ‘n doringboom in ‘n tuin, waarop die voëls gaan sit; net so aan ‘n lyk wat in die duister weggewerp word - daardie hout en vergulde en versilwerde gode van hulle.	",
"	71 Deurdat die koningsblou en die linneweefsel wat op hulle lê, vergaan, kan julle weet dat hulle nie elohim is nie. Oplaas word hulle self ook verteer, en hulle is ‘n skande in die Aarde.	",
"	72 Beter is derhalwe ‘n regverdige adamiet wat geen idole besit nie, want hy sal ver wees van die skande. Die Profesie van Barug.	",

]
}
];
