const daniëlChapters = [

{
book: 'Daniël',
chapter: '1',
content: [

"	1 IN die derde jaar van die regering van JeHôWjakim, die koning van JeHûWdah, het Nebukadnésar, die koning van Babel, na Jerusalem gekom en haar beleër.	",
"	2 En my Meester het JeHôWjakim, die koning van JeHûWdah, in sy hand gegee, met ’n gedeelte van die voorwerpe van die Huis van die Elohim, en hy het hulle na die Aarde van Sínear gebring in die huis van sy gode, en die voorwerpe het hy in die skathuis van sy gode gebring. [ZekarJaH 5:11]	",
"	3 Daarop het die koning aan Ashpenaz, die owerste van sy hofdienaars, bevel gegee om uit die kinders van JisraEl, uit die koninklike saad sowel as uit die edeles, te bring:	",
"	4 Jong seuns wie nie gekleurd was nie, maar wat suiwer van aansien was en vernuftig in allerhande Wysheid en in besit van Kennis en Insig in wetenskap, en wat bekwaam was om in die paleis van die koning te dien; en om hulle die Boekrol en die taal van die Chaldeërs te leer.	",
"	5 En die koning het vir hulle na die dag tot dag woord bestem uit die spys van die koning en van die wyn wat hy gedrink het; om hulle so drie jaar lank op te voed, sodat hulle aan die einde daarvan voor die koning kan dien.	",
"	6 En onder hulle was uit die kinders van JeHûWdah: DaniEl, GanánJaH, MisahaEl en AzarJaH.	",
"	7 Maar die owerste van die hofdienaars het hulle [ander] name gegee: DaniEl het hy Béltsasar genoem, en GanánJaH Sadrag, en MisahaEl Mesag, en AzarJaH Abednégo.	",
"	8 En DaniEl het hom voorgeneem om hom nie te besoedel met die spys van die koning of met die wyn wat hy gedrink het nie; daarom het hy die owerste van die hofdienaars vergunning gevra dat hy hom nie hoef te besoedel nie.	",
"	9 En die Elohim het aan DaniEl Guns en Barmhartigheid verleen by die owerste van die hofdienaars.	",
"	10 En die owerste van die hofdienaars het aan DaniEl gesê: Ek vrees my meester die koning, wat julle voedsel en julle drank vasgestel het; want waarom moet hy sien dat julle aangesigte meer vervalle is as dié van die jong seuns wat van julle leeftyd is, sodat julle my hoof by die koning met skuld sou belaai?	",
"	11 Maar DaniEl het aan die bediende gesê wat die owerste van die hofdienaars oor DaniEl, GanánJaH, MisahaEl en AzarJaH aangestel het;	",
"	12 Stel tog u dienaars tien dae lank op die proef, en laat hulle ons van die groente gee om te eet en water om te drink;	",
"	13 laat daarna ons voorkoms en die voorkoms van die jong seuns wat die spys van die koning eet, deur u besigtig word; handel dan met u dienaars soos u bevinding sal wees.	",
"	14 Hy het toe na hulle geluister in hierdie saak en hulle tien dae lank op die proef gestel.	",
"	15 En aan die einde van tien dae het hulle voorkoms beter en hulle voller van vlees gelyk as al die jong seuns wat die spys van die koning geëet het.	",
"	16 So het dan die bediende hulle spys en die wyn wat hulle moes drink, weggeneem en aan hulle groente gegee.	",
"	17 En hierdie vier jong seuns – die Elohim het aan hulle wetenskap en Verstand in allerhande Boekrolle en Wysheid gegee; ook het DaniEl Verstand gehad van allerhande gesigte en drome.	",
"	18 En aan die einde van die dae wat die koning vasgestel het om hulle in te bring, het die owerste van die hofdienaars hulle voor Nebukadnésar gebring.	",
"	19 En die koning het met hulle gespreek, en onder hulle almal is daar niemand gevind soos DaniEl, GanánJaH, MisahaEl en AzarJaH nie. So het hulle dan voor die koning gedien.	",
"	20 En in enige saak van wyse Insig waarin die koning hulle ondervra het, het hy bevind dat hulle al die geleerdes [en] besweerders in sy hele koninkryk tien maal oortref het.	",
"	21 En DaniEl was daar tot die eerste jaar van koning Kores.	",

]
},
{
book: 'Daniël',
chapter: '2',
content: [
		
"	1 EN in die tweede jaar van die regering van Nebukadnésar, het Nebukadnésar ’n droom gehad, sodat sy gees onrustig geword het en dit met sy slaap gedaan was.	",
"	2 Toe het die koning bevel gegee om die geleerdes en die besweerders en die towenaars en die Chaldeërs te roep, om vir die koning sy droom uit te lê. Toe hulle kom en voor die koning gaan staan,	",
"	3 sê die koning vir hulle: Ek het ’n droom gehad, en my gees is onrustig om die droom te verstaan.	",
"	4 Toe het die Chaldeërs met die koning gespreek in Aramees: Mag die koning vir altyd lewe! Vertel u dienaars die droom, en ons sal die uitlegging te kenne gee.	",
"	5 Die koning het geantwoord en aan die Chaldeërs gesê: Die saak staan by my vas: as julle die droom en sy uitlegging nie aan my bekend maak nie, sal julle in stukke gekap en van julle huise mishope gemaak word.	",
"	6 Maar as julle die droom en sy uitlegging te kenne gee, sal julle geskenke en gawes en groot eer van my ontvang; gee my daarom die droom en sy uitlegging te kenne.	",
"	7 Hulle het vir die tweede maal geantwoord en gesê: Laat die koning die droom aan sy dienaars vertel; dan sal ons die uitlegging te kenne gee.	",
"	8 Die koning het geantwoord en gesê: Ek weet verseker dat julle tyd wil win, omdat julle sien dat die saak by my vasstaan;	",
"	9 want as julle my die droom nie bekend maak nie, o dan is daar maar een uitspraak oor julle; julle het naamlik afgespreek om ’n leuenagtige en bedrieglike woord voor my te spreek totdat die tyd weer verander; daarom, vertel my die droom, dan sal ek weet of julle my sy uitlegging kan te kenne gee.	",
"	10 Die Chaldeërs het voor die koning geantwoord en gesê: Daar is geen persoon op die droë [grond] wat die koning se saak sou kan te kenne gee nie; daarom het dan ook geen koning, groot of magtig, ooit so iets van enige geleerde of besweerder of Chaldeër verlang nie.	",
"	11 Ja, die saak wat die koning verlang, is swaar, en daar is niemand anders wat dit voor die koning sou kan te kenne gee nie, behalwe die Elohim wie se woning nie by die vlees is nie.	",
"	12 Hieroor het die koning toornig en baie kwaad geword en bevel gegee om al die wyse manne van Babel om te bring.	",
"	13 Toe die bevel uitgevaardig is en die wyse manne gedood sou word, het hulle ook DaniEl en sy metgeselle gesoek om gedood te word.	",
"	14 Daarop het DaniEl aan Ariog, die owerste van die koninklike lyfwag wat uitgetrek het om die wyse manne van Babel dood te maak, ’n slim en verstandige antwoord gegee.	",
"	15 Hy antwoord en sê vir Ariog, die bevelhebber van die koning: Waarom is die bevel van die kant van die koning so streng? Toe het Ariog aan DaniEl die saak meegedeel.	",
"	16 Daarop het DaniEl ingegaan en die koning versoek dat hy hom tyd moes gee om die uitlegging aan die koning te kenne te gee.	",
"	17 Toe gaan DaniEl na sy huis en maak aan GanánJaH, MisahaEl en AzarJaH, sy metgeselle, die saak bekend,	",
"	18 en dat hulle Barmhartigheid van die Elohey van die Hemele moes afsmeek oor hierdie geheim, sodat hulle DaniEl en sy metgeselle saam met die orige wyse manne van Babel nie sou ombring nie.	",
"	19 Daarop is in ’n naggesig die geheim aan DaniEl geopenbaar. Toe het DaniEl die Elohey van die Hemele geloof.	",
"	20 DaniEl het toe gespreek en gesê: Mag die Naam van Eloah geprys word van ewigheid tot ewigheid, want die Wysheid en die Krag is SYNE.	",
"	21 HY tog verander die tye en die geleenthede; HY sit konings af en stel konings aan; HY verleen Wysheid aan die wyse manne en Kennis aan die wat Insig het;	",
"	22 HY openbaar ondeurgrondelike en verborge dinge; HY weet wat in die duister is, en die Lig woon by HOM.	",
"	23 U, Elohey² van my vaders, loof en prys ek, want U het my Wysheid en Krag verleen, en nou het U my bekend gemaak wat ons van U afgesmeek het, want die saak van die koning het U ons bekend gemaak.	",
"	24 Daarom het DaniEl ingegaan na Ariog, wat die koning aangestel het om die wyse manne van Babel om te bring; hy het gegaan en vir hom só gesê: Moenie die wyse manne van Babel ombring nie; bring my in voor die koning, dan sal ek aan die koning die uitlegging te kenne gee.	",
"	25 Toe het Ariog DaniEl haastig voor die koning ingebring en so vir hom gesê: Ek het ’n man onder die ballinge van JeHûWdah gevind wat die koning die uitlegging bekend sal maak.	",
"	26 Die koning het geantwoord en aan DaniEl, wie se naam Béltsasar was, gesê: Is jy in staat om aan my die droom wat ek gesien het, en sy uitlegging bekend te maak?	",
"	27 DaniEl het in teenwoordigheid van die koning geantwoord en gesê: Die geheim waarna die koning vra, kan die wyse manne, die besweerders, die geleerdes, die waarsêers nie aan die koning te kenne gee nie.	",
"	28 Maar daar is ’n Elohey in die Hemele wat geheime openbaar, en HY het koning Nebukadnésar bekend gemaak wat aan die einde van die dae sal gebeur. U droom en die gesigte van u hoof op u bed was dit:	",
"	29 Wat u betref, o koning, u gedagtes op u bed het opgestyg oor wat hierna sal gebeur, en die Openbaarder van die geheime het u bekend gemaak wat sal gebeur.	",
"	30 En wat my betref, hierdie geheim is my geopenbaar, nie deur ’n wysheid wat in my sou wees meer as in al die lewendes nie, maar met die bedoeling dat die uitlegging aan die koning bekend gemaak sal word en u die gedagtes van u hart kan ken.	",
"	31 U, o koning, het ’n gesig gehad - kyk, daar was ’n groot beeld; hierdie beeld was hoog, en sy helderheid was buitengewoon; hy het voor u gestaan en sy voorkoms was skrikwekkend.	",
"	32 Wat die beeld betref, sy hoof was van suiwer goud, sy bors en sy arms van silwer, sy buik en sy lendene van brons, [Boekrol van Henog 52:2; Hoséa 13:2]	",
"	33 sy bene van yster, sy voete gedeeltelik van yster en gedeeltelik van klei.	",
"	34 U het gekyk totdat daar sonder toedoen van [mense]hande ’n klip losraak wat die beeld getref het aan sy voete van yster en van klei en hom fyn gestamp het. [JeshaJaH 44:8]	",
"	35 Toe is tegelykertyd die yster, die klei, die brons, die silwer en die goud fyn gestamp, en hy het soos kaf geword van die dorsvloere in die somer, wat die wind wegneem, sodat daar geen spoor van gevind is nie; maar die klip wat die beeld getref het, het ’n groot rots geword wat die hele Aarde gevul het.	",
"	36 Dit is die droom; sy uitlegging sal ons nou voor die koning sê:	",
"	37 U, o koning, koning van die konings, aan wie die Elohey van die Hemele die koningskap, krag en sterkte en eer verleen het,	",
"	38 en in wie se hand HY in die hele bewoonde wêreld, die seun van adam, die wilde wesens van die veld en die vlieënde wesens in die lug gegee het, sodat HY u as vors oor hulle almal aangestel het - ú is die hoof van goud.	",
"	39 En ná u sal daar ’n ander koninkryk opstaan, geringer as dié van u; daarna ’n ander, ’n derde koninkryk, van brons, wat oor die hele Aarde sal heers;	",
"	40 en die vierde koninkryk sal hard wees soos yster, juis omdat yster alles fyn stamp en verpletter; en soos die yster wat vergruis, sal hy dit alles fyn stamp en vergruis.	",
"	41 En dat die voete en die tone, soos u gesien het, deels van pottebakkersklei en deels van yster was - sy sal ’n verdeelde koninkryk wees, en van die hardheid van die yster sal in haar wees, omdat u die yster met kleigrond gemeng gesien het.	",
"	42 En dat die tone van die voete deels van yster en deels van klei is - ’n gedeelte van die koninkryk sal hard en ’n gedeelte sal bros wees.	",
"	43 Dat u die yster gemeng met kleigrond gesien het - hulle saad sal deur menslike gemeenskap onder mekaar vermeng raak, maar hulle sal nie aanmekaar vasklewe nie, net soos yster nie met klei meng nie.	",
"	44 Maar in die dae van dié konings sal die Elohey van die Hemele ’n Koninkryk verwek wat in ewigheid nie vernietig sal word nie, en die heerskappy van Haar sal aan geen ander volk oorgelaat word nie; Sy sal al daardie koninkryke verbrysel en daar ’n einde aan maak, maar self sal Sy vir ewig bestaan - [DaniEl 6:26]	",
"	45 net soos u gesien het dat sonder toedoen van [mense]hande ’n klip van die berg af losgeraak het wat die yster, die brons, die klei, die silwer en die goud verbrysel het. Die grote Elohey het aan die koning bekend gemaak wat hierna sal gebeur; en die droom is waar en sy uitlegging betroubaar. [Boekrol van Henog 52:2; DaniEl 8:25]	",
"	46 Toe het koning Nebukadnésar op sy aangesig geval en uitgestrek voor DaniEl en bevel gegee om aan hom aanbiedinge uit te giet en kalmerende reukwerk te bring.	",
"	47 Die koning het DaniEl geantwoord en gesê: Waarlik, julle Elohey is die Elohey van die Elohim en Koning van die konings en die Openbaarder van geheimenisse, daarom was jy in staat om hierdie geheim te openbaar.	",
"	48 Toe het die koning DaniEl verhef en hom baie, groot geskenke gegee en hom aangestel as vors oor die hele provinsie Babel en as hoofowerste oor al die wyse manne van Babel.	",
"	49 En op versoek van DaniEl het die koning Sadrag, Mesag en Abednégo aangestel oor die bestuur van die provinsie Babel, maar DaniEl was in die paleis van die koning.	",
	
]
},
{
book: 'Daniël',
chapter: '3',
content: [
	
"	1 KONING Nebukadnésar het ’n beeld van goud gemaak; sy hoogte was sestig voorarm, sy breedte ses voorarm; hy het hom opgerig in die dal Dura, in die provinsie Babel. [Miga 4:10]	",
"	2 Daarna het koning Nebukadnésar die landvoogde, die bevelhebbers en die goewerneurs, die raadsmanne, die skatmeesters, die regters, die hoofamptenare en al die bestuurders van die provinsies laat versamel, dat hulle moes kom na die inwyding van die beeld wat koning Nebukadnésar opgerig het.	",
"	3 Toe het die landvoogde, die bevelhebbers en die goewerneurs, die raadsmanne, die skatmeesters, die regters, die hoofamptenare en al die bestuurders van die provinsies bymekaargekom by die inwyding van die beeld wat koning Nebukadnésar opgerig het, en hulle het voor die beeld gaan staan wat Nebukadnésar opgerig het.	",
"	4 En ’n uitroeper het hardop geroep: Julle word aangesê, o volke, nasies en tale,	",
"	5 sodra julle die geluid hoor van horing, fluit, siter, luit, harp, doedelsak en van allerhande musiekinstrumente, moet julle neerval en uitstrek vir die goue beeld wat koning Nebukadnésar opgerig het.	",
"	6 En hy wat nie neerval en uitstrek nie, sal op die daad binne-in die brandende vuuroond gegooi word.	",
"	7 Daarom het, op die oomblik toe al die volke die geluid van horing, fluit, siter, luit, harp en van allerhande musiekinstrumente hoor, al die volke, nasies en tale neergeval en uitgestrek vir die goue beeld wat koning Nebukadnésar opgerig het.	",
"	8 Daarvandaan het tegelykertyd Chaldese manne nader gekom en die manne van JeHûWdah aangeklaag.	",
"	9 Daarop het hulle met koning Nebukadnésar gespreek en gesê: Mag die koning vir ewig lewe!	",
"	10 U, o koning, het ’n bevel gegee dat elke persoon wat die geluid van horing, fluit, siter, luit, harp en doedelsak en van allerhande musiekinstrumente hoor, moet neerval en uitstrek vir die goue beeld;	",
"	11 en dat hy wat nie neerval en uitstrek nie, binne-in die brandende vuuroond gegooi moet word.	",
"	12 Daar is manne van JeHûWdah wat u oor die bestuur van die provinsie Babel aangestel het, Sadrag, Mesag en Abednégo; hierdie manne het hulle, o koning, aan u nie gesteur nie; hulle dien jou elohey nie en hulle strek nie uit vir die goue beeld wat u opgerig het nie.	",
"	13 Toe het Nebukadnésar, toornig en woedend, bevel gegee om Sadrag, Mesag en Abednégo te laat kom. Daarop is die manne voor die koning gebring.	",
"	14 En Nebukadnésar het gespreek en vir hulle gesê: Is dit met opset, Sadrag, Mesag en Abednégo, dat julle my gode nie dien en nie uitstrek vir die goue beeld wat ek opgerig het nie?	",
"	15 As julle dan nou, sodra julle die geluid van horing, fluit, siter, luit, harp en doedelsak en van allerhande musiekinstrumente hoor, bereid is om neer te buig en uit te strek vir die beeld wat ek gemaak het, maar as julle nie uitstrek nie, sal julle oombliklik binne-in die brandende vuuroond gegooi word, en wie is die Elohey wat julle uit my hand kan verlos?	",
"	16 Sadrag, Mesag en Abednégo het geantwoord en aan koning Nebukadnésar gesê: Ons ag dit nie nodig om u hierop ’n antwoord te gee nie.	",
"	17 As onse Elohey wat ons dien, in staat is om ons te verlos, dan sal Hy ons uit die brandende vuuroond en uit u hand, o koning, verlos;	",
"	18 maar so nie, laat dit u dan bekend wees, o koning, dat ons jou godinne nie sal dien nie en nie sal uitstrek vir die goue beeld wat u opgerig het nie.	",
"	19 Toe het Nebukadnésar baie woedend geword en sy gelaatstrekke het verander teenoor Sadrag(GanánJaH), Mesag (MisaEl) en Abednégo(AzarJaH); as antwoord het hy bevel gegee om die oond sewe maal warmer te maak as wat eintlik nodig was.	",
"	20 En aan sommige van die sterkste manne wat in sy leër was, het hy bevel gegee om Sadrag, Mesag en Abednégo te boei, om [hulle] in die brandende vuuroond te gooi.	",
"	21 Toe is daardie manne geboei met hulle mantels, hulle broeke en hulle tulbande en hulle [ander] klere aan, en hulle is binne-in die brandende vuuroond gegooi. [Exodus 28:36, ZekarJaH 3:5]	",
"	22 Omdat dan nou die woord van die koning streng en die oond uitermate verhit was, het die vlam van die vuur daardie manne wat Sadrag, Mesag en Abednégo opgeneem het, doodgebrand.	",
"	23 Maar daardie drie manne, Sadrag, Mesag en Abednégo, het geboeid binne-in die brandende vuuroond geval.	",
		
		
"	24 EN hulle het in die middel van die vuur gewandel terwyl hulle die lof van Elohim besing en JaHWeH geprys het.	",
"	25 Toe het AsarJaH opgestaan en soos volg gebid; binne-in die vuur het hy sy mond oopgemaak en gesê:	",
"	26 Geseënd is U, o JaHWeH, U die Elohey van ons vaders, en werd om geloof te word! En [mag] U Naam in ewigheid verhoog word!	",
"	27 Want U is Reg in alles wat U gedoen het, en al U werke is getrou en U Weë opreg, en al U oordele waaragtig.	",
"	28 In al die dinge wat U oor ons en oor die Stad van Apartheid van ons vaders, Jerusalem, gebring het, het U [ons] na Waarheid geoordeel; want volgens Waarheid en Reg het U al hierdie dinge vanweë ons oortredinge oor ons gebring.	",
"	29 Want ons het oortree en het verkeerd gehandel deur van U af te wyk;	",
"	30 ja, in alle dinge het ons gruwelik oortree, want ons het na U Gebooie nie geluister en hulle ook nie onderhou nie, en ons het nie gedoen wat U ons beveel het om te doen sodat dit met ons goed kon gaan nie.	",
"	31 Alles wat U oor ons laat kom het en alles wat U ons aangedoen het, het U in Geregtigheid gedoen.	",
"	32 U het ons oorgegee in die hande van wettelose vyande en van die mees veragtelike opstandelinge en aan ‘n roekelose koning, die mees wettelose in die hele wêreld.	",
"	33 Tog durf ons ons mond nie oopmaak nie; smaad en skande het die deel geword van U knegte en van hulle wat U aanbid.	",
"	34 Moet ons ter wille van U Naam nie tot vernietiging oorgee en verbreek tog nie U Verbond nie.	",
"	35 En moenie U Barmhartigheid aan ons onttrek nie, ter wille van Abraham wat U liefgehad het, en ter wille van Isak, U kneg, en ter wille van JisraEl, U aparte, [Génesis 17:1]	",
"	36 aan wie U beloof het dat U hulle nageslag sou vermeerder soos die Sterre van die Hemele en soos die sand wat op die seestrand is.	",
"	37 Want ons, o JaHWeH, het minder geword as al die nasies, en ons is oor die hele Aarde op hierdie dag verneder vanweë ons oortredinge.	",
"	38 Ook het ons in hierdie tyd geen vors of profeet of leidsman nie; ook nie brandoffer of slagoffer of spysbydrae of reukwerk nie; ook nie ‘n plek waar ons U ons Slagdier kan aanbied en Barmhartigheid kan vind nie.	",
"	39 Maar mag ons aanneemlik [voor U] wees op grond van ‘n berouvolle hart en ‘n ootmoedige gees,	",
"	40 asof dit geskied deur brandoffers van ramme en bulle en deur tienduisende vetgemaakte lammers. Laat ons aanbieding vandag só voor U wees, en gee dat ons U volkome mag volg, want hulle wat op U vertrou sal nie beskaam staan nie!	",
"	41 En nou volg ons U met ons hele hart en ons vrees U en soek U Aangesig.	",
"	42 Laat ons nie beskaam staan nie, maar handel met ons na U goedgunstigheid en volgens die grootheid van U Ontferming.	",
"	43 Verlos ons dan volgens U wonderdade, en verhoog U Naam, o JaHWeH!	",
"	44 En laat almal wat U diensknegte leed aangedoen het, beskaam word; laat hulle tot skande word en laat hulle al hul heerskappy en mag verloor, en hulle krag verbreek word.	",
"	45 En laat hulle gewaarword dat U alleen JaHWeH onse Elohey is, verhoog oor die ganse Aarde!	",
"	46 Intussen het die knegte van die koning wat hulle daarin gewerp het, nie opgehou om die oond met hars, pik, tou en klein stukkies hout te verhit nie.	",
"	47 En die vlam het nege-en-veertig voorarm bo die oond uitgeslaan.	",
"	48 En hy het versprei en die Chaldeërs wat rondom die oond was, verbrand.	",
"	49 Maar die Boodskapper van JaHWeH het neergedaal en Hom by AsarJaH en sy metgeselle in die oond gevoeg, en Hy het die vlam van die vuur uit die oond uit verdryf,	",
"	50 en het die middel van die oond gemaak asof ‘n vogtige wind daardeur geruis het, en die vuur het hulle hoegenaamd nie aangeraak en hulle ook geen leed aangedoen of bekommernis veroorsaak nie. [1 Konings 19:11]	",
"	51 Toe het die drie [manne] in die oond as uit een mond Elohim geprys, verhoog, geloof en gesê:	",
"	52 Geseënd is U, JaHWeH, die Elohey van ons vaders, geprese en hoog verhewe tot in ewigheid! En geseënd is U glansryke en verhewe Naam, en grootliks geprese en hoog verhewe tot in ewigheid.	",
		
"	53 Geseënd is U in die Tempel van U aparte Glansrykheid, hoog geprese en grootliks verhoog tot in ewigheid.	",
"	54 Geseënd is U wat die dieptes deurskou en op Gerubs sit, geprese en hoog verhewe tot in ewigheid.	",
"	55 Geseënd is U op die Troon van U koninkryk, grootliks geprese en hoog verhewe tot in ewigheid.	",
"	56 Geseënd is U in die uitspansel van die Hemele, geprese en verhoog tot in ewigheid.	",
"	57 Loof JaHWeH, o al die werke van JaHWeH, sing en verhef Sy lof tot in ewigheid.	",
"	58 Loof JaHWeH, o Hemele, sing en verhef Sy lof tot in ewigheid.	",
"	59 Loof JaHWeH, o Boodskappers van JaHWeH, sing en verhef Sy lof tot in ewigheid.	",
"	60 Loof JaHWeH, o al die waters wat bo aan die Hemele is, sing en verhef Sy lof tot in ewigheid. [Génesis 1:6]	",
"	61 Loof JaHWeH, o al die magte van JaHWeH, sing en verhef Sy lof tot in ewigheid.	",
"	62 Loof JaHWeH, o son en maan, sing en verhef Sy lof tot in ewigheid.	",
"	63 Loof JaHWeH, o Sterre van die Hemele, sing en verhef Sy lof tot in ewigheid.	",
"	64 Loof JaHWeH, o elke reënbui en douval, sing en verhef Sy lof tot in ewigheid.	",
"	65 Loof JaHWeH, o al die winde, sing en verhef Sy lof tot in ewigheid.	",
"	66 Loof JaHWeH, o vuur en hitte, sing en verhef Sy lof tot in ewigheid.	",
"	67 Loof JaHWeH, o koue en warmte, sing en verhef Sy lof tot in ewigheid.	",
"	68 Loof JaHWeH, o Dou en sneeu, sing en verhef Sy lof tot in ewigheid.	",
"	69 Loof JaHWeH, o nagte en dae, sing en verhef Sy lof tot in ewigheid.	",
"	70 Loof JaHWeH, o lig en donkerheid, sing en verhef Sy lof tot in ewigheid.	",
"	71 Loof JaHWeH, o ys en koue, sing en verhef Sy lof tot in ewigheid.	",
"	72 Loof JaHWeH, o ryp en sneeu, sing en verhef Sy lof tot in ewigheid.	",
"	73 Loof JaHWeH, o blitse en wolke, sing en verhef Sy lof tot in ewigheid.	",
"	74 Laat die Adamah [die adamiet se Aarde] JaHWeH loof, sing en verhef Sy lof tot in ewigheid.	",
"	75 Loof JaHWeH, o berge en heuwels, sing en verhef Sy lof tot in ewigheid.	",
"	76 Loof JaHWeH, o alles wat op die Adamah [die adamiet se Aarde] groei, sing en verhef Sy lof tot in ewigheid.	",
"	77 Loof JaHWeH, o Fonteine, sing en verhef Sy lof tot in ewigheid.	",
"	78 Loof JaHWeH, o see en riviere, sing en verhef Sy lof tot in ewigheid.	",
"	79 Loof JaHWeH, o Groot Drake en alles wat in die waters beweeg, sing en verhef Sy lof tot in ewigheid, [Genésis 1:21]	",
"	80 Loof JaHWeH, o voëls van die Hemele, sing en verhef Sy lof tot in ewigheid.	",
"	81 Loof JaHWeH, o wilde en mak diere, sing en verhef Sy lof tot in ewigheid.	",
"	82 Loof JaHWeH, o seuns van die Adam, sing en verhef Sy lof tot in ewigheid.	",
"	83 Loof JaHWeH, o JisraEl, sing en verhef Sy lof tot in ewigheid.	",
"	84 Loof JaHWeH, priesters van JaHWeH, sing en verhef Sy lof tot in ewigheid.	",
"	85 Loof JaHWeH, o knegte van JaHWeH, sing en verhef Sy lof tot in ewigheid.	",
"	86 Loof JaHWeH, o Geeste en siele van die regverdiges, sing en verhef Sy lof tot in ewigheid.	",
"	87 Loof JaHWeH, o apartes en nederiges van hart, sing en verhef Sy lof tot in ewigheid.	",
"	88 Loof JaHWeH, o Hananja, Asarja en Misael, sing en verhef Sy lof tot in ewigheid. Want Hy het ons uit die Doderyk/Sheol gered en ons uit die mag van die Dood verlos en ons uit die middel van die brandende oond gered, ja, uit die middel van die vuur het Hy ons gered!	",
"	89 Loof dan JaHWeH, want Hy is goed, want Sy goedgunstigheid duur tot in ewigheid.	",
"	90 Loof die Elohey van die Elohim, o almal wat JaHWeH dien, sing sy lof en dank Hom, want sy goedgunstigheid duur tot in ewigheid!	",
"	91{24} Toe het koning Nebukadnésar verskrik geword en haastig opgestaan; hy het sy raadsmanne toegespreek en gesê: Het ons nie drie manne geboeid binne-in die vuur gegooi nie? Hulle antwoord en sê aan die koning: Sekerlik, o koning!	",
"	92{25} Hy antwoord en sê: Kyk, ek sien vier manne los binne-in die vuur wandel sonder dat daar ’n letsel aan hulle is; en die voorkoms van die vierde lyk soos dié van ’n Seun van Elohim.	",
"	93{26} Toe het Nebukadnésar nader gekom na die opening van die brandende vuuroond en daarop gesê: Sadrag, Mesag en Abednégo, knegte van die Hoogste Eloah, gaan uit en kom hier! Toe het Sadrag, Mesag en Abednégo uit die vuuroond uitgegaan.	",
"	94{27} Daarop het die landvoogde, die bevelhebbers en die goewerneurs en die raadsmanne van die koning vergader en aan daardie manne gesien dat die vuur geen mag oor hulle liggame gehad en die hare van hulle hoof nie geskroei het nie, en dat hulle mantels geen verandering ondergaan en die reuk van die vuur nie aan hulle gekom het nie.	",
"	95{28} Daarop het Nebukadnésar gespreek en gesê: Geseënd [is] hulle Elohey, die van Sadrag, Mesag en Abednégo, wat Sy Boodskapper gestuur en Sy knegte verlos het, wat hulle op Hom verlaat het en die bevel van die koning oortree het, en wat hulle liggame oorgegee het om geen gode van andere te dien of neer te buig nie, behalwe hulle Elohey.	",
"	96{29} Daarom word deur my bevel gegee dat enige volk, nasie of taal wat oneerbiedig spreek teen hulle Elohey van Sadrag, Mesag en Abednégo, stukkend gekap en van sy huis ’n mishoop gemaak sal word, omdat daar geen gode van andere is wat so kan verlos nie.	",
"	97{30} Toe het die koning, Sadrag, Mesag en Abednégo voorspoedig laat word in die provinsie Babel.	",

]
},
{
book: 'Daniël',
chapter: '4',
content: [
		
"	1 KONING Nebukadnésar aan al die volke, nasies en tale wat op die hele Aarde woon: Mag julle vrede groot wees!	",
"	2 Dit behaag my om die tekens en wonders wat die Hoogste Eloah aan my gedoen het, te verkondig.	",
"	3 Hoe groot is Sy tekens, en hoe magtig Sy wonders! Sy Koninkryk is ’n ewige Koninkryk, en Sy heerskappy is van geslag tot geslag!	",
"	4 Ek, Nebukadnésar, het rustig in my huis gelewe en was voorspoedig in my paleis.	",
"	5 Ek het ’n droomgesig gesien wat my verskrik het - droombeelde op my bed en die gesigte van my hoof het my verontrus.	",
"	6 Daarop is deur my bevel gegee om al die wyse manne van Babel voor my te bring, dat hulle my die uitlegging van die droom bekend kan maak.	",
"	7 Toe het die geleerdes, die besweerders, die Chaldeërs en die waarsêers gekom, en ek het hulle die droom vertel, maar hulle het sy uitlegging my nie bekend gemaak nie;	",
"	8 totdat eindelik DaniEl voor my ingekom het, wie se naam Béltsasar is, (na die naam van my god), en in wie die Gees van die Apartheid van Elohim is; en ek het hom die droom vertel:	",
"	9 Béltsasar, owerste van die geleerdes, van wie ek weet dat die Gees van die Apartheid van Elohim in jou is en dat geen enkele geheim jou kwel nie, vertel my die droomgesigte wat ek gesien het, naamlik die uitlegging daarvan.	",
"	10 Wat nou die gesigte van my hoof op my bed betref - ek het gesien, en kyk, daar was ’n Boom in die middel van die Aarde, en sy hoogte was groot.	",
"	11 Die Boom het groot geword en sterk, en sy hoogte het tot aan die Hemele gereik, sodat hy tot aan die einde van die hele Aarde sigbaar was.	",
"	12 Sy blare was mooi en sy vrugte baie, en aan hom was vir alles voedsel; onder hom het die diere van die veld skaduwee gesoek, en in sy takke het die voëls van die Hemele gewoon, ja, alle vlees is deur hom gevoed.	",
"	13 Ek het in die gesigte van my hoof op my bed gesien, en kyk, ’n Wagter, naamlik ’n Aparte, het uit die Hemele neergedaal;	",
"	14 hy het hardop geroep en so gesê: Kap die Boom om en kap sy takke af, trek sy blare af en verstrooi sy vrugte; laat die diere onder hom uit wegvlug en die voëls uit sy takke.	",
"	15 Maar laat sy penwortel in die Aarde staan, en hom met ’n band van yster en brons in die groen gras van die veld; en laat hy deur die Dou van die Hemele natgemaak word en saam met die diere deel hê aan die plante van die Aarde.	",
"	16 Laat sy hart anders word as dié van ’n adamiet en ’n dierehart aan hom gegee word, en laat sewe tydperke oor hom heengaan.	",
"	17 Op ’n besluit van die Wagters berus die bevel, en ’n woord van die apartes is die saak, met die bedoeling dat die lewendes kan erken dat die Hoogste El mag het oor die koningskap van die mens en haar gee aan wie HY wil, en die nederige onder die mense oor haar aanstel.	",
"	18 Dit is die droomgesig wat ek, koning Nebukadnésar, gehad het; en jy, Béltsasar, sê my die uitlegging, omdat al die wyse manne van my koninkryk my die uitlegging nie kon bekend maak nie; maar jy is daartoe in staat, want die Gees van die Apartheid van Elohim is in jou.	",
"	19 Toe het DaniEl, wie se naam Béltsasar was, ’n oomblik verstom gestaan en sy gedagtes het hom verskrik. Die koning het daarop gespreek en gesê: Béltsasar, laat die droom en die uitlegging jou nie verskrik nie. Béltsasar het geantwoord en gesê: My meester, mag die droom u haters en sy uitlegging u teëstanders oorkom.	",
"	20 Die Boom wat u gesien het - wat groot en sterk geword het, en waarvan die hoogte tot aan die Hemele gereik het en wat vir die hele Aarde sigbaar was,	",
"	21 en waarvan die blare mooi en die vrugte baie gewees het, en waar voedsel vir alles aan was, waaronder die wilde wesens van die veld gehou en in die takke waarvan die voëls van die Hemele gewoon het -	",
"	22 hy is u, o koning, wat groot en sterk geword het, wie se grootheid toegeneem het en reik tot aan die Hemele en u heerskappy tot aan die Einde van die Aarde.	",
"	23 En dat die koning ’n Wagter, naamlik ’n Aparte, uit die Hemele sien neerdaal het met die woorde: Kap die Boom om en verwoes hom, maar laat sy penwortel in die Aarde staan, en hom met ’n band van yster en brons in die groen gras van die veld, en laat hy deur die Dou van die Hemele natgemaak word en sy lot saam met die wilde wesens van die veld wees totdat sewe tydperke oor hom heengegaan het -	",
"	24 dit is die uitlegging, o koning, en dit is die besluit van die Hoogste El wat oor my meester die koning kom:	",
"	25 Hulle sal u uit die mensdom verstoot, en u woning sal saam met die wilde wesens van die veld wees, en hulle sal u soos die beeste plante laat eet; en u sal deur die dou van die Hemele natgemaak word, en sewe tydperke sal oor u heengaan totdat u erken dat die Hoogste El mag het oor die koningskap van die mens en haar gee aan wie HY wil. [MattithJaHûW 28:18]	",
"	26 En dat hulle bevel gegee het om die penwortel van die Boom te laat staan - u koningskap sal vir u bestendig wees vandat u erken het dat die Hemele heers.	",
"	27 Daarom, o koning, laat my raad u welgevallig wees en breek met u oortredinge deur regverdig te wees en met u ongeregtigheid deur barmhartigheid te bewys aan die ellendiges as daar verlenging van u rus moet wees.	",
"	28 Dit alles het oor koning Nebukadnésar gekom.	",
"	29 Aan die einde van twaalf maande terwyl hy op die koninklike paleis van Babel rondwandel,	",
"	30 het die koning aangehef en gesê: Is dit nie die groot Babel wat ek opgebou het tot ’n koninklike verblyf, deur die sterkte van my vermoë, en tot aansien van my eerbaarheid nie? [Miga 4:10]	",
"	31 Terwyl die woord nog in die mond van die koning was, val daar ’n stem uit die Hemele: Koning Nebukadnésar, jou word aangesê - die koningskap word jou ontneem;	",
"	32 en hulle sal jou uit die mensdom verstoot, en jou woning sal saam met die wilde wesens van die veld wees; hulle sal jou plante laat eet soos die beeste, en sewe tydperke sal oor jou heengaan, totdat jy erken dat die Hoogste El mag het oor die koningskap van die mens en dit gee aan wie HY wil.	",
"	33 Dieselfde oomblik het die woord in vervulling gegaan oor Nebukad-nésar - hy is uit die mensdom verstoot en het plante geëet soos die beeste, en deur die Dou van die Hemele is sy liggaam natgemaak, totdat sy hare lank geword het soos die vere van arende, en sy naels soos dié van voëls.	",
"	34 En ná verloop van tyd het ek, Nebukadnésar, my oë na die Hemele opgeslaan, en my verstand het in my teruggekeer, en ek het die Hoogste El geloof en HOM wat ewig lewe, geprys en geëer, wie se heerskappy ’n ewige mag en wie se koningskap van geslag tot geslag is.	",
"	35 En al die bewoners van die Aarde word as niks geag nie, en na SY wil handel HY met die Leër van die Hemele en die bewoners van die Aarde, en daar is niemand wat Sy Hand kan afslaan en vir HOM kan sê: Wat doen U nie?	",
"	36 In dié tyd het my verstand in my teruggekeer; en wat die eer van my koningskap betref - my eerbaarheid en my helderheid het in my teruggekeer, en my raadsmanne en my leiers het my opgesoek; en ek is in my koningskap herstel, en buitengewone grootheid is my toegevoeg.	",
"	37 Nou prys ek, Nebukadnésar, en ek roem en eer die Koning van die Hemele: al Sy werke is Waarheid en Sy Paaie is Reg, en Hy kan verneder die wat in hulle trotsheid wandel.	",

]
},
{
book: 'Daniël',
chapter: '5',
content: [
		
"	1 KONING Bélsasar het ’n groot fees berei vir sy duisend maghebbers, en in teenwoordigheid van die duisend het hy wyn gedrink.	",
"	2 By die genot van die wyn het Bélsasar bevel gegee om die goue en silwervoorwerpe te bring wat sy vader Nebukadnésar uit die Tempel van Jerusalem weggevoer het, sodat die koning en sy maghebbers, sy vroue en sy byvroue daaruit kon drink.	",
"	3 Toe het hulle die goue voorwerpe gebring wat uit die Tempel, uit die Huis van Eloah in Jerusalem weggevoer was, en die koning en sy maghebbers, sy vroue en sy byvroue het daaruit gedrink.	",
"	4 Hulle het wyn gedrink en die gode van goud en silwer, koper, yster, hout en klip geprys.	",
"	5 Op dieselfde oomblik het daar vingers van ’n mens se hand te voorskyn gekom en teenoor die kandelaar op die kalk van die muur van die koninklike paleis geskrywe, en die koning het die deel van die hand gesien wat geskrywe het.	",
"	6 Toe het die gelaatskleur van die koning verander, en sy gedagtes het hom verskrik, en die gewrigte van sy heupe het losgeraak, en sy knieë het teen mekaar geslaan.	",
"	7 Die koning het hardop uitgeroep om die besweerders, die Chaldeërs en die waarsêers in te bring. Daarop het die koning gespreek en aan die wyse manne van Babel gesê: Enigeen wat hierdie skrif lees en my sy uitlegging te kenne gee, hy sal met purper beklee word, en ’n goue ketting sal om sy hals wees, en as derde in rang sal hy in die koninkryk heers.	",
"	8 Toe het al die wyse manne van die koning ingekom, maar hulle was nie in staat om die skrif te lees en sy uitlegging aan die koning bekend te maak nie.	",
"	9 Toe het koning Bélsasar baie verskrik geword, en sy gelaatskleur het aan hom verander, ook sy maghebbers was in verwarring.	",
"	10 Na aanleiding van die woorde van die koning en van sy maghebbers het die koningin in die eetsaal ingegaan; die koningin het begin spreek en gesê: Mag die koning in ewigheid lewe! Laat u gedagtes u nie verskrik en u gelaatskleur nie verander nie.	",
"	11 Daar is ’n man in u koninkryk in wie die Gees van die Apartheid van Elohim is: in die dae van u vader is Lig en Insig en Wysheid soos die Wysheid van Elohim in hom gevind; daarom het u vader, koning Nebukadnésar, hom as owerste van die geleerdes, die besweerders, die Chaldeërs, die waarsêers aangestel - u vader, o koning! -	",
"	12 omdat in hom ’n voortreflike Gees van Kennis en Verstand gevind is om drome uit te lê en raaisels op te los en knope los te maak - in DaniEl aan wie die koning die naam van Béltsasar gegee het; laat DaniEl nou geroep word, dan sal hy die uitlegging te kenne gee.	",
"	13 Toe is DaniEl voor die koning gebring; die koning het begin spreek en vir DaniEl gesê: Is jy DaniEl wat by die ballinge uit JeHûWdah behoort, wat die koning, my vader, uit JeHûWdah gebring het?	",
"	14 Ek het van jou gehoor dat die Gees van Elohim in jou is, en dat Lig en Verstand en voortreflike Wysheid in jou gevind word.	",
"	15 Nou net is die wyse manne, die besweerders, voor my gebring om hierdie skrif te lees en sy uitlegging aan my bekend te maak; maar hulle is nie in staat om die uitlegging van die woord te kenne te gee nie.	",
"	16 Maar ek het van jou gehoor dat jy uitlegginge kan gee en knope kan losmaak; as jy nou die skrif kan lees en sy uitlegging aan my bekend maak, sal jy met purper beklee word en ’n goue ketting sal daar om jou hals wees, en jy sal as derde in rang in die koninkryk heers.	",
"	17 Toe het DaniEl geantwoord en voor die koning gesê: U kan u gawes maar vir uself hou en u geskenke aan ’n ander gee; nogtans sal ek die skrif vir die koning lees en die uitlegging aan hom bekend maak.	",
"	18 Wat u betref, o koning, die Hoogste Eloah het aan u vader Nebukadnésar koningskap en oorvloedigheid en eer en grootsheid gegee.	",
"	19 En vanweë die grootheid wat HY hom gegee het, het al die volke, nasies en tale gebewe en vir hom gesidder; wie hy wou, het hy gedood, en wie hy wou, het hy laat lewe, en wie hy wou, het hy verhoog, en wie hy wou, het hy verneder.	",
"	20 Maar net toe sy hart hom verhef het en sy gees verhard is om oormoedig te wees, is hy van die troon van sy koningskap afgestoot, en die eer is hom ontneem.	",
"	21 En hy is uit die mense verstoot, en sy hart het soos dié van diere geword, en hy het saam met die wilde-esels gewoon; hulle het hom plante laat eet soos die beeste, en deur die Dou van die Hemele is sy liggaam natgemaak totdat hy erken het dat die Hoogste Eloah mag het oor die koningskap van die mens en daaroor kan aanstel wie HY wil.	",
"	22 Maar u, Bélsasar, sy seun, het u hart nie verneder nie, alhoewel u dit alles weet;	",
"	23 maar u het u verhef teen die Koning van die Hemele, en die voorwerpe van Sy Huis het hulle voor u gebring; en u en u maghebbers, u vroue en u byvroue het wyn daaruit gedrink; en u het die gode van silwer en goud, koper, yster, hout en klip geprys, wat nie sien en nie hoor en nie weet nie, maar die Eloah in Wie se Hand u asem en voor wie al u paaie is, Hom het u nie vereer nie.	",
"	24 Toe is deur Hom die deel van die Hand gestuur en hierdie skrif geskrywe.	",
"	25 En dit is die skrif wat geskrywe is: @ysir]p’W lqeT] anEm] anEm]]]]]]]]]]] [MENÉ/Getel, MENÉ/Getel, TEKÉL/Geweeg, UFARSÍN/en verdeel].	",
"	26 Dit is die uitleg van die woord: MENÉ- Eloah het u koningskap getel en daar ’n einde aan gemaak;	",
"	27 TEKÉL - U is op die weegskaal geweeg en te lig bevind;	",
"	28 PERES/VERDEEL - U koninkryk is verdeel en aan die Meders en Perse gegee.	",
"	29 Toe het Bélsasar bevel gegee, en hulle het DaniEl met purper beklee, met ’n goue ketting om sy hals, en aangaande hom openlik uitgeroep dat hy as derde in rang in die koninkryk sou heers.	",
"	30 In dieselfde nag is Bélsasar, die koning van die Chaldeërs, gedood.	",
"	31 En Daríus, die Meder, was twee-en-sestig jaar oud toe hy die koningskap ontvang het.	",
		
"	[Hoofstuk 9 pas kronologies hier in.]	",

]
},
{
book: 'Daniël',
chapter: '6',
content: [
		
"	1 DIT het Daríus behaag om oor die koninkryk honderd-en-twintig landvoogde aan te stel wat in die hele koninkryk sou wees;	",
"	2 en oor hulle drie ministers, van wie DaniEl een was, aan wie dié landvoogde rekenskap moes gee, sodat die koning nie sou skade ly nie.	",
"	3 Toe het hierdie DaniEl bo die ministers en die landvoogde uitgemunt, omdat ’n voortreflike Gees in hom was; daarom was die koning van plan om hom oor die hele koninkryk aan te stel.	",
"	4 Toe het die ministers en die landvoogde gesoek om ’n grond vir ’n aanklag teen DaniEl te vind met betrekking tot die regering, maar hulle kon geen enkele grond vir ’n aanklag of verkeerde handeling vind nie, omdat hy getrou was en geen nalatigheid of verkeerde handeling by hom te vinde was nie.	",
"	5 Daarop het dié manne gesê: Ons sal teen hierdie DaniEl geen enkele grond vir ’n aanklag vind nie, tensy ons dit teen hom vind aangaande die Wet aan sy Elohey.	",
"	6 Toe het hierdie ministers en landvoogde die koning bestorm en só vir hom gesê: Mag koning Daríus vir ewig lewe!	",
"	7 Al die ministers van die koninkryk, die bevelhebbers en die landvoogde, die raadsmanne en die goewerneurs het beraadslaag dat die koning ’n verordening moet uitvaardig en ’n verbod bekragtig dat elkeen wat gedurende dertig dae ’n versoek rig aan enige Elohey of man behalwe aan u, o koning, in die leeukuil gegooi sal word.	",
"	8 Stel nou ’n verbod vas, o koning, en laat ’n bevelskrif skrywe wat volgens die onveranderlike wet van Meders en Perse onherroeplik is.	",
"	9 Hierom het koning Daríus die bevelskrif en die verbod geskrywe.	",
"	10 En net toe DaniEl verneem dat die bevelskrif geskrywe was, het hy in sy huis gegaan; en hy het in sy bo-kamer vensters gehad wat oop was in die rigting van Jerusalem, en hy het drie maal op ’n dag op sy knieë geval en gebid en lofprysinge uitgespreek voor sy Elohey, net soos hy tevore gedoen het.	",
"	11 Daarop het daardie manne aangestorm en DaniEl gevind terwyl hy bid en voor sy Elohey om Barmhartigheid smeek.	",
"	12 Hulle het toe nader gekom en voor die koning oor die koninklike verbod gespreek: Het u nie ’n verbod geskrywe dat elkeen wat gedurende dertig dae ’n versoek doen aan enige elohey of man behalwe aan u, o koning, in die leeukuil gegooi moet word nie? Die koning het geantwoord en gesê: Die saak staan vas volgens onherroeplike wet van Meders en Perse.	",
"	13 Toe het hulle geantwoord en voor die koning gesê: DaniEl, een van die ballinge uit JeHûWdah, het hom aan u, o koning, en aan u verbod wat u geskrywe het, nie gesteur nie, maar drie maal op ’n dag doen hy sy gebed.	",
"	14 Toe die koning die woord hoor, het dit hom baie mishaag, en hy het planne beraam om DaniEl te verlos, ja, tot sonsondergang toe het hy moeite gedoen om hom te red.	",
"	15 Daarop het daardie manne die koning bestorm en aan die koning gesê: Weet, o koning, dat dit ’n wet van Meders en Perse is dat elke verbod of verordening wat die koning vasgestel het, nie verander mag word nie.	",
"	16 Toe het die koning bevel gegee, en hulle het DaniEl gebring en in die leeukuil gegooi. Die koning het begin spreek en vir DaniEl gesê: Mag jou Elohey wat jy gedurigdeur vereer, jou verlos!	",
"	17 En ’n klip is gebring en op die opening van die kuil gelê, en die koning het haar met sy ring en met die ring van sy maghebbers verseël, sodat niks anders met DaniEl sou gebeur nie.	",
"	18 Toe het die koning na sy paleis gegaan en met vas die nag deurgebring en die byvroue nie voor hom laat kom nie, en sy slaap het van hom weggevlug.	",
"	19 Daarop het die koning die môre vroeg toe dit lig word, opgestaan en haastig na die leeukuil gegaan.	",
"	20 En toe hy nader kom na die kuil, het hy met ’n droewige stem na DaniEl geroep; die koning het gespreek en aan DaniEl gesê: DaniEl, kneg van die lewende Elohey, was jou Elohey wat jy gedurigdeur vereer, in staat om jou van die leeus te verlos?	",
"	21 Toe het DaniEl met die koning gespreek: Mag die koning vir ewig lewe!	",
"	22 My Elohey het SY Boodskapper gestuur en die bek van die leeus toegesluit, sodat hulle my geen leed aangedoen het nie, omdat ek voor Hom onskuldig bevind is en ek ook teen u, o koning, geen onreg gedoen het nie.	",
"	23 Toe het die koning baie bly geword en bevel gegee om DaniEl uit die kuil op te trek. So is DaniEl dan uit die kuil opgetrek sonder dat daar ’n letsel aan hom gevind is, omdat hy op sy Elohey vertrou het.	",
"	24 En die koning het bevel gegee, en hulle het daardie manne gebring wat DaniEl aangeklaag het, en hulle, hulle kinders en hulle vroue in die leeukuil gegooi; en hulle het nog nie die bodem van die kuil bereik nie of die leeus het hulle oorweldig en al hulle bene vermorsel.	",
"	25 Toe het koning Daríus aan al die volke, nasies en tale wat op die hele Aarde woon, geskrywe: Mag julle vrede groot wees!	",
"	26 Deur my word bevel gegee dat hulle in die hele magsgebied van my koninkryk moet bewe en sidder voor die Elohey van DaniEl, want Hy is die lewende Eloah en Hy bestaan in ewigheid en Sy Koninkryk is een wat nie vernietig kan word nie en Sy heerskappy duur tot die einde toe. [DaniEl 2:44; Openbaring 3:9]	",
"	27 Hy verlos en red en doen tekens en wonders in die Hemele en op Aarde, Hy wat DaniEl uit die mag van die leeus verlos het.	",
"	28 En hierdie DaniEl was voorspoedig onder die regering van Daríus en onder die regering van Kores, die Pers.	",

]
},
{
book: 'Daniël',
chapter: '7',
content: [
		
"	1 IN die eerste jaar van Bélsasar, die koning van Babel, het DaniEl ’n droomgesig gesien en gesigte van sy hoof op sy bed. Toe het hy die droom opgeskrywe, die hoofsaak vertel.	",
"	2 DaniEl het gespreek en gesê: Ek het in die nag in my gesig gesien, en kyk, die vier Geeste van die Hemele het die groot see in beroering gebring; [JirmeJaH 49:36]	",
"	3 en vier groot diere het uit die see opgeklim, die een verskillend van die ander.	",
"	4 Die eerste was soos ’n leeu, en het vlerke van ’n arend gehad; ek het bly kyk totdat haar vlerke uitgeruk is en sy van die Aarde af opgehef en soos ’n mens op twee voete neergesit is en aan haar is ’n mensehart gegee. [Openbaring 12:14]	",
"	5 En kyk, ’n ander, ’n tweede, het gelyk soos ’n beer, en sy het haarself opgelig aan die een kant; en drie ribbes was in haar bek tussen haar tande; en só het hulle vir haar gesê: Staan op, eet baie vleis.	",
"	6 Daarna het ek gesien, en kyk, daar was ’n ander een soos ’n luiperd, en sy het vier vlerke van ’n voël op haar rug gehad; ook het die dier vier koppe gehad, en aan haar is heerskappy gegee.	",
"	7 Daarna het ek in die naggesigte gesien, en kyk, daar was ’n vierde dier, vreeslik en skrikwekkend en baie sterk, en sy het groot ystertande gehad; sy het verslind en vermorsel en die oorskot met haar pote vertrap; en sy was verskillend van al die diere wat voor haar gewees het, en sy het tien horings gehad. [Openbaring 13:2]	",
"	8 Terwyl ek op die horings ag gee, kom daar ’n ander horinkie tussen hulle op, en drie van die vorige horings is daarvoor ontwortel; en kyk, in hierdie horing was oë soos mens-oë, en ’n mond wat groot dinge spreek.	",
"	9 Ek het bly kyk totdat trone reggesit is en ’n OUE van dae gaan sit het; SY kleed was wit soos sneeu en die hare van SY hoof soos skoon wol; SY Troon was vuurvlamme, die Wiele van hom ’n brandende vuur;	",
"	10 ’n stroom van vuur het gevloei en voor HOM uit gegaan; duisend maal duisende het HOM gedien, en tienduisend maal tienduisende het voor HOM gestaan; die Gereg het gaan sit, en die Boekrolle is geopen.	",
"	11 Ek het toe bly kyk vanweë die stem van die groot woorde wat die horing gespreek het; ek het bly kyk totdat die dier gedood en haar liggaam vernietig en aan die verbranding deur vuur oorgegee is.	",
"	12 Ook aan die ander diere is hulle heerskappy ontneem, en verlenging van die lewe is aan hulle gegee tot op tyd en uur.	",
"	13 Ek het gesien in die naggesigte, en kyk, met die Wolkkolom van die Hemele het Een gekom soos die Seun van ’n Mens, en Hy het gekom tot by die OUE van dae, en hulle het Hom nader gebring voor HOM. [Openbaring 5:5 - 9]	",
"	14 En aan Hom is gegee Heerskappy en Eer en Koningskap; en al die volke en nasies en tale het Hom vereer; Sy Heerskappy is ’n Ewige Heerskappy wat nie sal vergaan nie, en Sy Koninkryk een wat nie vernietig sal word nie. [Boekrol van Henog 25:3; Lukas 1:32-33]	",
"	15 Die Gees van my, DaniEl, is in sy omhulsel verontrus, en die gesigte van my hoof het my verskrik.	",
"	16 Ek het nader gekom na Een van die wat daar gestaan het, en van Hom sekerheid gevra oor dit alles; en Hy het dit vir my gesê en die uitlegging van die dinge aan my bekend gemaak:	",
"	17 Hierdie groot diere wat vier is - vier konings sal uit die Aarde opstaan;	",
"	18 en die apartes van die Hoogste El sal die koningskap ontvang, en hulle sal die Koninkryk in besit neem tot in ewigheid, ja, tot in alle ewigheid.	",
"	19 Toe wou ek sekerheid verkry oor die vierde dier wat van al die ander verskillend was, buitengewoon vreeslik, met ystertande en met koperkloue, wat verslind, vermorsel en die oorskot met haar pote vertrap het,	",
"	20 en oor die tien horings wat op haar kop was, en die ander een wat opgekom het en waarvoor drie geval het, naamlik hierdie horing wat oë en ’n mond gehad het wat groot dinge gespreek het, terwyl haar gestalte groter was as van die ander.	",
"	21 Ek het gesien dat hierdie horing oorlog voer met die apartes en hulle oorwin, [Openbaring 13:7]	",
"	22 totdat die Oue van dae kom en aan die Apartes van die Hoogste El Reg verskaf is en die bepaalde tyd gekom het dat die Apartes die Koninkryk in besit geneem het.	",
"	23 Só het Hy gesê: Die vierde dier - die vierde koninkryk sal op die Aarde wees, wat verskil van al die koninkryke en die hele Aarde sal verslind en sy sal haar vertrap en sy sal haar verbrysel.	",
"	24 En die tien horings - uit daardie koninkryk sal tien konings opstaan, en ’n ander een sal ná hulle opstaan, en hy sal verskillend wees van die voriges en drie konings neerwerp. [Prediker 4:13 - 16]	",
"	25 En hy sal woorde spreek teen die Hoogste El en die Apartes van die Hoogste El mishandel; en hy sal probeer om tye en Wet te verander, en hulle sal in sy hand oorgegee word gedurende ’n tyd en tye en die helfte van ’n tyd.	",
"	26 Maar die Gereg sal sit, en Hulle sal hom die heerskappy ontneem om haar vir goed te verdelg en te vernietig.	",
"	27 Dan word die koningskap en die heerskappy en die grootheid van die koninkryke onder die ganse Hemele gegee aan die volk van die Apartes van die Hoogste El; hulle Koninkryk is ’n ewige Koninkryk, en al die heerskappye sal hulle vereer en gehoorsaam wees.	",
"	28 Hier is die einde van die saak. Wat my, DaniEl, betref, my gedagtes het my baie verskrik en my gelaatskleur het verander aan my, maar die saak het ek in my hart bewaar.	",

]
},
{
book: 'Daniël',
chapter: '8',
content: [
		
"	1 IN die derde jaar van die regering van koning Bélsasar het aan my, DaniEl, ’n gesig verskyn ná dié een wat die vorige keer aan my verskyn het.	",
"	2 Ek het naamlik in die gesig gesien - terwyl ek kyk, was ek in die vesting Susan wat in die provinsie Elam lê; en ek het in die gesig gesien dat ek my aan die Ulairivier bevind het. [JirmeJaH 49:38 - 39]	",
"	3 En ek het my oë opgeslaan en gesien, en kyk, daar staan ’n ram voor die rivier; en hy het twee horings gehad, en die twee horings was hoog, ook was die een hoër as die ander, en die hoogste het laaste uitgekom. [Openbaring 13:1]	",
"	4 Ek het die ram sien stoot na die weste en na die noorde en na die suide, en al die diere kon voor hom nie standhou nie, en daar was niemand wat uit sy mag gered het nie; maar hy het gedoen volgens sy wil, en het magtig geword.	",
"	5 Terwyl ek daarop ag gee, kom daar ’n bokram uit die weste aan oor die oppervlakte van die hele Aarde, sonder om aan die Aarde te raak; en die bok het ’n aansienlike horing tussen sy oë gehad.	",
"	6 En hy het na die ram met die twee horings aangekom wat ek voor die rivier sien staan het, en hom in die woede van sy krag stormgeloop.	",
"	7 En ek het hom gesien hoe hy tot by die ram kom en op hom verbitterd word en die ram stoot en sy twee horings verbreek; en daar was geen krag in die ram om voor hom stand te hou nie, sodat hy hom teen die Aarde gegooi en hom vertrap het, en daar was niemand wat die ram uit sy mag gered het nie.	",
"	8 En die bok het uitermate magtig geword; maar toe hy sterk was, het die groot horing afgebreek, en vier aansienlike [horings] het in sy plek uitgekom na die vier windstreke van die Hemele.	",
"	9 En uit een van dié het ’n horing, eers klein, uitgekom, maar hy het baie groot geword na die suide en na die ooste en na die Pragtige Land toe.	",
"	10 En hy het groot geword tot by die Leër van die Hemele en het [sommige] van die Leër, naamlik van die Sterre, op die Aarde laat val en hulle vertrap.	",
"	11 Selfs tot by die Vors van die skeppings-leërmag het hy groot geword, sodat die voortdurende Hom ontneem en Sy Apartheidsplek neergewerp is.	",
"	12 En hy het ‘n leër oorgegee teen die voortdurende deur ‘n opstand; en hy het die Waarheid op die Aarde neergewerp en in sy optrede sukses gehad.	",
"	13 Toe hoor ek ’n apartgestelde spreek; en ’n ander apartgestelde het aan die een wat spreek, gesê: Hoe lank duur die gesig aangaande die voortdurende en die opstand van verwoesting - waar die plek van Apartheid sowel as die leër aan vertrapping oorgegee sal word? [Levítikus 26]	",
"	14 En hy het vir my gesê: Tweeduisend-driehonderd aande en môres, en dan sal Apartheid regverdig word.	",
"	15 En toe ek, DaniEl, die gesig gesien het, het ek probeer om haar te verstaan, en kyk, daar het iemand voor my gestaan wat soos ’n krygsman gelyk het.	",
"	16 En ek het ’n stem van ‘n adamiet gehoor uit die Ulai wat geroep en gesê het: GabriEl, laat hierdie een die gesig verstaan!	",
"	17 Toe kom hy by my staanplek; en toe hy kom, het ek geskrik en op my aangesig geval. En hy het vir my gesê: Let op, seun van adam, want die gesig sien op die tyd van die einde.	",
"	18 En terwyl hy met my spreek, het ek bewusteloos met my aangesig op die Aarde geval; toe het hy my aangeroer en my op my staanplek opgerig	",
"	19 en gesê: Kyk, ek maak jou bekend wat aan die einde van die strafgerig sal gebeur, want sy sien op die bepaalde tyd van die einde.	",
"	20 Die ram wat jy gesien het met die twee horings, is die konings van die Meders en die Perse.	",
"	21 En die harige bok is die koning van Griekeland; en die groot horing wat tussen sy oë was, hy is die eerste koning.	",
"	22 En dat hy gebreek is en vier in sy plek ontstaan het - vier koninkryke sal uit sy nasie ontstaan, maar nie met sy krag nie.	",
"	23 Maar aan die einde van hulle heerskappy, as die opstandiges die maat volgemaak het, sal ’n koning optree, hard van aangesig en wat raaisels verstaan.	",
"	24 En sy krag sal sterk word, maar nie deur sy krag nie; en hy sal [met] wonders vernietig en dit voorspoedig uitvoer; en hy sal magtiges vernietig en ook die volk van die apartes.	",
"	25 En op grond van sy slimheid sal hy met voorspoed bedrog pleeg, en hy sal groot dinge onderneem in sy hart en baie mense onverwags vernietig, ja, optree teen die Vors van die vorste, maar hy sal sonder toedoen van [mense]hand verbreek word. [DaniEl 2:45; 2 Ezra 11:40]	",
"	26 En die gesig van die aande en die môres waarvan gespreek is, sy is Waarheid; en jy, hou die gesig geheim, want sy sien op ’n verre toekoms.	",
"	27 En ek, DaniEl, was gedaan en was dae lank siek; daarna het ek opgestaan en die werk van die koning gedoen; en ek was verstom oor die gesig, maar niemand het dit gemerk nie. [2 Ezra 5:14]	",
		

]
},
{
book: 'Daniël',
chapter: '9',
content: [
		
"	1 IN die eerste jaar van Daríus, die seun van Ahasvéros, uit die saadlyn van die Meders, wat koning gemaak was oor die koninkryk van die Chaldeërs,	",
"	2 in die eerste jaar van sy regering het ek, DaniEl, in die Boekrolle gemerk dat die getal jare waaroor die Woord van JaHWeH tot die profeet JirmeJaH gekom het met betrekking tot die puinhope van Jerusalem, sewentig volle jare was.	",
"	3 En ek het my aangesig tot my Meester die Elohim gerig om met vas, en in roukleed en as, my aan gebed en smekinge te wy.	",
"	4 En ek het tot JaHWeH my Elohey gebid en belydenis gedoen en gesê: Ag, my Meester, grote en gedugte El, wat die Verbond en die Medelye hou vir die wat Hom liefhet en Sy Gebooie onderhou,	",
"	5 ons het oortree en verkeerd gedoen en besoedel gehandel en gerebelleer teen U deur van U Gebooie en Regsprake af te wyk.	",
"	6 En ons het nie geluister na U knegte, die profete, wat in U Naam gespreek het tot ons konings, ons owerstes en ons vaders en tot die hele volk van die Aarde nie.	",
"	7 Aan U, my Meester, kom die Geregtigheid toe, maar aan ons beskaming van die aangesig soos dit vandag is, aan die manne van JeHûWdah en aan die inwoners van Jerusalem en aan die hele JisraEl, die wat naby en die wat ver is in die Aarde waarheen U hulle verdryf het, oor hulle ontrou wat hulle teen U begaan het.	",
"	8 My Meester, aan ons kom toe beskaming van die aangesig, aan ons konings, aan ons owerstes en aan ons vaders, omdat ons teen U oortree het.	",
"	9 By my Meester onse Elohey is Barmhartigheid en vergewing, al het ons teen Hom gerebelleer	",
"	10 en na die Stem van JaHWeH onse Elohey nie geluister om te wandel in Sy Wette wat Hy ons deur die diens van Sy knegte, die profete, voorgehou het nie. [Deuteronómium 28]	",
"	11 Maar die hele JisraEl het U Wet oortree en afgewyk deurdat hulle nie na U Stem geluister het nie; daarom is die vloek en die eed oor ons uitgestort wat geskrywe is in die Wet van Moshè, die kneg van die Elohim, want ons het teen Hom oortree. [Levítikus 26]	",
"	12 En Hy het Sy Woorde in vervulling laat gaan wat Hy oor ons gespreek het en oor ons rigters wat ons bestuur het, deur groot besoedeling oor ons te bring wat onder die ganse Hemele nie gebeur het soos in Jerusalem nie;	",
"	13 soos in die Wet van Moshè geskrywe is - al hierdie besoedeling het oor ons gekom, en ons het die Aangesig van JaHWeH onse Elohey nie om Guns gesmeek deur ons te bekeer van ons ongeregtigheid en ag te gee op U Waarheid nie.	",
"	14 Daarom was JaHWeH wakker oor die besoedeling, om haar oor ons te bring; want JaHWeH onse Elohey is regverdig by al Sy werke wat Hy doen, maar ons het nie na Sy Stem geluister nie.	",
"	15 Nou dan,my Meester onse Elohey wat U volk uit die Aarde van Egipte met ’n Sterke Hand uitgelei en vir U ’n Naam gemaak het soos Hy vandag is, ons het oortree, ons was het besoedel geraak.	",
"	16 My Meester, laat tog volgens al U Geregtigheid U Toorn en U Grimmigheid van U Stad Jerusalem, berg van U Apartheid, afgewend word, want om ons oortredinge en die ongeregtigheid van ons vaders is Jerusalem en U volk ’n voorwerp van versmading vir almal rondom ons.	",
"	17 Hoor dan nou, onse Elohey, na die gebed van U kneg en na sy smekinge, en laat U Aangesig skyn oor U Apartheidsplek wat verwoes lê; vir my Meester se onthalwe.	",
"	18 Neig U Oor, my Elohey, en hoor, open U Oë en aanskou ons verwoeste plekke en die Stad waar U Naam oor uitgeroep is; want nie op grond van ons geregtigheid werp ons ons smekinge voor U Aangesig neer nie, maar op grond van U grote Barmhartigheid.	",
"	19 My Meester, hoor! My Meester, vergeef! My Meester, merk op en doen dit, vertoef tog nie, om U ontwil, my Elohey; want U Naam is oor U Stad en U volk uitgeroep.	",
"	20 Terwyl ek nog spreek en bid en my oortredinge en die oortredinge van my volk JisraEl bely en my smeking voor die Aangesig van JaHWeH my Elohey neerwerp, ter wille van die berg van Apartheid van my Elohey,	",
"	21 terwyl ek nog spreek in die gebed, het die Man GabriEl wat ek, uitgeput van vermoeienis, ’n vorige keer in die gesig gesien het, na my gekom omtrent die tyd van die aand spysbydrae.	",
"	22 En hy het my onderrig en met my gespreek en gesê: DaniEl, nou het ek heengegaan om jou Insig te gee. [2 Ezra 10:38]	",
"	23 By die begin van jou smekinge het ’n Woord uitgegaan, en ek het gekom om Hom mee te deel, want jy is ’n geliefde man; gee dan ag op die Woord en verstaan die gesig.	",
"	24 Sewentig sewetalle is oor jou volk en oor jou Stad van Apartheid bepaal, om die opstandigheid te voleindig en die oortredinge te beseël en om die maat vol te maak en om die ongeregtigheid te versoen en om ewige Geregtigheid aan te bring en om gesig en profeet te beseël en om wat Apartheid van Aparthede is, te salf.	",
"	25 Nou moet jy weet en verstaan: van die uitgang van die woord af om Jerusalem te herstel en op te bou tot op ’n Gesalfde Regeerder, is sewe sewetalle; en twee-en-sestig sewetalle lank sal sy herstel en opgebou word, met pleine en slote, maar in tye van benoudheid. [Exodus 12:2]	",
"	26 En ná die twee-en-sestig sewetalle sal die Gesalfde afgesny word, maar sonder iets vir Hom; en die volk van [die] regeerder wat sal kom, sal die Stad en die Apartheid verwoes, maar sy einde sal met ’n oorstroming wees, en tot die einde toe sal dit oorlog wees, vasbeslote verwoestings.	",
"	27 En Hy sal een week lank met baie ’n sterk Verbond sluit, en gedurende die helfte van die week sal Hy slagdier en spysbydrae laat ophou; en op die vleuel van gruwels sal daar ’n verwoester wees, en wel tot aan die einde; en wat vas besluit is, sal oor wat woes is, uitgestort word.	",

]
},
{
book: 'Daniël',
chapter: '10',
content: [
		
"	1 IN die derde jaar van Kores, die koning van die Perse, is ’n woord geopenbaar aan DaniEl wat Béltsasar genoem is, en die woord is Waarheid maar groot swarigheid; en hy het die woord verstaan en Insig gehad in die gesig.	",
"	2 In daardie dae het ek, DaniEl, drie volle weke getreur.	",
"	3 Brood van begeerte het ek nie geëet en vleis en wyn het nie in my mond gekom nie; en ek het my glad nie gesalf nie, totdat drie volle weke om was.	",
"	4 En op die vier-en-twintigste dag van die eerste maand, terwyl ek op die wal van die groot rivier was, dit is die Hiddékel(ontstuimige),	",
"	5 het ek my oë opgeslaan, en daar sien ek ’n Man met linne bekleed, en Sy heupe was omgord met goud van Ufas. [JeHôWshua 5:13, 14]	",
"	6 En Sy liggaam was soos chrisoliet, en Sy Aangesig soos die geflikker van bliksem en Sy oë soos fakkels van vuur en Sy arms en Sy voete soos blink geskuurde koper en die geluid van Sy woorde soos die gedruis van ’n menigte.	",
"	7 En ek, DaniEl, alleen het die gesig gesien, maar die manne wat saam met my was, het die gesig nie gesien nie; nogtans het ’n groot skrik hulle oorval, sodat hulle gevlug het om hulle te verberg.	",
"	8 Toe het ék alleen oorgebly en hierdie groot gesig gesien, en geen krag het in my oorgebly nie, en my gesonde kleur het aan my verander en verdwyn, en ek het geen krag oorgehou nie.	",
"	9 En ek het die geluid van Sy woorde gehoor, en toe ek die geluid van Sy woorde hoor, het ek bewusteloos op my aangesig, met my aangesig op die Aarde, geval.	",
"	10 En kyk, ’n hand het my aangeraak en my op my knieë en op die handpalms waggelend laat opstaan.	",
"	11 En Hy het vir my gesê: DaniEl, geliefde man, gee ag op die woorde wat Ek met jou spreek, en gaan staan op jou staanplek, want Ek is nou na jou gestuur. En terwyl Hy hierdie woord met my spreek, het ek in bewing gestaan.	",
"	12 Toe sê Hy vir my: Wees nie bevrees nie, DaniEl; want van die eerste dag af dat jy jou hart daarop gerig het om ag te gee en jou voor die Aangesig van jou Elohey te verootmoedig, is jou woorde gehoor, en om jou woorde ontwil het Ek gekom;	",
"	13 maar die vors van die koninkryk van die Perse het een-en-twintig dae lank teenoor My gestaan, en kyk, MikaEl, een van die vernaamste vorste, het gekom om My te help; en Ek het daar oorgebly by die konings van Persië.	",
"	14 Ek het dan gekom om jou inligting te gee oor wat jou volk aan die einde van die dae te beurt sal val, want die gesig sien nog op die verre toekoms.	",
"	15 En terwyl Hy hierdie woorde met my spreek, het ek my aangesig na die Aarde gedraai en stom geword.	",
"	16 En kyk, Een wat soos ’n adamiet gelyk het, het my lippe aangeraak. Toe het ek my mond oopgemaak en gespreek en aan Hom wat teenoor my staan, gesê: My Meester, deur die gesig het krampe my oorval en het ek geen krag oorgehou nie.	",
"	17 Want hoe kan ’n dienskneg van my Meester staande bly, terwyl hy met sy Meester spreek? Wat my aangaan, bestaan daar nou geen krag in my nie, en geen asem het in my oorgebly nie.	",
"	18 Toe het die een wat soos ’n adamiet gelyk het, my weer aangeraak en my versterk	",
"	19 en gesê: Wees nie bevrees nie, geliefde man, Vrede vir jou, wees sterk, ja, sterk! En terwyl Hy met my spreek, het ek moed geskep en gesê: My Meester kan maar spreek, want U het my versterk.	",
"	20 Toe sê Hy: Weet jy waarom Ek na jou gekom het? Ek moet dan nou teruggaan om te veg met die vors van die Perse; en as Ek heengegaan het, kyk, dan kom die vors van Jawan (Griekeland).	",
"	21 Nogtans sal Ek jou te kenne gee wat geskrywe is in die Geskrifte van die Waarheid; en daar is nie een wat hom saam met My dapper gedra teen hulle nie, behalwe julle vors MikaEl.	",

]
},
{
book: 'Daniël',
chapter: '11',
content: [
		
"	1 EN ek, in die eerste jaar van Darius,die Meder,het ek opgetree as ‘n versterking en beskutting vir hóm.	",
"	2 EN nou sal Ek jou die Waarheid te kenne gee. Kyk, nog drie konings sal opstaan vir die Perse, en die vierde sal groter rykdom verwerf as almal; en as hy sterk is deur sy rykdom, sal hy alles in beweging bring teen die koninkryk van Jawan (Griekeland).	",
"	3 Dan sal ’n dapper koning opstaan wat groot heerskappy sal hê en sal maak net soos hy wil.	",
"	4 En as hy opgetree het, sal sy koninkryk verbreek word en na die vier windstreke van die Hemele verdeel word; en dit sal nie aan sy nakomelingskap behoort en nie wees soos die heerskappy wat hy gehad het nie - want sy koninkryk sal verwoes word en nie aan hulle behoort nie, maar aan ander.	",
"	5 En die koning van die Suide sal sterk word, maar van sy vorste sal sterker word as hy en heers; sy heerskappy sal ’n groot heerskappy wees.	",
"	6 En ná verloop van jare sal hulle ’n bondgenootskap met mekaar aangaan, en die dogter van die koning van die Suide sal na die koning van die Noorde kom om vrede te sluit; maar sy sal die krag van die arm nie behou nie - hy en sy mag sal nie standhou nie, en sy self sal prysgegee word saam met die wat haar gebring het, sowel as hy wat haar verwek het en haar in dié tyd verwerf het.	",
"	7 Dan sal een uit die spruite van haar wortels in sy plek oprys en teen die leër optrek, en hy sal in die vesting(laer) van die koning van die Noorde indring en teen hulle optree en magtig wees;	",
"	8 ja, ook hulle gode en hulle dranke saam met hulle kosbare voorwerpe, silwer en goud, in gevangenskap na Egipte bring, en hy sal jare lank die koning van die Noorde met rus laat.	",
"	9 Dan sal dié in die koninkryk van die koning van die Suide intrek, maar hy sal na sy Adamah [die adamiet se Aarde] terugtrek.	",
"	10 En sy seuns sal hulle in die oorlog begewe en ’n menigte groot leërs versamel; en hy sal sekerlik aankom en instroom en oorloop, en weer terugkom, en hulle sal oorlog voer tot by sy vesting(laer).	",
"	11 Dan sal die koning van die Suide verbitterd word en uittrek en teen hom, die koning van die Noorde, veg, wat [ook] ’n groot menigte op die been sal bring, maar hierdie menigte sal in sy hand oorgegee word.	",
"	12 As die menigte vernietig is, sal sy hart hom verhef; en hy sal tienduisende neerslaan, maar nie sterk bly nie.	",
"	13 Dan sal die koning van die Noorde weer ’n groter menigte op die been bring as die eerste, en ná verloop van tyd, van jare, sal hy sekerlik kom met ’n groot leër en ’n groot gevolg.	",
"	14 En in dié tye sal baie teen die koning van die Suide opstaan, en die gewelddadige burgers van jou volk sal hulle verhef om ’n gesig in vervulling te laat gaan, maar hulle sal omkom.	",
"	15 So sal dan die koning van die Noorde kom en ’n wal opwerp en ’n versterkte Stad inneem; en die leërs van die Suide sal nie standhou nie, selfs sy uitgesoekte manskappe nie, sodat daar geen krag sal wees om stand te hou nie.	",
"	16 En hy wat [uit die Noorde] teen hom kom, sal maak net soos hy wil, en niemand sal voor hom standhou nie; hy sal ook gaan staan in die Pragtige Aarde, terwyl daar verdelging in sy hand is.	",
"	17 En hy sal sy aangesig daarop rig om met die sterkte van sy hele koninkryk te kom, maar hy sal met hom vrede sluit; en hy sal vir hom ’n jongedogter gee om te gronde te rig. Maar dit sal nie tot stand kom nie, en daar sal niks vir hom wees nie.	",
"	18 Daarna sal hy sy aangesig wend na die kuslande en baie daarvan verower; maar ’n aanvoerder sal aan sy gesmaad ’n einde maak, ja, hy sal sy gesmaad op homself laat terugval.	",
"	19 Dan sal hy sy aangesig wend na die vesting van sy Aarde, maar hy sal struikel en val en nie meer gevind word nie.	",
"	20 En in sy plek sal iemand optree wat ’n geldinsamelaar deur die pragtigste deel van die koninkryk sal laat deurtrek, maar binne enkele dae sal hy verbreek word, maar nie deur toorn of deur oorlog nie.	",
"	21 Daarna sal ’n veragtelike in sy plek optree op wie geen koninklike waardigheid gelê was nie, maar hy sal onverwags kom en met liste die koninkryk bemagtig.	",
"	22 En die leërs van die instromende mag sal voor hom weggespoel en verbreek word, en ook die Vors van die Verbond.	",
"	23 Want sodra ’n bondgenootskap met hom aangegaan is, pleeg hy bedrog; en hy sal omhoog kom en met min manskappe sterk word.	",
"	24 Onverwags en in die vetste dele van die provinsie sal hy inkom, en hy sal doen wat sy vaders en sy grootvaders nie gedoen het nie: roof en buit en goed sal hy onder hulle uitstrooi en teen vestings planne beraam, maar net vir ’n tyd.	",
"	25 En hy sal sy krag en sy hart opwek teen die koning van die Suide met ’n groot leër; en die koning van die Suide sal hom in die oorlog begewe met ’n groot en baie sterk leër, maar hy sal nie standhou nie, want hulle sal planne teen hom beraam.	",
"	26 En die wat sy spys eet, sal hom te gronde rig; en sy leër sal wegvloei, en daar sal baie gesneuweldes lê.	",
"	27 En wat die twee konings betref, hulle hart sal wees om te besoedel; en aan een tafel sal hulle leuens spreek, maar dit sal nie gebeur nie, want die einde sal eers op die vasgestelde tyd wees.	",
"	28 En hy sal na sy Aarde teruggaan met baie goed, en sy hart sal teen die Verbond van Apartheid wees, en hy sal optree en na sy Aarde teruggaan. [JeshaJaH 35:8]	",
"	29 Op die vasgestelde tyd sal hy terugkeer en in die Suide kom, maar dit sal die laaste keer nie wees soos die eerste keer nie.	",
"	30 Want skepe van die Kittiërs sal teen hom kom, en hy sal moedeloos word; dan sal hy teruggaan en sy toorn openbaar teen die Verbond van Apartheid en optree; en hy sal teruggaan en ag gee op die wat die Verbond van Apartheid versaak het.	",
"	31 En uitgestrekte arms sal van hulle opgaan en hulle sal die Apartheidsplek, die laer/vesting, besoedel, en hulle sal die voortdurende opsy stoot en die veragtelike gruwel oprig wat verlate maak. [Exodus 25:30]	",
"	32 En die wat besoedel handel teen die Verbond, sal hy met vleiery afvallig maak, maar die volk wat sy Elohey ken, sal vashou en optree.	",
"	33 En die verstandiges onder die volk sal baie tot insig bring; maar hulle sal struikel deur swaard en vlam, deur gevangenskap en berowing, dae lank.	",
"	34 En terwyl hulle struikel, sal hulle met ’n klein Hulp ondersteun word; dan sal baie uit listigheid by hulle aansluit.	",
"	35 En sommige van die verstandiges sal faal, om hulself te veredel, om hulself uit te suiwer en om hulself te verblank tot die tyd van die einde - want dit sal nog duur tot op die vasgestelde tyd.	",
"	36 En die koning sal doen net soos hy wil en homself verhef en hom groot hou bo al die elim(elle), en teen die El van die elim(elle) sal hy wonderbaarlike dinge spreek; en hy sal voorspoedig wees, totdat die grimmigheid ten einde is; want wat vas besluit is, sal uitgevoer word.	",
"	37 En op die gode van sy vaders sal hy nie ag slaan nie, en op die begeertes van die vroue en op enige godin sal hy geen ag gee nie; want hy sal homself bo alles groot hou.	",
"	38 Maar in plaas daarvan sal hy die godin van die vestings vereer, en die godin wat sy vaders nie geken het nie, sal hy met goud en silwer en edelgesteente en kosbaarhede vereer.	",
"	39 So sal hy dan optree teen die versterkte vestings met behulp van ’n vreemde godin; diegene wat hy erken, sal hy baie eer en hulle oor baie laat heers en die Adamah[adamiet se Aarde] as beloning uitdeel.	",
"	40 Maar in die tyd van die einde sal die koning van die Suide met hom in botsing kom, en die koning van die Noorde sal op hom afstorm met strydwaens en perderuiters en baie skepe, en hy sal daarmee in die Aarde inkom en instroom en haar oorvloei.	",
"	41 Hy sal ook kom in die Pragtige Land, en baie sal struikel; maar hierdie [volke] sal uit sy hand vryraak: Edom en Moab en die beste deel van die kinders van Ammon.	",
"	42 En hy sal sy hand uitsteek teen die Aarde; ook die Aarde van Egipte sal nie vrykom nie.	",
"	43 En hy sal mag hê oor die skatte van goud en silwer en oor al die kosbaarhede van Egipte, terwyl die Líbiërs en die Kuwshiete sy voetstappe volg.	",
"	44 Maar gerugte uit die ooste en uit die noorde sal hom verskrik; daarom sal hy met groot woede uittrek om ‘n menigte te verdelg en met die banvloek te tref.	",
"	45 En hy sal sy paleistente opslaan tussen die see en die berg van apartheidsprag; maar hy sal aan sy einde kom, en daar sal vir hom geen helper wees nie.	",

]
},
{
book: 'Daniël',
chapter: '12',
content: [
		
"	1 EN in dié tyd sal MikaEl, die groot vors wat oor die kinders van jou volk staan, optree; en dit sal ’n tyd van benoudheid wees soos daar nie gewees het vandat ’n volk bestaan het tot op dié tyd nie; maar in dié tyd sal jou nasie gered word, elkeen wat in die Boekrol opgeskrywe staan. [Boekrol van Henog 20:5]	",
"	2 En baie van die wat in die stof van die Aarde slaap, sal ontwaak, sommige tot die Ewige Lewe en sommige tot groot skande, vir ewig afgryslik. [JeségiEl 37:10; 2 Ezra 7:32]	",
"	3 En die verstandiges sal glinster soos die glans van die Koepel, en die wat baie tot Geregtigheid lei, soos die Sterre vir ewig en ewig. [2 Ezra 7:134]	",
"	4 En jy, DaniEl, hou die woorde geheim en verseël die Boekrol tot die tyd van die einde toe; baie sal hom deursoek, en die Kennis sal vermeerder.	",
"	5 En ek, DaniEl, het gesien, en kyk daar het twee ander gestaan, die een duskant op die wal van die rivier en die ander oorkant op die wal van die rivier.	",
"	6 En een het aan die Man, met linne bekleed, wat bo-oor die water van die rivier was, gesê: Hoe lank sal die einde van hierdie wonderbaarlike dinge uitbly?	",
"	7 Toe hoor ek die Man, met linne bekleed, wat bo-oor die water van die rivier was, en Hy het Sy regterhand en Sy linkerhand na die Hemele opgehef en gesweer by die Ewig-Lewende: ’n Tyd, tye en ’n halwe tyd en as hulle die Hand van die volk van Apartheid geheel verstrooi het, sal al hierdie dinge vervul word.	",
"	8 En ek het dit gehoor, maar nie verstaan nie; daarom het ek gesê: My Meester, wat is die uiteinde van hierdie dinge?	",
"	9 En Hy het gesê: Gaan heen, DaniEl, want die woorde bly verborge en verseël tot die tyd van die einde toe.	",
"	10 Baie sal hulself veredel, hulself verblank en hulself uitsuiwer, maar die besoedelde sal meer besoedel word; en geeneen van die besoedeldes sal verstaan nie, maar die verstandiges sal verstaan. [Boekrol van Henog 38:4; Openbaring 22:11]	",
"	11 En van die tyd af dat die voortdurende afgeskaf en die veragtelike gruwel opgerig word wat lei tot die verwoesting, sal duisend-tweehonderd-en-negentig dae verloop.	",
"	12 Geseënd is hy wat bly verwag en duisend-driehonderd vyf-en-dertig dae bereik.	",
"	13 En jy, gaan heen na die einde; en jy sal rus en staan in jou roeping aan die einde van die dae.	",
		

]
},
{
book: 'Daniël',
chapter: '13',
content: [
		
"	1 DAAR het eenmaal in Babel ‘n man met die naam JeHôWjakim gewoon.	",
"	2 Hy het in die huwelik getree met ‘n vrou wie se naam Susanna was, die dogter van HilkiJaH, ‘n besonder mooi vrou wat JaHWeH gevrees het. [Hooglied 2:2; 2 Ezra 5:24]	",
"	3 Haar ouers was vroom mense en het hulle dogter in die Wet van Moshè onderrig.	",
"	4 JeHôWjakim was baie ryk en het ‘n pragtige tuin naas sy huis gehad; en die Hebreërs was gewoond om hom te besoek omdat hy die aansienlikste van hulle almal was.	",
"	5 In daardie jaar is twee van die oudstes van die volk tot regters aangestel, mense van die soort van wie JaHWeH gesê het: Ongeregtigheid het uit Babel voortgekom, van oudstes wat regters was, wat veronderstel was om die volk te regeer.	",
"	6 Hierdie manne het gereeld in die huis van JeHôWjakim verkeer, en almal wat ‘n regsaak gehad het, het hulle daar besoek.	",
"	7 Wanneer die mense dan in die namiddag vertrek het, het Susanna gewoonlik in die tuin van haar man gaan wandel.	",
"	8 En die twee oudstes wat haar daagliks sien ingaan en rondwandel het, is deur ‘n hartstogtelike begeerte na haar oorweldig.	",
"	9 So het hulle hul gedagtes besoedel en hulle oë afgewend om nie na die Hemele op te kyk en aan regverdige regsbeslissinge te dink nie.	",
"	10 En alhoewel albei smoorverlief op haar was, het hulle nie hul smart aan mekaar durf openbaar nie,	",
"	11 want hulle was skaam om hulle hartstog bekend te maak, want hulle het begeer om met haar gemeenskap te hê.	",
"	12 En daagliks het hulle met ywer elke geleentheid waargeneem om haar te sien.	",
"	13 En die een het vir die ander gesê: Laat ons huis toe gaan, want dit is tyd vir die middagete.	",
"	14 En toe hulle uitgaan, het hulle van mekaar geskei, maar in die stilligheid het hulle weer teruggekeer en by mekaar uitgekom. En toe hulle mekaar na ‘n verklaring uitvra, het hulle hul hartstog erken. Toe het hulle ooreengekom op ‘n tyd wanneer hulle haar alleen sou kon aantref.	",
"	15 Nou het dit gebeur dat terwyl hulle na ‘n geskikte geleentheid uitgesien het, sy volgens haar daaglikse gebruik met slegs twee diensmeisies in die tuin gegaan het met die bedoeling om haar te bad omdat dit so warm was. [Spreuke 9:3]	",
"	16 En daar was niemand nie, behalwe die twee oudstes wat hulleself verskuil het en besig was om haar te bespied.	",
"	17 En sy het vir haar diensmeisies gesê: Bring vir my Olyfolie en seep en maak die hekke van die tuin toe sodat ek kan bad.	",
"	18 En hulle het gedoen soos sy gesê het en die hekke van die tuin gesluit, en by die sydeure uitgegaan om die gevraagde goed te gaan haal; en hulle het die oudstes nie gesien nie, want hulle het hul skuilgehou.	",
"	19 En toe die diensmeisies uit is; het die twee oudstes opgespring en na [Susanna] toe gehardloop en gesê:	",
"	20 Kyk, die hekke van die tuin is gesluit, en niemand kan ons sien nie; ons begeer jou, daarom willig in en voldoen aan ons begeerte.	",
"	21 As jy dit nie doen nie, sal ons teen jou getuig dat daar ‘n jong man saam met jou was en dat dit die rede is waarom jy jou diensmeisies weggestuur het.	",
"	22 Toe het Susanna gesug en gesê: Ek is van alle kante vasgekeer, want as ek dit doen, sal dit my dood beteken, en as ek weier, kan ek uit julle hande nie ontvlug nie.	",
"	23 Dit is vir my egter verkiesliker om in julle hande te val en dit nie te doen nie, as om voor die Aangesig van JaHWeH te oortree.	",
"	24 Toe het Susanna hardop geskreeu, maar die oudstes het teen haar in geroep.	",
"	25 Die een het toe gehardloop en die tuinhekke oopgemaak.	",
"	26 Toe die huisbediendes die geskreeu in die tuin hoor, het hulle by die sydeur ingestorm om vas te stel wat met haar gebeur het.	",
"	27 Maar toe die oudstes hulle verhaal vertel het, was die bediendes baie skaam omdat so iets nog nooit in verband met Susanna gesê is nie.	",
"	28 En dit het gebeur toe die mense die volgende dag by haar eggenoot JeHôWjakim byeengekom het dat die twee oudstes ook daar opgedaag het met die besoedelde bedoeling om Susanna om die lewe te laat bring.	",
"	29 En hulle het ten aanhore van die mense gesê: Laat Susanna, die dogter van HilkiJaH, die vrou van JeHôWjakim, hier verskyn.	",
"	30 En hulle het gestuur. En sy het gekom saam met haar ouers en haar kinders en haar hele familie.	",
"	31 Nou was Susanna ‘n besonder beskeie vrou en mooi van aansien.	",
"	32 En hierdie wettelose manne het beveel dat haar sluier afgeneem moes word - want sy was gesluierd - sodat hulle hul in haar skoonheid kon verlustig. [2 Ezra 7:26]	",
"	33 Maar hulle wat by haar was en almal wat haar gesien het, het geween.	",
"	34 En die twee oudstes het te midde van die mense opgestaan en hul hande op haar hoof gelê.	",
"	35 Maar sy het terwyl sy huil, na die Hemele opgekyk, want haar hart het op JaHWeH vertrou.	",
"	36 Toe het die oudstes gesê: Terwyl ons alleen in die tuin rondgewandel het, het hierdie vrou saam met twee diensmeisies ingekom, die hekke van die tuin gesluit en die diensmeisies weggestuur.	",
"	37 Toe het ‘n jong man wat daar verskuil was, na haar toe gekom en met haar gemeenskap gehad.	",
"	38 En ons was juis in die hoek van die tuin, en toe ons hierdie skandelike daad sien, het ons na hulle toe gehardloop,	",
"	39 en alhoewel ons hulle saam gesien het, was ons nie in staat om hom vas te hou nie omdat hy sterker as ons was, en hy het die hekke oopgemaak en uitgehardloop.	",
"	40 Maar ons het hierdie vrou gegryp en haar gevra wie die jong man was, dog sy wou ons nie vertel nie. Dit is ons getuienis.	",
"	41 En die vergadering het hulle geglo omdat hulle oudstes van die volk en regters was, en hulle het haar tot die dood veroordeel.	",
"	42 Maar Susanna het met ‘n groot stem uitgeroep en gesê: 0 Ewige Elohim, U wat die verborge dinge ken en van alles weet voordat dit plaasgevind het;	",
"	43 U weet dat die dinge wat hulle teen my getuig het, vals is, en nou moet ek sterwe terwyl ek niks gedoen het van die dinge waarvan hulle my op kwaadwillige wyse beskuldig het nie.	",
"	44 En JaHWeH het haar geroep gehoor.	",
"	45 Want toe sy weggelei is om gedood te word, het Elohim die Gees van die Apartheid in ‘n jong man met die naam DaniEl opgewek,	",
"	46 en hy het hardop uitgeroep: Ek is onskuldig aan die bloed van hierdie vrou!	",
"	47 Toe het al die mense hulle na hom toe gekeer en gesê: Wat beteken die woord wat jy daar gespreek het?	",
"	48 En terwyl hy in die middel van hulle gestaan het, het hy gesê : O kinders van JisraEl, hoe is julle so dwaas dat julle ‘n dogter van JisraEl sonder behoorlike ondersoek en van ‘n bevestiging van die Waarheid, veroordeel het? [JeHôWganan 16]	",
"	49 Gaan terug na die plek van die gereg, want hierdie manne het valse getuienis teen haar gelewer.	",
"	50 Daarop het al die mense haastig teruggekeer. En die oudstes het vir hom gesê: Kom, neem jou plek tussen ons in en onderrig ons, want Elohim het aan jou die eer van ‘n oudste gegee.	",
"	51 En DaniEl het vir hulle gesê: Laat hulle ver van mekaar af staan en ek sal hulle ondervra.	",
"	52 Toe hulle dan van mekaar geskei is, het hy een van hul nader geroep en vir hom gesê: O jy wat oud geword het in ongeregtigheid, hoe het die oortreding wat jy vantevore bedryf het, jou ingehaal	",
"	53 deurdat jy onwettige regsbeslissinge gevel het, die onskuldiges veroordeel en die skuldiges vry laat uitgaan het, ten spyte van die Woord van JaHWeH dat jy die onskuldige en die regverdige nie mag ombring nie.	",
"	54 En nou, as jy hierdie vrou gesien het, vertel ons onder watter boom het jy hulle bymekaar gesien? En hy het geantwoord: Onder ‘n mastikboom.	",
"	55 Toe sê DaniEl: Jy het ten koste van jou lewe ‘n leuen vertel, want ‘n Boodskapper van JaHWeH het reeds die oordeel van Elohim ontvang, en Hy sal jou middeldeur kap.	",
"	56 Daarop het hy hom opsy laat staan en beveel dat hulle die ander een moes inbring. En aan hom het hy gesê: 0 jou saadlyn van Kanaän en nie van JeHûWdah nie, skoonheid het jou mislei en begeerte het jou hart bederf.	",
"	57 Dit is die wyse waarop jy die dogters van JisraEl wat hulle uit vrees aan jou oorgegee het, behandel het, maar hierdie dogter van JeHûWdah het haar nie aan jou besoedeling onderwerp nie.	",
"	58 Daarom vertel my onder watter boom het jy hulle betrap terwyl hulle mekaar omhels het? En hy het gesê: Onder ‘n akkerboom.	",
"	59 Toe het DaniEl vir hom gesê: Ook jy het ‘n leuen ten koste van jou lewe vertel, want ‘n Boodskapper van JaHWeH wag reeds met Sy swaard om jou middeldeur te kap en om julle albei te verdelg.	",
"	60 En die hele vergadering het hardop uitgeroep en JaHWeH geloof, omdat Hy hulle verlos wat op Hom hoop.	",
"	61 En hulle het hul gewerp op die twee oudstes wat deur DaniEl uit hulle eie mond as valse getuies ontmasker is,	",
"	62 en met hulle gehandel soos hulle op kwaadwillige wyse van plan was om met hulle naaste te doen; en hulle het hul ooreenkomstig die Wet van Moshè om die lewe gebring. En op daardie dag is die vergieting van onskuldige bloed voorkom.	",
"	63 En HilkiJaH en sy vrou het JaHWeH geloof vir hulle dogter Susanna, saam met haar eggenoot JeHôWjakim en haar hele familie, omdat sy niks verkeerds gedoen het nie. [Openbaring 14]	",
"	64 En van daardie dag af en verder het DaniEl groot aansien in die oë van die volk geniet.	",

]
},
{
book: 'Daniël',
chapter: '14',
content: [
		
"	1 TOE koning Astyages by sy vaders versamel is, het die Pers, Cyrus, hom in sy koninkryk opgevolg.	",
"	2 En DaniEl was ‘n vertroueling van die koning en is meer as al sy vriende geëer.	",
"	3 En nou het die Babel-inwoners ‘n idool met die naam van Bel gehad, waaraan hulle daagliks twaalf groot mate fynmeel, veertig skape en ses mate wyn bestee het.	",
"	4 Die koning het hierdie idool vereer en het daagliks heengegaan om hom te aanbid, maar DaniEl het sy eie Elohey aanbid. En die koning het vir hom gesê: Waarom aanbid jy Bel nie?	",
"	5 En hy antwoord: Omdat ek nie idole wat met die hande gemaak is, vereer nie, maar die lewende Elohim wat Hemele en Aarde geskape het en wat heerskappy het oor alle vlees.	",
"	6 Toe sê die koning vir hom: Glo jy nie dat Bel ‘n lewende el is nie? Sien jy dan nie hoeveel hy elke dag eet en drink nie?	",
"	7 Maar DaniEl lag en sê: Moenie u laat mislei nie, o koning, want hy bestaan slegs van klei van binne en koper van buite en hy het nog nooit enigiets geëet of gedrink nie.	",
"	8 Toe word die koning kwaad en hy roep die priesters van Bel en sê vir hulle: As julle my nie kan vertel wie dit is wat hierdie voorrade opeet nie, sal julle sterwe,	",
"	9 maar as julle my kan bewys dat Bel dit eet, sal DaniEl sterwe, want hy het lasterlik teen Bel gespreek. En Daniel sê vir die koning: Laat dit geskied volgens u woord!	",
"	10 Nou was daar sewentig priesters van Bel, behalwe hulle vrouens en kinders. En die koning vergesel van DaniEl het na die tempel van Bel gegaan.	",
"	11 Toe sê die priesters van Bel: Kyk, ons sal buitentoe gaan, en plaas u self, o koning, die voedsel op die tafel en bied u self die gemengde wyn aan en grendel die deure en verseël dit met u seëlring.	",
"	12 En as u in die môre terugkom en u vind dat Bel dit nie alles opgeëet het nie, sal ons sterwe, of anders sal DaniEl wat hierdie valse beskuldiginge teen ons gemaak het, [sterwe].	",
"	13 En hulle was onbevrees, want hulle het ‘n verborge ingang onder die tafel gemaak en daardeur het hulle gereeld ingegaan en hierdie dinge verteer.	",
"	14 En toe hulle uitgegaan het, gebeur dit dat die koning die voedsel vir Bel op die tafel plaas. Toe beveel DaniEl sy diensknegte om as te bring, en voor die aangesig slegs van die koning, strooi hulle dit oor die hele tempel. Daarna gaan hulle uit, sluit die deur en verseël dit met die koning se seëlring, en vertrek.	",
"	15 En die priesters het soos gewoonlik in die nag met hulle vrouens en kinders gekom en dit alles opgeëet en gedrink.	",
"	16 Die volgende môre staan die koning vroeg op, en DaniEl vergesel hom.	",
"	17 En die koning sê: DaniEl, is die seëls nog ongeskonde? En hy antwoord: Hulle is ongeskonde, o koning!	",
"	18 En nadat hy die deure oopgemaak het, kyk die koning na die tafel en roep hardop uit: Groot is u, o Bel, en daar is geen bedrog aan u nie!	",
"	19 Maar Daniel lag en hou die koning teë sodat hy nie kan ingaan nie en sê: Let op die vloer en kyk wie se voetspore dit is.	",
"	20 Toe sê die koning: Ek sien die voetspore van manne, vroue en kinders!	",
"	21 En die koning het kwaad geword en die priesters en hulle vrouens en kinders gegryp, en hulle het hom die geheime ingang gewys waardeur hulle ingekom het om die dinge wat op die tafel was, te verteer.	",
"	22 Toe het die koning hulle om die lewe gebring en Bel aan DaniEl prysgegee, wat hom saam met sy tempel vernietig het.	",
"	23 Daar was ook ‘n groot draak wat die Babel-inwoners vereer het. [Odes van Salomo 22:5]	",
"	24 Toe sê die koning vir DaniEl: Van hom sal jy tog nie kan beweer dat hy van koper is nie. Kyk, hy leef, hy eet en drink. Van hom kan jy nie sê dat hy nie ‘n lewende el is nie, daarom, aanbid hom!	",
"	25 Maar DaniEl antwoord: Ek sal JaHWeH, my Elohey, aanbid, want Hy is ‘n lewende El.	",
"	26 Dog met u verlof, o koning, sal ek hierdie draak sonder swaard of stok verslaan. En die koning sê: Ek gee jou my verlof!	",
"	27 Toe neem DaniEl pik en vet en hare en kook dit deurmekaar, en nadat hy brokstukke daarvan gemaak het, steek hy dit in die bek van die draak, en hy [die draak] het dit geëet en oopgebars. En hy [DaniEl] het gesê: Kyk, die voorwerpe van julle aanbidding!	",
"	28 Toe die Babel-inwoners dit hoor, het hulle baie kwaad geword en teen die koning saamgesweer en gesê: Die koning het ‘n Hebreër geword! Hy het Bel vernietig, die draak doodgemaak en die priesters om die lewe gebring!	",
"	29 Daarop het hulle na die koning gegaan en gesê: Lewer DaniEl aan ons uit, of anders sal ons u en u huisgesin doodmaak.	",
"	30 Toe die koning sien dat hulle sterk by hom daarop aandring, het hy noodgedwonge DaniEl aan hulle uitgelewer.	",
"	31 En hulle het hom in die leeukuil gewerp, en daar het hy ses dae gebly.	",
"	32 En daar was sewe leeus in die kuil, en hulle het gewoonlik elke dag twee lyke en twee skape aan hulle gegee; maar toe het hulle hul niks gegee nie, sodat hulle DaniEl sou verslind.	",
"	33 Nou was daar in JeHûWdah die profeet Habakuk wat ete voorberei en brood in ‘n kom gebrokkel het en wat op die punt was om hom na oeswerkers op die landerye te neem.	",
"	34 Maar die Boodskapper van JaHWeH sê vir Habakuk: Bring die voedsel wat jy daar het na Babel, na DaniEl in die leeukuil.	",
"	35 Maar Habakuk antwoord: Meester, Babel het ek nog nooit gesien nie, en die kuil ken ek nie.	",
"	36 Toe gryp die Boodskapper van JaHWeH hom aan sy kop en tel hom aan die hare van sy hoof op en laat hom met die snelheid van wind in Babel reg bo die kuil neer.	",
"	37 En Habakuk roep uit: DaniEl, DaniEl! Neem die middagmaal wat Elohim jou gestuur het!	",
"	38 Toe sê DaniEl: U het aan my gedink, o JaHWeH, en het diegene wat U liefhet, nie verlaat nie.	",
"	39 Daarop staan DaniEl op en eet. En die Boodskapper van JaHWeH het Habakuk onmiddellik weer na sy eie plek teruggebring.	",
"	40 Op die sewende dag het die koning gekom om oor DaniEl rou te bedryf; en hy het tot by die kuil gekom en ingekyk, en daar sit DaniEl!	",
"	41 Toe roep die koning hardop uit: U is groot, JaHWeH, die Elohey van DaniEl, en daar is niemand soos U nie!	",
"	42 En hy het hom uitgehaal en die manne wat sy ondergang wou veroorsaak in die kuil gewerp, en in ‘n enkele oomblik is hulle voor sy oë verslind.	",

]
}
];
