const een_esraChapters = [

{
book: 'Een_Esra',
chapter: '1',
content: [
		
"	1 En JoshiJaHûW het die Pasga in Jerusalem vir sy Elohey gehou, en die Pasga op die veertiende dag van die eerste maand gebloei;	",
"	2 nadat hy die priesters wat in lang gewade gekleed was, geplaas het volgens hulle daaglikse dienste in die Huis van JaHWeH.	",
"	3 En hy het met die Leviete gespreek, die tempeldienaars van JisraEl, dat hulle hulself aan JaHWeH moes wy, dat hulle die Ark van Apartheid van JaHWeH in die huis wat koning Salomo, die seun van Dawid, gebou het, moes plaas; en gesê:	",
"	4 Julle sal die Ark nie langer op julle skouers moet dra nie; daarom, dien JaHWeH julle Elohey en slaan ag op Sy volk JisraEl, en berei alles voor volgens julle geslagte en stamme,	",
"	5 soos deur Dawid, die koning van JisraEl voorgeskryf is, en volgens die Glansrykheid van Salomo, sy seun; en staan in die Tempel volgens die onderskeie afdelings van julle families, die Leviete, wat voor die aangesig van julle broers die kinders van JisraEl dien,	",
"	6 Berei die Pasga ordelik, en maak die bydraes vir julle broers gereed en vier die Pasga ooreenkomstig die Bevel van JaHWeH, wat Hy aan Moshè gegee het.	",
		
		
"	7 En aan die adamiete wat daar was, het JoshiJaHûW dertigduisend lammers en boklammers gegee en drieduisend kalwers. Dit is gegee uit die goed van die koning, volgens sy belofte, aan die volk, aan die priesters en aan die Leviete.	",
"	8 Maar GielkiJaHûW, ZekarJaHûW en Suëlus, die owerstes van die Tempel, het vir die Pasga aan die priesters tweeduisend-seshonderd skape gegee en driehonderd kalwers. [2 Kronieke 35:8]	",
"	9 En KownánJaHûW en ShemaJaHûW, en NethanEl sy broer, en GashabJaHûW, en Ogiel, en JeHôWram, owerstes oor duisend, het vir die Pasga aan die Leviete vyfduisend skape gegee en sewehonderd kalwers. [2 Kronieke 35:9]	",
"	10 En toe hierdie dinge na behore gedoen is, het die priesters en die Leviete met die ongesuurde brode, in gepaste orde volgens hul stamme en volgens die onderskeie ampte van die vaders, voor die volk gestaan,	",
"	11 om aan JaHWeH te slag soos dit geskryf is in die Boekrol van Moshè, en ooreenkomstig die vroeë aanbieding.	",
"	12 En hulle het die Pasga op die vuur gerooster, soos dit gebruiklik was. En die bydraes het hulle in koperpotte en panne met suiwer reukwerk gekook	",
"	13 en dit voor die hele volk gebring. Daarna het hulle dit vir hulself voorberei, vir die priesters en vir hulle broers, die seuns van Aäron.	",
"	14 Want die priesters het die harde vet/niervet tot die aand toe aangebied; en die Leviete het dit vir hulleself voorberei, en vir die priesters se broers, die kinders van Aäron.	",
"	15 En die gewyde sangers, die kinders van Asaf, is in rangorde geplaas, volgens die bevel van Dawid, te wete Asaf, ZekarJaH en Jedutun wat uit die koning se gevolg was.	",
"	16 En deurwagters is by elke Poort geplaas; dit was nie vir enigeen geoorloof om sy daaglikse diens te verlaat nie; want hulle broers, die Leviete, het dit vir hulle voorberei.	",
"	17 So is dan op daardie dag volbring alles wat tot die bydraes aan JaHWeH behoort, sodat hulle die Pasga kon hou	",
"	18 en die slaggoed op die altaar van JaHWeH kon naderbring, volgens die bevel van koning JoshiJaHûW.	",
"	19 So het die kinders van JisraEl wat daar teenwoordig was, die Pasga en die Fees van Ongesuurde Brode vir sewe dae lank gevier.	",
"	20 En so ‘n Pasga is nie in JisraEl gehou sedert die tyd van die profeet ShemuEl nie.	",
"	21 Ja, al die konings van JisraEl het nie so ‘n Pasga gehou soos JoshiJaHûW nie, en die priesters en die Leviete en die manne van JeHûWdah het hom gehou saam met die hele JisraEl wat in Jerusalem gewoon het.	",
"	22 In die agtiende jaar van die regering van JoshiJaHûW is hierdie Pasga gevier.	",
"	23 En die werke van JoshiJaHûW was opreg voor die Aangesig van JaHWeH, met ‘n hart vol van ywer.	",
"	24 En wat betref die dinge wat in sy tyd gebeur het, hulle is beskryf in vorige tye - oor hulle wat oortree het en wat besoedeling gepleeg het teen JaHWeH, meer as enige ander volk en koninkryk, wat Hom bedroef het, en die Woorde van JaHWeH het opgegaan teen JisraEl.	",
		
		
"	25 NA al hierdie handelinge van JoshiJaHûW het dit gebeur dat Farao [Nego], die koning van Egipte, oorlog verwek het teen As-Aram [Kargamis] aan die Eufraat, en JoshiJaHûW het teen hom opgetrek. [2 Konings 23:29]	",
"	26 Maar die koning van Egipte het ‘n boodskap na hom gestuur en gesê: Wat het ek met u te doen, o koning van JeHûWdah?	",
"	27 Ek is nie deur JaHWeH Elohim teen u uitgestuur nie; want my oorlog is aan die Eufraat: en nou, JaHWeH is met my en ek haas my voort: gaan weg van my en wees nie teen JaHWeH nie.	",
"	28 Nogtans het JoshiJaHûW nie met sy strydwaens teruggedraai nie, maar onderneem om teen hom te veg, en hy het nie ag geslaan op die woorde van die profeet JirmeJaHûW wat gespreek is uit die Mond van JaHWeH nie.	",
"	29 Maar hy het met hom ‘n stryd aangeknoop in die dal van Megiddo, en die owerstes het teen JoshiJaHûW opgestaan.	",
"	30 Toe het die koning aan sy bediendes gesê: Dra my weg van die stryd; want ek is baie swak. En sy bediendes het hom dadelik weggeneem uit die stryd.	",
"	31 En hy het op sy tweede strydwa geklim en nadat hy na Jerusalem teruggebring is, het hy gesterf en is begrawe in sy vader se graf.	",
"	32 En die hele JeHûWdah het oor JoshiJaHûW getreur, en JirmeJaHûW die profeet het oor JoshiJaHûW geweeklaag, en die hoofmanne met die vroue het oor hom geweeklaag tot hierdie dag toe: en daar is ‘n bevel uitgevaardig dat dit vir altyd deur die hele saadlyn van JisraEl moes geskied.	",
"	33 Hierdie dinge is beskryf in die Boek van die geskiedenis van die konings van JeHûWdah, en elkeen van die dinge wat JoshiJaHûW gedoen het, en sy glorie, en van sy kennis van die Wet van JaHWeH, en die dinge wat hy voorheen gedoen het, en die dinge wat nou vertel word, word beskryf in die Boek van die konings van JisraEl en JeHûWdah.	",
		
		
"	34 EN die volk het JeHôWagaz, die seun van JoshiJaHûW, geneem en hom koning gemaak in die plek van JoshiJaHûW sy vader, toe hy drie-en-twintig jaar oud was. [2 Kronieke 36:1,2]	",
"	35 En hy het drie maande lank in JeHûWdah en Jerusalem regeer. En toe het die koning van Egipte hom onttroon sodat hy in Jerusalem geen koning meer sou wees nie. [2 Kronieke 36:2]	",
"	36 En hy het die volk met eenhonderd talente silwer en een talent goud belas. [2 Kronieke 36:3]	",
"	37 Die koning van Egipte het sy broer, JeHôWjakim as koning oor JeHûWdah en Jerusalem aangestel. [2 Kronieke 36:4]	",
"	38 En hy het JeHôWjakim en die hooggeplaastes gebind; maar JôWagaz°, sy broer, het hy geneem en uit Egipte gebring. °[2 Kronieke 36:4]	",
"	39 JeHôWjakim was vyf-en-twintig jaar oud toe hy koning geword het oor JeHûWdah en Jerusalem; en hy het gedoen wat verkeerd was voor Elohim.	",
"	40 Teen hom het opgestaan Nebukadnésar, die koning van Babel, en hy het hom met ‘n metaalband gebind en hom na Babel toe weggevoer.	",
"	41 En Nebukadnésar het ook van die gewyde bakke van JaHWeH geneem en hulle weggedra en hulle in sy eie tempel in Babel geplaas.	",
"	42 Die verhaal oor sy besoedeling en ongeregtigheid, is geskryf in die Kronieke van die konings.	",
"	43 En JeHôWjakim se seun het in sy plek regeer; hy, was net agtien jaar oud toe hy koning gemaak is; [2 Kronieke 36:9]	",
"	44 en hy het drie maande en tien dae lank in Jerusalem regeer; en gedoen wat besoedel was voor die Aangesig van JaHWeH.	",
"	45 En na ‘n jaar het Nebukadnésar die saak geskik en hom na Babel toe laat bring, tesame met die gewyde bakke van JaHWeH;	",
"	46 en hy het SedekiJaHûW koning van JeHûWdah en Jerusalem gemaak toe hy een-en-twintig jaar oud was en hy het elf jaar lank regeer: [2 Kronieke 36:10,11]	",
"	47 en hy het gedoen wat besoedel was voor die Aangesig van JaHWeH, en hom nie gesteur aan die woorde wat deur die profeet JirmeJaHûW uit die Mond van JaHWeH tot hom gespreek is nie. [2 Kronieke 36:12]	",
"	48 En hoewel hy, in die Naam van JaHWeH, aan koning Nebukadnésar ‘n eed afgelê het, het hy meineed gepleeg en afvallig geraak; en hy het sy nek verhard en sy hart, en hy het die Insettinge van JaHWeH, die Elohey van JisraEl oortree. [2 Kronieke 36:13]	",
"	49 En ook die owerstes van die volk en die priesters het vele besoedeling bedryf, volgens die gruwels van die nasies, en hulle het die Huis van JaHWeH besoedel, wat in Jerusalem deur Elohim apartgestel was. [2 Kronieke 36:13]	",
"	50 En die Elohey van hulle vaders het Sy boodskapper gestuur om hulle tot bekering te roep, omdat Hy hulle, asook Sy Tabernakel, sou vergewe. [2 Kronieke 36:15]	",
"	51 Maar hulle het Sy boodskappers gespot, en op die dag wat JaHWeH met hulle gespreek het, het hulle Sy profete uitgelag; [2 Kronieke 36:16]	",
"	52 totdat Hy, vertoorn vanweë Sy volk se besoedeling, die konings van die Chaldeërs beveel het om teen hulle op te staan. [2 Kronieke 36:17]	",
"	53 Die het hulle jongmanne met die swaard verslaan, selfs in die huis van hulle gewyde plek, en hulle het nóg jongman, nóg maagd, nóg ou man, nóg kind gespaar, want Hy het almal in hulle hand oorgegee. [2 Kronieke 36:17]	",
"	54 En toe het hulle al die gewyde bakke van JaHWeH geneem, beide groot en klein, tesame met die voorwerpe van JaHWeH, en die koninklike skatte, en dit weggevoer na Babel. [2 Kronieke 36:18]	",
"	55 En hulle het die Huis van JaHWeH verbrand, en die mure van Jerusalem afgebreek, en haar torings aan die brand gesteek, en wat in haar kosbaar was, het hulle vernietig. [2 Kronieke 36:19]	",
"	56 En diegene wat oorgebly het van die swaard, is na Babel [in Ballingskap] weggevoer [2 Kronieke 36:20]	",
"	57 en hulle was diensknegte vir hulle en hul kinders, totdat die Perse regeer het, om die Woord van JaHWeH wat deur die mond van JirmeJaHûW gespreek is, te vervul,	",
"	58 totdat die Aarde aan sy Sabbatte ‘n welbehae het, en die volle tyd van verwoesting gerus het, en totdat sewentig jaar vervul is. [2 Kronieke 36:21]	",

]
},
{
book: 'Een_Esra',
chapter: '2',
content: [
		
"	1 En in die eerste jaar van Kores, die koning van Persië - sodat die Woord van JaHWeH volbring sou word wat Hy deur die mond van JirmeJaHûW gespreek het,	",
"	2 het Elohim die gees van Kores, die koning van Persië opgewek, en hy het ‘n proklamasie uitgevaardig dwarsdeur sy hele koninkryk, asook deur ‘n skrywe, [2 Kronieke 36:22]	",
"	3 en hy het gesê: So sê Kores, die koning van Persië; JaHWeH, die Elohey van JisraEl, die Hoogste El, het my koning oor al die koninkryke van die Aarde gemaak,	",
"	4 en my beveel om vir Hom ‘n Huis te bou in Jerusalem wat in JeHûWdah is. [2 Kronieke 36:23]	",
		
		
"	5 AS daar dus enige van julle is wat van Sy volk is, laat JaHWeH sy Elohey met hom wees, en laat hom opgaan na Jerusalem wat in JeHûWdah is, en die Huis van JaHWeH sy Elohey van JisraEl herbou, Hy is JaHWeH wat in Jerusalem woon. [2 Kronieke 36:23]	",
"	6 Wie ook al dan in verskillende plekke woon, laat hulle wat in sy eie plek is mekaar help, met goud en met silwer,	",
"	7 met geskenke, met perde en ook met vee en ander dinge wat met geloftes toegebring is in die Huis van JaHWeH wat in Jerusalem is.	",
"	8 Toe het die vernaamstes uit die stamme van JeHûWdah en Benjamin opgestaan; ook die priesters en die Leviete, en almal wie se gees deur JaHWeH beweeg is om te gaan om ‘n Huis vir JaHWeH in Jerusalem te bou.	",
"	9 En die wat rondom hulle woonagtig was, het hulle in allerlei dinge gehelp, met silwer en goud, met perde en vee, en met baie geskenke, groot in getal, wie se gees daartoe beweeg is.	",
"	10 Koning Kores het ook die gewyde bakke van Elohim te voorskyn gebring wat Nebukadnésar uit Jerusalem weggevoer en in sy gode se tempel opgestel het.	",
		
		
"	11 EN toe Kores, die koning van Persië hulle te voorskyn gebring het, het hy hulle gegee aan Mitridates, sy skatmeester;	",
"	12 en deur hom is hulle oorgegee aan Sanabassar, die goewerneur van JeHûWdah.	",
"	13 En die getal daarvan was: eenduisend goue bekers, en ‘n duisend silwer bekers, nege-en-twintig silwer wierookbakke, dertig goue flesse, en tweeduisend-vierhonderd-en-tien silwer, en ‘n duisend ander houers.	",
"	14 Al die houers van goud en silwer wat weggedra is, was vyf-duisend-vierhonderd-nege-en-sestig.	",
"	15 Dit is saam met hulle van die ballingskap af teruggebring deur Sanabassar uit Babel na Jerusalem.	",
"	16 Maar in die tyd van Artasásta, die koning van die Persië, het Belemus en Mitridates, en Tabellius, en Rathymus, en Baltemus, en Samellius, die sekretaris, wat saam met hulle opdrag gegee is, en in Samaria en ander plekke gewoon het, die volgende briewe aan hom geskryf teen hulle wat in JeHûWdah en Jerusalem gewoon het:	",
"	17 Aan koning Artasásta ons meester, u diensknegte, Rathymus die storieskrywer, en Samellius die skrywer, en die res van hulle raadsvergadering, en die regters wat in Celo-Aram en Fenícië is.	",
"	18 Laat dit aan ons meester die koning bekend wees dat die manne van JeHûWdah van u af na ons in Jerusalem gekom het om weer die besoedelde en opstandige Stad te kom herbou, om die markpleine en die mure van haar te herstel, en die fondament van die Tempel te lê.	",
"	19 As hierdie Stad dan nou herbou word en die mure van haar weer opgerig is, sal hulle nie alleen weier om belasting te betaal nie, maar hulle sal ook teen die koning rebelleer.	",
"	20 En terwyl hulle dan nou met die werk aan die Tempel besig is, het ons dit goed gedink om nie te versuim nie,	",
"	21 maar dat ons ons meester en koning moet laat weet, dat as dit u sou behaag, daar [hieroor] gesoek moet word in die boekrolle van u vaders;	",
"	22 en u sal in die kronieke waaroor daar oor hierdie dinge geskrywe is, vind en verstaan dat die Stad afvallig was en aan beide konings en stede moeite besorg het;	",
"	23 en dat die manne van JeHûWdah in haar opstandig was en altyd oorloë veroorsaak het; as gevolg waarvan hierdie Stad dan ook verwoes is.	",
"	24 Daarom verklaar ons nou aan u, o meester die koning, dat as hierdie Stad herbou word, en die mure van haar nuut opgerig word, sal u van nou af aan geen toegang hê tot Celo-Aram en Fenícië nie.	",
		
		
"	25 TOE het die koning weer die volgende teruggeskryf aan Rathymus die storieskrywer, aan Balthemus, aan Semellius die skrywer, en aan die res wat in die afvaardiging was, en die inwoners van Samaria en Aram en Fenícië:	",
"	26 Ek het die brief gelees wat julle aan my gestuur het, daarom het ek beveel dat daar ondersoek ingestel moes word, en dit is bevind dat daardie Stad van ouds af teen die konings gekant was	",
"	27 en dat die manne in haar geneig was tot rebellie en oorlog: dat magtige en gewelddadige konings in Jerusalem regeer het, en belasting afgedwing het in Celo-Aram en Fenícië.	",
"	28 Daarom het ek bevel gegee dat daardie manne verhinder moet word om die Stad te herbou, en dat daarop ag gegee moet word dat niks gedoen moet word wat teenstrydig is met hierdie bevel nie;	",
"	29 en dat daardie besoedelde werke nie verder mag voortgaan tot die ergernis van konings nie.	",
"	30 En nadat Artasásta se briewe gelees is, het Rathymus en Semellius, die skrywer, en die res wat saam met hulle in die afvaardiging was, haastig weggegaan na Jerusalem met ‘n troep perderuiters en ‘n menigte voetvolk in oorlogsgewaad,	",
"	31 en hulle het begin om die bouers te verhinder. So het die bou van die Tempel in Jerusalem dan tot stilstand gekom tot in die tweede jaar van die regering van Darius, die koning van Persië.	",

]
},
{
book: 'Een_Esra',
chapter: '3',
content: [
		
"	1 Darius het ‘n groot fees vir al sy onderdane gehou, en vir sy hele huishouding, en vir al die prinse van Medië en Persië,	",
"	2 en vir al sy vorste en kapteins en luitenante wat onder hom was, vanaf Indië tot Kuwsh, in die honderd sewe-en-twintig provinsies.	",
"	3 En toe hulle geëet en gedrink het, en versadig was en huis toe gegaan het, het Darius die koning in sy slaapkamer ingegaan en geslaap en uit sy slaap wakker geword.	",
"	4 Toe het die drie jongmanne wat van die koning se lyfwagte was, met mekaar gepraat en gesê:	",
"	5 Laat elkeen van ons een spreuk spreek - WIE IS DIE STERKSTE - en hy wie s’n wyser sal wees as die ander, aan hom sal koning Darius groot geskenke gee en groot dinge as teken van oorwinning:	",
"	6 Hy sal hom met purper beklee, en uit goue bekers laat drink en op ‘n goue bed laat slaap, en ‘n strydwa gee wat deur perde met goue tooms getrek word, en ‘n hooftooisel van fyn linne en ‘n ketting om sy nek:	",
"	7 en hy sal langs Darius sit vanweë sy wysheid en hy sal genoem word Darius se bloedvriend.	",
		
		
"	8 EN toe het elkeen sy spreuk neergeskryf, dit verseël, en dit onder koning Darius se kussing geplaas;	",
"	9 en gesê dat wanneer die koning opstaan, sal hulle aan hom die geskrifte gee; en die koning en die drie prinse van Persië sou dit beoordeel om te sien wie s’n die wysste is, en aan hom sal die oorwinning gegee word, soos dit geskryf is.	",
"	10 Die eerste het geskryf, Wyn is die sterkste	",
"	11 Die tweede het geskryf, Die koning is die sterkste.	",
"	12 Die derde het geskryf, Die vrou is die sterkste; maar bowe alles sal die Waarheid oorwin.	",
		
		
"	13 TOE die koning opgestaan het, het hulle die geskrifte geneem en dit aan hom gegee, en hy het dit gelees;	",
"	14 en toe het hy uitgestuur en al die prinse van Persië en Medië laat roep, en die goewerneurs, en die kapteins, en die luitenante, en die burgermeesters;	",
"	15 en hy het gaan sit op die koninklike regterstoel; en die geskrifte is voor hulle gelees.	",
"	16 En hy het gesê: Roep die jongmanne, en laat hulle hul spreuke verklaar. Toe is hulle geroep en hulle het ingekom.	",
"	17 En hy het aan hulle gesê: Verklaar aan ons wat julle geskrywe het.	",
"	18 Toe het die eerste begin, die een wat gepraat het van die krag van die wyn, en hy het so gesê: O julle manne, hoe buitengewoon sterk is wyn! Hy verlei alle mense wat hom drink;	",
"	19 hy maak die verstand van die koning en die wilde wese eenders; ook maak hy die verstand van die slaaf en die vryman gelyk, van die dienskneg en die vrye, ook van die arme en die ryke;	",
"	20 en hy verander elke gedagte in joligheid en pret, sodat ‘n man nie meer aan droefheid of skuld sal dink nie;	",
"	21 en hy maak elke hart ryk, sodat ‘n man nie meer aan die koning of vors sal dink nie; en hy veroorsaak dat almal van talente [silwer] praat;	",
"	22 en wanneer hulle met hul bekers sit, vergeet hulle hul liefde vir beide hulle vriende en broers, en sommer gou-gou trek hulle die swaard;	",
"	23 maar wanneer hulle van die wyn herstel het, onthou hulle nie wat hulle gedoen het nie.	",
"	24 O menere, is die wyn nie die sterkste terwyl hy ons dwing om hierdie dinge te doen nie? En nadat hy so gespreek het, het hy stil gebly.	",

]
},
{
book: 'Een_Esra',
chapter: '4',
content: [
		
"	1 TOE het die tweede, hy wat gepraat het van die sterkte van die koning, begin praat en gesê,	",
"	2 O menere, is die manne wat die see regeer en die Aarde en alles wat in haar is, nie die sterkste nie?	",
"	3 Maar tog is die koning magtiger: want hy is meester van al hierdie dinge en het heerskappy oor hulle; en wat hy hulle ook al beveel, dit doen hulle.	",
"	4 As hy hulle vra om die een teen die ander oorlog te maak, doen hulle dit; as hy hulle teen die vyand uitstuur, gaan hulle en oorkom berge, mure en torings.	",
"	5 Hulle verslaan en word verslaan, en oortree nie die koning se bevel nie; as hulle die oorwinning behaal, bring hulle alles na die koning, sowel die buit as al die ander dinge.	",
"	6 En almal wat nie slagveld toe gaan nie en nie oorlog voer nie, maar die boerdery behartig, wanneer hulle gesaai en geoes het, bring hulle dit na die koning, en verplig mekaar om ‘n skatting te betaal aan die koning. En tog is hy maar net een man.	",
"	7 As hy beveel dat daar doodgemaak moet word, maak hulle dood; en as hy beveel dat verskoon moet word, verskoon hulle;	",
"	8 as hy beveel dat verslaan moet word, verslaan hulle; as hy beveel dat daar verwoes moet word, dan verwoes hulle; as hy beveel dat daar gebou moet word, bou hulle;	",
"	9 as hy beveel dat afgebreek moet word, breek hulle af; as hy beveel dat geplant moet word, plant hulle.	",
"	10 Al sy onderdane en sy leërs gehoorsaam hom;	",
"	11 verder nog gaan lê hy, eet hy en drink hy, en neem hy sy rus; en staan daar wagte rondom hom, ook mag niemand weggaan om sy eie sake te doen nie, en ook is niemand ongehoorsaam aan hom nie.	",
"	12 O menere, hoe kan die koning nie die magtigste wees as hy op so ‘n manier gehoorsaam word nie? En hy het stil gebly.	",
		
		
"	13 TOE het die derde, die een wat oor die vroue en van die Waarheid gespreek het dit was Serubbábel - begin praat.	",
"	14 O menere, is die koning nie groot, of die manne ‘n menigte nie, en die wyn sterk nie? Wie is dit dan wat hulle regeer of wat heerskappy oor hulle het? Is hulle nie vroue nie?	",
"	15 Die vrou het die koning gebaar, en ook die hele volk wat die see en die Aarde regeer, is uit haar gebore.	",
"	16 Sy het selfs diegene opgevoed wat die Wingerd aanplant en waarvandaan die wyn kom.	",
"	17 En sy self het ook die klere vir die manne gemaak; hulle bring eer aan die mans, maar sonder vroue kan die man nie bestaan nie.	",
"	18 Ja, en as die manne goud en silwer versamel het, of enige ander mooi ding, en hulle sien ‘n vrou wat aanvallig in voorkoms en gestalte is,	",
"	19 dan verlaat hulle dit alles en wend die oog op haar en hulle aanskou haar oopmond, hulle oë vasgenael op haar; en het meer begeerte na haar as na silwer of goud of enige mooi ding.	",
"	20 ‘n Man verlaat sy eie vader wat hom grootgemaak het, sy eie deel van die Aarde, en kleef sy vrou aan.	",
"	21 En by sy vrou eindig sy dae, en onthou hy nie meer sy vader of sy moeder of sy deel van die Aarde nie.	",
"	22 Hierdeur moet julle ook weet dat die vrou heerskappy oor julle het:	",
"	23 arbei en swoeg julle nie en bring en gee dit alles vir die vrou nie? Ja, ‘n man neem sy swaard, en gaan uit om te roof en te steel, om op die see en op riviere te vaar;	",
"	24 en hy sien ‘n leeu en loop in die donker; en wanneer hy gesteel, gebuit en geroof het, bring hy dit na sy beminde.	",
"	25 Waardeur ‘n man sy vrou meer liefhet as sy vader of sy moeder.	",
"	26 Ja, daar is baie wat hulle verstand verloor het deur ‘n vrou en slawe geword het ter wille van haar.	",
"	27 Baie het ook omgekom, en vergaan en oortree ter wille van die vrou.	",
"	28 En nou glo julle my nie? Is die koning nie groot in sy mag nie? En vrees alle konings nie om hom aan te val nie?	",
"	29 Tog het ek hom en Apame gesien, die koning se houvrou en dogter van die bewonderenswaardige Bartacus, terwyl sy aan die regterkant van die koning gesit het;	",
"	30 en sy het die kroon van die koning se kop afgehaal en dit op haar eie kop gesit, sy het die koning ook met haar linkerhand geklap.	",
"	31 En tog, ten spyte hiervan, het die koning hom vergaap en oopmond na haar gestaar; wanneer sy vir hom gelag het, het hy ook gelag, maar as sy enige misnoeë met hom gehad het, was hy gewillig om haar te vlei sodat sy weer met hom versoen sou raak.	",
"	32 O menere, hoe kan dit anders wees as dat vroue sterk is, terwyl hulle so doen?	",
		
		
"	33 TOE het die koning en prinse na mekaar gekyk; en hy het begin praat oor die Waarheid.	",
"	34 O menere, is vroue nie sterk nie? Groot is die Aarde, hoog is die Hemele, snel is die son op sy baan, want hy omsirkel die Hemele op sy kringloop, en hy keer weer terug na sy plek in een dag.	",
"	35 Is Hy nie groot wat al hierdie dinge gemaak het nie? Maar die Waarheid is groter en sterker as alle ander dinge.	",
"	36 Die hele Aarde roep uit na die Waarheid en die Hemele seën Haar; alle werke skud en bewe vir Haar en by Haar is geen onreg te vind nie.	",
"	37 Wyn is onreg, die koning is onreg, vroue is onreg, al die kinders van die adam is wetteloos, en so is al hulle besoedelde dade; en daar is geen Waarheid in hulle nie; en deur hulle ongeregtigheid sal hulle ook vergaan.	",
"	38 Maar die Waarheid bly, en Sy is sterk tot in ewigheid; en Sy leef en heers tot in alle ewigheid.	",
"	39 En by Haar is daar geen aanneming van die persoon nie; Sy maak ook geen onderskeid nie en doen wat Reg is, en weerhou Haar van alles wat onregverdig en besoedel is; En almal het ‘n welbehae in Haar werke.	",
"	40 Daar is in Haar oordeel ook geen onreg nie; en Sy is die Krag, en die Koninkryk, en die Mag en Majesteit van alle tye. Geseënd is die Elohey van Waarheid!	",
		
		
"	41 EN daarmee het hy stilgebly. En die hele volk het toe uitgeroep en gesê: Groot is die Waarheid en magtig bo alle dinge.	",
"	42 Toe het die koning aan hom gesê: Vra wat jy wil, meer as wat daar geskrywe is en ons sal dit aan jou gee, want jy is die wysste gevind; en jy sal langs my sit en sal my bloedvriend genoem word.	",
"	43 Toe het hy aan die koning gesê: Onthou tog u belofte wat u belowe het om Jerusalem te herbou in die dae toe u u koninkryk ontvang het,	",
"	44 en dat u al die voorwerpe wat weggeneem is uit Jerusalem, wat Kores eenkant gesit het toe hy gesweer het om Babel te vernietig, weer daarheen terug sal stuur.	",
"	45 U het belowe om die Tempel te herbou wat die Edomiete verbrand het toe JeHûWdah verslaan is deur die Chaldeërs.	",
"	46 En nou, o meester, die koning, dit is wat ek verlang en wat ek van u begeer; en dit is die prinslike vryheid wat deur my van u geëis word: Ek vra daarom dat u die belofte sal nakom, die vervulling waarvan u met u eie mond aan die Koning van die Hemele belowe het.	",
		
		
"	47 TOE het Darius die koning opgestaan en hom gekus en vir hom briewe geskryf aan al die rentmeesters en landvoogde en krygsowerstes en vorste, dat hy hom geleide sou doen en almal saam met hom sal opgaan om Jerusalem te herbou.	",
"	48 Hy het ook briewe geskryf aan al die landvoogde wat in Celo-Aram en Fenícië is, en aan hulle in Libanon, dat hulle sederhout moes saambring van die Libanonberg na Jerusalem en dat hulle die Stad saam met hom moes herbou.	",
"	49 Verder nog het hy vir al die manne van JeHûWdah geskryf wat uit sy koninkryk vry sou wees om op te gaan na JeHûWdah, en dat geen vors of landvoog of rentmeester, met geweld by hulle deure sou ingaan nie;	",
"	50 en dat die hele Aarde wat hulle bewoon, vry sou wees van belasting; en dat die Edomiete die dorpe van die manne van JeHûWdah wat hulle in besit geneem het, sou verlaat;	",
"	51 en dat daar jaarliks twintig talente gegee sou word vir die bou van die Tempel totdat hy voltooi is;	",
"	52 en dat hulle nog tien talente jaarliks sou bydra vir elke dag se brandoffers op die altaar, aangesien hulle ‘n bevel gehad het om sewentien te slag;	",
"	53 en dat almal wat van Babel af gekom het om die Stad te bou, volle vryheid sou hê, sowel hulle as hul saadlyn, en al die priesters wat gekom het.	",
"	54 Hy het ook geskryf oor die onderhoud van die priesters en van die priestersgewaad waarin hulle diens sou doen;	",
"	55 dieselfde het gegeld vir die onderhoud van die Leviete, om aan hulle gegee te word tot op die dag wat die Huis [van Elohim] voltooi en Jerusalem herbou is.	",
"	56 En hy het beveel dat almal wat die Stad bewaak, grond en lone gegee moet word.	",
"	57 Hy het ook teruggestuur al die bakke van Babel, wat Kores eenkant gehou het, asook alles wat Kores beveel het om te doen, het hy ook beveel om te doen en na Jerusalem terug te stuur	",
		
		
"	58 EN toe hierdie jongman uitgegaan het, het hy sy aangesig opgehef na die Hemele in die rigting van Jerusalem, en die Koning van die Hemele geloof en gesê:	",
"	59 Van U kom die oorwinning, en van U kom die Wysheid, aan U behoort die Glansrykheid en ek is U dienskneg.	",
"	60 Geseënd is U wat aan my die Wysheid gegee het, en aan U gee ek my dank, o JaHWeH van ons vaders.	",
		
		
"	61 EN toe het hy die briewe geneem en weggetrek na Babel en alles aan sy broers vertel.	",
"	62 En hulle het die Elohim van hulle vaders geloof omdat Hy aan hulle vryheid en Verlossing gegee het	",
"	63 om op te gaan en Jerusalem te herbou, en die Tempel waaroor Sy Naam uitgeroep is; en hulle het fees gevier met vreugde en snaarinstrumente, sewe dae lank.	",

]
},
{
book: 'Een_Esra',
chapter: '5',
content: [
		
"	1 HIERNA is die owerstes van die huise volgens hul stamme gekies om op te gaan met hulle vroue en kinders en dogters, met hulle diensknegte en diensmaagde en hulle vee.	",
"	2 En Darius het saam met hulle ‘n duisend perderuiters gestuur om hulle in vrede geleide te doen na Jerusalem, met musiek, tromme en fluite.	",
"	3 En al hulle broers het gespeel, en hy het hulle gedwing om saam met hulle te gaan.	",
		
		
"	4 EN dit is die name van die manne wat opgegaan het na die huise van hul vaders in die stamme, na die verdeling van hulle heerskappy.	",
"	5 Die priesters, die kinders van Pínehas, die seun van Aäron: JeHôWshua die seun van JôWtsadak, die seun van SeráJaH, en JeHôWjakin, die seun van Serubbábel, die seun van SalathiEl van die huis van Dawid uit die genelyn van Fares van die stam van JeHûWdah;	",
"	6 hy wat die wyse woorde gespreek het voor Darius die koning van Persië in die tweede jaar van sy heerskappy, in die maand Nisan(Abib) wat die eerste maand is.	",
"	7 Dit is hulle wat uit JeHûWdah opgetrek het uit gevangeskap waar hulle as vreemdelinge gewoon het, en wat deur Nebukadnésar, die koning van Babel, weggevoer is na Babel.	",
"	8 En hulle het na Jerusalem teruggekeer en ook na die ander dele van JeHûWdah, elke man na sy eie Stad, wat saam met Serubbábel gekom het met JeHôWshua, NegemJaH en ZebádJaH, en ResaJaH, Enenius, Mardocheus, Belsarus, Asfarasus, Reëlius, Rorinus en Baanas, hulle owerstes.	",
"	9 Die getal van hulle wat van die volk was, saam met hulle owerstes was: die kinders van Parosch tweeduisend en honderd-twee-en-sewentig;	",
"	10 die kinders van Safat, vierhonderd-twee-en-sewentig: die kinders van Ares sewehonderd-ses-en-vyftig;	",
"	11 die kinders van Pahat-Moab: uit die kinders van JeHôWshua en JôWab tweeduisend-agthonderd-en-twaalf;	",
"	12 die kinders van Elam ‘n duisend-tweehonderd vier-en-vyftig; die kinders van Sathaï negehonderd-vyf-en-veertig; die kinders van Chorvas sewehonderd-en-vyf; die kinders van Bani seshonderd-agt-en-veertig;	",
"	13 die kinders van Babai seshonderd-drie-en-dertig; die kinders van Argas drieduisend-tweehonderd-twee-en-twintig;	",
"	14 die kinders van Adoníkam seshonderd-sewe-en-dertig; die kinders van Bagoë tweeduisend-ses-en-sestig; die kinders van JôWab vierhonderd-vier-en-vyftig;	",
"	15 die kinders van Ater uit EsekiJaH twee-en-negentig; die kinders van Cilas en Azenas sewe-en-sestig; die kinders van Asar vierhonderd-twee-en-dertig;	",
"	16 die kinders van Amri honderd-en-een; die kinders van Arom twee-en-dertig; en die kinders van Basse driehonderd-drie-en-twintig; die kinders van Asefurit ‘n honderd-en-twee;	",
"	17 die kinders van Beter drieduisend-en-vyf;	",
"	18 die kinders van Bethlomon ‘n honderd-drie-en-twintig; die van Nethofas vyf-en-vyftig; die van Anathoth ‘n honderd-agt-en-vyftig; hulle van Bethasmon twee-en-veertig;	",
"	19 die van Cariathiri vyf-en-twintig; die van Cathiras en Berogh sewehonderd-drie-en-veertig; die van Pira sewehonderd; Gadiasiete en Ammidiërs vierhonderd-twee-en-twintig;	",
"	20 die van Kiramas en Gabbes seshonderd-een-en-twintig; die van Makalon ‘n honderd-twee-en-twintig; die van Betolië twee-en-vyftig;	",
"	21 die kinders van Nifis ‘n honderd-ses-en-vyftig; die kinders van Kalamelali en Onus sewehonderd-vyf-en-twintig;	",
"	22 die kinders van Jerechu tweehonderd-vyf-en-veertig;	",
"	23 die kinders van Sanaas drieduisend-driehonderd-en-dertig.	",
"	24 Die priesters; die kinders van Jeddu die seun van JeHôWshua onder die kinders van Lanasib negehonderd-twee-en-sewentig; die kinders van Emeruth ‘n duisend-twee-en-vyftig;	",
"	25 die kinders van Fassur ‘n duisend-vierhonderd-en-sewe; die kinders van Eharmi ‘n duisend-en-sewentien.	",
"	26 Die Leviete: die kinders van Jusua en Kadoëli en Banni en Sudi vier-en-sewentig.	",
"	27 Die gewyde sangers: die kinders van Asaf ‘n honderd-agt-en-twintig.	",
"	28 Die deurwagters: die kinders van Sallum, die kinders van Atar, die kinders van Tolman, die kinders van Dahub, die kinders van Ateta, die kinders van Tobi altesaam ‘n honderd-nege-en-dertig.	",
"	29 Die diensknegte van die Tempel: die kinders van Hesai, die kinders van Asifa, die kinders van Tabaoth, die kinders van Ceras, die kinders van Suda, die kinders van Faleas,	",
"	30 die kinders van Labana, die kinders van Agraba, die kinders van Akud, die kinders van Uta, die kinders van Cetab, die kinders van Akaba, die kinders van Sjiba, die kinders van Anan, die kinders van Cathua,	",
"	31 die kinders van Geddur, die kinders van Laïr, die kinders van Desan, die kinders van Noëba, die kinders van Chaseba, die kinders van Casera, die kinders van Osia, die kinders van Finoë, die kinders van Asara,	",
"	32 die kinders van Basthaï, die kinders van Assana, die kinders van Mavi, die kinders van Nafis, die kinders van Akuf, die kinders van Achiba, die kinders van Asub, die kinders van Farenaces, die kinders van Basalot, die kinders van Meeda, die kinders van Kouta, die kinders van Charea, die kinders van Charkus, die kinders van Aserer, die kinders van Tomoi, die kinders van Nasit, die kinders van Atifa.	",
"	33 Die kinders van die diensknegte van Salomo; die kinders van Asapfioth, die kinders van Farera, die kinders van Jejeli, die kinders van Loson, die kinders van IsdaEl, die kinders van Safni,	",
"	34 die kinders van HagiJaH, die seuns van Sachareth, die kinders van SabiJaH, die kinders van Saroth, die kinders van Misaje, die kinders van Gas, die kinders van Addus, die kinders van Suba, die kinders van Aferra, die kinders van Barod, die kinders van Safag, die kinders van Allom.	",
"	35 Die volgende het almal gedien in die Tempel, en was die kinders van die diensknegte van Salomo, driehonderd twee-en-sewentig.	",
"	36 Die volgende het opgetrek van Thermeleth en Thelersa, deur Charnatalan gelei, en Aalar;	",
"	37 maar hulle kon ook nie hulle stede of families uitwys of hoe hulle uit JisraEl stam nie; die kinders van Dalan, die seun van Baëma, die kinders van Nehoda seshonderd-twee-en-vyftig.	",
"	38 En uit die priesters wat die priesterskap bedien en wie se geslagsregister nie gevind kon word nie; die kinders van Obdie, die kinders van Akbos, die kinders van Jaddu wat met Augia, een van die dogters van Faëseldeus, getrou het en na sy naam vernoem is.	",
"	39 En as die geslagsgeskrif in die register gesoek is en nie gevind is nie, is hulle van die priesteramp onthef:	",
"	40 En Nehemia en Attaria het aan hulle gesê dat hulle geen deel sou hê aan die aparte dinge totdat daar ‘n hoëpriester opgestaan het wat geklee is met die Openbaring en Waarheid nie.	",
"	41 Al die Jisraeliete van twaalf jaar en ouer, sonder die diensknegte en diensmaagde, was in getal twee-en-veertigduisend-driehonderd-en-sestig.	",
"	42 Hulle knegte en diensmaagde was seweduisend-driehonderd-sewe-en-dertig; die sangers en sangeresse tweehonderd-vyf-en-veertig;	",
"	43 vierhonderd-vyf-en-dertig kamele, seweduisend-ses-en-dertig perde, tweehonderd-vyf-en-veertig muilesels, vyfduisend-vyfhonderd-vyf-en-twintig esels.	",
"	44 En enigeen onder die owerstes van hulle families, toe hulle in die Tempel van Elohim in Jerusalem kom, het belowe om weer die Huis van Elohim te bou op sy eie plek en volgens hulle vermoëns.	",
"	45 En om aan die gewyde skatkis van die werke, ‘n duisend talente goud te gee, vyfduisend silwer en ‘n honderd priesterlike gewade.	",
"	46 En die priesters en die Leviete van die volk het in Jerusalem gewoon en in die landelike gebiede, en die gewyde sangers, asook die deurwagters; en die hele JisraEl in hulle dorpe.	",
"	47 Maar toe die sewende maand op hande was, en die kinders van JisraEl elkeen in sy eie woonplek was, het hulle almal eendragtig saamgekom in die voorhof van die eerste Poort wat na die ooste was.	",
"	48 Toe het JeHôWshua, die seun van JôWtsadak, opgestaan asook sy broers, die priesters, en Serubbábel, die seun van ShealtiEl, en sy broers,	",
"	49 en hulle het die altaar van die Elohim van JisraEl gereedgemaak om brandoffers op hom te slag soos dit uitdruklik beveel is in die Boek van Moshè, die man van Elohim.	",
		
		
"	50 EN hulle het die altaar opgerig op sy plek, hoewel daar van die ander volke van die Aarde teen hulle versamel het, want al die volke van die Aarde was in vyandskap met hulle.	",
"	51 Want al die volke wat op die Aarde was, het hulle versterk. En hulle het slagdiere geslag volgens die tyd en brandoffers aan JaHWeH, beide oggend en aand.	",
"	52 Ook het hulle die Fees van Takskuilings gevier soos wat dit in die Wet beveel word, en hulle het daaglikse [vuurbereidings] gebring volgens voorskrif; en daarna die voortdurende spysbydrae en die bydrae van die Sabbatte, en van die vernuwings, en van al die ander feesdae, voor hulle wat gewy was. [Levítikus 23:37,38]	",
"	53 En almal van hulle wat ‘n belofte aan Elohim gemaak het, het begin om slagdiere aan Elohim te slag vanaf die eerste dag van die sewende maand, alhoewel die Tempel van Elohim nog nie herbou was nie.	",
"	54 En hulle het aan die bouers en skrynwerkers silwer gegee, spys en drank.	",
"	55 Aan die Sidoniërs en ook Tiriërs het hulle rytuie gegee sodat hulle sederbome van Libanon kon bring om op vlotte oor te vaar na die hawe van Jafo, soos wat hulle beveel was deur Kores, koning van Persië.	",
"	56 En in die tweede jaar en tweede maand na sy koms na die Tempel van Elohim in Jerusalem, het Serubbábel, die seun van ShealtiEl, en JeHôWshua die seun van JôWtsadak en hulle broers en die priesters en die Leviete, en almal hulle wat na Jerusalem gekom het uit gevangeskap, daarmee begin.	",
		
		
"	57 EN hulle het die fondament vir die Huis van Elohim gelê op die eerste dag van die tweede maand in die tweede jaar nadat hulle na JeHûWdah en Jerusalem gekom het.	",
"	58 En hulle het die Leviete van twintig jaar en ouer aangestel oor die werke van JaHWeH. En JeHôWshua het opgestaan met sy seuns en sy broers, en KadmiEl sy broer, en die seuns van Emadabus, met die kinders van Joda die seun van EliJaHdad met hulle seuns en broer, al hierdie Leviete, het eenparig voortgegaan met die werk, en geswoeg om die werke in die Huis van Elohim te bevorder.	",
"	59 En die bouers het die Huis van JaHWeH gebou. En die priesters het uitgedos in hulle kledingstukke gestaan met snarespel en basuine; en die Leviete, die kinders van Asaf, het simbale gehad	",
"	60 terwyl hulle liedere van danksegging sing, en JaHWeH geprys het volgens wat Dawid, die koning van JisraEl, verordineer het.	",
"	61 En hulle het hulle stemme verhef met liedere tot eer van JaHWeH, en JaHWeH geloof, dat Sy Barmhartigheid en Sy Majesteit vir ewig oor die hele JisraEl sal wees.	",
"	62 En die hele volk het op trompette geblaas en met ‘n harde stem geroep en liedere van danksegging tot JaHWeH gesing oor die oprigting van die Huis van JaHWeH.	",
"	63 Dog elkeen van die priesters en Leviete, en van die owerstes van hulle families, wat oud was en die Huis wat voor hierdie een was, gesien het,	",
"	64 het die bou van hierdie Huis genader met geween en met groot geroep en baie basuine en vreugde in luide stem,	",
"	65 sodat die volk die basuine nie kon hoor weens die geween van die volk nie; want die skare het so luid uitgeroep dat dit van ver gehoor kon word.	",
"	66 En toe die vyande van die stam van JeHûWdah en Benjamin dit hoor, het hulle gekom om uit te vind wat daardie geluid van basuine kon beteken.	",
"	67 En hulle het verstaan dat hulle wat in gevangeskap was, die Tempel vir JaHWeH die Elohey van JisraEl gebou het.	",
"	68 Toe het hulle na Serubbábel en JeHôWshua gegaan, en na die owerste van die families en aan hulle gesê: Laat ons saam met julle bou.	",
"	69 Want ons behoort aan julle Elohey, soos julle, en ons slag aan Hom sedert die dae van Asbakaf, die koning van die Aramiërs, wat ons hierheen gebring het.	",
"	70 Toe het Serubbábel en JeHôWshua en die owerste van die families van JisraEl aan hulle gesê:	",
"	71 Dit is nie vir ons en julle om saam ‘n Huis vir JaHWeH ons Elohey te bou nie.	",
"	72 Ons sal alleen vir die Elohey van JisraEl bou, volgens wat Kores die koning van Persië ons beveel het.	",
		
		
"	73 Maar die nasies van die Aarde het hulle opgedring aan die inwoners van JeHûWdah, en hulle beset en hulle verhinder om te bou;	",
"	74 en deur hinderlae, sameswering en oorlopery, het hulle die voltooiing van die bouwerk gedurende koning Kores se leeftyd verhinder, en so is die bouwerk twee jaar lank vertraag totdat Darius se koningskap aangebreek het.	",
		

]
},
{
book: 'Een_Esra',
chapter: '6',
content: [
		
"	1 NOU in die tweede jaar van die heerskappy van Darius, het Haggai en ZekarJaH, [die seun van BerekJaHûW] die seun van Addo, geprofeteer oor die manne van JeHûWdah in JeHûWdah en Jerusalem in die Naam van JaHWeH die Elohey van JisraEl wat op hulle was.	",
"	2 Toe het Serubbábel, die seun van ShealtiEl, en JeHôWshua, die seun van JôWtsadak, opgestaan en die Huis van JaHWeH in Jerusalem begin bou, die profete van JaHWeH was met hulle en het hulle gehelp.	",
		
		
"	3 OP dieselfde tyd het na hulle gekom Sisinnes, die onder-goewerneur van Aram en Fenícië en Satrabusan en sy metgeselle, en hy het aan hulle gesê:	",
"	4 Deur wie se opdrag bou julle hierdie Huis en hierdie dak, en doen julle al die ander dinge en voltooi dit? En wie is die werkers wat hierdie dinge doen?	",
"	5 En nadat die ondersoek gedoen is oor die gevangenisse, het die oudstes van die manne van JeHûWdah Barmhartigheid gevind in die Oë van JaHWeH, en hulle is nie van die bouwerk verhinder nie totdat Darius hiervan laat weet is, en die mense ‘ n antwoord kon bekom.	",
"	6 Die afskrif van die briewe wat Sisinnes geskryf het en na Darius gestuur het, is soos volg:	",
"	7 Sisinnes, die goewerneur van Aram en Fenícië, en Satrabusan en sy metgeselle wat in Aram en Fenícië owerstes is, wens Darius die koning voorspoed toe.	",
"	8 Laat alle dinge bekend wees aan ons meester die koning, dat na ons in die landstreek van JeHûWdah gekom het en die Stad van Jerusalem ingegaan het, dat ons in die Stad van Jerusalem die oudstes van die manne van JeHûWdah gevind het wat uit gevangeskap gekom het,	",
"	9 en wat ‘n nuwe en groot Huis vir Elohim aan die bou was, met gekapte kosbare steen en die houtwerk in die mure gelê.	",
"	10 En daardie werke is gedoen met groot haas, en dit gaan voorspoedig daarmee in hulle hande en met alle eer en ywer word dit gedoen.	",
"	11 Toe het ons hierdie oudstes gevra en gesê: Deur wie se bevel bou julle hierdie Huis en lê die fondasies van hierdie werke?	",
"	12 En ons het dit aan hulle gevra met die voorneme om u daaroor in te lig deur te skrywe watter manne daaroor aangestel is; en ons het dan ook skriftelik van hulle die name van hulle owerstes geëis.	",
"	13 Maar hulle het ons geantwoord en gesê: Ons is die kinders van JaHWeH wat Hemele en Aarde gemaak het.	",
"	14 En wat hierdie Huis betref, hy was baie jare gelede gebou deur ‘n groot en sterk koning van JisraEl, wat hom voltooi het.	",
"	15 Maar toe ons vaders teen die Elohey van JisraEl wat in die Hemele is, oortree het, en Hom verbitter het, het Hy hulle oorgegee aan die mag van Nebukadnésar, koning van Babel van die Chaldeërs	",
"	16 wat die Huis afgebreek en hom verbrand het en die mense in gevangeskap weggevoer het na Babel.	",
"	17 Maar in die eerste jaar wat koning Kores oor die Aarde van Babel regeer het, het koning Kores geskryf dat hierdie Huis weer herbou sal word.	",
"	18 En die gewyde goue en silwer voorwerpe wat Nebukadnésar weggevoer het uit die Huis in Jerusalem en in sy eie tempel geplaas het, het Kores die koning weer uitgeneem met die tempel in Babel en dit aan Serubbábel en aan Sabanasser die onder-goewerneur gegee,	",
"	19 met die bevel dat hy hierdie selfde bakke sou wegneem en hulle in die Tempel in Jerusalem terugplaas; en dat die Huis van JaHWeH op hierdie plek herbou moes word.	",
"	20 Toe Sabanasser daar aankom, het hy die fondasies gelê van die Huis van JaHWeH in Jerusalem; en van toe af tot nou toe word dit steeds gebou en is hy nog nie heeltemal voltooi nie.	",
"	21 Daarom, as dit goed is in die oë van die koning, laat daar ondersoek ingestel word in die rekords van koning Kores;	",
"	22 en as dit bevind word dat die herbou van die Huis van JaHWeH gedoen is met die toestemming van koning Kores, en as ons meester, die koning, dit so wil, laat hom ons daarvan in kennis stel.	",
"	23 Toe het koning Darius beveel dat daar in die geskrifte van Babel gesoek moet word, en daar is by Ecbatana die paleis, wat in die Aarde van Media was, ‘n rol gevind waarin hierdie dinge opgeteken is.	",
"	24 In die eerste jaar van die heerskappy van Kores het koning Kores beveel dat die Huis van JaHWeH weer herbou moes word in Jerusalem, waar hulle met voortdurende vuur geslag het;	",
"	25 die hoogte van hom sou sestig voorarm wees en die breedte sestig voorarm met drie wande gekapte steen en een wand van nuwe hout van daardie deel van die Aarde; en die uitgawes van hom moes kom uit die Huis van koning Kores	",
"	26 en dat die gewyde bakke van die Huis van JaHWeH, beide goud en silwer, wat Nebukadnésar uit die Huis in Jerusalem geneem het, weer teruggebring sou word na die Huis in Jerusalem en weer op die plek gesit word waar hulle voorheen was.	",
		
		
"	27 EN hy het ook beveel dat Sisinnes die onder-goewerneur van Aram en Fenícië, en Satrabusan en hulle metgeselle en ander landvoogde, wat in Aram en Fenícië aangestel was, versigtig moet wees om nie in te meng met die plek nie, maar toe te laat dat Serubbábel, die dienskneg van JaHWeH, en owerste van JeHûWdah, en die oudstes van die manne van JeHûWdah, die Huis van JaHWeH op daardie plek bou.	",
"	28 Ek het ook beveel dat dit gestaak moet word; en dat hulle moet toesien dat die manne van JeHûWdah wat uit die gevangeskap gekom het, gehelp word totdat die Huis van JaHWeH voltooi is:	",
"	29 En ook dat die inkomste uit Celo-Aram en Fenícië met ywer en oorleg aan Serubbábel, die owerste gegee word vir hierdie mense as ‘n slagdier aan JaHWeH van osse, ramme en lammers;	",
"	30 en ook koring, sout, wyn en olie, gedurende elke jaar gegee word sonder verdere vrae, volgens wat die priesters in Jerusalem sal aantoon wat elke dag gebruik sou word.	",
"	31 Want dranke sal gemaak word aan die Hoogste El vir die koning en vir sy kinders, en dat hulle mag bid vir ‘n lang lewe.	",
"	32 En hy het beveel dat wie ook al oortree, of enigiets wat tevore gespreek of geskryf is, verontagsaam, moet aan ‘n balk uit sy eie huis opgehang word, en dat al sy goedere die koning sal toekom.	",
"	33 Daarom sal JaHWeH, Wie se Naam daar aangeroep word, elke koning en volk heeltemal vernietig wat sy hand uitsteek om die bou van die Huis van JaHWeH in Jerusalem te verhinder of hom te beskadig.	",
"	34 Ek, Darius, die koning, het dit goed gevind dat hierdie dinge gedoen sal word met ywer volgens hierdie voorskrifte.	",

]
},
{
book: 'Een_Esra',
chapter: '7',
content: [
		
"	1 TOE het Sisinnes die goewerneur van Celo-Aram en Fenícië en Satrabusan en hulle metgeselle, die bevele van koning Darius uitgevoer,	",
"	2 en ywerig oor die gewyde werke toesig gehou, en die oudstes van die manne van JeHûWdah en owerstes van die Tempel bygestaan.	",
"	3 En so het die gewyde werk gefloreer soos Aggeus en ZekarJaH die profete geprofeteer het.	",
"	4 En hulle het hierdie dinge voltooi volgens die Bevel van JaHWeH, die Elohey van JisraEl en met die toestemming van Kores, Darius en Artasásta, die konings van Persië.	",
		
		
"	5 EN so is die Huis van Apartheid voltooi in die derde dag van die maand Adar, in die sesde jaar van Darius se koningskap.	",
"	6 En die kinders van JisraEl, die priesters en die Leviete en ander wat in gevangeskap was en wat by hulle gevoeg is, het gedoen volgens wat geskryf is in die Boekrolle van Moshè.	",
		
		
"	7 EN vir die inwyding van die Huis van JaHWeH het hulle honderd jong osse geslag, tweehonderd ramme, vierhonderd lammers;	",
"	8 en twaalf bokke vir die oortredinge van die hele JisraEl, volgens die getal van die stamme van JisraEl.	",
"	9 Die priesters en die Leviete het ook gestaan volgens die stamme, uitgedos in hulle gewade in diens van JaHWeH, die Elohey van JisraEl, volgens die Boek van Moshè, en die deurwagters was by elke Poort.	",
		
		
"	10 EN die kinders van JisraEl wat uit gevangeskap gekom het, het die Pasga gevier op die veertiende dag van die eerste maand, daarna is die priesters en die Leviete ingewy.	",
"	11 Hulle wat uit die gevangeskap was, is nie almal saam ingewy nie, maar die Leviete is almal saam ingewy.	",
"	12 En so het hulle die Pasga aangebied vir almal uit gevangeskap, en vir hulle broers, die priesters en vir hulleself.	",
"	13 En die kinders van JisraEl wat uit gevangeskap gekom het, het geëet, almal wat hulleself afgesonder het van die verfoeilikhede [gruwels] van die mense van die Aarde, en hulle het JaHWeH gesoek.	",
		
		
"	14 EN hulle het die Fees van die Ongesuurde Brode gevier, sewe dae lank en was vrolik voor die Aangesig van JaHWeH,	",
"	15 omdat Hy die raad van die koning van Assirië in hulle guns gedraai het om hulle hande te versterk in die werke van JaHWeH die Elohey van JisraEl.	",


]
},
{
book: 'Een_Esra',
chapter: '8',
content: [
		
"	1 EN hierna, toe Artasásta die koning van Persië regeer het, het Ezra gekom, die seun van SeráJaH, die seun van AzarJaH, die seun van GielkiJaH, die seun van Sallum,	",
"	2 die seun van Sadok, die [seun van] Ahítub, die seun van AmarJaH, die seun van AzarJaH, die seun van Mérajot, die seun van ZeragJaH, die seun van Ussi, die seun van Bukki, die seun van Abisúa, die seun van Pínehas, die seun van El-Azar, die seun van Aäron, die hoëpriester. [Ezra 7:1-5]	",
"	3 Hierdie Ezra het van Babel gekom as ‘n skrifgeleerde, baie geleerd in die Wet van Moshè wat deur die Elohey van JisraEl gegee is. [Ezra 7:6]	",
"	4 En die koning het aan hom eer bewys; want hy het barmhartigheid in sy oë gevind in al sy versoeke.	",
"	5 Daar het ook saam met hom opgegaan sekere van die kinders van JisraEl, en die priesters, en die Leviete, en van die sangers, deurwagters, en dienaars van die Apartheidsplek. [Ezra 7:7]	",
"	6 In die sewende jaar van die heerskappy van Artasásta, in die vyfde maand, dit was die koning se sewende jaar, het hulle uit Babel gegaan op die eerste dag van die eerste maand,	",
"	7 en na Jerusalem gekom na die voorspoedige reis wat JaHWeH hulle gegee het. [Ezra 7:10]	",
"	8 Want Ezra het groot vaardigheid gehad sodat hy niks uitgelaat het van dit wat in die Wet van JaHWeH was nie, en van die Gebooie, om aan die hele JisraEl die Verordeninge en oordele te onderrig. [Ezra 7:11]	",
"	9 Hierby was ook ‘n skriftelike opdrag van die koning Artasásta aan Ezra, die priester en leermeester van die Wet van JaHWeH, waarvan die afskrif soos volg is:	",
		
		
"	10 KONING Artasásta wens aan Ezra, die priester en leser van die Wet van JaHWeH, groete te stuur. [Ezra 7:12]	",
"	11 Aangesien ek my voorgeneem het om medelye te betoon, het ek bevel gegee dat diegene van die volk van [JeHûWdah] en van die priesters en Leviete wat in ons gebied is en wat gewillig en begerig is, saam met u na Jerusalem moet gaan. [Ezra 7:13]	",
"	12 Soveel van hulle wat graag wil gaan, laat hulle saam met u vertrek, aangesien dit goed gelyk het vir my en my sewe vriende, die raadgewers;	",
"	13 sodat hulle kan omsien na die sake van JeHûWdah en Jerusalem wat in die Wet van [jou] Elohey vervat is, [Ezra 7:14]	",
"	14 en hulle die geskenke aan die Elohey van JisraEl kan dra na Jerusalem wat ek en my vriende belowe het en al die goud en die silwer wat in die Aarde van Babel gevind kan word, dat hulle dit weer kan bring na hulle Elohey in Jerusalem, [Ezra 7:15]	",
"	15 Saam met dit wat deur u volk gegee word vir die Huis van hulle Elohey wat in Jerusalem is; en die silwer en goud wat bymekaargemaak kan word vir jong osse, ramme, lammers en dinge wat daaraan toebehoort; [Ezra 7:16]	",
"	16 met die doel dat hulle spysbydraes mag naderbring vir hulle Elohey op die altaar van hulle Elohey wat in Jerusalem is. [Ezra 7:17]	",
"	17 En wat jy en jou broers ook al met die silwer en goud doen, doen dit volgens die wil van julle Elohey. [Ezra 7:18]	",
"	18 En die bakke van JaHWeH wat aan jou gegee word vir gebruik in die Huis van jou Elohey wat in Jerusalem is. [Ezra 7:19]	",
"	19 Dit sal jy gee uit die skatkamer van die koning.	",
"	20 En ek, Artasásta, het ook beveel dat hulle wat aangestel is oor die skatte van Aram en Fenícië,	",
"	21 en wat Ezra die priester en leermeester van die Wet van die Hoogste El sal vra, dit sal spoedig aan hom gegee word	",
"	22 tot die som van ‘n honderd talente silwer, so ook koring, selfs tot ‘n honderd mud, en ‘n honderd dele wyn en ander dinge in oorvloed.	",
"	23 Laat alle dinge gedoen word volgens die Wet van Elohim, ywerig aan die Hoogste El, sodat gramskap nie kom op die koninkryk van die koning en sy kinders nie.	",
"	24 Ek het jou ook beveel dat jy geen belastings moet hef of laste op enige van die priesters of Leviete of gewyde sangers of deurwagters of skrifge-leerdes van die Tempel, of van enigeen wat werk in hierdie Tempel het, mag lê nie.	",
"	 25 Ook dat geen man die outoriteit het om enigiets op hulle op te lê nie.	",
"	26 En jy, Ezra, volgens die Wysheid van die Elohim, beëdig die regters en skeidsregters sodat hulle in die hele Aram en Fenícië kan oordeel almal wat die Wet van jou Elohey ken; en hulle wat haar nie ken nie, sal jy onderrig.	",
"	27 En wie ook al die Wet van jou Elohey oortree, en van die koning, sal streng gestraf word, of dit deur die dood is of deur ander lyfstraf of deur geldboete of gevangenisneming.	",
"	28 Toe sê Ezra die skrifgeleerde: Geseënd is JaHWeH en Hy alleen wat hierdie dinge in die hart van die koning gelê het om hierdie Huis wat in Jerusalem is te verhoog;	",
"	29 en Hy het my vereer in die aangesig van die koning en sy raadgewers, en al sy vriende en edelliede.	",
"	30 Daarom is ek aangemoedig deur die hulp van my Meester JaHWeH, en het ek manne van JisraEl bymekaargemaak om op te trek saam met my.	",
		
		
"	31 EN dit is die owerstes volgens hulle geslagregister en die verdeling van die heerskappy, wat saam met my opgetrek het van Babel onder die ryk van die koning, Artasásta: [Ezra 8:1]	",
"	32 Uit die kinders van Pínehas, Gersom; uit die kinders van Itamar, Gamalië; van die kinders van Dawid, Gattush die seun van ShekanJaH; [Ezra 8:1]	",
"	33 van die kinders van Párhos, ZekarJaH; en saam met hom is getel ‘n honderd-en-vyftig manne; [Ezra 8:3]	",
"	34 van die kinders van Pahat-Moab, ElJeHôWeynay, die seun van ZeragJaH en saam met hom tweehonderd man; [Ezra 8:4]	",
"	35 van die kinders van Sattu, ShekanJaH die seun van JahaziEl JehiEl, en saam met hom driehonderd man; [Ezra 8:5]	",
"	36 uit die kinders van Adin, Ebed, die seun van JôWnathan, en saam met hom tweehonderd-en-vyftig man; [Ezra 8:6]	",
"	37 van die kinders van Elam, JeshaJaH seun van AtálJaH en saam met hom sewentig man; van die kinders van ShafátJaH, ZebádJaH, die seun van MikaEl, en saam met hom sewentig man; [Ezra 8:8]	",
"	38 van die kinders van JôWab, ObadJaH seun van JehiEl, en saam met hom tweehonderd-en-twaalf man; [Ezra 8:9]	",
"	39 van die kinders van Bani: Sélomit seun van JôwsifJaH, en saam met hom ‘n honderd-en-sestig man; [Ezra 8:10]	",
"	40 van die kinders van Bébai, ZekarJaH seun van Bébai, en saam met hom agt-en-twintig man; [Ezra 8:11]	",
"	41 van die kinders van Asgad, JôWganan seun van Hakkátan en saam met hom ‘n honderd-en-tien man [Ezra 8:12]	",
"	42 van die kinders van Adoníkam, die laaste, en hierdie is hulle name: EliFelet, die seun van JeiEl, en ShemaJaH, en saam met hulle sewentig man [Ezra 8:13]; van die kinders van Bigwai, Utai en Sabbud en saam met hulle sewentig man. [Ezra 8:14]	",
"	43 En hierdie het ek bymekaar gebring by die rivier Ahawa, waar ons ons tente vir drie dae opgeslaan het; en ek het hulle ondersoek.	",
"	44 Maar toe ek daar geen priesters en Leviete vind nie, [Ezra 8:15]	",
"	45 het ek EliEzer gestuur, en AriEl, en ShemaJaH, en Masma en El-Natan, en Jarib, en JôWjarib, en Natan, El-Natan, ZekarJaH, en Mesúllam, hoofmanne en geleerd. [Ezra 8:16]	",
"	46 En ek het hulle gevra dat hulle na Iddo, die owerste, moes gaan wat in die plek van die skatkamer was,	",
"	47 en hulle beveel dat hulle met KasífJaH, sy broers, en met die rentmeesters in daardie plek moes praat, om aan ons manne te stuur wat die priesters se amp in die Huis van onse Elohey kon uitvoer. [Ezra 8:17]	",
"	48 En deur die magtige hand van onse Elohey het hulle vaardige manne van die kinders van Magli die seun van Levi, die seun van JisraEl na ons gebring, SerébJaH en sy seuns en sy broers wat reeds agtien was. [Ezra 8:18]	",
"	49 En GashabJaH en JeshaJaH en Hosea, sy broer, van die kinders van Merári en hulle kinders, twintig man. [Ezra 8:18]	",
"	50 En van die diensknegte van die Tempel wat Dawid en die owerstes verordineer het tot die diens van die Leviete, tweehonderd-en-twintig dienaars in die Tempel, hulle almal se name is skriftelik aangeteken. [Ezra 8:20]	",
"	51 En daar het ek ‘n vas aanbeveel vir die jong manne voor onse Elohey, om van Hom ‘n voorspoedige reis te vra, beide vir ons en vir hulle wat met ons was, vir ons kinders en ons vee; [Ezra 8:21]	",
"	52 want ek was skaam om vir die koning se huisknegte en ruiters te vra om op te tree as beskerming teen ons teenstanders.	",
"	53 Want ons het aan die koning gesê dat die Krag van ons Elohey met hulle is wat Hom in alle opregtheid soek. [Ezra 8:22]	",
"	54 En weer het ons onse Elohey gesmeek aangaande hierdie dinge en het Hom gunstig teenoor ons gevind. [Ezra 8:23]	",
"	55 Toe het ek twaalf van die owerstes van die priesters afgesonder, SerébJaH, en GashabJaH en nog tien manne van hulle broers saam met hulle; [Ezra 8:24]	",
"	56 en ek het die silwer en die goud vir hulle geweeg, die bydraes, en die gewyde bakke van die Huis van onse Elohey, wat die koning en sy raadgewers en die prinse en die hele JisraEl gegee het. [Ezra 8:24]	",
"	57 En nadat ek dit geweeg het, het ek aan hulle gegee seshonderd-en-vyftig talente silwer en goue bakke van ‘n honderd talente en ‘n honderd talente goud, [Ezra 8:26]	",
"	58 en twintig goue drinkbekers en twaalf bakke van fyn geelkoper, wat soos goud geglinster het. [Ezra 8:27]	",
"	59 En ek het aan hulle gesê: Albei van julle is apartgestel vir JaHWeH, en die bakke is apartgestel, en die goud en die silwer is ‘n eed aan JaHWeH, die Elohey van ons vaders. [Ezra 8:28]	",
"	60 Hou wag en pas hulle op totdat julle hulle aan die owerste van die priesters en die Leviete gegee het en aan die owerste van die stamme van JisraEl in Jerusalem, in die kamers van die Huis van JaHWeH. [Ezra 8:29]	",
"	61 Toe het die priesters en Leviete die silwer en goud en die bakke ontvang om dit na Jerusalem in die Huis van JaHWeH te bring. [Ezra 8:30]	",
		
		
"	62 EN ons het op die twaalfde van die eerste maand van die Ahawarivier af weggetrek en by Jerusalem gekom deur die Magtige Hand van onse Elohey wat met ons was; [Ezra 8:31-32]	",
"	63 en vanaf die begin van ons reis het Hy ons van elke vyand verlos en so het ons by Jerusalem gekom. En toe ons daar drie dae was, is die goud en die silwer, wat afgeweeg was, op die vierde dag in die Huis van onse Elohey afgelewer aan Méremot, die priester en seun van UriJaH. [Ezra 8:31]	",
"	64 En saam met hom was El-Azar, die seun van Pínehas, en saam met hulle was JôWzabad, die seun van Jehshua, en NoadJaH, die seun van Bínnuï, en die Leviete: alles is, volgens getal en gewig, aan hulle gegee. [Ezra 8:33]	",
"	65 En die volle gewig daarvan is opgeskryf in dieselfde uur. [Ezra 8:34]	",
"	66 En hulle wat uit ballingskap gekom het, het aan JaHWeH, die Elohey van JisraEl geslag, twaalf jong osse vir die hele JisraEl,	",
"	67 ses-en-negentig ramme, twee-en-sewentig lammers, twaalf bokke vir die oortreding; alles as ‘n brandoffer aan JaHWeH. [Ezra 8:35]	",
"	68 En hulle het die koning se bevele oorgedra aan die koning se rentmeesters en aan die landvoogde van Celo-Aram en Fenícië; en hulle het die volk en die Huis van JaHWeH vereer. [Ezra 8:36]	",
		

"	69 NA hierdie dinge gedoen is, het die owerstes na my gekom en gesê: Die volk van JisraEl, die owerstes, die priesters en Leviete, het hulle nie afgeskei van die verbasterde volke van die Aarde nie, ook nie van hulle gruwels nie;	",
"	70 van hierdie volke, die Kanaäniete, Hetiete, Feresiete, Jebusiete en die Moabiete, Egiptenare en Edomiete nie. [Ezra 9:1]	",
"	71 Want hulle en hul seuns het met die dogters van hierdie volke getrou, en so het die saadlyn van Apartheid, vermeng geraak met die verbasterde volke van die Aarde; en die owerstes en regeerders het hulle van die begin af aan hierdie wetsoortreding skuldig gemaak en eerste daaraan deel gehad. [Ezra 9:2]	",
"	72 En sodra ek dit gehoor het, het ek my klere geskeur, en ook my gewyde kleed, en ek het my hare uit my kop gepluk en ook my baard, en ek het bedroef en baie treurig gaan sit. [Ezra 9:3]	",
"	73 Toe het almal wat deur die Woord van die Elohim van JisraEl beweeg is, by my vergader terwyl ek getreur het oor die ongeregtigheid; maar ek het stil en droewig tot die skemerspysbydrae daar gesit. [Ezra 9:4]	",
"	74 En ek het opgestaan uit die vas met my geskeurde klere en gewyde kleed, en ek het neergekniel, en my handpalms na JaHWeH my Elohey en gesê: [Ezra 9:5]	",
"	75 O, JaHWeH, ek is beskaamd en bevrees voor U Aangesig,	",
"	76 want ons ongeregtigheid het bo ons hoofde vermenigvuldig en ons skuld reik op tot in die Hemele, van die tyd van ons vaders af. [Ezra 9:6]	",
"	77 En ons was in groot oortreding tot op hierdie dag.	",
"	78 En as gevolg van ons ongeregtigheid en ons vaders s’n, is ons met ons broers en ons konings en ons priesters met skande oorgegee aan die konings van die Aarde, aan die swaard, en aan ballingskap, en as ‘n buit tot op hierdie dag. [Ezra 9:7]	",
"	79 En nou was daar vir ‘n klein oomblik Barmhartigheid van die kant van JaHWeH onse Elohey betoon, dat daar ‘n oorblyfsel en ‘n Naam oorgebly het in die plek van U Apartheid; [Ezra 9:7]	",
"	80 om vir ons ‘n Lig te wees in die Huis van onse Elohey, en om aan ons Brood te gee in die tyd van ons slawerny. [Ezra 9:8]	",
"	81 Ja, toe ons knegte was, was ons nie deur ons Elohey verlaat nie; maar Hy het aan ons Medelye betoon voor die konings van Persië sodat hulle aan ons lewensbehoud gegee het;	",
"	82 en om die Huis van onse Elohey te verhoog en die verlatenheid van Sion op te hef, en om ons ‘n vastigheid te gee in JeHûWdah en Jerusalem. [Ezra 9:9]	",
"	83 En nou, o JaHWeH, wat sal ons sê noudat ons hierdie dinge het? Want ons het U Bevele oortree wat U aan ons gegee het deur die hand van U diensknegte, die profete, wat gesê het	",
"	84 dat die Aarde wat ons binnegaan om as ‘n besitting en ‘n erflating te neem, is ‘n Aarde wat besoedel is deur die besoedelinge van die verbasterde volke van die Aarde, want hulle het haar gevul met hulle vuilheid. [Ezra 9:11]	",
"	85 Daarom sal julle nou nie julle dogters verbind aan hulle seuns nie, ook sal julle nie hulle dogters neem vir julle seuns nie.	",
"	86 Meer nog, julle sal nooit hulle vrede [voorspoed] soek nie, sodat julle sterk sal wees en die suiwer dinge van die Aarde sal eet en sodat julle die erflating van die Aarde sal kan nalaat vir julle kinders vir ewig. [Ezra 9:12]	",
"	87 En alles wat ons oorgekom het, is die gevolg van ons besoedelde werke en groot skuld;	",
"	88 want U, o JaHWeH, het ons oortredinge lig gemaak en aan ons ‘n wortel gegee, maar ons het weer teruggedraai en U Wet oortree deur onsself te vermeng met die besoedeling van die gruwelike volke van die Aarde. [Ezra 9:13,14]	",
"	89 Sou U dan nie oor ons vertoorn wees totdat ons vernietig is nie? Sodat U aan ons geen wortel, saad of naam kan oorlaat nie? [Ezra 9:14]	",
"	90 O Elohey van JisraEl, U is getrou: want daar is vir ons hierdie dag ‘n wortel oorgelaat. [Ezra 9:15]	",
"	91 Kyk, nou is ons voor U met ons ongeregtigheid, want ons kan as gevolg daarvan nie langer voor U staan nie.	",
"	92 En toe Ezra bid en hul oortreding bely, en ween en plat op die Aarde voor die Tempel lê, het daar uit Jerusalem ‘n groot menigte manne en vroue en kinders vergader; want daar was ‘n groot geween onder die skare. [Ezra 10:1]	",
"	93 Toe het ShekanJaH, die seun van JehiEl, een van die seuns van Elam, uitgeroep en gesê: O Ezra, ons het oortree teen JaHWeH, ons het verbasterde vroue uit die volke van hierdie Aarde as vroue geneem, [Ezra 10:2]	",
"	94 nou is die hele JisraEl in twyfel, maar laat ons daaroor ‘n eed aan JaHWeH sweer dat ons al ons vroue wat ons uit die nasies geneem het, saam met hulle kinders, onder ons sal uitdryf.	",
"	95 Na jou goeddunke, en aan soveel as wat die Wet van JaHWeH gehoorsaam, staan op, en doen so! [Ezra 10:3]	",
"	96 Want aan jou behoort hierdie saak, en ons sal by jou staan, met die krag om dit te doen.	",
"	97 En Ezra het opgestaan en ‘n eed gesweer namens die hoofpriesters en Leviete van die hele JisraEl om hierdie dinge te doen; en hulle het so gesweer. [Ezra 10:4,5]:	",

]
},
{
book: 'Een_Esra',
chapter: '9',
content: [
		
"	1 TOE het Ezra opgestaan in die voorhof van die Tempel en gegaan na die kamer van JeHôWganan, die seun van El-Jashib. [Ezra 10:3]	",
"	2 En hy het daar gebly en nie brood geëet of water gedrink nie, en getreur oor die groot ongeregtigheid van die menigte. [Ezra 10:6]	",
"	3 En daar is ‘n proklamasie uitgevaardig deur die hele JeHûWdah en Jerusalem, aan almal wat uit die ballingskap gekom het, dat hulle in Jerusalem bymekaar moes kom; [Ezra 10:7]	",
"	4 en wie ook al nie daar was binne twee of drie dae nie, volgens dit wat die owerste ouderlinge bepaal het, hulle vee sou verban word en hulleself van die bannelinge geskei word. [Ezra 10:8]	",
"	5 En in drie dae het almal van die stam van JeHûWdah en Benjamin bymekaar gekom in Jerusalem op die twintigste dag van die negende maand.	",
"	6 En die hele menigte het in die voorhof van die Tempel gesit en van koue gebewe as gevolg van die saak en die reën. [Ezra 10:9]	",
		
		
"	7 TOE het Ezra opgestaan en aan hulle gesê: Julle het die Wet oortree deur verbasterde vroue te trou en daardeur die skuld van JisraEl vermeerder. [Ezra 10:10]	",
"	8 En nou, bely dit en verhoog JaHWeH, die Elohey van ons vaders, [Ezra 10:11]	",
"	9 en doen Sy Wil en skei julle af van die volke van die Aarde en van die verbasterde vroue.	",
"	10 Toe het die hele menigte uitgeroep en met ‘n harde stem gesê: Soos u gespreek het, so sal ons doen. [Ezra 10:12]	",
"	11 Maar die menigte is groot en dis winter, en ons kan nie onder die blote Hemele bly staan nie, en dit is geen werk vir ons van een of twee dae nie, want ons het hierin baie oortree. [Ezra 10:13]	",
"	12 Laat dus die voorgangers van die menigte agterbly en laat almal uit ons streek wat verbasterde vroue het,	",
"	13 op die aangewese tyd bymekaar kom, en saam met hulle die heersers en regters van elke gebied totdat ons die brandende Woede van JaHWeH in hierdie saak van ons, afgewend het. [Ezra 10:14]	",
"	14 Toe het JôWnathan die seun van AsaEl en JakséJaH die seun van Tikwa die saak volgens daardie bepaling op hulle geneem: en Mesúllam die Leviet en Sábbetai was hulle mede-regters. [2 Ezra 7:40; Ezra 10:15]	",
"	15 En hulle wat uit ballingskap kom, het hulle hierin gevolg.	",
"	16 En Ezra, die priester, het vir hom die hoofmanne van hulle vadershuise gekies, almal volgens hulle name: op die eerste dag van die tiende maand het hulle vergader om die saak te ondersoek. [Ezra 10:16]	",
"	17 En die saak aangaande die manne wat verbasterde vroue aangehou het, is op die eerste dag van die eerste maand tot ‘n einde gebring. [Ezra 10:17]	",
"	18 Onder die priesters is daar gevind wat verbasterde vroue gehad het.	",
"	19 Van die kinders van JeHôWshua, die seun van JôWtsadak en sy broers, MaàseiJâH en El-Azar en Jarib en GhedalJaH. [Ezra 10:18]	",
"	20 En hulle het hul hande uitgesteek om hulle vroue weg te stuur en om ramme nader te bring as versoening vir hulle skuld. [Ezra 10:19]	",
"	21 En van die kinders van Immer: Hanáni en ZebádJaH en Manes en Lameos en Hiereël en Azarias.	",
"	22 En van die kinders van Fesur; ElJôWeynay, MaàseiJâH, Mijamin JisMijamin en NethanEl en JôWzabad en El-Asah.	",
"	23 En van die Leviete: JôWzabad en Símeï en KeláJaH, wat genoem was Kelíta, en PetagJaH en JeHûWdah en EliEzer.	",
"	24 Van die gewyde sangers; El-Jashib en Uri.	",
"	25 Van die deurwagters; Sallum en Telem.	",
"	26 Van die JisraEliete, uit die kinders van Párhos; Hiermas en JesawJaH en MalkiJah en Mijamin en El-Azar en MalkiJah en BenáJaH.	",
"	27 Van die kinders van Elam; MattánJaH, ZekarJaH en JehiEl en Abdi en Jéremot en EliJaH.	",
"	28 En van die kinders van Samot; OtAzarJaH, Jarimoi en Labath en Seralias.	",
"	29 Van die kinders van Bébai; JeHôWganan en GanánJaH en Sabbai en Atlai.	",
"	30 Van die kinders van Bani; Mesúllam, Mallug, AdáJaH, Jasub, Seal en Jéremot.	",
"	31 En van die kinders van Addi; Naath en Moosias, Laerum en Naid en Matthanias en Sesthel, Balim en Manasse.	",
"	32 En uit die kinders van Anan; Elionas en Asajas en MalkiJah en Sabbeus en Simon Chosameus.	",
"	33 En van die kinders van Asom; Altaneus en Matthatias en Sabbaneus, en EliFelett en Manasses en Semer.	",
"	34 En van die kinders van Baani; Hieremias, Momdi, Ismaer, Juel, Mabdai en Pedias en Anos, Rabasion en Enasis en Mammitanem, El-Jashib, Bannus, Eliali, Sameis; Selemias, Natanius: En van die kinders van Ezora; Sesis, Esril, AsaEl, Samatus, Zamvre, JôWsef.	",
"	35 En van die kinders van Nebo; [JeiEl] MattithJaH, Sabad, [Sebína], Jáddai, JôWEl, BenáJaH.	",
"	36 Hulle almal het verbasterde vroue geneem en hulle het hul met hulle kinders weggestuur.	",
"	37 En die priesters en Leviete en die ander uit JisraEl, het in Jerusalem en omgewing gaan woon op die eerste dag van die sewende maand; en die kinders van JisraEl was in hulle woongebiede.	",
		
		
"	38 EN die hele menigte het eendragtig saamgekom op die groot ruimte wat voor die gewyde Poort na die ooste was;	",
"	39 en hulle het aan Ezra die priester en leermeester gesê dat hy die Wette van Moshè moes bring wat JaHWeH aan JisraEl gegee het. [NegemJaH 8:1-2]	",
"	40 En Ezra, die hoëpriester, het die Wet na die hele menigte gebring, aan mans sowel as vroue, en aan al die priesters, om die Wet op die eerste dag van die sewende maand te hoor. [NegemJaH 8:2-3]	",
"	41 En hy het in die groot plek voor die Waterpoort van die oggend tot die middag gelees, voor die aangesig van beide manne en vroue; en die hele menigte het na die Wet geluister. [NegemJaH 8:4]	",
"	42 En Ezra, die priester en leermeester van die Wet, het op ‘n verhewe houtstoel wat vir daardie doel gemaak is, gesit.	",
"	43 En daar het by hom gestaan MattithJaH, Sema, AnaJaH, Asarias, UriJaH, GielkiJaH en MaàseiJâH aan die regterkant;	",
"	44 en aan die linkerkant het gestaan PedahJaH, MisahaEl, MalkiJah, Hasum en Hasbaddána, ZekarJaH en Mesúllam. [NegemJaH 8:5]	",
"	45 Toe het Ezra die Boekrol van die Wet voor die hele menigte geneem, en hy het eervol in die teenwoordigheid van hulle almal gesit.	",
"	46 En toe hy die Wet uitlê, het hulle almal regop gestaan. [NegemJaH 8:6]  Toe het Ezra, Majesteit JaHWeH die Hoogste El geloof, die Elohey van die Skeppingsleërmag, die Almagtige.	",
		
"	47 En die hele volk het daarop geantwoord, Amein; en hulle hande opgelig en na die Aarde neergebuig en JaHWeH aanbid. [NegemJaH 8:7]	",
"	48 Ook Jehshua, Bani, SerébJaH, Jamin, Akkub, Sábbetai, HodiJaH, MaàseiJâH en Kelíta, AzarJaH en JôWzabad en Hanan PelaJaH, die Leviete, het hulle in die Wet van Elohim onderrig. [NegemJaH 8:8]	",
"	49 En hulle het die Wet van Elohim voor die menigte gelees sodat almal haar kon verstaan. [NegemJaH 8:9]	",
"	50 Toe het NegemJaH met Ezra, die hoëpriester en voorleser, gepraat en met die Leviete wat die menigte onderrig het en gesê:	",
"	51 Hierdie dag is apartgestel aan JaHWeH julle Elohey; en hulle het almal geween toe hulle die Wet hoor: [NegemJaH 8:10]	",
"	52 Gaan dan heen en eet en drink soet dranke en stuur ‘n deel daarvan as geskenke aan hulle wat niks het nie; [NegemJaH 8:11]	",
"	53 want hierdie dag is apartgestel vir JaHWeH: en wees nie bedroef nie, want JaHWeH sal julle verhoog. [NegemJaH 8:12]	",
		
		
"	54 TOE het die Leviete die hele volk beveel en gesê: Hierdie dag is apartgestel vir JaHWeH, wees nie bedroef nie.	",
"	55 Toe het almal op hulle weg gegaan, elkeen om te gaan eet en drink en vrolik te wees en om geskenke te gee aan hulle wat niks het nie, en om hulle grootliks op te vrolik,	",
"	56 want hulle het die woorde verstaan waarin hulle onderrig is en waarvoor hulle bymekaargekom het.	",

]
}
];
