const esraChapters = [

{
book: 'Esra',
chapter: '1',
content: [

"	1 EN in die eerste jaar van Kores, die koning van Persië, het JaHWeH, sodat die Woord van JaHWeH vervul kon word wat deur die mond van JirmeJaH gespreek is - die gees van Kores, die koning van Persië, opgewek, dat hy ’n oproep deur sy hele koninkryk laat gaan het, selfs ook skriftelik, om te sê:	",
"	2 So sê Kores, die koning van Persië: Al die koninkryke van die Aarde het JaHWeH, die Elohey van die Hemele, aan my gegee; en Hy het my opgedra om vir Hom ’n Huis te bou in Jerusalem wat in JeHûWdah is.	",
"	3 Enigeen onder julle wat aan Sy volk behoort - mag sy Elohey met hom wees, en laat hom optrek na Jerusalem wat in JeHûWdah is, en die Huis van JaHWeH, die Elohey van JisraEl, bou! Hy is die Elohim wat in Jerusalem is.	",
"	4 En enigeen wat oorgebly het, in enige plek waar hy as vreemdeling vertoef- hom moet die manne van sy woonplek ondersteun met silwer en goud en met goed en vee, en met die vrywillige skenkings vir die Huis van die Elohim wat in Jerusalem is.	",
"	5 Toe het die hoofde van die vaders van JeHûWdah en Benjamin klaargemaak, en die priesters en die Leviete - elkeen wie se gees die Elohim opgewek het om op te trek, om die Huis van JaHWeH wat in Jerusalem is, te bou.	",
"	6 En almal wat rondom hulle was, het hul hande versterk met silwervoorwerpe, met goud, met goed en vee en kosbare geskenke, behalwe alles wat hulle as vrywillige skenkings aangebring het.	",
"	7 En koning Kores het die voorwerpe van die Huis van JaHWeH uitgelewer wat Nebukadnésar uit Jerusalem weggevoer en in die huis van sy gode gesit het.	",
"	8 En Kores, die koning van Persië, het dit uitgelewer onder toesig van Mítredat, die skatmeester; en dié het dit aan Sésbassar, die vors van JeHûWdah, voorgetel.	",
"	9 En dit was hulle getal: dertig goue drinkbekers, duisend silwer drinkbekers, nege-en-twintig messe;	",
"	10 dertig goue bekers; verder vierhonderd-en-tien silwerbekers, duisend ander voorwerpe.	",
"	11 Al die voorwerpe van goud en silwer was: vyfduisend-vierhonderd; dit alles het Sésbassar saamgebring toe die ballinge uit Babel na Jerusalem opgetrek het.	",

]
},
{
book: 'Esra',
chapter: '2',
content: [
		
"	1 EN dit is die inwoners van die provinsie [JeHûWdah] wat opgetrek het uit die gevangenskap van die ballinge wat Nebukadnésar, die koning van Babel, na Babel weggevoer het, wat na Jerusalem en JeHûWdah teruggekeer het, elkeen na sy stad;	",
"	2 wat saam met Serubbábel, Jehshua, NegemJaH, SeráJaH, ReelaJaH, Mórdegai, Bilsan, Mispar, Bigwai, Rehum, Baäna gekom het; die aantal manne van die volk van JisraEl was:	",
"	3 die kinders van Parhos, tweeduisend-eenhonderd-twee-en-sewentig;	",
"	4 die kinders van ShafátJaH, driehonderd-twee-en-sewentig;	",
"	5 die kinders van Arag, sewehonderd-vyf-en-sewentig;	",
"	6 die kinders van Pahat-Moab, van die kinders van Jehshua [en] JôWab, tweeduisend-agthonderd-en-twaalf;	",
"	7 die kinders van Elam, duisend-tweehonderd-vier-en-vyftig;	",
"	8 die kinders van Sattu, negehonderd-vyf-en-veertig;	",
"	9 die kinders van Sakkai, sewehonderd-en-sestig;	",
"	10 die kinders van Bani, seshonderd-twee-en-veertig;	",
"	11 die kinders van Bébai, seshonderd-drie-en-twintig;	",
"	12 die kinders van Asgad, duisend-tweehonderd-twee-en-twintig;	",
"	13 die kinders van Adoníkam, seshonderd-ses-en-sestig;	",
"	14 die kinders van Bigwai, tweeduisend-ses-en-vyftig;	",
"	15 die kinders van Adin, vierhonderd-vier-en-vyftig;	",
"	16 die kinders van Ater, van JegizkiJaH, agt-en-negentig;	",
"	17 die kinders van Bésai, driehonderd-drie-en-twintig;	",
"	18 die kinders van Jora, honderd-en-twaalf;	",
"	19 die kinders van Hasum, tweehonderd-drie-en-twintig;	",
"	20 die kinders van Gibaar, vyf-en-negentig;	",
"	21 die kinders van Betlehem, honderd-drie-en-twintig;	",
"	22 die manne van Netófa, ses-en-vyftig;	",
"	23 die manne van Anatot, honderd-agt-en-twintig;	",
"	24 die kinders van Asmáwet, twee-en-veertig;	",
"	25 die kinders van Kirjat-Arim, Kefíra en Béërot, sewehonderd-drie-en-veertig;	",
"	26 die kinders van Rama en Geba, seshonderd-een-en-twintig;	",
"	27 die manne van Migmas, honderd-twee-en-twintig;	",
"	28 die manne van BetEl en Ai, tweehonderd-drie-en-twintig;	",
"	29 die kinders van Nebo, twee-en-vyftig;	",
"	30 die kinders van Magbis, honderd-ses-en-vyftig;	",
"	31 die kinders van die ander Elam, duisend-tweehonderd-vier-en-vyftig;	",
"	32 die kinders van Harim, driehonderd-en-twintig;	",
"	33 die kinders van Lod, Hadid en Ono, sewehonderd-vyf-en-twintig;	",
"	34 die kinders van Jérigo, driehonderd-vyf-en-veertig;	",
"	35 die kinders van Sénaä, drieduisend-seshonderd-en-dertig.	",
"	36 Die priesters: die kinders van JedaJaH, van die huis van Jehshua, negehonderd-drie-en-sewentig;	",
"	37 die kinders van Immer, duisend-twee-en-vyftig;	",
"	38 die kinders van Pasgur, duisend-tweehonderd-sewe-en-veertig;	",
"	39 die kinders van Harim, duisend-en-sewentien.	",
"	40 Die Leviete: die kinders van Jehshua en KadmiEl, van die kinders van HodawJaH, vier-en-sewentig.	",
"	41 Die sangers: die kinders van Asaf, honderd-agt-en-twintig.	",
"	42 Die kinders van die poortwagters: die kinders van Sallum, die kinders van Ater, die kinders van Talmon, die kinders van Akkub, die kinders van Hatíta, die kinders van Sobai, almal saam honderd-nege-en-dertig.	",
"	43 Die tempeldienaars: die kinders van Síha, die kinders van Hasúfa, die kinders van Tábbaot;	",
"	44 die kinders van Keros, die kinders van Síaha, die kinders van Padon;	",
"	45 die kinders van Lebána, die kinders van Hagába, die kinders van Akkub;	",
"	46 die kinders van Hagab, die kinders van Samlai, die kinders van Hanan;	",
"	47 die kinders van Giddel, die kinders van Gahar, die kinders van ReáJaH;	",
"	48 die kinders van Resin, die kinders van Nekóda, die kinders van Gassam;	",
"	49 die kinders van Ussa, die kinders van Paséag, die kinders van Bésai;	",
"	50 die kinders van Asna, die kinders van die Meüniete, die kinders van die Nefisiete;	",
"	51 die kinders van Bakbuk, die kinders van Hakúfa, die kinders van Harhur;	",
"	52 die kinders van Baslut, die kinders van Mehída, die kinders van Harsa;	",
"	53 die kinders van Barkos, die kinders van Sísera, die kinders van Temag;	",
"	54 die kinders van Nesíag, die kinders van Hatífa;	",
"	55 die kinders van die dienaars van Salomo: die kinders van Sotai, die kinders van Hassoféret, die kinders van Perúda;	",
"	56 die kinders van Jáäla, die kinders van Darkon, die kinders van Giddel;	",
"	57 die kinders van ShafátJaH, die kinders van Hattil, die kinders van Pogéret-Hassebáim, die kinders van Ami -	",
"	58 al die tempeldienaars en die kinders van die dienaars van Salomo was driehonderd-twee-en-negentig.	",
"	59 En dit is hulle wat uit Tel-Melag, Tel-Harsa, Kerub, Addan, Immer opgetrek het, maar wat nie hulle familie en hulle saadlyn kon aanwys of hulle van JisraEl afkomstig was nie -	",
"	60 die kinders van DeláJaH, die kinders van TobiJaH, die kinders van Nekóda, ses-honderd-twee-en-vyftig.	",
"	61 En van die kinders van die priesters: die kinders van KabáJaH, die kinders van Hakkos, die kinders van Barsíllai, wat uit die dogters van Barsíllai, die Gileadiet, ’n vrou geneem het en na hulle naam genoem is.	",
"	62 Hulle het hul stamboom gesoek onder die wat in die register opgeneem is, maar dit was nie te vinde nie; daarom is hulle gekleurd verklaar, onbevoeg vir die priesterskap.	",
"	63 En die goewerneur het aan hulle gesê dat hulle nie mag eet van die Apartheid van die Aparthede nie, totdat ’n priester sou optree met Urim en Tummim.	",
"	64 Die hele vergadering saam was twee-en-veertigduisend-driehonderd-en-sestig,	",
"	65 behalwe hulle slawe en hulle slavinne; dié was seweduisend-driehonderd-sewe-en-dertig. En hulle het tweehonderd sangers en sangeresse gehad.	",
"	66 Hulle perde was sewehonderd-ses-en-dertig; hulle muile, tweehonderd-vyf-en-veertig;	",
"	67 hulle kamele, vierhonderd-vyf-en-dertig; esels, sesduisend-sewehonderd-en-twintig.	",
"	68 En van die hoofde van die vaders het, toe hulle by die Huis van JaHWeH kom wat in Jerusalem is, vrywillig gegee vir die Huis van die Elohim om dit weer op te rig op sy plek.	",
"	69 Na hul vermoë het hulle bygedra tot die fonds van die werk: in goud een-en-sestigduisend dragmes, en in silwer vyfduisend mines en honderd priesterrokke.	",
"	70 So het dan die priesters en die Leviete en van die volk en die sangers en die poortwagters en die tempeldienaars in hulle stede gaan woon, en die hele JisraEl in húlle stede.	",

]
},
{
book: 'Esra',
chapter: '3',
content: [
		
"	1 EN toe die sewende maand aankom en die kinders van JisraEl in die stede was, het die volk soos een man in Jerusalem byeengekom.	",
"	2 En Jehshua, die seun van JôWtsadak, met sy broers, die priesters, en Serubbábel, die seun van ShealtiEl, met sy broers, het klaargemaak en die altaar van die Elohey van JisraEl gebou om daar brandoffers op te dra soos geskrywe staan in die Wet van Moshè, die man van die Elohim.	",
"	3 En hulle het die altaar op sy grondveste opgerig, omdat die skrik vir die volke van die Aarde op hulle gekom het; en hulle het daar brandoffers opgedra aan JaHWeH, brandoffers smôrens en saans.	",
"	4 En hulle het die Fees van die Takskuilings gehou soos geskrywe staan, en brandoffers dag vir dag volgens die getal, na die eis van elke dag, soos voorgeskrywe was;	",
"	5 en daarna die voortdurende brandoffer en dié van die vernuwings en van al die aangewyste Feestye van JaHWeH en van elkeen wat aan JaHWeH ’n vrywillige skenking gebring het.	",
"	6 Van die eerste dag van die sewende maand af het hulle begin om brandoffers aan JaHWeH te bring, alhoewel die fondament van die Huis van JaHWeH nog nie gelê was nie.	",
"	7 Maar hulle het silwer gegee aan die klipkappers en die skrynwerkers, en aan die Sidoniërs en Tiriërs voedsel en drank en olie om sederhout van die Líbanon te bring na die see, na Jafo, volgens die verlof van Kores, die koning van Persië, aan hulle.	",
"	8 En in die tweede jaar ná hulle aankoms by die Huis van die Elohim in Jerusalem, in die tweede maand, het Serubbábel, die seun van ShealtiEl, ’n begin gemaak, hy en Jehshua, die seun van JôWtsadak, en hulle ander broers, die priesters en die Leviete en almal wat uit die gevangenskap na Jerusalem gekom het: hulle het die Leviete van twintig jaar oud en daarbo aangestel om toesig te hou oor die werk aan die Huis van JaHWeH.	",
"	9 En Jehshua het opgetree, sy seuns en sy broers, KadmiEl met sy seuns, die seuns van JeHûWdah, soos een man, om toesig te hou oor die wat die werk gedoen het aan die Huis van die Elohim, [met] die seuns van Hénadad, hulle seuns en hulle broers, die Leviete.	",
"	10 Toe die bouers dan die fondament van die Huis van JaHWeH lê, het hulle die priesters in ampsgewaad met trompette, en die Leviete, die seuns van Asaf, met simbale opgestel om JaHWeH te loof volgens die instelling van Dawid, die koning van JisraEl.	",
"	11 En hulle het aangehef met lof en dank aan JaHWeH, want Hy is suiwer, want Sy Medelye met JisraEl is ewig! En die hele volk het gejuig met groot gejuig toe hulle JaHWeH loof, omdat die fondament van die Huis van JaHWeH gelê was.	",
"	12 Maar baie van die priesters en die Leviete en die hoofde van die vaders, van die oues wat die eerste Huis gesien het, het hardop gehuil toe die fondament van hierdie Huis voor hulle oë gelê is, terwyl baie met gejuig, met Blydskap die stem verhef het.	",
"	13 En die volk kon die geluid van blye gejuig nie onderskei van die geluid van gehuil van die volk nie, want die volk het gejuig met groot gejuig, sodat die geluid tot ver weg gehoor is.	",

]
},
{
book: 'Esra',
chapter: '4',
content: [
		
"	1 EN toe die teëstanders van JeHûWdah en Benjamin hoor dat die ballinge ’n Tempel bou vir JaHWeH, die Elohey van JisraEl,	",
"	2 het hulle aangekom na Serubbábel en na die hoofde van die vaders en aan hulle gesê: Laat ons saam met julle bou, want net soos julle soek ons julle Elohey, en aan Hom slag ons van die dae van Esar-Haddon af, die koning van Assirië, wat ons hierheen laat optrek het.	",
"	3 Maar Serubbábel en Jehshua en die ander hoofde van die vaders van JisraEl het aan hulle gesê: Dit sal nie gaan dat julle saam met ons ’n Huis vir ons Elohey bou nie, maar óns alleen sal vir JaHWeH, die Elohey van JisraEl, dit bou soos koning Kores, die koning van Persië, ons beveel het.	",
"	4 Toe het die volk van die Aarde die hande van die volk van JeHûWdah laat verslap en hulle afgeskrik om nie te bou nie.	",
"	5 En hulle het raadgewers teen hulle gehuur om hulle plan te verydel al die dae van Kores, die koning van Persië, tot op die regering van Darius, die koning van Persië.	",
"	6 En onder die regering van Ahasvéros, in die begin van sy regering, het hulle ’n aanklag geskrywe teen die inwoners van JeHûWdah en Jerusalem.	",
"	7 En in die dae van Artasásta het Bislam, Mítredat, TabeEl en sy ander partygenote aan Artasásta, die koning van Persië, geskrywe; en die skrif van die brief was Aramees geskrywe en in Aramees vertaal.	",
"	8 Rehum, die bevelhebber, en Simsai, die skrywer, het ’n brief geskrywe teen Jerusalem aan Artasásta, die koning, van die volgende inhoud:	",
"	9 Rehum, die bevelhebber, en Simsai, die skrywer, en hulle ander partygenote, die Dinaïete, die Afarsatgiete, die Tarpeliete, die Afarsiete, die Arkewiete, die Babiloniërs, die Susangiete, naamlik die Elamiete,	",
"	10 en die ander volke wat die groot en beroemde Asnappar weggevoer en in die stad Samaría en die orige gebied wes van die Eufraat laat woon het. En nou -	",
"	11 dit is ’n afskrif van die brief wat hulle aan hom gestuur het: Aan koning Artasásta, u dienaars, die manne wes van die Eufraat. En nou -	",
"	12 aan die koning word bekend gemaak dat die manne van JeHûWdah wat van u af na ons opgetrek het, in Jerusalem aangekom het. Hulle is besig om die rebelse en slegte Stad op te bou: die mure voltooi hulle en die fondamente herstel hulle.	",
"	13 Laat dit nou aan die koning bekend wees dat hulle, as dié Stad opgebou en die mure voltooi is, geen belasting, opbrengs of tol sal gee nie - wat aan die inkomste van die konings skade sal doen.	",
"	14 Aangesien ons nou die sout van die paleis geëet het en dit ons nie pas om die smaad van die koning aan te sien nie, daarom stuur ons en laat die koning weet,	",
"	15 dat hulle kan soek in die Boekrol van die Geskiedenis van u vaders; dan sal u in die Boekrol van die Geskiedenis vind en [daaruit] verneem dat dié Stad ’n rebelse Stad was wat aan konings en provinsies skade gedoen het, en dat hulle van ouds af binne-in haar oproer verwek het; daarom is dié Stad verwoes.	",
"	16 Ons maak die koning bekend dat, as dié Stad opgebou en die mure voltooi word, u daardeur geen deel sal hê wes van die Eufraat nie.	",
"	17 Die koning het as antwoord gestuur: Aan Rehum, die bevelhebber, en Simsai, die skrywer, en hulle ander partygenote wat in Samaría en in die orige gebied wes van die Eufraat woon: Voorspoed in sulke tye -	",
"	18 die brief wat julle aan ons gestuur het, is aan my in vertaling voorgelees.	",
"	19 En deur my is bevel gegee, en hulle het gesoek en gevind dat dié Stad van ouds af hom teen konings versit, en dat rebellie en oproer in haar verwek is.	",
"	20 En magtige konings was daar oor Jerusalem wat geheers het oor die hele gebied wes van die Eufraat, en belasting, opbrengs en tol is aan hulle gegee.	",
"	21 Gee nou bevel dat dié manne moet ophou en hierdie Stad nie opgebou mag word totdat deur my bevel gegee sal word nie.	",
"	22 En wees gewaarsku om hierin geen nalatigheid te begaan nie, dat daar nie groter skade tot nadeel van die konings ontstaan nie.	",
"	23 Net toe die afskrif van die brief van Artasásta, die koning, aan Rehum en Simsai, die skrywer, en hulle partygenote voorgelees is, het hulle haastig na Jerusalem, na die manne van JeHûWdah gegaan en hulle met geweld en mag laat ophou.	",
"	24 Toe het die werk aan die Huis van Eloah wat in Jerusalem is, opgehou; en dit is gestaak tot op die tweede jaar van die regering van Daríus, die koning van Persië.	",

]
},
{
book: 'Esra',
chapter: '5',
content: [
		
"	1 MAAR Hággai, die profeet, en ZekarJaH, die seun van Iddo, die profete, het vir die manne van JeHûWdah wat in JeHûWda en Jerusalem was, geprofeteer in die Naam van die Elohey van JisraEl wat oor hulle was.	",
"	2 Toe het Serubbábel, die seun van ShealtiEl, en Jehshua, die seun van JôWtsadak, klaargemaak, en hulle het begin om die Huis van Eloah wat in Jerusalem was, te bou, en saam met hulle was die profete van Eloah wat hulle ondersteun het.	",
"	3 In dié tyd het Tattenai, die goewerneur wes van die Eufraat, en Setar-Bosenai en hulle partygenote na hulle gekom en só aan hulle gesê: Wie het julle bevel gegee om hierdie Huis te bou en hierdie muur te voltooi?	",
"	4 Só het ons dan vir hulle gesê wat die name was van die manne wat hierdie gebou oprig.	",
"	5 Maar die Oog van hulle Eloah was oor die oudstes van die manne van JeHûWdah, sodat hulle hul nie verhinder het nie, totdat die berig voor Daríus sou kom, en dan daaroor ’n brief teruggebring sou word.	",
"	6 ’n Afskrif van die brief wat Tattenai, die goewerneur wes van die Eufraat, en Setar-Bosenai en sy partygenote, die Afarsegaïete wat wes van die Eufraat was, aan koning Daríus gestuur het.	",
"	7 Hulle het aan hom ’n berig gestuur, en só was binne-in haar geskrywe: Aan koning Daríus - alle voorspoed!	",
"	8 Aan die koning word bekend gemaak dat ons na die provinsie JeHûWda, na die Huis van die grote Eloah, gegaan het; en hy word van groot klippe gebou, en hout word teen die mure gelê, en daardie werk word sorgvuldig gedoen en vorder goed onder hulle hande.	",
"	9 Toe het ons daardie oudstes gevra; só het ons aan hulle gesê: Wie het julle bevel gegee om hierdie Huis te bou en hierdie muur te voltooi?	",
"	10 Verder het ons vir hulle ook hul name gevra om u bekend te maak, dat ons die name van die manne wat aan hul hoof staan, kan skrywe.	",
"	11 En hulle het ons die volgende antwoord gegee en gesê: Ons is knegte van die Elohey van Hemele en Aarde, en ons herbou die Huis wat baie jare gelede gebou is, wat ’n groot koning van JisraEl gebou en voltooi het.	",
"	12 Maar omdat ons vaders die Elohey van die Hemele vertoorn het, het Hy hulle oorgegee in die hand van Nebukadnésar, die koning van Babel, die Chaldeër; hy het hierdie Huis verwoes en die volk na Babel weggevoer.	",
"	13 Maar in die eerste jaar van Kores, die koning van Babel, het koning Kores bevel gegee om hierdie Huis van Eloah te bou.	",
"	14 En ook die goue en silwervoorwerpe van die Huis van Eloah wat Nebukadnésar uit die Tempel in Jerusalem weggevoer en in die tempel van Babel gebring het, dit het koning Kores uit die tempel van Babel uitgehaal, en dit is oorhandig aan een, met die naam van Sésbassar, wat hy as goewerneur aangestel het;	",
"	15 en hy het vir hom gesê: Neem hierdie voorwerpe, gaan sit dit in die Tempel in Jerusalem, en laat die Huis van Eloah gebou word op sy plek.	",
"	16 Toe het hierdie Sésbassar gekom, hy het die fondamente van die Huis van Eloah in Jerusalem gelê, en van toe af tot nou toe is daar gebou, maar hy is nog nie voltooi nie.	",
"	17 As die koning dit nou goedvind, laat dan nagesoek word in die skathuis van die koning daar in Babel, of dit so is dat deur koning Kores bevel gegee is om hierdie Huis van Eloah in Jerusalem te bou; en mag die koning sy beslissing hieroor aan ons stuur.	",

]
},
{
book: 'Esra',
chapter: '6',
content: [
	
"	1 TOE het koning Daríus bevel gegee, en hulle het nagesoek in die Huis van die boekrolle waar hulle in Babel die skatte wegbêre.	",
"	2 En in Agméta, in die vesting wat in die provinsie Médië lê, is ’n Boekrol van die geskiedenis gevind, en só was binne-in haar geskrywe:	",
"	3 In die eerste jaar van koning Kores het koning Kores bevel gegee: Die Huis van Eloah - in Jerusalem - dié Huis moet gebou word as ’n plek waar hulle slagdiere bring, en sy fondamente moet gelê word; sy hoogte moet sestig voorarm, sy breedte sestig voorarm wees;	",
"	4 met drie lae groot klippe en een laag nuwe hout; en die onkoste sal deur die huis van die koning gedra word.	",
"	5 En ook die goue en silwervoorwerpe van die Huis van Eloah wat Nebukadnésar uit die Tempel in Jerusalem weggevoer en na Babel gebring het, moet hulle teruggee, dat dit in die Tempel in Jerusalem op hulle plek kan kom, en jy moet dit in die Huis van Eloah sit.	",
"	6 Tattenai, goewerneur wes van die Eufraat, Setar-Bosenai met hulle partygenote, die Afarsegaiete wes van die Eufraat - julle moet daar nou ver van af bly.	",
"	7 Laat die werk aan daardie Huis van Eloah toe; die goewerneur van die manne van JeHûWdah en die oudstes van die manne van JeHûWdah mag daardie Huis van Eloah op sy plek bou.	",
"	8 En deur my word bevel gegee hoe julle met hierdie oudstes van die manne van JeHûWdah moet handel om daardie Huis van Eloah te bou, naamlik: Uit die inkomste van die koning, uit die belasting van die westelike gebied van die Eufraat moet die onkoste aan daardie manne sorgvuldig vergoed word sonder vertraging.	",
"	9 En wat nodig is, jong bulle sowel as ramme en lammers vir brandoffers aan die Elohey van die Hemele, koring, sout, wyn en olie moet aan hulle volgens opgawe van die priesters in Jerusalem sonder versuim dag vir dag gelewer word,	",
"	10 dat hulle welgevallig kan wees en reukwerk bring aan die Elohey van die Hemele en bid vir die lewe van die koning en van sy seuns.	",
"	11 En deur my word bevel gegee dat van elkeen wat hierdie bevel oortree, ’n balk uit sy huis geruk sal word, en dat hy daaraan opgehang en vasgeslaan sal word, en van sy huis hieroor ’n puinhoop gemaak sal word.	",
"	12 En mag Eloah wat Sy Naam daar laat woon het, elke koning en volk neerwerp wat sy hand uitsteek om dit te oortree, om naamlik die Huis van Eloah in Jerusalem te verwoes. Ek, Daríus, gee bevel; sorgvuldig moet dit uitgevoer word.	",
"	13 Toe het Tattenai, die goewerneur wes van die Eufraat, Setar-Bosenai en hulle partygenote sorgvuldig net so gehandel soos koning Daríus laat weet het.	",
"	14 En die oudstes van die manne van JeHûWdah het gebou en goed gevorder deur die profetiese werksaamheid van die profeet Hággai en ZekarJaH, die seun van Iddo; en hulle het gebou en voltooi op bevel van die Elohey van JisraEl en op bevel van Kores en Daríus en Artasásta, koning van Persië.	",
"	15 En hierdie Huis was klaar op die derde dag van die maan[d] van Adar; dit was die sesde jaar van die regering van koning Daríus.	",
		
		
"	16 EN die kinders van JisraEl, die priesters en die Leviete en die ander, uit die ballingskap afkomstig, het die inwyding van hierdie Huis van Eloah met vreugde gevier.	",
"	17 En hulle het by die inwyding van die Huis van Eloah nadergekom met honderd bulle, tweehonderd ramme, vierhonderd lammers en twaalf bokke opgedra vir die oortredings wat begaan is vir die hele JisraEl volgens die getal van die stamme van JisraEl.	",
"	18 En hulle het die priesters aangestel volgens hulle afdelings en die Leviete volgens hulle afdelings vir die diens van Eloah in Jerusalem, volgens die voorskrif in die Boekrol van Moshè.	",
"	19 En die ballinge het die Pasga gehou op die veertiende van die eerste maand.	",
"	20 Want die priesters en die Leviete het hulle soos een man gesuiwer en hulle almal was skoon - en die Pasga is doodgebloei vir al die ballinge en vir hulle broers, die priesters, en vir hulleself.	",
"	21 En die kinders van JisraEl wat uit die ballingskap teruggekeer het, het hom geëet en elkeen wat hom van die besoedeling van die nasies van die Aarde afgesonder het om saam met hulle JaHWeH, die Elohey van JisraEl, te soek.	",
"	22 Hulle het ook die Fees van die Ongesuurde Brode met Blydskap sewe dae lank gehou; want JaHWeH het hulle verbly en die hart van die koning van Assirië na hulle omgewend, om hul hande te versterk in die werk aan die Huis van die Elohim, die Elohey van JisraEl.	",

]
},
{
book: 'Esra',
chapter: '7',
content: [
		
"	1 EN ná hierdie gebeurtenisse, onder die regering van Artasásta, die koning van Persië, het Ezra, die seun van SeráJaH, die seun van AzarJaH, die seun van GielkiJaH,	",
"	2 die seun van Sallum, die seun van Sadok, die seun van Ahítub,	",
"	3 die seun van AmarJaH, die seun van AzarJaH, die seun van Mérajot,	",
"	4 die seun van ZeragJaH, die seun van Ussi, die seun van Bukki,	",
"	5 die seun van Abisúa, die seun van Pínehas, die seun van El-Azar, die seun van Aäron, die hoëpriester, [1 Ezra 8:1-2]	",
"	6 het hierdie Ezra opgetrek uit Babel; en hy was ’n skrifgeleerde, vaardig in die Wet van Moshè wat JaHWeH, die Elohey van JisraEl, gegee het; en die koning het, omdat die hand van JaHWeH sy Elohey oor hom was, al sy begeertes ingewillig. [1 Ezra 8:3]	",
"	7 Ook van die kinders van JisraEl en van die priesters en die Leviete en die sangers en die poortwagters en die tempeldienaars het na Jerusalem opgetrek in die sewende jaar van koning Artasásta.	",
"	8 En hy het in Jerusalem gekom in die vyfde maand; dit was die sewende jaar van die koning. [1 Ezra 8:5]	",
"	9 Want op die eerste vanaf die eerste maand het hy die optog uit Babel gereël, en op die eerste vanaf die vyfde maand het hy in Jerusalem aangekom, omdat die suiwer Hand van sy Elohey oor hom was. [1 Ezra 8:6-7]	",
"	10 Want Ezra het sy hart daarop gerig om die Wet van JaHWeH te ondersoek en te betrag, en om JisraEl die Insettinge en Regsprake te leer. [1 Ezra 8:8]	",
"	11 En dit is die afskrif van die brief wat koning Artasásta gegee het aan Ezra, die priester-skrifgeleerde, wat skrifgeleerd was in die woorde van die Gebooie en Insettinge van JaHWeH oor JisraEl: [1 Ezra 8:9]	",
"	12 Artasásta, die koning van die konings, aan die priester Ezra, skrifgeleerde in die Wet van die Elohey van die Hemele, volkome [Vrede]! En nou - [1 Ezra 8:10]	",
"	13 deur my is bevel gegee dat elkeen van die volk van JisraEl en van sy priesters en Leviete wat in my koninkryk gewillig is om na Jerusalem te trek, met jou mag saamtrek; [1 Ezra 8:11]	",
"	14 omdat jy vanweë die koning en sy sewe raadsmanne gestuur is om oor JeHûWdah en in Jerusalem ondersoek te doen volgens die Wet van jou Elohey wat in jou hand is, [1 Ezra 8:13]	",
"	15 en om die silwer en goud weg te bring wat die koning en sy raadsmanne vrywillig gee aan die Elohey van JisraEl wie se woning in Jerusalem is,	",
"	16 en al die silwer en goud wat jy sal vind in die hele provinsie Babel saam met die vrywillige gawes van die volk en die priesters wat vrywillig gee vir die Huis van hulle Eloah wat in Jerusalem is. [1 Ezra 8:14-15]	",
"	17 Daarom moet jy sorgvuldig met hierdie silwer koop bulle, ramme, lammers met die spysbydraes en drank wat daarby behoort, en dit op die altaar van die Huis van julle Eloah in Jerusalem naderbring. [1 Ezra 8:16]	",
"	18 En wat jy en jou broers goedvind om met die orige silwer en goud te doen, kan julle doen volgens die wil van julle Eloah. [1 Ezra 8:17]	",
"	19 Maar die voorwerpe wat aan jou gegee word vir die diens van die Huis van jou Elohey, moet jy aflewer voor die Elohey van Jerusalem. [1 Ezra 8:18]	",
"	20 En die ander benodigdhede vir die Huis van jou Elohey wat jy sal moet gee, mag jy gee uit die skathuis van die koning.	",
"	21 En deur my, koning Artasásta, is bevel gegee aan al die skatmeesters wat wes van die Eufraat is, dat alles wat Ezra, die priester, die skrifgeleerde in die Wet van die Elohey van die Hemele, van julle vra, sorgvuldig gedoen moet word,	",
"	22 tot honderd talente silwer en tot honderd kor koring en tot honderd bat wyn en tot honderd bat olie toe en sout sonder beperking.	",
"	23 Alles wat volgens die bevel van die Elohey van die Hemele is, moet stiptelik uitgevoer word vir die Huis van die Elohey van die Hemele; want waarom sou daar ’n Woede kom oor die koninkryk van die koning en sy seuns?	",
"	24 En ons maak julle bekend dat wat betref al die priesters en Leviete, sangers, poortwagters, tempeldienaars of dienaars van hierdie Huis van Eloah, niemand gemagtig is om hulle belasting, opbrengs of tol op te lê nie.	",
"	25 En jy, Ezra, volgens die Wysheid van jou Elohey wat jy besit, stel owerhede en regters aan om vir die hele volk wat wes van die Eufraat is, Reg te spreek, almal wat die Wette van jou Elohey ken; en wie dit nie ken nie, moet julle dit leer.	",
"	26 En elkeen wat die Wet van jou Elohey en die wet van die koning nie doen nie, teen hom moet geregtelik opgetree word, hetsy ter dood of tot verbanning of konfiskering van eiendom of gevangenisstraf.	",
"	27 Geloofd sy JaHWeH, die Elohey van ons vaders, wat so iets in die hart van die koning gegee het, om die Huis van JaHWeH wat in Jerusalem is, te versier;	",
"	28 en wat met my Medelye gehad het voor die koning en sy raadsmanne en voor al die magtige vorste van die koning. Toe het ek moed geskep, omdat die hand van JaHWeH my Elohey oor my was, en ek het die hoofde uit JisraEl versamel om saam met my op te trek.	",

]
},
{
book: 'Esra',
chapter: '8',
content: [
		
"	1 EN dit is hulle hoofde van die vaders, met hulle geslagregister, wat saam met my onder die regering van koning Artasásta uit Babel opgetrek het: [1 Ezra 8:31-32]	",
"	2 van die kinders van Pínehas: Gersom; van die kinders van Itamar: DaniEl; van die kinders van Dawid: Gattush,	",
"	3 van die kinders van ShekanJaH; van die kinders van Párhos: ZekarJaH, en saam met hom in die register opgeneem, aan manspersone, honderd-en-vyftig; [1 Ezra 8:33]	",
"	4 van die kinders van Pahat-Moab: ElJeHôWeynay, die seun van ZeragJaH, en saam met hom tweehonderd man; [1 Ezra 8:34]	",
"	5 van die kinders van [Sattu]: ShekanJaH, die seun van JahaziEl, en saam met hom driehonderd man; [1 Ezra 8:35]	",
"	6 en van die kinders van Adin: Ebed, die seun van JôWnathan, en saam met hom vyftig manspersone; [1 Ezra 8:36]	",
"	7 en van die kinders van Elam: JeshaJaH, die seun van AtálJaH, en saam met hom sewentig manspersone; [1 Ezra 8:37]	",
"	8 en van die kinders van ShafátJaH: ZebádJaH, die seun van MikaEl, en saam met hom tagtig manspersone;	",
"	9 van die kinders van JôWab: ObadJaH, die seun van JehiEl, en saam met hom tweehonderd-en-agttien manspersone; [1 Ezra 8:38]	",
"	10 en van die kinders van [Bani]: Sélomit, die seun van JôwsifJaH, en saam met hom honderd-en-sestig manspersone; [1 Ezra 8:39]	",
"	11 en van die kinders van Bébai: ZekarJaH, die seun van Bébai, en saam met hom agt-en-twintig manspersone; [1 Ezra 8:40]	",
"	12 en van die kinders van Asgad: JôWganan, die seun van Hakkátan, en saam met hom honderd-en-tien manspersone; [1 Ezra 8:41]	",
"	13 en van die kinders van Adoníkam wat later [gekom het], en dit was hulle name: EliFelet, JeiEl en ShemaJaH, en saam met hulle sestig manspersone; [1 Ezra 8:42]	",
"	14 en van die kinders van Bigwai: Utai en Sabbud, en saam met hom sewentig manspersone. [1 Ezra 8:42]	",
"	15 En ek het hulle versamel by die rivier wat na Ahawa loop, en ons het daar drie dae laer opgeslaan; en ek het op die volk en die priesters ag gegee, maar van die kinders van Levi daar nie aangetref nie. [1 Ezra 8:43-44]	",
"	16 Daarom het ek EliEzer, AriEl, ShemaJaH en El-Natan en Jarib en El-Natan en Natan en ZekarJaH en Mesúllam, die hoofde, en JôWjarib en El-Natan, die leraars, gestuur [1 Ezra 8:45]	",
"	17 en hulle bevel gegee aan Iddo, die hoof in die plek KasífJaH; en ek het die woorde in hulle mond gelê wat hulle met Iddo, [en] sy broers, die tempeldienaars in die plek KasífJaH, moes spreek, dat hulle vir ons dienaars vir die Huis van onse Elohey moes bring. [1 Ezra 8:47]	",
"	18 En hulle het vir ons, omdat die suiwer Hand van onse Elohey oor ons was, verstandige manne uit die kinders van Magli, die seun van Levi, die seun van JisraEl, gebring, naamlik SerébJaH met sy seuns en sy broers, agttien; [1 Ezra 8:48]	",
"	19 en GashabJaH, en saam met hom JeshaJaH, van die kinders van Merári, sy broers en hulle seuns, twintig; [1 Ezra 8:49]	",
"	20 en van die tempeldienaars wat Dawid en die owerstes vir die diens van die Leviete gegee het, tweehonderd-en-twintig tempel-dienaars wat almal met hulle name aangewys was. [1 Ezra 8:50]	",
"	21 Toe het ek daar ’n vastyd uitgeroep aan die rivier Ahawa, om ons te verootmoedig voor die Aangesig van onse Elohey ten einde van Hom ’n voorspoedige reis te vra vir ons en ons families en al ons goed. [1 Ezra 8:51]	",
"	22 Want ek was skaam om van die koning ’n leër en perderuiters te vra om ons te help teen vyande op die pad, omdat ons met die koning gespreek en gesê het: Die Hand van onse Elohey is ten goede oor almal wat Hom soek, maar Sy Krag en Sy Woede oor almal wat Hom verlaat. [1 Ezra 8:52-53]	",
"	23 So het ons dan gevas en onse Elohey dit gevra, en Hy het ons verhoor.	",
"	24 Toe het ek van die priesterowerstes twaalf afgesonder: SerébJaH, GashabJaH en tien van hulle broers saam met hulle.	",
"	25 En ek het vir hulle die silwer en die goud en die voorwerpe afgeweeg, die bydraes aan die Huis van onse Elohey wat die koning en sy raadsmanne en sy vorste en die hele JisraEl wat aanwesig was, aangebied het. [1 Ezra 8:55-56]	",
"	26 En ek het in hulle hand afgeweeg: seshonderd-en-vyftig talente silwer en silwervoorwerpe van honderd talente, honderd talente in goud,	",
"	27 en twintig goue drinkbekers van duisend darieke en twee mooi goudgeel voorwerpe van koper, kosbaar soos goud. [1 Ezra 8:57-58]	",
"	28 En ek het vir hulle gesê: Julle is Apartheid aan JaHWeH, en die implemente is Apartheid, en die silwer en die goud is vrywillige skenkings aan JaHWeH, die Elohey van julle vaders. [1 Ezra 8:59]	",
"	29 Waak daaroor en bewaar dit, totdat julle dit afweeg voor die owerstes van die priesters en die Leviete en die familie-owerstes van JisraEl in Jerusalem, in die vertrekke van die Huis van JaHWeH. [1 Ezra 8:60]	",
"	30 Toe het die priesters en die Leviete die gewig van die silwer en die goud en die voorwerpe ontvang om dit na Jerusalem, na die Huis van onse Elohey te bring. [1 Ezra 8:61]	",
"	31 Daarna het ons weggetrek van die rivier Ahawa af op die twaalfde vanaf die eerste maand, om na Jerusalem te gaan; en die Hand van onse Elohey was oor ons, sodat Hy ons gered het uit die handpalms van die vyand en die wat ons voorlê op die pad.	",
"	32 En ons het in Jerusalem aangekom en daar drie dae gebly. [1 Ezra 8:62-63]	",
"	33 En op die vierde dag is die silwer en die goud en die voorwerpe in die Huis van onse Elohey afgeweeg onder bewaring van die priester Méremot, die seun van UriJaH, en by hom was El-Azar, die seun van Pínehas, en by hulle JôWzabad, die seun van Jehshua, en NoadJaH, die seun van Bínnuï, die Leviete -	",
"	34 volgens getal en gewig van alles; en tegelykertyd is die hele gewig opgeskrywe. [1 Ezra 8:64-65]	",
"	35 Hulle wat uit die gevangenskap gekom het, die seuns van die ballingskap, het brandoffers nadergebring aan die Elohey van JisraEl: twaalf bulle vir die hele JisraEl, ses-en-negentig ramme, sewe-en-sewentig lammers, twaalf bokke vir die oortreding - dit alles as brandoffer aan JaHWeH.	",
"	36 En hulle het die bevelskrifte van die koning gegee aan die landvoogde van die koning en die goewerneurs wes van die Eufraat, en dié het die volk en die Huis van die Elohim ondersteun. [1 Ezra 8:66-68]	",
		

]
},
{
book: 'Esra',
chapter: '9',
content: [
		
"	1 EN toe dit klaar was, het die owerstes na my gekom en gesê: Die volk van JisraEl en die priesters en die Leviete het hulle nie afgeskei van die volke van die Aarde, wat hulle gruwels betref nie, naamlik van die Kanaäniete, Hetiete, Feresiete, Jebusiete, Ammoniete, Moabiete, Egiptenaars en Amoriete.	",
"	2 Want hulle het van húlle dogters vir hulleself en vir hul seuns geneem, sodat die saad van die Apartheid hom met die volke van die Aarde vermeng het; en die owerstes en die leiers het in hierdie ontrou eerste die hand gehad.	",
"	3 En toe ek dit hoor, het ek my kleed en my mantel geskeur en van die hare van my hoof en my baard uitgepluk en verslae neergesit.	",
"	4 En by my het byeengekom almal wat gebeef het vir die Woorde van die Elohey van JisraEl, oor die ontrou van die ballinge; maar ek het verslae bly sit tot die skemerspysbydrae toe.	",
"	5 Maar op die tyd van die skemerspysbydrae het ek opgestaan uit my verootmoediging; en terwyl ek my kleed en my mantel skeur, het ek op my knieë my gebuig en my handpalms uitgestrek na JaHWeH my Elohey	",
"	6 en gesê: My Elohey, ek voel te beskaamd en verleë om my aangesig tot U, my Elohey, op te hef, want ons ongeregtigheid het oor ons hoof gegroei, en ons skuld is hemelhoog.	",
"	7 Van die dae van ons vaders af tot vandag toe is ons in ’n groot skuld, en oor ons ongeregtigheid is ons self, asook konings en ons priesters oorgegee in die hand van die konings van die Aarde, aan die swaard, aan gevangenskap en aan plundering en beskaming van die aangesig soos dit vandag is.	",
"	8 En nou was daar vir ’n klein oomblik Barmhartigheid van die kant van JaHWeH onse Elohey, om ‘n oorblyfsel vir ons te laat oorbly en ons ’n pen te gee in die plek van Sy Apartheid, sodat onse Elohey ons oë verhelder het en ons ’n bietjie lewensbehoud geskenk het in ons slawerny.	",
"	9 Want slawe is ons; in ons slawerny egter het ons Elohey ons nie verlaat nie, maar Hy het Medelye met ons gehad voor die konings van Persië, sodat hulle ons lewensbehoud geskenk het om die Huis van ons Elohey weer op te rig en sy puinhope te herstel en ons ’n muur te gee in JeHûWdah en Jerusalem.	",
"	10 En wat sal ons nou ná hierdie dinge sê, onse Elohey? Want ons het U Gebooie verlaat	",
"	11 wat U deur U knegte, die profete, beveel het deur te sê: Die Aarde waar julle inkom om haar in besit te neem, is ’n besoedelde Aarde vanweë die onsuiwerheid van die volke van die Aarde, deur hulle gruwels waarmee hulle haar van die een end tot die ander vervul het deur hulle vuilheid.	",
"	12 Gee dan nou julle dogters nie aan hulle seuns en neem hulle dogters nie vir julle seuns nie, en soek tot in ewigheid nie hulle vrede en voorspoed nie, sodat julle kan sterk word en die suiwere van die Aarde geniet en haar aan julle kinders as besitting kan gee tot in ewigheid.	",
"	13 En ná alles wat oor ons gekom het vanweë ons besoedelde dade en ons groot skuld - want U, onse Elohey, het ons minder toegereken as wat ons ongeregtigheid verdien het, en aan ons nog ontkoming gegee het-	",
"	14 sal ons weer U Gebooie verbreek en ons verswaer met hierdie gruwelike volke? Sal U nie op ons vertoorn wees, totdat ons vernietig is, sodat daar geen oorblyfsel of vrygeraakte meer is nie? [Exodus 20:14]	",
"	15 JaHWeH, Elohey van JisraEl, U is regverdig; want ons het as vrygeraaktes oorgebly soos dit vandag is. Hier is ons in ons skuld voor U Aangesig, want niemand kan om sulke dinge voor U Aangesig bestaan nie.	",

]
},
{
book: 'Esra',
chapter: '10',
content: [
		
"	1 EN terwyl Ezra bid en hy wenende neerval en belydenis doen voor die Huis van die Elohim, kom daar uit JisraEl ’n baie groot vergadering van manne en vroue en kinders by hom bymekaar; want die volk het geween met ’n groot geween.	",
"	2 Toe het ShekanJaH, die seun van JehiEl, van die seuns van Elam, begin spreek en aan Ezra gesê: Ons het ontrou gehandel teen onse Elohey, dat ons volksvreemde vroue uit die volke van die Aarde getrou het; maar tog is daar nog hoop vir JisraEl in hierdie saak.	",
"	3 Laat ons dan nou ’n Verbond met onse Elohey sluit om al die vroue en wat uit hulle gebore is, weg te stuur volgens die raad van my meester en van die wat beef vir die Gebod van onse Elohey, en laat volgens die Wet gehandel word.	",
"	4 Staan op, want die saak rus op u, en ons staan by u; wees sterk en handel!	",
"	5 Toe het Ezra opgestaan en hy het die owerstes van die priesters, die Leviete en die hele JisraEl laat sweer om volgens hierdie woord te handel; en hulle het gesweer.	",
"	6 En Ezra het hom opgerig van voor die Huis van die Elohim en weggegaan na die kamer van JeHôWganan, die seun van El-Jashib. En hy het daar gekom; geen brood het hy geëet en geen water gedrink nie, want hy het rou bedrywe oor die ontrou van die ballinge.	",
"	7 Toe het hulle ’n oproep deur JeHûWdah en Jerusalem laat gaan aan al die ballinge om in Jerusalem saam te kom.	",
"	8 En elkeen wat nie binne drie dae inkom nie, dié se hele besitting sou volgens besluit van die owerstes en die oudstes deur die banvloek getref word, en hy self uit die vergadering van die ballinge uitgesluit word.	",
"	9 Daarop het al die manne van JeHûWdah en Benjamin binne drie dae in Jerusalem saamgekom; dit was die negende maand, op die twintigste vanaf die maand; en die hele volk het op die plein van die Huis van die Elohim gesit en bewe vanweë die saak self en vanweë die reënbuie.	",
"	10 En die priester Ezra het opgestaan en vir hulle gesê: Julle was ontrou en het volksvreemde vroue getrou om die skuld van JisraEl te vermeerder.	",
"	11 Gee dan nou aan JaHWeH, die Elohey van julle vaders, die danksegging en doen wat Hom vreugde verskaf en skei julle af van die volke van die Aarde en van die volksvreemde vroue.	",
"	12 Toe antwoord die hele vergadering en sê hardop: Só, volgens u woorde, is ons verplig om te handel;	",
"	13 maar die mense is baie, en dit is die reëntyd - dit is onmoontlik om buite te staan; en dit is nie ’n werk van een dag en nie van twee nie, want ons het in hierdie saak swaar oortree.	",
"	14 Laat tog ons owerstes vir die hele vergadering optree, dan kan almal in ons stede wat volksvreemde vroue getrou het, op vasgestelde tye kom, en die oudstes en die regters van elkeen se stad saam met hulle, om die brandende Woede van onse Elohey, wat hierdie saak betref, van ons af te wend.	",
"	15 Net JôWnathan, die seun van AsaEl, en JakséJaH, die seun van Tikwa, het hierteen opgetree, en Mesúllam en die Leviet Sábbetai het hulle gesteun.	",
"	16 Maar die seuns van die ballingskap het so gedoen; en afgesonder is: Ezra, die priester, [saam met] manne, hoofde van die vaders volgens die huis van hul vaders, en hulle is almal by hul naam [genoem]; en hulle het op die eerste dag vanaf die tiende maand sitting gehou om die saak te ondersoek,	",
"	17 en met al die manne wat volksvreemde vroue getrou het, was hulle gereed op die eerste dag vanaf die eerste maand.	",
"	18 En van die seuns van die priesters wat volksvreemde vroue getrou het, was daar van die seuns van Jehshua, die seun van JôWtsadak, en sy broers: MaàseiJâH en EliEzer en Jarib en GhedalJaH.	",
"	19 Maar hulle het hulle hand daarop gegee dat hulle hul vroue sou wegstuur en dat hulle ’n ram skuldig sou wees vir hulle skuld.	",
"	20 En van die seuns van Immer: Hanáni en ZebádJaH;	",
"	21 en van die seuns van Harim: MaàseiJâH en EliJaH en ShemaJaH en JehiEl en UzziJaH;	",
"	22 en van die seuns van Pasgur: ElJôWeynay, MaàseiJâH, JismaEl, NethanEl, JôWzabad en El-Asah.	",
"	23 En van die Leviete: JôWzabad en Símeï en KeláJaH (dit is Kelíta), PetagJaH, JeHûWdah en EliEzer.	",
"	24 En van die sangers: El-Jashib; en van die poortwagters: Sallum en Telem en Uri.	",
"	25 En uit JisraEl, van die seuns van Párhos: RamJaH en JizziJaH en MalkiJaH en Míjamin en El-Azar en MalkiJaH en BenáJaH;	",
"	26 en van die seuns van Elam: MattánJaH, ZekarJaH en JehiEl en Abdi en Jéremot en EliJaH;	",
"	27 en van die seuns van Sattu: ElJôWenay, El-Jashib, MattánJaH en Jéremot en Sabad en Asísa;	",
"	28 en van die seuns van Bébai: JeHôWganan, GanánJaH, Sabbai en Atlai;	",
"	29 en van die seuns van Bani: Mesúllam, Mallug en AdáJaH, Jasub en Seal, Jéremot;	",
"	30 en van die seuns van Pahat-Moab: Adna en Kelal, BenáJaH, MaàseiJâH, MattánJaH, BesalEl en Bínnuï en Manasse;	",
"	31 en van die seuns van Harim: EliEzer, JishiJaH, MalkiJaH, ShemaJaH, Símeon,	",
"	32 Benjamin, Mallug, SemarJaH;	",
"	33 van die seuns van Hasum: Mátnai, Mattátta, Sabad, EliFelet, Jerémai, Manasse, Símeï;	",
"	34 van die seuns van Bani: Máädai, Amram en UwEl,	",
"	35 BenáJaH, BedeJaH, Kelúhu,	",
"	36 WanJaH, Méremot, El-Jashib,	",
"	37 MattánJaH, Mátnai en Jáäsai	",
"	38 en Bani en Bínnuï, Símeï	",
"	39 en ShelemJaH en Natan en AdáJaH,	",
"	40 Magnádbai, Sásai, Sárai,	",
"	41 AzarEl en ShelemJaHûW, SemarJaH,	",
"	42 Sallum, AmarJaH, JôWsef;	",
"	43 van die seuns van Nebo: JeiEl, MattithJaH, Sabad, Sebína, Jáddai en JôWEl, BenáJaH.	",
"	44 Hulle almal het volksvreemde vroue getrou, en daaronder was vroue wat kinders voortgebring het.	",

]
}

];
