const esterChapters = [

{
book: 'Ester',
chapter: '1',
content: [
		
"	1 EN in die dae van Ahasvéros - dit is die Ahasvéros wat geregeer het van Indië af tot by Kuwsh, honderd-sewe-en-twintig provinsies -	",
"	2 in dié dae toe koning Ahasvéros op sy koninklike troon in die vesting Susan gesit het,	",
"	3 in die derde jaar van sy regering, het hy ’n maaltyd berei vir al sy vorste en sy dienaars; die leërmag van Persië en Medië, die vername manne en die vorste van die provinsies was voor hom;	",
"	4 waarby hy die rykdom van sy koninklike glorie en die skitterende prag van sy grootheid baie dae, honderd-en-tagtig dae lank, vertoon het.	",
"	5 En toe dié dae verby was, het die koning vir al die mense wat in die vesting Susan aanwesig was, van die grootste tot die kleinste, ’n maaltyd berei, sewe dae lank, op die voorplein van die tuin van die koninklike paleis.	",
"	6 Linne-, katoen- en pers stowwe was met linne- en purperrooi bande vasgemaak aan silwerringe en marmerpilare! Goue en silwerrusbanke op ’n plaveisel van malaehiet en van witmarmer en perlemoensteen en gevlekte marmer!	",
"	7 Daarby het hulle laat drink uit goue bekers, en die een beker was verskillend van die ander beker, en daar was koninklike wyn in oorvloed, eg koninklik!	",
"	8 En hulle het gedrink volgens voorskrif: niemand het gedwing nie; want so het die koning bevel gegee aan al die hoë beamptes van sy paleis, dat hulle na elkeen se sin moes handel.	",
"	9 Ook het die koningin Vasti ’n vrouemaaltyd aangerig in die koninklike paleis van koning Ahasvéros.	",
"	10 Op die sewende dag, toe die hart van die koning vrolik was van die wyn, het hy aan Mehúman, Bista, Harbóna, Bigta en Abágta, Setar en Karkas, die sewe hofdienaars wat voor koning Ahasvéros gedien het, gesê	",
"	11 dat hulle koningin Vasti met die koninklike kroon op voor die koning moet bring om haar skoonheid aan die volke en die vorste te toon, want sy was mooi van aansien.	",
"	12 Maar koningin Vasti het geweier om te kom op die bevel van die koning deur middel van die hofdienaars aan haar oorgebring. Toe het die koning baie kwaad geword, en sy woede het in hom ontvlam.	",
"	13 En die koning het aan die wyse manne, die kenners van die tye, gesê - want só word die sake van die koning aan al die kenners van wet en reg voorgelê;	",
"	14 en die naaste aan hom was: Karséna, Setar, Admáta, Tarsis, Meres, Marséna, Memúgan, die sewe vorste van die Perse en Meders wat die aangesig van die koning gesien het, wat vooraan gesit het in die koninkryk -	",
"	15 wat moet volgens wet gedoen word met koningin Vasti, omdat sy die bevel van koning Ahasvéros, deur middel van sy hofdienaars, nie opgevolg het nie?	",
"	16 Toe sê Memúgan voor die koning en die vorste: Nie alleen teen die koning het koningin Vasti oortree nie, maar ook teen al die vorste en al die volke wat in al die provinsies van koning Ahasveros is.	",
"	17 Want die geval van die koningin sal by al die vroue bekend word, sodat dit hulle manne in hul oë veragtelik sal maak as daar gesê word: Koning Ahasvéros het bevel gegee om koningin Vasti voor hom te bring, maar sy het nie gekom nie.	",
"	18 Dieselfde dag nog sal die vorstinne van die Perse en Meders, as hulle die geval van die koningin hoor, dit aan al die vorste van die koning vertel; en dan sal dit genoeg veragting en gramskap afgee!	",
"	19 As die koning dit goedvind, laat daar ’n koninklike woord van hom uitgaan en beskrywe word in die wette van die Perse en Meders, sodat dit onherroeplik is, dat Vasti nie meer voor koning Ahasvéros mag kom nie; en laat die koning haar koninklike waardigheid aan haar vroulike naaste gee wat beter is as sy.	",
"	20 As dan van die bevelskrif van die koning gehoor word wat hy in sy hele koninkryk - want sy is groot - uitvaardig, sal al die vroue aan hulle manne eer bewys, van die grootste tot die kleinste.	",
"	21 En die woord was goed in die oë van die koning en van die vorste, en die koning het gehandel volgens die raad van Memúgan.	",
"	22 En hy het briewe gestuur aan al die provinsies van die koning, aan elke provinsie volgens haar eie skrif en aan elke volk volgens sy eie taal, dat elke man in sy huis baas moet wees en sy volkstaal praat.	",
	
]
},
{
book: 'Ester',
chapter: '2',
content: [
		
"	1 TOE ná die dinge die woede van koning Ahasvéros bedaar het, het hy aan Vasti gedink en aan wat sy gedoen het en wat oor haar besluit is.	",
"	2 Toe sê die jongmanne van die koning wat hom dien: Laat hulle vir die koning maagde soek wat mooi van aansien is;	",
"	3 en laat die koning beamptes aanstel in al die provinsies van sy koninkryk, dat hulle al die maagde wat mooi van aansien is, bymekaar laat kom in die vesting Susan, in die vrouehuis, onder toesig van Hege, die hofdienaar van die koning, die bewaker van die vroue; en laat hulle skoonheidsmiddele aan hulle gee.	",
"	4 En die jongmeisie wat die koning geval, moet in die plek van Vasti koningin word. Hierdie woord dan was goed in die oë van die koning, en hy het so gedoen.	",
"	5 Daar was ’n man van JeHûWdah in die vesting Susan met die naam van Mórdegai, die seun van Jaïr, die seun van Símeï, die seun van Kis, ’n Benjaminiet,	",
"	6 wat uit Jerusalem weggevoer was onder die ballinge wat in ballingskap moes gaan saam met JegonJaH, die koning van JeHûWdah, wat Nebukadnésar, die koning van Babel, weggevoer het.	",
"	7 En hy was die opvoeder van Hadássa, sy is Ester, die dogter van sy oom, want sy het geen vader of moeder gehad nie; en die jongmeisie was skoon van gestalte en mooi van aansien, en by die dood van haar vader en haar moeder het Mórdegai haar as sy dogter aangeneem.	",
"	8 En toe die bevel van die koning en sy wet bekend gemaak is, en baie meisies in die vesting Susan onder toesig van Hegai byeengebring is, het hulle Ester ook saamgeneem na die paleis van die koning, onder toesig van Hegai, die bewaker van die vroue.	",
"	9 En die meisie het hom geval en guns by hom gevind; daarom het hy gou gemaak om haar die nodige skoonheidsmiddele en die regte ete te gee en haar die sewe uitgesoekte meisies uit die paleis van die koning te verskaf; en hy het haar met haar meisies verplaas na die beste gedeelte van die vrouehuis.	",
"	10 Ester het haar volk en haar afkoms nie te kenne gegee nie, omdat Mórdegai haar beveel het om dit nie te vertel nie.	",
"	11 En Mórdegai het dag vir dag voor die voorhof van die vrouehuis gewandel om te verneem na die welstand van Ester en wat met haar sou gebeur.	",
"	12 En as die beurt van elke meisie aankom om na koning Ahasvéros in te gaan, nadat twaalf maande lank met haar volgens die wet vir die vroue gehandel is - want so lank het die dae van hulle voorbereiding geduur: ses maande lank met mirre-olie en ses maande met balsem en ander skoonheidsmiddele van die vroue -	",
"	13 as die meisie dan so na die koning ingaan, word alles wat sy sê, aan haar gegee, dat dit saam met haar uit die vrouehuis na die koninklike paleis kan gaan.	",
"	14 As sy in die aand ingaan en in die môre terugkom na die tweede vrouehuis onder toesig van Saäsgas, die hofdienaar van die koning wat die byvroue bewaak, dan mag sy nie weer by die koning ingaan nie, behalwe as die koning behae in haar vind en sy by die naam geroep word.	",
"	15 Toe die beurt van Ester, die dogter van Abígail, die oom van Mórdegai, wat haar as sy dogter aangeneem het, kom om in te gaan na die koning, het sy niks verlang nie, behalwe wat Hegai, die hofdienaar van die koning wat die vroue bewaak, gesê het; en Ester het guns gevind in die oë van almal wat haar gesien het.	",
"	16 Ester is toe by koning Ahasvéros in sy koninklike paleis opgeneem in die tiende maand, dit is die maand Tebet, in die sewende jaar van sy regering.	",
"	17 En die koning het Ester liefgekry meer as al die vroue, en sy het guns en welwillendheid voor hom gevind meer as al die maagde; en hy het die koninklike kroon op haar hoof gesit en haar koningin gemaak in die plek van Vasti.	",
"	18 En die koning het ’n groot maaltyd aangerig vir al sy vorste en sy dienaars, die maaltyd van Ester, en hy het ’n vrye dag bepaal vir die provinsies en geskenke gegee, eg koninklik!	",
"	19 En toe die maagde vir die tweede keer versamel is, terwyl Mórdegai in die poort van die koning sit -	",
"	20 Ester het haar afkoms en haar volk nie te kenne gegee nie, soos Mórdegai haar beveel het; en Ester het die bevel van Mórdegai opgevolg soos toe sy by hom opgevoed is -	",
		
		
"	20a IN die tweede jaar van die regering van die beroemde Ahasvéros, op die eerste dag van die maand Nisan(Abib), het Mórdegai, die seun van Jaïr, die seun van Simeï die seun van Kis ‘n Benjaminiet, ‘n droom gesien.	",
"	20b Hy was ‘n man van JeHûWdah wat in die stad Susan gewoon het; hy was hoog in aansien en een van die belangrikste manne in die koninklike paleis.	",
"	20c Hy het tot daardie ballinge behoort wat Nebukadnésar, die koning van Babel, saam met JegónJaH, die koning van JeHûWdah, uit Jerusalem weggevoer het.	",
"	20d En dit was sy droom: Daar het ‘n geroep en ‘n geraas ontstaan, en donderslae en aardbewinge, en ‘n groot verwarring op die Aarde.	",
"	20d1 En kyk, twee groot Drake het teenoor mekaar gestaan, en hulle was gereed om te veg.	",
"	20e En toe hulle skreeu, het al die nasies hulle voorberei vir die stryd teen die volk van die regverdiges.	",
"	20f Dit was ‘n dag van duisternis en gevaar, van verdrukking en benoudheid; en ‘n geweldige Vrees het oor die Aarde gekom.	",
"	20g Die volk van die regverdiges was ontsteld, want hulle het groot besoedeling vir hulleself verwag en hulle het hulle voorberei om te sterwe.	",
"	20h Hulle het na Elohim geroep. En terwyl hulle roep, het ‘n klein Fontein vermeerder tot ‘n baie groot rivier en voortgevloei soos ‘n magtige stroom. [Sirah 24:30-31]	",
"	20i Lig en die son het gekom; en die wat verdruk is, het hulle verhef en die hoogmoediges verslind.	",
"	20j Toe Mórdegai hierdie dinge gesien het, het hy opgestaan van sy bed, en hy het gepeins wat Elohim voornemens was om te doen. En hy het die droomgesig vasgehou in sy gees, omdat hy begeer het om die sin daarvan te verstaan.	",
"	20k In daardie tyd het hy in die poort van die koning gesit met Bigtan en Teres, twee hofdienaars van die koning, wat drumpelwagters van die paleis was.	",
"	20l En omdat hy hulle oorleg in die oog gehou het en noukeurig ag gegee het op hulle voorsorge, het hy ontdek dat hulle pogings gaan aanwend om die hand te slaan aan koning Ahasvéros; en hy het die koning daaroor verwittig.	",
"	20m Die koning het hulle twee ondervra, en toe hulle beken, het hy beveel om hulle ter dood te bring.	",
"	20n Maar die koning het die gebeurtenisse ook in die kroniekboeke beskrywe, terwyl ook Mórdegai dit opgeskryf het tot gedagtenis.	",
"	20o Ook het die koning hom opdrag gegee om in die koninklike hof te woon, en hy het hom vir die aanbring met geskenke beloon.	",
"	21 In dié dae dan, terwyl Mórdegai in die poort van die koning sit, het Bigtan en Teres, twee hofdienaars van die koning, drumpelwagters, kwaad geword en getrag om die hand aan koning Ahasvéros te slaan.	",
"	22 Maar Mórdegai het dit te wete gekom en dit aan koningin Ester meegedeel; en Ester het dit uit naam van Mórdegai aan die koning gesê.	",
"	23 Toe die saak ondersoek en so bevind is, is hulle twee aan ’n galg opgehang; en dit is in die kroniekboeke voor die koning beskrywe.	",
		

]
},
{
book: 'Ester',
chapter: '3',
content: [
	
"	1 NÁ hierdie dinge het koning Ahasvéros Haman, die seun van Hammedáta, die Agagiet, groot gemaak en hom verhoog en sy setel hoër gestel as dié van al die vorste wat by hom was.	",
"	2 En al die dienaars van die koning wat in die poort van die koning was, het gebuig en voor Haman neergeval; want so het die koning aangaande hom bevel gegee; maar Mórdegai het nie gebuig of neergeval nie.	",
"	3 En die dienaars van die koning, in die poort van die koning, het aan Mórdegai gesê: Waarom oortree jy die gebod van die koning?	",
"	4 En toe hulle hom dit elke dag sê, en hy nie na hulle luister nie, het hulle dit aan Haman meegedeel om te sien of die handelwyse van Mórdegai sou standhou, want hy het hulle te kenne gegee dat hy ’n man van JeHûWdah was.	",
"	5 Toe Haman sien dat Mórdegai nie buig en voor hom nie neerval nie, was Haman met woede vervul.	",
"	6 Maar hy het dit vir hom te gering geag om die hand aan Mórdegai alleen te slaan; want hulle het hom die volk van Mórdegai te kenne gegee. Daarom het Haman daarna gesoek om al die manne van JeHûWdah wat in die hele koninkryk van Ahasvéros was, die volk van Mórdegai, te verdelg.	",
"	7 In die eerste maand, dit is die maand Nisan(Abib), in die twaalfde jaar van koning Ahasvéros, het hulle die Pur, dit is die lot, voor Haman gewerp vir elke dag en vir elke maand, twaalf in getal, dit is die maand Adar.	",
"	8 Toe sê Haman aan koning Ahasvéros: Daar is een volk wat verstrooid en afgesonderd is tussen die volke in al die provinsies van u koninkryk, en hulle Wette is anders as dié van enige volk; ook hou hulle die wette van die koning nie, sodat dit die koning nie pas om hulle te laat begaan nie.	",
"	9 As die koning dit goedvind, laat daar dan geskrywe word om hulle te verdelg, en ek sal tienduisend talente silwer afweeg in die hande van die beamptes om dit by die skatte van die koning te voeg.	",
"	10 Toe trek die koning sy seëlring van sy hand af en gee dit aan Haman, die seun van Hammedáta, die Agagiet, die teëstander van die manne van JeHûWdah.	",
"	11 En die koning het aan Haman gesê: Die silwer word jou geskenk; ook die volk, om daarmee te doen soos goed is in jou oë.	",
"	12 Toe is die skrywers van die koning geroep in die eerste maand, op die dertiende dag daarvan, en daar is geskrywe net soos Haman beveel het aan die landvoogde van die koning en aan die goewerneurs wat oor elke provinsie was, en aan die vorste van elke volk, aan elke provinsie volgens haar skrif en aan elke volk in sy taal; in die naam van koning Ahasvéros is dit geskrywe en verseël met die seëlring van die koning.	",
"	Die teks van die bevelskrif teen die manne van JeHûWdah.	",
"	12a Ahasvéros, die grootste koning, aan die landvoogde van die honderd sewe en twintig provinsies vanaf Indië tot Etiopië, en aan die ondergeskikte bestuurders, groete!	",
"	12b Ofskoon ek oor ‘n groot menigte nasies geheers het en die hele wêreld aan my heerskappy onderwerp het, was dit nooit my bedoeling om die grootheid van my mag te misbruik nie; maar wel om my onderdane met goedertierenheid en welwillendheid te regeer, sodat hulle rustig en vry van verskrikking sou lewe en die vrede sou geniet wat enige sterfling begeer.	",
"	12c Ek het my raadgewers gevra hoe hierdie doel verwesenlik kan word. Toe het een, wat die ander deur wysheid en trou oortref en wat die eerste is na die koning en wie se naam Haman is,	",
"	12d aan my meegedeel dat ‘n sekere volk, wat oor die hele grondgebied versprei is, volgens vreemde Wette leef en dat hulle ingaan teen die gewoontes van al die nasies. Hulle minag die bevele van die koning en verbreek die eendrag onder al die nasies deur hulle vyandige gesindheid.	",
"	12e Nadat ons hierdie dinge verneem het en ons sien dat alleen hierdie volk wat teen die hele mensdom in opstand gekom het, volgens slegte wette leef en ons verordeninge dwarsboom en daardeur die vrede en eensgesindheid van al ons onderhorige provinsies skend,	",
"	12f het ons beveel: al diegene wat aangewys word deur Haman, wat aan die hoof staan van al die provinsies en die eerste na die koning is en deur ons soos ‘n vader geëer word, saam met hulle vroue en kinders moet uitgeroei word deur hulle vyande op die veertiende dag van die twaalfde maand, dit is die maand Adar van hierdie jaar; en niemand mag hom oor hulle ontferm nie,	",
"	12g Op hierdie wyse sal die misdadige mense op een dag na die Doderyk/Sheol afdaal en aan ons koninkryk die vrede teruggee wat hulle verbreek het.	",
"	13 En briewe is gestuur met die hardlopers na al die provinsies van die koning om al die manne van JeHûWdah te verdelg, dood te maak en uit te roei, die seun sowel as die grysaard, die kindertjies en die vroue, op een dag, op die dertiende van die twaalfde maand, dit is die maand Adar, en om hulle besittings as buit te plunder.	",
"	14 ’n Afskrif van die bevelskrif moes as wet in elke provinsie uitgevaardig en openbaar gemaak word aan al die volke, om gereed te wees teen daardie dag.	",
"	15 Die hardlopers het haastig op bevel van die koning uitgegaan, en die wet is in die vesting Susan uitgevaardig terwyl die koning en Haman sit en drink; maar die stad Susan was in verwarring.	",

]
},
{
book: 'Ester',
chapter: '4',
content: [
		
"	1 TOE Mórdegai verneem alles wat gebeur het, het Mórdegai sy klere geskeur en ’n roukleed aangetrek, en daar was as op sy hoof; en hy het uitgegaan dwarsdeur die stad en hardop en bitter geskreeu.	",
		
		
"	1a Mórdegai het tot JaHWeH gebid en aan al Sy werke gedink.	",
"	1b En hy het gesê: my Meester JaHWeH Almagtige Koning, omdat alles aan U mag onderwerp is en daar niemand is wat U Wil kan weerstaan nie, wanneer U wil besluit om JisraEl te red.	",
"	1c U het die Hemele en die Aarde gemaak en alles wat onder die Hemele is.	",
"	1d U is die Elohey van alles, en daar is niemand wat my Meester kan weerstaan nie.	",
"	1e U ken alles, en U weet dat ek nie uit hoogmoed of minagting of enige eersug gehandel het nie, toe ek weier om neer te val voor daardie verwaande Haman.	",
"	1f Want ter wille van die welsyn van JisraEl sou ek bereid wees om met gretigheid selfs sy voetspore te kus.	",
"	1g Maar ek het gevrees dat ek die eer van my Elohey sou oordra na ‘n mens, en dat ek nie Elohim nie, maar ‘n mens sou aanbid.	",
"	1h Nou dan my Meester JaHWeH, Elohey van Abraham, ontferm U oor U volk! Want ons vyande wil ons uitroei en U Erfdeel verdelg.	",
"	1i Verag U nie U Erfdeel wat U vir Uself uit Egipte gelei het nie!	",
"	1j Hoor my smeking, en wees U lot en meetsnoer barmhartig! Verander ons rou in Vreugde, sodat ons sal lewe en U Naam loof, JaHWeH! Sluit nie die monde toe wat U lofsing nie!	",
"	1k En ook die hele JisraEl het in dieselfde gees deur smeekbedes geroep na JaHWeH, omdat hulle deur ‘n gewisse dood gedreig is.	",
"	2 So het hy dan tot voor die poort van die koning gekom; want niemand het met ’n roukleed aan by die poort van die koning mag ingaan nie.	",
"	3 En in al die provinsies waar die bevel van die koning en sy wet ook al aankom, was daar groot rou onder die manne van JeHûWdah met vas en geween en rouklag; baie het sak en as onder hulle uitgesprei.	",
"	4 Toe die meisies van Ester en haar hofdienaars kom en haar dit meedeel, was die koningin baie beangs, en sy het klere gestuur om Mórdegai dit aan te trek en om sy roukleed van hom weg te neem; maar hy het dit nie aangeneem nie.	",
"	5 Hierop roep Ester Hatag, een van die hofdienaars van die koning, wat hy in haar diens gestel het, en beveel hom om na Mórdegai te gaan om te verneem wat dit beteken en waarom dit gebeur.	",
"	6 En Hatag het uitgegaan na Mórdegai na die stadsplein wat voor die poort van die koning gelê het.	",
"	7 Toe deel Mórdegai hom mee alles wat hom oorgekom het, en die juiste bedrag van die silwer wat Haman beloof het om in die skatte van die koning af te weeg as prys vir die manne van JeHûWdah om hulle uit te roei.	",
"	8 En hy het hom ’n afskrif gegee van die bevelskrif wat in Susan uitgevaardig was om hulle te verdelg, sodat hy dit aan Ester kon wys en haar die saak kon meedeel en haar kon opdra om na die koning te gaan om hom barmhartigheid te vra en by hom ’n voorspraak te wees vir haar volk.	",
"	9 Daarop het Hatag ingegaan en die woorde van Mórdegai aan Ester meegedeel.	",
"	10 Toe sê Ester vir Hatag, terwyl sy hom ’n opdrag gee aan Mórdegai:	",
"	11 Al die dienaars van die koning en die volk van die provinsies van die koning weet dat vir elke man of vrou wat na die koning in die binneste voorhof ingaan, sonder dat hy geroep is, een en dieselfde wet geld: hy moet gedood word; behalwe wanneer die koning sy goue septer na hom uitsteek, dat hy mag lewe; en ek is nou al dertig dae lank nie geroep om by die koning in te kom nie.	",
"	12 En hulle het die woorde van Ester aan Mórdegai meegedeel.	",
"	13 Daarop sê Mórdegai dat hulle Ester moes antwoord: Verbeel jou nie dat jou siel alleen uit al die manne van JeHûWdah in die huis van die koning sal vrykom nie.	",
"	14 Want as jy nou werklik swyg, sal daar van ’n ander kant af verligting en redding vir die manne van JeHûWdah tot stand kom, maar jy en jou familie sal omkom, en wie weet of jy nie met die oog op ’n tyd soos hierdie tot die koninklike waardigheid geraak het nie?	",
		
		
"	14a EN hy [dit is ongetwyfeld Mórdegai] het haar gelas om na die koning te gaan, en om hom te smeek vir haar volk en haar deel van die Aarde.	",
"	14b Hy het gesê: dink aan die dae van jou geringheid, en hoe jy deur my hand gevoed is. Want Haman, wat eerste agter die koning kom, het dinge gepraat wat ons dood sal veroorsaak.	",
"	14c jy dan, roep na JaHWeH en spreek tot die koning vir ons, en verlos ons van die dood.	",
"	15 Toe sê Ester dat hulle Mórdegai moes antwoord:	",
"	16 Gaan heen, versamel al die manne van JeHûWdah wat in Susan te vinde is, en vas julle om my ontwil; en julle moet nie eet en drink nie, drie dae lank, nag en dag; ek ook met my dienaresse sal ook so vas; so sal ek na die koning ingaan, wat nie volgens wet is nie, en as ek omkom, dan kom ek om.	",
"	17 En Mórdegai het heengegaan en gedoen net soos Ester hom opgedra het.	",
		
		
"	17a OOK koningin Ester het haar toevlug geneem tot JaHWeH, want sy het gebewe voor die dreigende gevaar.	",
"	17b Sy het haar koninklike kleed afgelê en klere aangetrek wat pas by trane en rou; en in plaas van verskeie salfolies het sy as en vuilgoed op haar hoof gesprei, en sy het haar liggaam onderwerp deur te vas. En die plekke waar sy vroeër vrolik gevoel het, was nou vol hare wat sy uitgetrek het.	",
"	17c En sy het JaHWeH die Elohey van JisraEl gesmeek en gesê: My Elohey, U alleen is ons Koning! Help my wat eensaam is, en vir wie daar geen ander helper is as U nie.	",
"	17d Die gevaar is in my hande.	",
"	17e Van my vader het ek gehoor dat U, JaHWeH, JisraEl uit al die ander nasies afgesonder het en ons vaders weer uit hulle voorgeslag, sodat U ‘n ewige Erfdeel sou besit. En U het aan hulle gedoen soos U gespreek het.	",
"	17f Ons het oortree voor U Aangesig. Daarom het U ons oorgelewer in die hande van ons vyande.	",
"	17g Want ons het hulle gode aanbid. JaHWeH, U is regverdig.	",
"	17h Maar nou is dit vir hulle nie genoeg om ons deur swaar diensbaarheid te verdruk nie, dog hulle skryf selfs die krag van hulle hande toe aan die mag van hulle gode.	",
"	17i So wil hulle U beloftes verydel en U Erfdeel uitroei en die monde toesluit wat U loof, en die Glansrykheid van U Apartheidsplek en altaar verdelg.	",
"	17j Dan kan hulle die monde van die nasies oopmaak en die mag van die idole loof, en hulle kan ‘n liggaamlike koning verhoog tot in ewigheid.	",
"	17k JaHWeH, lewer U Septer nie uit aan die wat nie is nie, sodat hulle nie sal lag oor ons ondergang nie. Maar keer hulle planne teen hulleself; en verdelg hom wat teen ons losgebreek het.	",
"	17l Wees gedagtig, JaHWeH, en toon U aan ons in die tyd van ons verdrukking! Gee my vertroue, JaHWeH, Koning van die Elohim en van al die heerskappye.	",
"	17m Lê gepaste woorde in my mond voor die aangesig van die leeu, en neig sy hart tot haat teen ons vyand, sodat die self uitgeroei word saam met sy medestanders.	",
"	17n Maar ons, red ons deur U Hand; en help my, wat geen ander hulp het as alleen U, JaHWeH, wat alles weet!	",
"	17o U weet dat ek die roem van wetteloses haat, en dat ek afkerig is van die bed van onbesnedenes en van elke vreemdeling.	",
"	17p U weet dat ek gedwing is maar dat ek afkerig is van daardie teken van my verhoging en eer wat ek op my hoof dra op die dae van openbare vertoon, en dat ek dit haat soos die doek van ‘n vrou; sodat ek dit op stil dae nie dra nie.	",
"	17q U weet dat ek van Haman se tafel nie geëet het nie, dat ek die maaltyd van die koning nie geniet nie, en dat ek van die wyn van die plengoffers nie gedrink het nie;	",
"	17r en dat U diensmaagd, vanaf die dag dat ek na hierdie plek geneem is tot vandag toe, in niks anders Vreugde gevind het nie as alleen in U JaHWeH, Elohey van Abraham!	",
"	17s JaHWeH, wat magtiger as al die mense is, hoor na die stem van die wat geen ander hoop het nie; en red U ons uit die hand van die wetteloses, en verlos U my van my vrees.	",
		

]
},
{
book: 'Ester',
chapter: '5',
content: [
		
"	1 OP die derde dag het sy die klere van haar voorbereiding afgelê en haar koninklik aangetrek.	",
"	1b En terwyl sy glans in koninklike prag, het sy JaHWeH aangeroep as haar Leier en Redder. Daarna het sy twee dienaresse geneem;	",
"	1c en op die een het sy geleun, asof sy deur vreugde en besondere fynheid nie by magte was om regop te gaan nie;	",
"	1d en die ander meisie het agter haar meesteres gekom om haar kleed op te hou, wat tot die Aarde afhang.	",
"	1e Self het sy agter die rooskleur op haar gesig en agter haar vriendelike en stralende oë die droefheid verberg van haar hart, wat saamgetrek het vanweë haar groot vrees.	",
"	1f Sy het agtereenvolgens deur al die deure gegaan en toe teenoor die koning bly staan, waar hy in sy koninklike kleed op sy troon sit, glansend deur goud en edelstene; hy was vreeswekkend om te sien.	",
"	1g Toe hy sy hoof ophef en sy vlammende oë die woede van sy hart verraai, het die koningin onwel geword; haar kleur het verbleek, en sy het haar hoof magteloos laat rus op haar dienares.	",
"	1h Maar Elohim het die koning se hart verteder. Hy het skielik vol sorg opgespring van sy troon en haar in sy arms ondersteun, totdat sy herstel het. En op ‘n vertroulike toon het hy gesê:	",
"	1i Wat is dit, Ester? Ek is jou broer; moenie bevrees wees nie!	",
"	1j jy sal nie sterwe nie. Hierdie wet is nie vir jou gemaak nie maar vir die algemeen.	",
"	1k Kom dus naderby, en raak aan die septer.	",
"	1l Maar toe sy nog swyg, het hy die goue staf geneem en op haar nek gelê. En hy het haar gekus en gesê: Hoekom praat jy nie met my nie?	",
"	1m En sy het geantwoord: Ek het u gesien, meester, soos ‘n engel van Elohim; en my hart was ontstel uit vrees vir u majesteit.	",
"	1n Want u is bewonderenswaardig in ‘n groot mate, heer, en u aangesig is vol bevalligheid.	",
"	1o Maar terwyl sy praat, het sy opnuut onwel geword en byna in onmag geval.	",
"	1p Toe het die koning ongerus geword, en al sy dienaars het haar getroos.	",
"	1 Op die derde dag het Ester haar koninklik aangetrek en gaan staan in die binneste voorhof van die paleis van die koning, teenoor die saal van die koning, terwyl die koning op sy koninklike troon sit in die koninklike saal, teenoor die ingang van die saal.	",
"	2 En net toe die koning koningin Ester in die voorhof sien staan, het sy barmhartigheid in sy oë gevind; en die koning het die goue septer wat in sy hand was, na Ester uitgesteek; en Ester het nader gekom en die punt van die septer aangeraak.	",
"	3 Toe sê die koning vir haar: Wat wil jy hê, koningin Ester, of wat is jou versoek? Al was dit ook die helfte van die koninkryk - dit sal jou gegee word.	",
"	4 Daarop antwoord Ester: As die koning dit goedvind, laat die koning dan vandag met Haman na die maaltyd kom wat ek vir hom berei het.	",
"	5 En die koning sê: Bring Haman gou, dat ons kan handel volgens die woord van Ester! En die koning en Haman het gegaan na die maaltyd wat Ester berei het.	",
"	6 En terwyl hulle wyn drink, sê die koning vir Ester: Wat is jou bede? - dit sal jou toegestaan word. En wat is jou versoek? Al was dit ook die helfte van die koninkryk - daaraan sal voldoen word.	",
"	7 Daarop antwoord Ester en sê: My bede en my versoek is:	",
"	8 As ek barmhartigheid gevind het in die oë van die koning, en as die koning dit goedvind om my bede toe te staan en aan my versoek te voldoen, laat die koning en Haman na die maaltyd kom wat ek vir hulle sal berei, dan sal ek môre na die wens van die koning handel.	",
"	9 En op dié dag het Haman bly en opgeruimd heengegaan; maar toe Haman Mórdegai in die poort van die koning sien en dat hy nie opstaan of vir hom bevrees is nie, was Haman met woede vervul teen Mórdegai.	",
		
		
"	9b MAAR Haman, die seun van Hammedáta, die Bugeër, wat in die hoogste aansien gestaan het by die koning, het besluit om Mórdegai en sy volk skade te berokken vanweë die twee hofdienaars van die koning, wat ter dood gebring is.	",
"	10 Maar Haman het hom bedwing; en toe hy by sy huis kom, laat hy sy vriende en sy vrou Seres haal;	",
"	11 en Haman vertel hulle van die glorie van sy rykdom en van die veelheid van sy seuns en van alles waarin die koning hom groot gemaak het en hoe hy hom verhef het bo die vorste en die dienaars van die koning.	",
"	12 Verder sê Haman: Selfs het koningin Ester niemand saam met die koning na die maaltyd laat kom wat sy aangerig het nie, as net vir my, en ook vir môre is ek deur haar genooi saam met die koning.	",
"	13 Maar dit alles baat my niks, solank as ek die man van JeHûWdah Mórdegai in die poort van die koning sien.	",
"	14 Toe sê sy vrou Seres en al sy vriende vir hom: Laat hulle ’n galg van vyftig voorarm hoog maak, en sê môre vroeg aan die koning dat hulle Mórdegai daaraan moet ophang; gaan dan vrolik saam met die koning na die maaltyd. Dié woord het Haman geval, en hy het die galg laat maak.	",

]
},
{
book: 'Ester',
chapter: '6',
content: [
		
"	1 IN dieselfde nag het die slaap van die koning gewyk, en hy het gesê dat hulle die gedenkskrif, die kronieke, moes bring. En toe dit die koning voorgelees word,	",
"	2 vind hulle daar beskrywe dat Mórdegai openbaar gemaak het dat Bigtána en Teres, twee hofdienaars van die koning, uit die drumpel-wagters, getrag het om die hand aan koning Ahasvéros te slaan.	",
"	3 Daarop sê die koning: Watter eer en verhoging het Mórdegai daarvoor te beurt geval? En die jongmanne van die koning, sy dienaars, het geantwoord: Met hom het niks gebeur nie.	",
"	4 Toe sê die koning: Wie is in die voorhof? - juis toe Haman in die buitenste voorhof van die koninklike paleis kom om aan die koning te sê dat hulle Mórdegai moes ophang aan die galg wat hy vir hom laat oprig het.	",
"	5 En die jongmanne van die koning antwoord hom: Daar staan Haman in die voorhof. Toe sê die koning: Laat hy inkom.	",
"	6 Nadat Haman ingekom het, vra die koning hom: Wat moet met die man gedoen word aan wie die koning eer wil bewys? Haman dink toe by homself: Aan wie sou die koning eer wil bewys meer as aan my?	",
"	7 Daarom het Haman vir die koning gesê: Die man aan wie die koning eer wil bewys -	",
"	8 laat hulle ’n koninklike kleed bring waarmee die koning bekleed was, en ’n perd waar die koning op gery het en op die kop waarvan ’n koninklike kroon gesit is;	",
"	9 en laat hulle die kleed en die perd afgee aan een van die vorste van die koning, van die vername manne, dat hulle dit die man aantrek aan wie die koning eer wil bewys; en hulle moet hom laat ry op die perd oor die stadsplein en voor hom uitroep: So word gedoen aan die man aan wie die koning eer wil bewys.	",
"	10 Toe sê die koning vir Haman: Neem gou die kleed en die perd soos jy gespreek het, en doen so aan Mórdegai, die man van JeHûWdah, wat in die poort van die koning sit; jy moet nie een woord onvervuld laat bly van alles wat jy gespreek het nie.	",
"	11 En Haman het die kleed geneem en die perd, en hy het Mórdegai aangetrek en hom laat ry oor die stadsplein en voor hom uitgeroep: So word gedoen aan die man aan wie die koning eer wil bewys.	",
"	12 Daarna het Mórdegai teruggegaan na die poort van die koning; maar Haman het hom gehaas na sy huis toe, treurig en met bedekte hoof.	",
"	13 En Haman het aan sy vrou Seres en al sy vriende vertel alles wat hom oorgekom het. Toe sê sy wyse manne en sy vrou Seres vir hom: As Mórdegai voor wie jy alreeds begin val het, uit die saad van JeHûWdah is, sal jy niks teen hom kan uitrig nie, maar heeltemal voor hom val.	",
"	14 Onderwyl hulle nog met hom spreek, kom die hofdienaars van die koning aan, en hulle het Haman gou na die maaltyd gebring wat Ester gereedgemaak het.	",

]
},
{
book: 'Ester',
chapter: '7',
content: [
		
"	1 TOE die koning en Haman inkom om saam met koningin Ester die feesmaal te hou,	",
"	2 sê die koning aan Ester ook op die tweede dag, terwyl hulle wyn drink: Wat is jou bede, koningin Ester? - dit sal jou toegestaan word. En wat is jou versoek? Al was dit die helfte van die koninkryk - daaraan sal voldoen word.	",
"	3 En koningin Ester antwoord en sê: As ek barmhartigheid in u oë gevind het, o koning, en as die koning dit goedvind, laat my siel my geskenk word op my bede en my volk op my versoek.	",
"	4 Want ons is verkoop, ek en my volk, om verdelg, gedood en uitgeroei te word. Was ons nog as slawe en slavinne verkoop, dan sou ek geswyg het, maar hierdie ramp sal onder die verliese van die koning sy weerga nie hê nie.	",
"	5 Toe spreek koning Ahasvéros en sê aan koningin Ester: Wie is hy, en waar is hy wie se hart hom ingegee het om so te maak?	",
"	6 En Ester sê: Die teëstander en vyand is hierdie slegte Haman! Toe skrik Haman voor die koning en die koningin.	",
"	7 En die koning het in sy woede van die wynmaaltyd opgestaan en na die tuin van die paleis gegaan, terwyl Haman daar bly staan om van koningin Ester die behoud van sy siel af te smeek; want hy het gesien dat die oordeel oor hom by die koning vas besluit was.	",
"	8 Toe die koning uit die tuin van die paleis in die saal van die wynmaaltyd terugkom, en Haman juis op die rusbank neergeval het waar Ester op sit, sê die koning: Wil hy die koningin ook nog geweld aandoen by my in die huis? Die woord was nouliks uit die mond van die koning of hulle het die gesig van Haman bedek.	",
"	9 Daarop sê Harbóna, een van die hofdienaars voor die koning: Daar staan reeds die galg wat Haman laat maak het vir Mórdegai wat ten voordele van die koning gespreek het, by die huis van Haman, vyftig voorarm hoog! Toe sê die koning: Hang hom daaraan op!	",
"	10 En hulle het Haman opgehang aan die galg wat hy vir Mórdegai opgerig het, en die woede van die koning het bedaar.	",

]
},
{
book: 'Ester',
chapter: '8',
content: [
		
"	1 OP dieselfde dag het koning Ahasveros aan koningin Ester die huis gegee van Haman, die teëstander van die man van JeHûWdah; en Mórdegai het voor die koning gekom, want Ester het vertel wat hy van haar was.	",
"	2 En die koning het sy seëlring uitgetrek wat hy van Haman afgeneem het, en dit aan Mórdegai gegee; en Ester het Mórdegai aangestel oor die huis van Haman. [Spreuke 8:15-16]	",
		
		
"	3 EN Ester het weer voor die koning gespreek en voor sy voete neergeval en geween en hom gesmeek om die boosheid van Haman, die Agagiet, en sy plan wat hy teen die manne van JeHûWdah beraam het, te verydel.	",
"	4 En die koning het die goue septer na Ester uitgesteek, en Ester het haar opgerig en voor die koning gaan staan	",
"	5 en gesê: As die koning dit goedvind en ek barmhartigheid voor hom gevind het en die saak reg is voor die koning en ek welgevallig is in sy oë, laat dan geskrywe word om die briewe met die plan van Haman, die seun van Hammedáta, die Agagiet, te herroep wat hy geskrywe het om die manne van JeHûWdah wat in al die provinsies van die koning is, uit te roei.	",
"	6 Want hoe sou ek kan aansien die boosheid wat my volk sal tref? En hoe sou ek kan aansien die ondergang van my geslag?	",
"	7 Toe sê koning Ahasvéros aan koningin Ester en aan die man van JeHûWdah Mórdegai: Kyk, die huis van Haman het ek aan Ester gegee, en hom het hulle aan die galg opgehang, omdat hy sy hand teen die manne van JeHûWdah uitgesteek het.	",
"	8 Skryf julle maar, wat die manne van JeHûWdah betref, soos julle dit goedvind uit naam van die koning, en verseël dit met die seëlring van die koning; want ’n geskrif, in naam van die koning geskrywe en verseël met die seëlring van die koning, kan nie herroep word nie.	",
"	9 Toe is in dieselfde tyd die skrywers van die koning geroep, in die derde maand, dit is die maand Siwan, op die drie-en-twintigste daarvan; en daar is geskrywe net soos Mórdegai beveel het, aan die manne van JeHûWdah en aan die landvoogde en die goewerneurs en die vorste van die provinsies wat van Indië af tot by Kuwsh lê, honderd-sewe-en-twintig provinsies, aan elke provinsie volgens haar skrif en aan elke volk in sy taal, en aan die manne van JeHûWdah volgens hulle skrif en in hulle taal -	",
"	10 hy het laat skrywe uit naam van koning Ahasvéros en dit verseël met die seëlring van die koning en briewe gestuur met rapportgangers te perd wat gery het op koninklike renperde uit die stoetery,	",
		
		
		
"	10a AHASVEROS, die groot koning, aan die landvoogde en vorste wat hom onderdanig is in die honderd sewe en twintig provinsies vanaf Indië tot Kuwsh, groete!	",
"	10b Baie persone misbruik die goedheid van vorste en die eerbewyse wat hulle ondervind, tot trotsheid.	",
"	10c Hulle probeer dan nie alleen om die onderdane van die konings te verdruk nie maar, omdat hulle teen die verleende eerbewyse nie opgewasse is nie, span hulle ook lokvalle vir diegene wat hulle geëer het.	",
"	10d Dit is vir hulle ook nie genoeg om alleen maar ondankbaar te wees vir die weldade en die regte te misken wat menslike goedheid jeens hulle kan laat geld nie, maar hulle meen ook nog dat hulle die straf kan ontloop van Elohim, wat alles sien.	",
"	10e Hulle word selfs tot ‘n dergelike dwaasheid vervoer, dat hulle probeer om deur bedrieglike liste ook diegene te ondermyn wat pligsgetrou hulle opgelegde take uitvoer en wat hulle in alle opsigte so gedra, dat hulle elkeen se lof werd is.	",
"	10f Intussen bedrieg hulle deur listige oorleg die argelose ore van die vorste, wat ander persone beoordeel ooreenkomstig hulle eie geaardheid.	",
"	10g Dergelike dinge blyk uit die ou kroniekboeke en ook uit die gebeurtenisse van elke dag: hoe die bedoelinge van die konings deur die boosaardige influisteringe van sekere persone bederf word.	",
"	10h Daarom moet toesig gehou word oor die vrede in al die provinsies.	",
"	10i Wanneer ons derhalwe ‘n gewysigde bevel gee, moet nie gemeen word dat dit uit die ligsinnigheid van ons hart voortkom nie, maar dat ons besluite neem ooreenkomstig die aard en noodwendigheid van die omstandighede en die eise van die algemene welsyn.	",
"	10j En omdat julle ons woorde duideliker kan verstaan: Haman, die seun van Hammedáta, na gees en afstamming ‘n Macedoniër sonder enige Persiese bloed, wat ons mildheid deur sy wreedheid tot skande gemaak het, is destyds as vreemdeling deur ons opgeneem.	",
"	10k Hy het selfs ‘n dergelike goedheid ondervind, dat hy ons vader genoem is en deur almal as eerste na die koning geëer is.	",
"	10l Maar hy het hom tot so ‘n mate van verwaandheid opgeblaas, dat hy pogings aangewend het om ons van die koningskap en die lewe te beroof.	",
"	10m Want met allerlei vreemde en ongehoorde middele het hy die dood gesoek van Mórdegai, aan wie se trou en goeie dienste ons lewe te danke is, en van die deelgenote van ons koningskap, Ester, saam met haar hele volk.	",
"	10n Hy was van plan om ons, nadat hulle gesterf het, in ons eensaamheid te behaag en die koninkryk van die Perse aan die Macedoniërs uit te lewer.	",
"	10o Ons het egter gevind dat die manne van JeHûWdah, wat deur die slegste van die sterflinge vir uitroeiing bestem is, beslis nie skuldig is nie; inteendeel, dat hulle volgens regmatige Wette leef;	",
"	10p en dat hulle kinders is van die hoogste en grootste en ewige Elohim, wat in Sy mildheid sowel aan ons vaders as aan ons die koningskap gegee het en haar bewaak tot vandag toe.	",
"	10q Daarom moet julle weet dat die briewe wat daardie man namens ons gestuur het, kragteloos is.	",
"	10r Vir hierdie misdaad hang hy en sy familie aan die galg wat hy self voor die poorte van hierdie stad Susan laat oprig het; en dit is nie ons nie maar Elohim, wat hom na verdienste vergeld.	",
"	10s Hierdie bevelskrif wat ons nou stuur, moet in al die stede aangeslaan word, sodat die manne van JeHûWdah sal vry wees om ooreenkomstig hulle eie Wette te lewe.	",
"	10t En julle moet hulle help, sodat hulle die wat gereed staan om hulle te vermoor, kan ter dood bring op die dertiende dag van die maand wat Adar genoem word	",
"	10u Want die Almagtige JaHWeH het hierdie dag van droefheid en rou vir hulle in Vreugde verander.	",
"	10v Daarom moet julle ook hierdie dag by die ander feesdae voeg en in alle vrolikheid vier; sodat sy ook in die toekoms bekend sal wees	",
"	10w dat hulle almal wat troue onderdane van die Perse is, werd is om vir hulle trou beloon te word; maar dat die wat die koninkryk probeer verraai, gedood word vir hierdie misdaad.	",
"	10x Elke provinsie en stad wat nie aan hierdie feesviering wil deelneem nie, sal te vuur en te swaard omkom en so volkome verdelg word, dat sy vir altyd ontoeganklik bly vir mense en diere as ‘n voorbeeld van minagting en ongehoorsaamheid.	",
"	11 dat die koning aan die manne van JeHûWdah wat in elke stad woon, toegestaan het om bymekaar te kom en hulle siel te verdedig, deur te verdelg en dood te maak en uit te roei elke gewapende mag van volk of provinsie wat hulle in benoudheid mag bring, saam met kindertjies en vroue, en hulle besittings as buit te plunder,	",
"	12 op een dag in al die provinsies van koning Ahasvéros, op die dertiende van die twaalfde maand, dit is die maand Adar.	",
"	13 ’n Afskrif van die bevelskrif moes as wet uitgevaardig word in elke provinsie, openbaar gemaak aan al die volke, sodat die manne van JeHûWdah op dié dag gereed moes wees om hulle op hul vyande te wreek.	",
"	14 Die rapportgangers wat op die koninklike renperde gery het, het op bevel van die koning haastig en gou weggegaan, en die wet is in die vesting Susan uitgevaardig.	",
"	15 En Mórdegai het van die koning weggegaan in ’n koninklike kleed van pers en wit, met ’n groot goue kroon op en ’n mantel van fyn linne en purperrooi stof, terwyl die stad Susan jubel en vrolik was.	",
"	16 Vir die manne van JeHûWdah was daar lig en vrolikheid en vreugde en eer;	",
"	17 en in al die provinsies en in al die stede waar die bevel van die koning en sy wet ook al aangekom het, was daar vrolikheid en vreugde by die manne van JeHûWdah, maaltyd en feesdag; en baie uit die volke van die Aarde het hulle by die manne van JeHûWdah geskaar, want die skrik vir die manne van JeHûWdah het op hulle geval.	",

]
},
{
book: 'Ester',
chapter: '9',
content: [
		
"	1 EN in die twaalfde maand, dit is die maand Adar, op die dertiende dag daarvan, toe die bevel van die koning en sy wet uitgevoer sou word, op die dag toe die vyande van die manne van JeHûWdah gehoop het om hulle te oorweldig - maar dit net omgekeerd was, sodat juis die manne van JeHûWdah hulle haters sou oorweldig -	",
"	2 het die manne van JeHûWdah saamgekom in hulle stede in al die provinsies van koning Ahasvéros om die hand te slaan aan die wat hulle boosheid gesoek het; en niemand het voor hulle standgehou nie, want die skrik vir hulle het op al die volke geval.	",
"	3 En al die vorste van die provinsies en die landvoogde en die goewerneurs en die beamptes van die koning het die manne van JeHûWdah ondersteun, want die skrik vir Mórdegai het op hulle geval.	",
"	3a Want die man van JeHûWdah Mórdegai was die tweede in rang onder koning Ahasvéros; en hy was groot by die manne van JeHûWdah en ’n liefling by die menigte van sy broers, omdat hy die voorspoed van sy volk gesoek en tot welsyn van al sy saad gespreek het.	",
"	4 Want Mórdegai was groot in die paleis van die koning, en sy gerug het deur al die provinsies gegaan, omdat die man Mórdegai al groter geword het.	",
"	5 En die manne van JeHûWdah het onder hulle vyande ’n slagting aangerig deur die swaard en deur doodslag en verdelging, en met hulle haters na hulle goedvinde gehandel.	",
"	6 En in die vesting Susan het die manne van JeHûWdah vyfhonderd man gedood en uitgeroei;	",
"	7 en Parsandáta en Dalfon en Aspáta,	",
"	8 en Poráta en Adálja en Adidáta,	",
"	9 en Parmásta en Arísai en Aridai en Waisáta,	",
"	10 die tien seuns van Haman, die seun van Hammedáta, die teëstander van die manne van JeHûWdah, het hulle gedood, maar na die buit hulle hand nie uitgesteek nie.	",
"	11 Op dieselfde dag het die getal van die wat in die vesting Susan gedood is, voor die koning gekom;	",
"	12 en die koning het aan koningin Ester gesê: In die vesting Susan het die manne van JeHûWdah vyfhonderd man gedood en uitgeroei benewens die tien seuns van Haman; wat sou hulle wel in die ander provinsies van die koning gedoen het? Wat is dan jou bede? - dit sal jou toegestaan word. En wat is verder jou versoek? - daaraan sal voldoen word.	",
"	13 Toe sê Ester: As die koning dit goedvind, laat môre ook aan die manne van JeHûWdah wat in Susan is, toegestaan word om te handel volgens die wet wat geld vir vandag; en laat hulle die tien seuns van Haman aan die galg ophang.	",
"	14 En die koning het bevel gegee om so te doen; en ‘n wet is in Susan uitgevaardig, en hulle het die tien seuns van Haman opgehang.	",
"	15 En die manne van JeHûWdah wat in Susan was, het ook op die veertiende dag van die maand Adar saamgekom; en hulle het in Susan driehonderd man gedood, maar na die buit hulle hand nie uitgesteek nie.	",
"	16 En die ander manne van JeHûWdah wat in die provinsies van die koning was, het saamgekom en hulle siel verdedig en gerus van hul vyande; en hulle het onder hul haters vyf-en-sewentigduisend omgebring, maar na die buit hulle hand nie uitgesteek nie.	",
"	17 Dit was op die dertiende dag van die maand Adar; en op die veertiende daarvan het hulle gerus en dit ’n dag van maaltyd en vrolikheid gemaak.	",
"	18 Maar die manne van JeHûWdah wat in Susan was, het op die dertiende en die veertiende daarvan byeengekom, en op die vyftiende daarvan gerus, sodat hulle dit ’n dag van maaltyd en vrolikheid gemaak het.	",
"	19 Daarom maak die manne van JeHûWdah wat buite in die onbemuurde stede woon, van die veertiende dag van die maand Adar ’n dag van vrolikheid en maaltyd en ’n feesdag waarop hulle mekaar lekkernye stuur.	",
"	20 EN Mórdegai het hierdie dinge opgeskrywe en briewe gestuur aan al die manne van JeHûWdah wat in al die provinsies van koning Ahasvéros was, die wat naby en die wat ver was,	",
"	21 om vir hulle vas te stel dat hulle al jare die veertiende dag van die maand Adar en die vyftiende daarvan moes vier -	",
"	22 as die dae waarop die manne van JeHûWdah rus gekry het van hulle vyande, en die maand wat vir hulle van kommer in vrolikheid en van rou in ’n feesdag verander is - dat hulle daar dae van maaltyd en vrolikheid van moes maak en om mekaar lekkernye en aan die armes gawes te stuur.	",
"	22a En Mórdegai het gesê: Hierdie dinge het deur Elohim gebeur.	",
"	22b Want ek herinner my ‘n droomgesig waarin al hierdie dinge voorspel is, en nie een ding daarvan het onvervul gebly nie.	",
"	22c Die klein Fontein wat tot ‘n rivier vermeerder en dan in ‘n lig en die son verander en soos ‘n magtige stroom wat voortgevloei het, - sy is Ester, wat die koning as sy vrou geneem het en oor wie hy besluit het dat sy koningin sou wees.	",
"	22d Die twee Drake is ek en Haman.	",
"	22e Die nasies wat saamgekom het, is die wat pogings aangewend het om die naam van die manne van JeHûWdah uit te roei.	",
"	22f Maar my volk is JisraEl, wat na JaHWeH geroep het; en JaHWeH het Sy volk verlos: Hy het ons gered uit alle boosheid, en Hy het groot tekens en wonders gewerk onder die nasies.	",
"	22g Ook het Hy twee lotsbestemminge verordineer: een vir die volk van Elohim en ‘n ander vir die orige nasies.	",
"	22h En altwee lotsbestemminge het op die dag wat vanaf daardie tyd reeds vir al die nasies bepaal is, voor die Aangesig van Elohim gekom.	",
"	22i En JaHWeH het aan Sy volk gedink, en Hy het Hom ontferm oor Sy Erfdeel.	",
"	22j En hierdie dae moet in die maand Adar herdenk word op die veertiende en vyftiende dag van daardie maand; dit moet met ywer en vrolikheid gebeur wanneer al die mense bymekaar is, en tot in al die toekomstige geslagte van die volk van JisraEl.	",
"	23 En die manne van JeHûWdah het as insetting aangeneem wat hulle begin het om te doen en wat Mórdegai aan hulle geskryf het.	",
"	24 Want Haman, die seun van Hammedata, die Agagiet, teëstander van al die manne van JeHûWdah, het ’n plan beraam teen die manne van JeHûWdah om hulle uit te roei, en die Pur, dit is die lot, gewerp om hulle te vernietig en hulle uit te roei.	",
"	25 Maar toe dit voor die koning kom, het hy skriftelik bevel gegee dat sy bose plan wat hy teen die manne van JeHûWdah uitgedink het, op sy eie hoof moes neerkom; en hulle het hom en sy seuns aan die galg opgehang.	",
"	26 Daarom noem hulle dié dae Purim, na die naam Pur. Hierom, vanweë al die woorde van daardie brief en wat hulle self daarvan gesien het en wat hulle oorgekom het,	",
"	27 het die manne van JeHûWdah vasgestel en as insetting aangeneem vir hulle en hulle saad en vir almal wat hulle by hulle sou aansluit, sodat dit onherroeplik sou wees, dat hulle dié twee dae al die jare sou hou volgens die voorskrif daaromtrent en op die bepaalde tyd;	",
"	28 en dat dié dae herdenk en gehou moet word in al die geslagte, families, provinsies en stede, en dat dié Purim-dae onder die manne van JeHûWdah nie afgeskaf mag word nie en die gedagtenis daaraan onder hulle saad nie mag ophou nie.	",
"	29 En koningin Ester, die dogter van Abigail, en die man van JeHûWdah Mórdegai het met alle nadruk geskrywe om hierdie tweede brief oor die Purim krag te verleen.	",
"	30 En hy het briewe gestuur aan al die manne van JeHûWdah in die honderd-sewe-en-twintig provinsies, die koninkryk van Ahasvéros, woorde van Vrede en Waarheid,	",
"	31 om dié Purim-dae op hulle bepaalde tye vas te stel soos die man van JeHûWdah Mórdegai en koningin Ester dit vir hulle verorden het, en soos hulle vir hulself en hul saad die voorskrifte aangaande die vastyd en die daarby behorende weeklag vasgestel het.	",
"	32 En die bevel van Ester het die voorskrifte vir hierdie Purim vasgestel, en dit is in ’n boek geskrywe.	",

]
},
{
book: 'Ester',
chapter: '10',
content: [
		
"	1 DAARNA het koning Ahasvéros ’n belasting op die Aarde en op die kuslande van die see gelê.	",
"	2 En al die dade van sy mag en sterkte en die noukeurige berig oor die grootheid van Mórdegai waartoe die koning hom verhoog het, is dit nie beskrywe in die kroniekboeke van die konings van Medië en Persië nie?	",
"	3a In die vierde jaar van die regering van Ptolomeus en Cleopatra het Dosithes, wat homself ‘n priester uit die stam van Levi noem, saam met sy seun Ptolomeüs hierdie brief oor die Purim gebring. En hulle het gesê dat dit deur Lisímaehos, die seun van Ptolomeüs, in Jerusalem vertaal is.	",

]
}

];
