const handelinge_van_die_apostelsChapters = [

{
book: 'Handelinge_Van_Die_Apostels',
chapter: '1',
content: [

"	1 DIE eerste verhaal, Theófilus, het ek opgestel oor alles wat JaHWèshua begin doen en leer het	",
"	2 tot op die dag dat Hy opgeneem is, nadat Hy aan die Apostels wat Hy uitverkies het, deur die Gees van die Apartheid bevele gegee het;	",
"	3 aan wie Hy ook, ná Sy lyde, Hom lewend vertoon het deur baie kentekens, terwyl Hy gedurende veertig dae aan hulle verskyn het en oor die dinge van die Koninkryk van die Elohim gespreek het. [1 Nikodemus 16:1a]	",
"	4 En toe Hy nog met hulle saam was, het Hy hulle bevel gegee om nie van Jerusalem weg te gaan nie, maar om te wag op die Belofte van die VADER, wat julle, het Hy gesê, van My gehoor het. [Hebreërs 6:12]	",
"	5 Want JeHôWganan het wel in water gewas/gedoop, maar julle sal met die Gees van Apartheid gewas/gedoop word nie lank ná hierdie dae nie.	",
"	6 Die wat bymekaargekom het, vra Hom toe en sê: Meester, gaan U in hierdie tyd die koninkryk vir JisraEl weer oprig?	",
"	7 En Hy antwoord hulle: Dit kom julle nie toe om die tye of geleenthede te weet wat die VADER deur SY eie mag bepaal het nie;	",
"	8 maar julle sal Krag ontvang wanneer die Gees van die Apartheid oor julle kom, en julle sal My getuies wees in Jerusalem sowel as in die hele JeHûWdah en Samaría en tot aan die uiterste van die Aarde.	",
"	9 En nadat Hy dit gesê het, is Hy opgeneem terwyl hulle dit sien; en die Wolkkolom het Hom voor hulle oë weggeneem. [Psalm 47:5]	",
"	10 En toe hulle nog stip na die Hemele kyk terwyl Hy weggaan, staan daar twee Manne in wit klere by hulle,	",
"	11 wat sê: Galilése manne, waarom staan julle en kyk na die Hemele? Hierdie JaHWèshua wat van julle opgeneem is in die Hemele, sal net so kom soos julle Hom na die Hemele sien wegvaar het.	",
"	12 Daarop draai hulle om na Jerusalem van die berg af wat genoem word Berg van die Olywe, wat naby Jerusalem is, omtrent ’n Sabbatsreis.	",
"	13 En toe hulle daar kom, gaan hulle na die bovertrek waar hulle gewoond was om te vertoef, naamlik: Petrus en Jakobus en JeHôWganan en Andréas, Filippus en Thomas, Bartholoméüs en MattithJaHûW, Jakobus, die seun van Alféüs, en Simon, die Yweraar, en Judas, die seun van Jakobus.	",
"	14 Hulle almal het eendragtig volhard in gebed en smeking, saam met ’n aantal vroue en Mirjam, die moeder van JaHWèshua, en met Sy broers.	",
		

		
"	15 EN in dié dae het Petrus in die midde van die studente opgestaan - die skare van persone daar bymekaar was omtrent honderd-en-twintig - en gesê:	",
"	16 Broers, hierdie Skrif moes vervul word wat die Gees van die Apartheid voorspel het deur die mond van Dawid aangaande Judas wat die leier was van die wat JaHWèshua gevange geneem het; [Psalm 41:9]	",
"	17 want hy is saam met ons getal gereken en het die lot van hierdie bediening verkry.	",
"	18 Hy het dan ’n stuk grond gekoop met die loon van ongeregtigheid en het vooroor geval en oopgebars, en al sy ingewande het uitgestort;	",
"	19 en dit het bekend geword aan al die inwoners van Jerusalem, sodat daardie stuk grond in hulle eie taal Gelek-Dám genoem is, dit is Bloedgrond.	",
"	20 Want daar staan geskrywe in die Boekrol van die Psalms: Laat hulle laer woes word, laat in hulle tente geen bewoner wees nie! En: Laat ’n ander een sy opsienersamp neem. [Psalm 69:25]	",
"	21 Van die manne dan wat saam met ons rondgegaan het al die tyd waarin onse Meester JaHWèshua by ons in en uitgegaan het,	",
"	22 van die wassing/doop van JeHôWganan af tot op die dag dat Hy van ons opgeneem is - van hulle moet daar een saam met ons getuie word van Sy opstanding.	",
"	23 En hulle het twee voorgestel: JôWsef wat genoem is Bársabas, met die bynaam van Justus, en Matthías.	",
"	24 En hulle het gebid en gesê: U, JaHWeH, wat die harte van almal ken, wys uit hierdie twee die een aan wat U uitverkies het	",
"	25 om die lot van hierdie bediening en apostelskap te verkry, waarvan Judas afgewyk het om heen te gaan na sy eie plek.	",
"	26 Toe werp hulle die lot, en die lot het op Matthías geval; en hy is gekies om saam met die elf Apostels te wees.	",
		

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '2',
content: [
		
"	1 EN toe die Fees van die Weke aangebreek het, was hulle almal eendragtig bymekaar.	",
"	2 En daar kom skielik uit die Hemele ’n geluid soos van ’n geweldige rukwind, en sy het die hele huis gevul waar hulle gesit het.	",
"	3 Toe is deur hulle Tonge gesien soos van Vuur, wat Haarself verdeel en op elkeen van hulle gaan sit.	",
"	4 En hulle is almal vervul met die Gees van die Apartheid en het begin spreek in ander tale, soos die Gees aan hulle gegee het om uit te spreek.	",
"	5 En daar het in Jerusalem manne van JeHûWdah gewoon, gelowige manne, uit elke nasie wat onder die Hemele is.	",
"	6 En toe hierdie geluid kom, het die menigte saamgestroom en was in die war, want elkeen het gehoor hoe hulle in sy eie taal spreek;	",
"	7 en hulle was almal verbaas en verwonderd en sê vir mekaar: Is almal wat daar spreek, dan nie Galileërs nie?	",
"	8 En hoe hoor ons hulle, elkeen in ons eie taal waarin ons gebore is?	",
"	9 Parthers en Meders en Elamiete en die inwoners van Mesopotámië, JeHûWdah en Kappadócië, Pontus en Asië,	",
"	10 Frígië en Pamfílië, Egipte en die streke van Líbië by Ciréne, en Romeine wat hier vertoef, en manne van JeHûWdah,	",
"	11 Kretense en Arabiere - ons hoor hulle in ons eie taal oor die groot dade van die Elohim spreek.	",
"	12 En hulle was almal verbaas en radeloos en sê die een vir die ander: Wat kan dit tog wees?	",
"	13 Maar ander het gespot en gesê: Hulle is vol soetwyn.	",
		

		
"	14 MAAR Petrus het opgestaan met die elf en sy stem verhef en hulle toegespreek: Manne van JeHûWdah en almal wat in Jerusalem woon, dit moet julle weet, en luister na my woorde.	",
"	15 Hierdie mense is tog nie dronk soos julle dink nie, want dit is nog maar die derde uur in die môre.	",
"	16 Maar dit is wat deur die Profeet JôWEl gespreek is:	",
"	17 En in die laaste dae, spreek JaHWeH, sal Ek My Gees uitgiet op alle vlees, en julle seuns en julle dogters sal profeteer, en julle jongelinge sal visioene sien, en julle oues sal drome droom. [JôWEl 2:28]	",
"	18 En ook op die diensknegte en op die diensmaagde sal Ek in dié dae My Gees uitgiet. [JôWEl 2:29]	",
"	19 En Ek sal wondertekens gee aan die Hemele en tekens onder op die Aarde, bloed en vuur en pilare van rook. [JôWEl 2:30]	",
"	20 Die son sal verander in duisternis en die maan in bloed voordat die groot en deurlugtige dag van JaHWeH kom. [JôWEl 2:31]	",
"	21 En elkeen wat die Naam van JaHWeH aanroep, sal gered word; want op die Berg van Sion en in Jerusalem sal daar ontkoming wees soos JaHWeH gesê het, en onder die oorblyfsel van die wat JaHWeH sal roep]. [JôWEl 2:32]	",
"	22 JisraEliete, luister na hierdie woorde! JaHWèshua, die Nasaréner, ’n Man deur die Elohim vir julle aangewys met kragte en wonders en tekens wat Elohim deur Hom onder julle gedoen het, soos julle ook self weet -	",
"	23 Hom, wat deur ‘n vorige besluit van die Raad en Voorkennis van Elohim oorgelewer is, het julle deur die hande van wettelose manne geneem en gefolter en omgebring;	",
"	24 Hom het Elohim opgewek, nadat Hy die smarte van die Dood ontbind het, omdat dit onmoontlik was dat Hy deur haar vasgehou sou word.	",
"	25 Want Dawid sê van Hom: Ek stel JaHWeH altyddeur voor my; omdat Hy aan my regterhand is, sal Ek nie wankel nie.	",
"	26 Daarom is my hart bly en my tong juig, ja, ook sal my vlees nog rus in hoop.	",
"	27 Want U sal my siel nie aan die Doderyk /Sheol oorlaat of U Aparte Een oorgee, om verderwing te sien nie.	",
"	28 U het my die Weë van die lewe bekend gemaak, U sal my vervul met Vreugde by U Aangesig.	",
"	29 Broers, ek kan vrylik met julle spreek oor die aartsvader Dawid, dat hy gesterf het en ook begrawe is, en sy graf is by ons tot vandag toe.	",
"	30 Omdat hy dan ’n Profeet was en geweet het dat Elohim vir hom met ’n Eed gesweer het dat hy uit die vrug van sy lendene, wat die vlees betref, die Gesalfde sou verwek om op sy Troon te sit,	",
"	31 het hy, omdat hy dit vooruit gesien het, gespreek van die opstanding van die Gesalfde, dat Sy siel nie in die Doderyk/Sheol verlaat is en Sy vlees ook nie verderwing gesien het nie.	",
"	32 Hierdie JaHWèshua het Elohim opgewek, waarvan ons almal getuies is.	",
"	33 Nadat Hy dan aan die Regterkant van JaHWeH verhoog is en van die VADER die Belofte van die Gees van Apartheid ontvang het, het Hy Haar uitgestort, wat julle nou sien en hoor.	",
"	34 Want Dawid het nie in die Hemele opgevaar nie, maar hy self sê: JaHWeH het gespreek tot my Meester: Sit aan My regterkant	",
"	35 totdat EK U vyande gemaak het ’n Voetbank vir U voete. [Psalm 110:1]	",
"	36 Laat dan die hele huis van JisraEl sekerlik weet dat Elohim Hom Meester en Gesalfde gemaak het, hierdie JaHWèshua wat julle gefolter het.	",
		

		
"	37 TOE hulle dit hoor, is hulle diep in die hart getref en het vir Petrus en die ander Apostels gesê: Wat moet ons doen, broers?	",
"	38 En Petrus sê vir hulle: Bekeer julle, en laat elkeen van julle gewas/gedoop word in die Naam van JaHWèshua die Gesalfde tot vergewing van oortredinge, en julle sal die gawe van die Gees van die Apartheid ontvang.	",
"	39 Want die Belofte kom julle toe en julle kinders en almal wat daar ver is, die wat JaHWeH onse Elohey na Hom sal roep.	",
"	40 En met baie ander woorde het hy hulle besweer en vermaan en gesê: Laat julle red uit hierdie verbasterde saadlyn.	",
"	41 Die wat toe Sy woord met blydskap aangeneem het, is gewas/gedoop; en daar is op dié dag omtrent drieduisend siele toegebring.	",
"	42 En hulle het volhard in die leer van die Apostels en in die gemeenskap en in die breking van die Brood en in die gebede.	",
"	43 En vrees het op elke siel gekom, en baie wonders en tekens het deur die Apostels plaasgevind.	",
"	44 En almal wat gelowig geword het, was bymekaar, en het alles gemeenskaplik besit.	",
"	45 En hulle eiendomme en besittings het hulle verkoop en die opbrengs onder almal verdeel, volgens wat elkeen nodig gehad het.	",
"	46 En dag vir dag het hulle eendragtig volhard in die Tempel en van huis tot huis Brood gebreek en hulle voedsel met blydskap en eenvoudigheid van hart geniet,	",
"	47 terwyl hulle JaHWeH geprys het en in guns was by die hele volk. En die Koning het daagliks by die gemeente gevoeg die wat gered is.	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '3',
content: [

		
"	1 EN Petrus en JeHôWganan het saam na die Tempel opgegaan op die uur van die gebed, die negende uur.	",
"	2 En daar is ’n sekere man aangedra wat van sy geboorte af kreupel was; hulle het hom elke dag neergesit by die tempelpoort wat die Skone genoem word, om ’n aalmoes te vra van die wat in die Tempel ingaan.	",
"	3 Toe hy sien dat Petrus en JeHôWganan die Tempel wou binnegaan, het hy om ’n aalmoes gevra.	",
"	4 En Petrus saam met JeHôWganan het hom stip aangekyk en gesê: Kyk na ons.	",
"	5 En hy het sy oë op hulle gehou in die verwagting dat hy iets van hulle sou ontvang.	",
"	6 Maar Petrus sê: Silwer en goud het ek nie; maar wat ek het, dit gee ek vir jou: In die Naam van JaHWèshua die Gesalfde, die Nasaréner, staan op en loop!	",
"	7 Toe gryp hy hom aan sy regterhand en rig hom op, en onmiddellik het sy voete en enkels sterk geword.	",
"	8 En hy het opgespring en gestaan en rondgeloop en saam met hulle in die Tempel ingegaan terwyl hy rondloop en spring en Elohim prys.	",
"	9 En die hele volk het gesien hoe hy daar loop en Elohim prys.	",
"	10 En hulle het hom herken, dat dit hy was wat by die Skone Poort van die Tempel gesit het om te bedel, en hulle is vervul met verwondering en verbasing oor wat met hom gebeur het.	",
"	11 En toe die kreupel man wat genees was, aan Petrus en JeHôWganan vashou, het die hele volk uitermate verbaas na hulle gehardloop in die pilaargang wat Salomo s’n genoem word.	",
"	12 En toe Petrus dit sien, sê hy vir die volk: JisraEliete, waarom is julle hieroor verwonderd, of waarom kyk julle ons so aan asof ons deur ons eie krag of eerbaarheid bewerk het dat hy loop?	",
"	13 Die Elohey van Abraham en Isak en Jakob, die Elohey van ons vaders, het SY Kind JaHWèshua verhoog, Hom wat julle oorgelewer en teen getuig het voor Pilatus toe hy besluit het om Hom los te laat.	",
"	14 En julle het teen die Aparte Een en Regverdige getuig en gevra dat ‘n moordenaar aan julle geskenk sou word,	",
"	15 en die Leidsman tot die lewe het julle gedood. Elohim het Hom uit die dode opgewek, waarvan ons getuies is.	",
"	16 En deur die Geloof in Sy Naam het Sy Naam hierdie man, wat julle sien en ken, sterk gemaak, en die Geloof wat deur Hom is, het hom hierdie volkome gesondheid gegee voor die aangesig van julle almal.	",
"	17 En nou, broers, ek weet dat julle dit in onwetendheid gedoen het, net soos julle owerstes;	",
"	18 maar Elohim het op dié manier vervul wat Hy tevore verkondig het deur die mond van al Sy Profete, dat die Gesalfde sou ly.	",
"	19 Kom dan tot inkeer en bekeer julle, sodat julle oortredinge uitgewis kan word en tye van verkwikking van die Aangesig van JaHWeH mag kom,	",
"	20 en HY Hom mag stuur wat vooraf aan julle verkondig is, naamlik JaHWèshua die Gesalfde,	",
"	21 Hom wat die Hemele moet ontvang tot op die tye van die wederoprigting van alle dinge, waarvan Elohim van ouds af gespreek het deur die mond van al Sy Profete van Apartheid.	",
"	22 Want Moshè het tot die vaders gespreek: ’n Profeet uit jou midde, uit jou broers, soos ek is, sal JaHWeH jou Elohey vir jou verwek; na Hom moet julle luister - volgens alles wat Hy met julle sal spreek. [Deuteronómium 18:15,19]	",
"	23 En elke siel wat nie na dié Profeet luister nie, sal uit die volk uitgeroei word.	",
"	24 En ook al die Profete van ShemuEl af en die wat gevolg het, almal wat gespreek het, het ook hierdie dae aangekondig.	",
"	25 En julle is kinders van die Profete en van die Verbond wat Elohim met ons vaders gesluit het toe Hy vir Abraham gesê het: En in jou saad sal al die geslagte van die Adamah [die adamiet se Aarde] geseën word. [Génesis 22:18]	",
"	26 Elohim het, nadat HY SY Kind JaHWèshua opgewek het, Hom eers vir julle gestuur om julle te seën deur elkeen van sy besoedeling te bekeer.	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '4',
content: [
	
"	1 EN terwyl hulle besig was om met die volk te spreek, het die priesters en die hoofman van die Tempel en die Sadduseërs op hulle afgekom,	",
"	2 baie ontevrede dat hulle die volk leer en in JaHWèshua die opstanding uit die dode verkondig.	",
"	3 En hulle het die hande aan hulle geslaan en hulle in die gevangenis gesit tot die volgende môre toe, want dit was al aand.	",
"	4 En baie van die wat die woord gehoor het, het geglo; en die getal van die manne het omtrent vyfduisend geword.	",
"	5 Die volgende dag kom toe hulle owerstes en oudstes en skrywers in Jerusalem bymekaar,	",
"	6 ook Annas, die hoëpriester, en Kájafas en JeHôWganan en Alexander en almal wat van die hoëpriesterlike ras was;	",
"	7 en toe hulle hul voorgebring het, vra hulle: Deur watter mag en deur watter naam het julle dit gedoen?	",
"	8 Daarop sê Petrus, vervul met die Gees van die Apartheid, aan hulle: Owerstes van die volk en oudstes van JisraEl,	",
"	9 as ons vandag ondervra word oor ’n weldaad aan ’n siek man, waardeur hy gesond geword het,	",
"	10 laat dit bekend wees aan julle almal en aan die hele volk van JisraEl dat deur die Naam van JaHWèshua die Gesalfde, die Nasaréner, wat julle gefolter het, maar wat Elohim uit die dode opgewek het, dat deur Hom hierdie man gesond voor julle staan.	",
"	11 Sy [die Gees] is die Steen wat deur julle, die bouers, verag is, wat ’n Hoeksteen geword het. [Psalm 118:22]	",
"	12 En die Verlossing is in niemand anders nie, want daar is ook geen ander Naam onder die Hemele wat onder die adamiete gegee is, waardeur ons gered moet word nie.	",
"	13 En toe hulle die vrymoedigheid van Petrus en JeHôWganan sien en verstaan dat hulle ongeleerde en eenvoudige manne was, was hulle verwonderd en het hulle as metgeselle van JaHWèshua herken.	",
"	14 En omdat hulle die man wat genees was, by hulle sien staan, kon hulle niks daarteen sê nie.	",
"	15 Hulle het hul toe gelas om buitekant die Raad te gaan, en met mekaar beraadslaag	",
"	16 en gesê: Wat moet ons met hierdie manne doen? Want dat daar ’n kenlike Teken deur hulle plaasgevind het, is duidelik vir al die inwoners van Jerusalem; ons kan dit nie ontken nie.	",
"	17 Maar dat dit nie nog meer onder die volk versprei word nie, laat ons hulle dreig om nie meer in hierdie Naam met enige adamiet te spreek nie.	",
"	18 En hulle het hul geroep en hulle bevel gegee om in die geheel nie in die Naam van JaHWèshua te spreek of te leer nie.	",
"	19 Toe antwoord Petrus en JeHôWganan en sê vir hulle: Of dit reg is voor Elohim om julle meer gehoorsaam te wees as Elohim, moet julle self beslis;	",
"	20 want vir ons is dit onmoontlik om nie te spreek oor wat ons gesien en gehoor het nie.	",
"	21 En nadat hulle nog dreigemente bygevoeg het, aangesien hulle geen rede kon vind om hulle te straf nie, het hulle ter wille van die volk hulle losgelaat, want almal het Elohim vereer oor wat gebeur het.	",
"	22 Want die man aan wie hierdie teken van genesing plaasgevind het, was meer as veertig jaar oud.	",
"	23 En nadat hulle losgelaat was, het hulle na hul eie mense gegaan en alles vertel wat die owerpriesters en die oudstes aan hulle gesê het.	",
"	24 En toe hulle dit hoor, het hulle eendragtig die stem tot Elohim verhef en gesê: O JaHWeH, onse Elohey, wat die Hemele en die Aarde en die see en alles wat daarin is, gemaak het,	",
"	25 wat deur die mond van U kneg Dawid gesê het: Waarom woel die nasies en bedink die volke nietige dinge? [Psalm 2:1]	",
"	26 Die konings van die Aarde staan gereed, en die vorste hou saam raad teen JaHWeH en teen SY Gesalfde. [Psalm 2:2]	",
"	27 Want waarlik, Herodes en Pontius Pilatus het saam met heidene en die volke van JisraEl vergader teen U Kind van Apartheid, JaHWèshua, wat U gesalf het,	",
"	28 om alles te doen wat U Hand en U Raad vooruit bepaal het om plaas te vind.	",
"	29 En nou, my Meester, let op hulle dreigemente en gee aan U diensknegte om met alle vrymoedigheid U Woord te spreek,	",
"	30 deurdat U U Hand uitstrek tot genesing, en tekens en wonders deur die Naam van U Kind van Apartheid, JaHWèshua laat plaasvind. [Exodus 23:25]	",
"	31 En toe hulle gebid het, is die plek geskud waar hulle saam was, en hulle is almal vervul met die Gees van die Apartheid en het die woord van die Elohim met vrymoedigheid gespreek.	",
		
		
"	32 EN die menigte van die wat gelowig geword het, was een van hart en siel, en nie een het gesê dat iets van sy besittings sy eie was nie, maar hulle het alles in gemeenskap gehad.	",
"	33 En met groot Krag het die Apostels getuienis gegee van die opstanding van die Meester, JaHWèshua, en groot Barmhartigheid was oor hulle almal.	",
"	34 Want niemand onder hulle was behoeftig nie; want almal wat besitters van gronde of huise was, het haar verkoop en die prys van wat verkoop is, gebring en aan die voete van die Apostels neergelê.	",
"	35 En aan elkeen is uitgedeel volgens wat hy nodig gehad het.	",
"	36 En Joses wie se bynaam onder die Apostels Bárnabi was - wat as dit [uit Aramees] vertaal word, beteken seun van vertroosting - ’n Leviet, van geboorte uit Ciprus,	",
"	37 het ’n stuk grond gehad en haar verkoop en die geld gebring en aan die voete van die Apostels neergelê.	",
		

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '5',
content: [
		
"	1 MAAR ’n sekere man met die naam van Ananías het saam met sy vrou Saffíra ’n eiendom verkoop,	",
"	2 en ook met die medewete van sy vrou van die prys agtergehou en ’n sekere deel gebring en aan die voete van die Apostels neergelê.	",
"	3 Toe sê Petrus: Ananías, waarom het die Satan jou hart vervul om vir die Gees van die Apartheid te lieg en van die prys van die grond agter te hou?	",
"	4 As sy nie verkoop was nie, het sy nie joune gebly nie? En toe sy verkoop is, was dit nie in jou mag nie? Waarom is dit dat jy hierdie saak in jou hart voorgeneem het? Jy het nie vir mense gelieg nie, maar vir Elohim.	",
"	5 En toe Ananías hierdie woorde hoor, het hy neergeval en gesterwe; en ’n groot Vrees het gekom oor almal wat dit gehoor het.	",
"	6 Daarna het die jongmanne opgestaan en hom toegedraai en uitgedra en begrawe.	",
"	7 En ná verloop van omtrent drie uur kom sy vrou in sonder om te weet wat voorgeval het.	",
"	8 En Petrus het haar aangespreek: Sê vir my of julle die grond vir soveel verkoop het? En sy sê: Ja, vir soveel.	",
"	9 En Petrus sê vir haar: Waarom het julle ooreengekom om die Gees van JaHWeH te versoek? Kyk, die voete van die wat jou man begrawe het, is by die deur, en hulle sal jou uitdra.	",
"	10 Toe val sy onmiddellik aan sy voete neer en het gesterwe. En die jongmanne het ingekom en haar dood gevind en haar uitgedra en by haar man begrawe.	",
"	11 En ’n groot Vrees het oor die hele gemeente gekom en oor almal wat dit gehoor het.	",
"	12 En deur die hande van die Apostels het daar baie tekens en wonders onder die volk plaasgevind; en hulle was almal eendragtig saam in die pilaargang van Salomo.	",
"	13 En daar was niemand van die ander wat dit gewaag het om hom by hulle te voeg nie, maar die volk het hulle baie geëer.	",
"	14 En daar is meer en meer gelowiges in die Hoogste El bygevoeg, menigtes van manne sowel as vroue,	",
"	15 sodat hulle die siekes op die strate uitgedra en op bedde en draagbare gelê het, met die bedoeling dat, as Petrus kom, al was dit net sy skaduwee op iemand van hulle sou val.	",
"	16 En die menigte van die stede in die omtrek het ook in Jerusalem bymekaargekom en siekes gebring en mense wat deur geeste van besoedeling gekwel was; en hulle is almal genees.	",
		
		
"	17 EN die hoëpriester het opgestaan en almal wat saam met hom was - dit is die party van die Sadduseërs - en hulle was met nydigheid vervul,	",
"	18 en hulle het die hande aan die Apostels geslaan en hulle in die openbare gevangenis gesit.	",
"	19 Maar ’n Boodskapper van JaHWeH het in die nag die deure van die gevangenis oopgemaak en hulle uitgelei en gesê:	",
"	20 Gaan heen, staan en vertel in die Tempel aan die volk al die woorde van hierdie lewe.	",
"	21 En hulle het geluister en vroeg in die môre in die Tempel gegaan en begin leer. Maar die hoëpriester en die wat saam met hom was, het gekom en die Raad en al die oudstes van die kinders van JisraEl bymekaargeroep; en hulle het na die gevangenis gestuur om hulle te laat haal.	",
"	22 Maar toe die dienaars daar kom, het hulle hul nie in die gevangenis gekry nie; en hulle het omgedraai en berig gebring en gesê:	",
"	23 Die gevangenis het ons in alle sekerheid toegesluit gevind, en die wagte het buite gestaan voor die deure; maar toe ons oopmaak, kry ons niemand daarbinne nie.	",
"	24 En toe die hoëpriester en die hoofman van die Tempel en die owerpriesters hierdie woorde hoor, was hulle daarmee verleë wat nou hiervan sou word.	",
"	25 En daar kom een en bring aan hulle berig en sê: Kyk, die manne wat julle in die gevangenis gesit het, staan in die Tempel en leer die volk.	",
"	26 Daarop gaan die hoofman met die dienaars en bring hulle, maar nie met geweld nie, uit vrees vir die volk dat hulle gestenig sou word.	",
"	27 Hulle het hul dan gebring en voor die Raad gestel; en die hoëpriester het hulle gevra en gesê:	",
"	28 Het ons julle nie uitdruklik verbied om in dié Naam te leer nie? En kyk, julle het Jerusalem met julle leer vervul; en julle wil die bloed van hierdie Man op ons bring.	",
"	29 En Petrus en die Apostels antwoord en sê: Ons moet aan Elohim meer gehoorsaam wees as aan die mense.	",
"	30 Die Elohey van ons vaders het JaHWèshua opgewek, wat julle omgebring het deur Hom aan ’n hout te hang.	",
"	31 Hom het Elohim as Leidsman en Verlosser deur SY Regterhand verhoog om aan JisraEl bekering en vergifnis van oortredinge te skenk.	",
"	32 En ons is Sy getuies van hierdie dinge, en ook die Gees van die Apartheid wat Elohim gegee het aan die wat Hom gehoorsaam is.	",
"	33 Toe hulle dit hoor, was hulle woedend en wou hulle om die lewe bring.	",
"	34 Maar ’n Fariseër met die naam van GamaliEl, ’n leraar van die Wet wat by die hele volk hoog in aansien was, het in die Raad opgestaan en bevel gegee dat hulle die Apostels ’n bietjie buitentoe moes bring.	",
"	35 Toe sê hy vir hulle: JisraEliete, pas op wat julle gaan doen met hierdie manne;	",
"	36 want nie lank gelede nie het Theudas opgestaan en gesê dat hy iets besonders was. By hom het ’n aantal mense - omtrent vierhonderd - aangesluit. Hy is gedood, en almal wat na hom geluister het, is uitmekaargejaag en het tot niet geword.	",
"	37 En ná hom het Judas, die Galileër, opgestaan, in die dae van die inskrywing, en ’n aansienlike getal mense afvallig gemaak agter hom aan. Hy het ook omgekom, en almal wat na hom geluister het, is verstrooi.	",
"	38 En nou sê ek vir julle, bly af van hierdie manne en laat hulle staan; want as hierdie voorneme of hierdie werk uit mense is, sal dit vernietig word;	",
"	39 maar as dit uit Elohim is, kan julle dit nie vernietig nie - dat dit nie miskien bevind word dat julle selfs teen Elohim stry nie.	",
"	40 En hulle het na hom geluister. En nadat hulle die Apostels ingeroep het, het hulle hul laat slaan en hulle bevel gegee om nie in die Naam van JaHWèshua te spreek nie en hulle laat gaan.	",
"	41 Hulle het toe van die Raad af weggegaan, bly dat hulle waardig geag was om vir Sy Naam oneer te ly.	",
"	42 En hulle het nie opgehou om elke dag in die Tempel en van huis tot huis te leer nie, en die goeie nuus te verkondig dat JaHWèshua die Gesalfde is. [Handelinge 9:22]	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '6',
content: [
		
"	1 EN in dié dae toe die studente vermeerder het, het daar ’n murmurering ontstaan van die Helleniste teen die Hebreërs omdat hulle weduwees in die daaglikse versorging oor die hoof gesien is.	",
"	2 En die twaalf het die menigte van die studente byeengeroep en gesê: Dit is nie reg dat ons die Woord van Elohim nalaat om die tafels te bedien nie.	",
"	3 Kyk dan uit, broers, na sewe manne uit julle, van goeie getuienis, vol van die Gees van die Apartheid en Wysheid, wat ons oor hierdie nodige saak kan aanstel;	",
"	4 maar ons sal volhard in die gebed en die bediening van die Woord.	",
"	5 En die Woord het byval gevind by die hele menigte; en hulle het gekies: Stéfanus, ’n man vol van Geloof en van die Gees van die Apartheid, en Filippus en Próchorus en Nikánor en Timon en Pármenas en Nikoláüs, ’n bekeerling uit Antiochíë,	",
"	6 wat hulle voor die Apostels gestel het; en hulle het gebid en hulle die hande opgelê.	",
"	7 En die Woord van Elohim het toegeneem, en die getal van die studente het in Jerusalem baie vermeerder, en ’n groot menigte van priesters het gehoorsaam geword aan die Geloof.	",
		
		
"	8 EN Stéfanus, vol van Geloof en Krag, het groot wonders en tekens onder die volk gedoen.	",
"	9 En daar het sommige van die sogenaamde vergadering van die Libertyne opgestaan, en van die Cirenéërs en Alexandryne, en van die mense van Cilícië en Asië, en hulle het met Stéfanus geredetwis.	",
"	10 Maar hulle kon die Gees en die Wysheid, waardeur hy gespreek het, nie weerstaan nie.	",
"	11 Toe het hulle manne opgestook om te sê: Ons het hom lasterlike dinge hoor praat teen Moshè en Elohim.	",
"	12 En hulle het die volk en die oudstes en die skrywers in beweging gebring en op hom afgekom en hom gegryp en voor die Raad gebring.	",
"	13 En hulle het valse getuies laat optree om te sê: Dié man hou nie op om lasterlike dinge te praat teen hierdie Plek van Apartheid en die Wet nie.	",
"	14 Want ons het hom hoor sê: Hierdie JaHWèshua, die Nasaréner, sal hierdie plek afbreek en die gebruike wat Moshè aan ons oorgelewer het, verander.	",
"	15 En terwyl almal wat in die Raad sit, hul oë stip op hom hou, sien hulle dat sy gesig soos die gesig van ’n Boodskapper was.	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '7',
content: [
		
"	1 TOE sê die hoëpriester: Is hierdie dinge dan so?	",
"	2 En hy sê: Broers en vaders, luister! El, die Elohey van Glansrykheid het verskyn aan ons vader Abraham toe hy in Mesopotámië was, voordat hy in Haran gewoon het,	",
"	3 en vir hom gesê: Trek uit jou Aarde en uit jou familie, en kom na die Adamah [die adamiet se Aarde] wat Ek jou sal wys.	",
"	4 Toe het hy getrek uit die Aarde van die Chaldeërs en in Haran gaan woon; en ná die dood van sy vader het Hy hom daarvandaan laat verhuis na hierdie deel van Aarde waarin julle nou woon.	",
"	5 En Hy het hom geen Erfdeel in haar gegee nie, selfs nie ’n voetbreed nie, maar Hy het belowe om haar aan hom en sy saad ná hom as eiendom te gee, toe hy nog geen kind gehad het nie.	",
"	6 En Elohim het aan hom dít gesê, dat sy saad bywoners in ’n vreemde deel van die Aarde sou wees en die mense hulle tot slawe sou maak en mishandel, vierhonderd jaar lank.	",
"	7 En die nasie aan wie hulle diensbaar sal wees, sal Ek oordeel, het Elohim gesê; en daarna sal hulle uittrek en My in hierdie plek dien.	",
"	8 En Hy het hom die Verbond van die Besnydenis gegee, en so het Hy Isak gekry en hom op die agtste dag besny; en so het Isak vir Jakob gekry, en Jakob van die twaalf aartsvaders.	",
"	9 En die aartsvaders was jaloers op JôWsef en het hom verkoop na Egipte toe; maar Elohim was met hom	",
"	10 en het hom uit al sy verdrukkinge verlos en hom Guns en Wysheid geskenk voor Farao, die koning van Egipte; en dié het hom goewerneur gemaak oor Egipte en oor sy hele huis.	",
"	11 En ’n hongersnood en groot benoudheid het oor die hele Aarde van Egipte en Kanaän gekom, en ons vaders kon geen voedsel kry nie.	",
"	12 En toe Jakob hoor dat daar koring in Egipte was, het hy ons vaders die eerste keer uitgestuur.	",
"	13 En die tweede keer is JôWsef deur sy broers herken, en die ras van JôWsef het aan Farao bekend geword.	",
"	14 Toe het JôWsef gestuur en sy vader Jakob laat roep en sy hele familie, vyf-en-sewentig siele.	",
"	15 En Jakob het afgetrek na Egipte en daar gesterwe, hy en ons vaders.	",
"	16 En hulle is oorgebring na Sigem en weggelê in die graf wat Abraham vir ’n som geld gekoop het van die seuns van Hemor, die [vader] van Sigem.	",
"	17 En namate die tyd van die belofte wat Elohim aan Abraham met ’n Eed beloof het, nader kom, het die volk toegeneem en vermeerder in Egipte,	",
"	18 totdat daar ’n ander koning opgestaan het wat nie vir JôWsef geken het nie.	",
"	19 Hy het listig met ons ras te werk gegaan en ons vaders mishandel deur hulle te verplig om hul kindertjies weg te gooi, sodat hulle nie in die lewe behou kon word nie.	",
"	20 In dié tyd is Moshè gebore, en hy was pragtig. Drie maande lank is hy in die huis van sy vader versorg;	",
"	21 en toe hy weggesteek is, het Farao se dogter hom opgeneem en hom as haar seun grootgemaak.	",
"	22 En Moshè is opgelei in al die wysheid van die Egiptenaars en was magtig in woorde en dade.	",
"	23 En nadat hy die ouderdom van veertig jaar bereik het, het dit in sy hart opgekom om sy broers, die kinders van JisraEl, te besoek;	",
"	24 en toe hy sien dat iemand onreg aangedoen word, het hy hom verdedig en die man wat mishandel was, gewreek deur die Egiptenaar te verslaan.	",
"	25 En hy het gedink dat sy broers sou verstaan dat Elohim hulle deur Sy Hand Verlossing sou gee; maar hulle het dit nie verstaan nie.	",
"	26 En die volgende dag het hy by hulle verskyn terwyl hulle besig was om te veg, en hy het by hulle aangedring om vrede te maak en gesê: Manne, julle is broers; waarom doen julle mekaar onreg aan?	",
"	27 Maar hy wat sy naaste onreg aangedoen het, het hom afgestoot en gesê: Wie het jou as ’n owerste en regter oor ons aangestel?	",
"	28 Jy wil my tog nie doodmaak soos jy gister die Egiptenaar doodgemaak het nie?	",
"	29 En Moshè het op hierdie woord gevlug en ’n bywoner geword in die Aarde van Mídian, waar hy twee seuns gekry het.	",
"	30 En toe veertig jaar verby was, het ‘n Boodskapper van JaHWeH aan hom verskyn in die wildernis van die berg Sinai, in die vuurvlam van ’n doringbos. [Exodus 3:2]	",
"	31 En Moshè het dit gesien en hom oor die gesig verwonder; en toe hy daarheen gaan om dit te sien, het die Stem van Elohim tot hom gekom:	",
"	32 Ek [is] die Elohey van jou vaders, die Elohey van Abraham en die Elohey van Isak en die Elohey van Jakob. En Moshè het begin bewe en nie gewaag om dit te bekyk nie. [Exodus 3:6]	",
"	33 Toe sê JaHWeH vir hom: Trek die skoene van jou voete af, want die plek waarop jy staan, is Adamah [die adamiet se Aarde] van Apartheid. [Exodus 3:5]	",
"	34 Ek het duidelik gesien die mishandeling van My volk wat in Egipte is, en hulle gesug gehoor en neergedaal om hulle te verlos. En nou, kom hier, Ek wil jou na Egipte stuur.	",
"	35 Hierdie Moshè wat hulle teen getuig het deur te sê: Wie het jou aangestel as ’n owerste en regter? - hom het Elohim as owerste en verlosser gestuur deur die hand van die Boodskapper wat aan hom verskyn het in die doringbos. [Exodus 3:2]	",
"	36 Hy het hulle uitgelei en wonders en tekens in die Aarde van Egipte en in die Rooi See en die wildernis gedoen, veertig jaar lank.	",
"	37 Dit is dié Moshè wat aan die kinders van JisraEl gesê het: ’n Profeet uit jou midde, uit jou broers, soos ek is, sal JaHWeH jou Elohey vir jou verwek; na Hom moet julle luister. [Deuteronómium 18:15,19]	",
"	38 Dit is hy wat in die vergadering in die wildernis was saam met die Boodskapper wat met hom op die berg Sinai gespreek het, en saam met ons vaders; hy het die Lewende Woorde ontvang om aan ons te gee.	",
"	39 Na hom wou ons vaders nie luister nie, maar hulle het hom verstoot en met hulle harte na Egipte teruggekeer	",
"	40 toe hulle vir Aäron gesê het: Maak vir ons gode wat voor ons uit sal trek; want hierdie Moshè wat ons uit die Aarde van Egipte uitgelei het, ons weet nie wat van hom geword het nie.	",
"	41 En hulle het in daardie dae ’n kalf gemaak en aan die afbeelding ’n slagdier gebring en hulle in die werke van hulle hande verbly.	",
"	42 Maar Elohim het Hom afgewend en hulle oorgegee om die leër van die Hemele te dien, soos geskrywe is in die Boek van die Profete: Het julle aan My slagdiere en spysbydraes gebring veertig jaar lank in die wildernis, o huis van JisraEl? [Amos 5:25]	",
"	43 Ja, julle het die takskuiling van julle koning gedra en Kewan, julle Ster, julle god, die afbeelding wat julle vir julself gemaak het om hulle te aanbid. En Ek sal julle anderkant Damaskus [in ballingskap] wegvoer. [Amos 5:26,27]	",
"	44 Die Tent van die Getuienis was onder ons vaders in die wildernis, soos Hy wat met Moshè gespreek het, hom bevel gegee het om hom te maak volgens die afbeelding wat hy gesien het.	",
"	45 En ons vaders het hom ontvang en met JeHôWshua ingebring in die besitting van die nasies wat Elohim voor ons vaders uitgedryf het, tot op die dae van Dawid	",
"	46 wat Barmhartigheid gevind het voor Elohim en gevra het om ’n woonplek vir die Elohey van Jakob te verkry.	",
"	47 En Salomo het ’n Huis vir Hom gebou.	",
"	48 Maar die Hoogste El woon nie in tempels wat met hande gemaak is nie, soos die Profeet sê:	",
"	49 Die Hemele is My Troon en die Aarde die Voetbank van My voete. Watter soort Huis sal julle vir My bou, sê JaHWeH, of hoedanig is die Plek van My rus? [Génesis 1:1; 1 Kronieke 28:2; JeshaJaH 66:1, 2; Handelinge 7:49; MattithJaHûW 5:35]	",
"	50 Het My Hand nie al hierdie dinge gemaak nie?	",
"	51 Julle hardnekkiges en onbesnedenes van hart en ore, julle weerstaan altyd die Gees van die Apartheid; net soos julle vaders, so ook julle.	",
"	52 Watter een van die Profete het julle vaders nie vervolg nie? Ja, hulle het dié gedood wat vooraf die koms verkondig het van die Regverdige, van wie julle nou verraaiers en moordenaars geword het;	",
"	53 julle wat die Wet deur die beskikkinge van Boodskappers ontvang het en tog nie onderhou het nie!	",
"	54 En toe hulle dit hoor, was hulle woedend in hul harte en het teen hom op die tande gekners.	",
"	55 Maar hy was vol van die Gees van die Apartheid en het die oë na die Hemele gehou en die Glansrykheid van Elohim gesien en JaHWèshua wat staan aan die regterkant van Elohim.	",
"	56 En hy het gesê: Kyk, ek sien die Hemele geopend en die Seun van die adam aan die regterkant van die Elohim staan.	",
"	57 Maar hulle het met ’n groot stem geskreeu en hulle ore toegestop en soos een man op hom aangestorm.	",
"	58 En hulle het hom buitekant die stad uitgewerp en hom gestenig; en die getuies het hulle klere neergelê by die voete van ’n jongman met die naam van Saulus.	",
"	59 En hulle het Stéfanus gestenig terwyl hy uitroep en sê: My Meester JaHWèshua, ontvang my gees!	",
"	60 En hy het op sy knieë neergeval en met ’n groot stem uitgeroep: JaHWeH, reken hulle hierdie oortreding nie toe nie! En met dié woorde het hy ontslaap.	",
		

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '8',
content: [
		
"	1 EN Saulus het ook sy vermoording goedgekeur. En daar het in dié tyd ’n groot vervolging teen die gemeente in Jerusalem ontstaan, en almal is verstrooi oor die streke van JeHûWdah en Samaría, behalwe die Apostels.	",
"	2 En toegewyde manne het Stéfanus begrawe en ’n groot rou oor hom bedrywe.	",
"	3 Maar Saulus het die gemeente verwoes en in die huise gegaan en manne en vroue uitgesleep en in die gevangenis oorgelewer.	",
"	4 En die wat verstrooi was, het die Aarde deurgegaan en die Woord van die goeie nuus verkondig.	",
"	5 En Filippus het afgekom in ’n stad van Samaría en die Gesalfde aan hulle verkondig.	",
"	6 En die skare het eendragtig ag gegee op die woorde van Filippus toe hulle dit hoor en die tekens sien wat hy doen.	",
"	7 Want uit baie van die wat geeste van besoedeling  gehad het, het die geeste uitgegaan terwyl hulle met ’n groot stem skreeu; en baie wat lam en kreupel was, het gesond geword.	",
"	8 En daar was groot blydskap in daardie stad.	",
"	9 En ’n sekere man met die naam van Simon het vantevore in die stad met towery omgegaan en die bevolking van Samaría verbyster deur te sê dat hy iets besonders was.	",
"	10 En almal, klein en groot, het hom aangehang en gesê: Hy is die groot Krag van Elohim.	",
"	11 En hulle het hom aangehang, omdat hy hulle ’n geruime tyd deur sy towerye verbyster het.	",
"	12 Maar toe hulle Filippus geglo het, wat die goeie nuus aangaande die Koninkryk van Elohim en die Naam van JaHWèshua die Gesalfde verkondig het, is hulle gewas/gedoop, manne sowel as vroue.	",
"	13 En Simon het ook self gelowig geword, en nadat hy gewas/gedoop is, gedurig by Filippus gebly; en hy was verbaas toe hy die tekens en groot kragte sien gebeur.	",
"	14 En toe die Apostels in Jerusalem hoor dat Samaría die Woord van die Elohim aangeneem het, het hulle Petrus en JeHôWganan na hulle gestuur.	",
"	15 Húlle het afgekom en vir hulle gebid, dat hulle die Gees van die Apartheid mag ontvang,	",
"	16 want Sy het toe nog op niemand van hulle geval nie, maar hulle was net gewas/gedoop in die Naam van hulle Meester JaHWèshua.	",
"	17 Hulle het hul toe die hande opgelê, en hulle het die Gees van die Apartheid ontvang.	",
"	18 En toe Simon sien dat deur die handoplegging van die Apostels die Gees van die Apartheid gegee word, het hy hulle geld aangebied	",
"	19 en gesê: Gee aan my ook hierdie Mag, sodat elkeen wat ek die hande oplê, die Gees van die Apartheid kan ontvang.	",
"	20 Maar Petrus sê vir hom: Mag jou geld saam met jou vergaan, omdat jy gedink het om die Gawe van Elohim deur geld te verkry. [Spreuke 17:16]	",
"	21 Jy het geen deel of lot in hierdie saak nie, want jou hart is nie reg voor Elohim nie.	",
"	22 Bekeer jou dan van hierdie besoedeling van jou, en bid Elohim of die gedagte van jou hart jou miskien vergewe mag word.	",
"	23 Want ek sien dat jy in ’n gal van bitterheid en bande van Ongeregtigheid is.	",
"	24 Maar Simon het geantwoord en gesê: Bid julle tot die Meester vir my, sodat niks van wat julle gesê het, oor my mag kom nie.	",
"	25 Nadat hulle dan kragtig getuig en die Woord van JaHWeH gespreek het, het hulle na Jerusalem teruggegaan en die goeie nuus aan baie dorpe van die Samaritane verkondig.	",
		
		
"	26 EN ’n Boodskapper van JaHWeH het met Filippus gespreek en gesê: Staan op en gaan na die suide op die pad wat afloop van Jerusalem na Gasa. Dit is ’n eensame pad.	",
"	27 Toe het hy opgestaan en gegaan. En daar was ’n man van Ethiópië, ’n hofdienaar, ’n hoë amptenaar onder Kandacé, die koningin van die Ethiópiërs, wat oor al haar skatte was en na Jerusalem gekom het om te aanbid.	",
"	28 En hy was op die terugreis en het op sy wa gesit en die Profeet JeshaJaHûW gelees.	",
"	29 Toe sê die Gees vir Filippus: Gaan daarheen en bly by daardie wa.	",
"	30 En Filippus het daarheen gehardloop en hom die Profeet JeshaJaHûW hoor lees; en hy sê: Verstaan u wel wat u lees?	",
"	31 En hy antwoord: Hoe kan ek tog as niemand my die Weg wys nie? Toe vra hy Filippus om op te klim en by hom te kom sit.	",
"	32 En die gedeelte van die Skrif wat hy besig was om te lees, was dit: Soos ’n lam wat na die slagplek gelei word en soos ’n ooi wat stom is voor haar skeerders - ja, Hy het Sy Mond nie oopgemaak nie. [JeshaJaH 53:7]	",
"	33 In Sy vernedering is Sy oordeel weggeneem, en wie sal Sy geslag beskrywe? Want Sy lewe word van die Aarde weggeneem.	",
"	34 En die hofdienaar antwoord en sê vir Filippus: Ek bid u, van wie sê die Profeet dit, van homself of van iemand anders?	",
"	35 En Filippus het sy mond geopen en van hierdie Skrif af begin en die goeie nuus van JaHWèshua aan hom verkondig.	",
"	36 En terwyl hulle voortreis op die pad, kom hulle by water; en die hofdienaar sê vir hom: Daar is water; wat verhinder my om gewas/gedoop te word?	",
"	37 Toe sê Filippus: As u glo met u hele hart, is dit geoorloof. En hy antwoord en sê: Ek glo dat JaHWèshua die Gesalfde, die Seun van JaHWeH is. {Nota: hierdie vers is uit die Afrikaanse 1983-Vertaling verwyder.}	",
"	38 En hy het beveel dat die wa moes stilhou; en hulle het altwee in die water afgeklim, Filippus en die hofdienaar; en hy het hom gewas/gedoop.	",
"	39 En toe hulle uit die water opklim, het die Gees van JaHWeH Filippus skielik weggevoer, en die hofdienaar het hom nie meer gesien nie, want hy het sy weg met blydskap gereis.	",
"	40 Maar Filippus is in Asdod gevind. En hy het die Aarde deurgegaan en die goeie nuus verkondig in al die stede, totdat hy in Cesaréa gekom het.	",
		

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '9',
content: [
		
"	1 MAAR Saulus, wat nog dreiging en moord geblaas het teen die studente van JaHWeH, het na die hoëpriester gegaan	",
"	2 en van hom briewe gevra aan die vergaderings in Damaskus, sodat as hy mense sou vind wat van die Weg was, manne sowel as vroue, hy hulle geboeid na Jerusalem kon bring. [Psalm 18:31]	",
"	3 En toe hy op sy reis naby Damaskus kom, omstraal hom skielik ’n lig van die Hemele af;	",
"	4 en hy val op die Aarde en hoor ’n stem vir hom sê: Saul, Saul, waarom vervolg jy My?	",
"	[5 En hy sê: Wie is U, Meester? En die Meester antwoord: Ek is JaHWèshua wat jy vervolg. Dit is hard vir jou om teen die prikkels te skop.	",
"	6 En terwyl hy bewe en verbaas was, sê hy: Meester, wat wil U hê moet ek doen? En JaHWèshua antwoord hom: Staan op en gaan na die stad, en dit sal jou gesê word wat jy moet doen.]	",
		
"	7 En die manne wat saam met hom op pad was, het sprakeloos gestaan terwyl hulle wel die stem hoor, maar niemand sien nie.	",
"	8 Toe staan Saulus van die grond af op, en alhoewel sy oë oop was, het hy niemand gesien nie; en hulle het hom aan die hand gelei en in Damaskus ingebring.	",
"	9 En drie dae lank het hy niks gesien nie, en niks geëet of gedrink nie.	",
"	10 En daar was ’n student in Damaskus met die naam van Ananías; en JaHWeH het vir hom in ’n gesig gesê: Ananías! En hy antwoord: Hier is ek, my Meester.	",
"	11 Toe sê JaHWeH vir hom: Staan op en gaan na die straat wat genoem word Reguit, en vra in die huis van Judas na ’n man met die naam van Saulus van Tarsus, want kyk, hy bid;	",
"	12 en hy het in ’n gesig ’n man met die naam van Ananías sien inkom en hom die hande oplê, sodat hy weer kon sien.	",
"	13 Maar Ananías antwoord: Meester, ek het van baie mense aangaande hierdie man gehoor hoeveel kwaad hy U Apartes in Jerusalem aangedoen het;	",
"	14 en hy het hier volmag van die owerpriesters om almal te boei wat U Naam aanroep.	",
"	15 Maar JaHWèshua sê vir hom: Gaan, want hy is vir My ’n uitverkore werktuig om My Naam te dra voor nasies en konings en die kinders van JisraEl.	",
"	16 Want Ek sal hom toon hoeveel hy vir My Naam moet ly.	",
"	17 En Ananías het gegaan en in die huis gekom en hom die hande opgelê en gesê: Saul, broeder, JaHWèshua het my gestuur, naamlik die Meester wat aan jou verskyn het op die pad waarmee jy gekom het, sodat jy weer kan sien en met die Gees van die Apartheid vervul word.	",
"	18 En dadelik het daar iets soos skille van sy oë afgeval, en hy kon onmiddellik weer sien; en hy het opgestaan en is gewas/gedoop.	",
"	19 En nadat hy voedsel gebruik het, het hy weer sterk geword. En Saulus was ’n paar dae saam met die studente in Damaskus.	",
"	20 En hy het dadelik die Gesalfde in die vergaderings verkondig, dat Hy die Seun van Elohim is.	",
"	21 En almal wat hom gehoor het, was verbaas en het gesê: Is hy nie die man wat in Jerusalem uitgeroei het die wat hierdie Naam aanroep, en hier gekom het met die doel om hulle geboeid na die owerpriesters te bring nie?	",
"	22 Maar Saulus het al meer krag ontvang en die manne van JeHûWdah wat in Damaskus woon, in die war gebring deur te leer: Ek is die Gesalfde.1 [Psalm 37:35]	",
"	23 En ná geruime tyd het die manne van JeHûWdah beraadslaag om hom om te bring.	",
"	24 En hulle plan het aan Saulus bekend geword. En hulle het die poorte dag en nag bewaak, dat hulle hom kon ombring;	",
"	25 maar die studente het hom geneem en in die nag deur die muur neergelaat deur hom in ’n mandjie te laat afsak.	",
"	26 En toe Saulus in Jerusalem aankom, het hy probeer om by die studente aan te sluit; maar almal was vir hom bang, omdat hulle nie geglo het dat hy ’n student was nie.	",
"	27 Maar Bárnabas het hom geneem en na die apostels gebring en hulle vertel hoe hy op die pad vir JaHWèshua gesien het en dat Hy met hom gespreek het, en hoe hy in Damaskus vrymoediglik in die Naam van JaHWèshua gespreek het.	",
"	28 En hy het saam met hulle in en uitgegaan in Jerusalem	",
"	29 en vrymoediglik gespreek in die Naam van die Meester JaHWèshua, en ook met die Griekssprekende manne van JeHûWdah gepraat en geredetwis, maar hulle het probeer om hom dood te maak.	",
"	30 En toe die broeders dit agterkom, het hulle hom na Cesaréa afgebring en hom na Tarsus weggestuur.	",
"	31 En die gemeentes deur die hele JeHûWdah en Galiléa en Samaría het Vrede gehad; en terwyl hulle opgebou is en gewandel het in die Vrees van JaHWeH en die vertroosting van die Gees van die Apartheid, het hulle vermeerder.	",
"	32 En onderwyl Petrus oral rondgaan, het hy ook gekom by die Apartes wat in Lidda woon	",
"	33 en hy het daar ’n man gevind met die naam van Enéas, wat al agt jaar bedlêend en verlam was.	",
"	34 En Petrus sê vir hom: Enéas, JaHWèshua die Gesalfde maak jou gesond, staan op en maak jou bed op! En hy het dadelik opgestaan.	",
"	35 En al die inwoners van Lidda en Saron het hom gesien en hulle tot die Meester bekeer.	",
"	36 En in Joppe was daar ’n sekere student met die naam van Tsabíta, wat, as dit [in Grieks] vertaal word beteken Dorkas. Sy was oorvloedig in goeie werke en aalmoese wat sy gedoen het.	",
"	37 En in dié dae het sy siek geword en gesterwe, en hulle het haar gewas en in ’n bovertrek neergelê.	",
"	38 En omdat Lidda naby Joppe was en die studente gehoor het dat Petrus daar was, het hulle twee manne na hom gestuur wat hom moes smeek dat hy sonder uitstel na hulle moet oorkom.	",
"	39 En Petrus het opgestaan en saam met hulle gegaan. En toe hy daar kom, bring hulle hom in die bovertrek; en al die weduwees kom by hom staan en ween en wys hom die onder- en bo-klere wat Dorkas alles gemaak het toe sy nog by hulle was.	",
"	40 En Petrus het almal buitentoe gestuur en neergekniel en gebid. En hy het hom na die liggaam gedraai en gesê: Tsabíta, staan op! En sy het haar oë oopgemaak; en toe sy Petrus sien, het sy regop gesit.	",
"	41 En hy gee haar sy hand en laat haar opstaan. Daarop roep hy die Apartes en die weduwees en stel haar lewendig voor hulle.	",
"	42 En dit het bekend geword in die hele Joppe, en baie het in die Meester geglo.	",
"	43 En hy het ’n geruime tyd in Joppe gebly by ’n sekere Simon, ’n leerlooier.	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '10',
content: [
		
"	1 EN daar was in Cesaréa ’n man met die naam van Cornelius, ’n hoofman oor honderd van die sogenaamde Italiaanse leërafdeling.	",
"	2 Hy met sy hele huis was opreg en het Elohim gevrees en het baie aalmoese aan die volk gegee en was altyddeur in die gebed tot Elohim.	",
"	3 Hy het duidelik in ’n gesig omtrent die negende uur van die dag ’n Boodskapper van Elohim na hom sien inkom en vir hom sê: Cornelius!	",
"	4 En hy het die oë op hom gehou en vol vrees gesê: Wat is dit, my meester? Toe antwoord hy hom: Jou gebede en jou aalmoese het voor Elohim in gedagtenis gekom.	",
"	5 Stuur dan nou manne na Joppe en laat vir Simon haal wat ook Petrus genoem word.	",
"	6 Hy is tuis by ’n sekere Simon, ’n leerlooier, wie se huis by die see is. Hy sal jou sê wat jy moet doen.	",
"	7 En toe die Boodskapper wat met Cornelius gespreek het, weg was, roep hy twee van sy huisbediendes en ’n toegewyde soldaat van die wat altyd by hom was,	",
"	8 en vertel hulle alles en stuur hulle na Joppe.	",
"	9 En die volgende dag, terwyl hulle op pad was en naby die stad kom, het Petrus omtrent die sesde uur op die dak geklim om te bid;	",
"	10 en hy het baie honger geword en wou eet; en terwyl hulle besig was om klaar te maak, het daar ’n verrukking van sinne oor hom gekom:	",
"	11 hy sien die Hemele geopend en ’n voorwerp soos ’n groot laken na hom afdaal, wat aan die vier hoeke vasgebind is en op die Aarde neergelaat word.	",
"	12 Daarin was al die viervoetige diere van die Aarde en die wilde en kruipende diere en die voëls van die Hemele.	",
"	13 Toe kom daar ’n Stem na hom: Staan op, Petrus, slag en eet!	",
"	14 En Petrus sê: Nooit nie, my Meester, want ek het nooit iets vermeng of besoedeld geëet nie.	",
"	15 En weer het die Stem vir die tweede keer na hom gekom: Wat Elohim gesuiwer het, mag jy nie vuil ag nie.	",
"	16 En dit het drie maal gebeur, en die voorwerp is weer in die Hemele opgeneem.	",
"	17 En terwyl Petrus by homself daaroor verleë was wat die gesig tog kon beteken wat hy gesien het, staan die manne wat deur Cornelius gestuur was, daar by die poort en verneem na die huis van Simon.	",
"	18 En hulle roep en vra of Simon, wat ook Petrus genoem word, daar tuis is.	",
"	19 En terwyl Petrus nadink oor die gesig, sê die Gees vir hom: Daar is drie manne wat jou soek.	",
"	20 Staan dan op, klim af en gaan saam met hulle sonder om te twyfel, want Ek het hulle gestuur.	",
"	21 En Petrus het afgeklim na die manne wat deur Cornelius na hom gestuur was, en gesê: Kyk, dit is ek wat julle soek. Wat is die rede waarom julle hier is?	",
"	22 En hulle sê: Cornelius, ’n hoofman oor honderd, ’n regverdige man wat Elohim vrees, wat ’n goeie naam het by al die volke van JeHûWdah, het ’n openbaring van Elohim ontvang deur ’n Boodskapper van [‘n] Aparte, om u te laat haal na sy huis om te hoor wat u sal sê.	",
"	23 En hy het hulle binnegenooi en geherberg. En die volgende dag het Petrus saam met hulle afgereis, en enkele van die broers uit Joppe het met hom saamgegaan.	",
"	24 Die dag daarop het hulle in Cesaréa aangekom. En Cornelius was hulle te wagte, en hy het alreeds sy familie en besondere vriende bymekaargeroep.	",
"	25 Toe Petrus dan binnekom, het Cornelius hom tegemoetgegaan en aan sy voete neergeval en hom hulde bewys.	",
"	26 Maar Petrus het hom opgerig en gesê: Staan op, ek is self ook maar ’n adamiet.	",
"	27 En onderwyl hy met hom spreek, gaan hy binne en vind baie wat vergader het;	",
"	28 en hy sê vir hulle: Julle weet dat dit ongeoorloof is vir ’n man van JehûWdah om met iemand van ’n ander volk omgang te hê of hom te besoek; maar Elohim het my getoon dat ek geen adamiet[witman] vermeng of besoedel mag noem nie. [Deuteronómium 23:7]	",
"	29 Daarom het ek, toe ek gehaal is, gekom sonder om teë te spreek. Ek vra dan om watter rede julle my laat haal het.	",
"	30 En Cornelius sê: Vier dae gelede was ek besig om te vas tot op hierdie uur, en die negende uur het ek in my huis gebid,	",
"	31 en meteens staan daar ’n Man voor my in ’n glansende kleed en sê: Cornelius, jou gebed is verhoor en jou aalmoese is voor Elohim in herinnering gebring.	",
"	32 Stuur dan na Joppe en laat Simon haal wat ook Petrus genoem word. Hy vertoef in die huis van Simon, ’n leerlooier, by die see; as hy kom, sal hy met jou spreek.	",
"	33 Ek het toe op die daad na u gestuur, en u het goed gedoen om te kom. Ons is dan nou almal voor die Aangesig van die Elohim aanwesig om alles te hoor wat deur JaHWeH aan u opgedra is.	",
"	34 En Petrus het sy mond geopen en gesê: Ek sien waarlik dat Elohim geen aannemer van die persoon is nie,	",
"	35 maar dat in elke nasie die een wat HOM vrees en geregtigheid doen, HOM welgevallig is.	",
"	36 Dit is die Woord wat HY gestuur het aan die kinders van JisraEl toe HY die goeie nuus van Vrede verkondig het deur JaHWèshua die Gesalfde - Hy is Meester van almal.	",
"	37 Julle weet van die saak wat deur die hele JeHûWdah gebeur het en van Galiléa af begin het, na die wassing/doop wat JeHôWganan verkondig het,	",
"	38 met betrekking tot JaHWèshua van Násaret, hoe Elohim Hom gesalf het met die Gees van die Apartheid en met Krag. Hy het die Aarde deurgegaan, goed gedoen en almal genees wat onder die mag van die Satan was, omdat die Elohim met Hom was.	",
"	39 En ons is getuies van alles wat Hy gedoen het in die Aarde van JeHûWdah en in Jerusalem. En hulle het Hom omgebring deur Hom aan ’n hout op te hang.	",
"	40 Hom het Elohim op die derde dag opgewek en beskik dat Hy sou verskyn	",
"	41 nie aan die hele volk nie, maar aan getuies wat deur Elohim vantevore verkies is, aan ons wat met Hom saam geëet en gedrink het nadat Hy uit die dode opgestaan het.	",
"	42 En Hy het ons bevel gegee om aan die volk te verkondig en met Krag te betuig dat dit Hy is wat deur Elohim bestem is as Regter van lewende en dode.	",
"	43 Aangaande Hom getuig al die Profete dat elkeen wat in Hom glo, vergifnis van oortredinge deur Sy Naam ontvang.	",
"	44 En toe Petrus nog besig was om hierdie woorde te spreek, het die Gees van die Apartheid op almal geval wat die woord gehoor het.	",
"	45 En die gelowiges uit die Besnydenis, almal wat saam met Petrus gekom het, was verbaas dat die gawe van die Gees van die Apartheid ook op die nasies uitgestort is.	",
"	46 Want hulle het gehoor hoe hulle in tale spreek en Elohim groot maak. Toe het Petrus begin spreek:	",
"	47 Niemand kan tog die water weghou, sodat hierdie mense, wat net soos ons die Gees van die Apartheid ontvang het, nie gewas/gedoop word nie?	",
"	48 En hy het beveel dat hulle gewas/gedoop moet word in die Naam van JaHWeH. Toe het hulle hom gevra om nog ’n paar dae te bly.	",
		

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '11',
content: [
		
"	1 EN die Apostels en die broers wat in JeHûWdah was, het gehoor dat die verstrooides ook die Woord van die Elohim aangeneem het.	",
"	2 En toe Petrus opgaan na Jerusalem, het die wat uit die Besnydenis was, met hom getwis	",
"	3 en gesê: By onbesnede manne het jy in die huis gegaan en saam met hulle geëet.	",
"	4 En Petrus het begin en vir hulle die loop van die saak uiteengesit en gesê:	",
"	5 Ek was in die stad Joppe in die gebed, en in ’n verrukking van sinne het ek ’n gesig gesien: ’n voorwerp het uit die Hemele neergedaal soos ’n groot laken wat aan die vier hoeke uit die Hemele neergelaat word, en dit het tot by my gekom.	",
"	6 En toe ek die oë daarop hou en dit waarneem, sien ek die viervoetige diere van die Aarde en die wilde en die kruipende diere en die voëls van die Hemele.	",
"	7 En ek hoor ’n stem vir my sê: Staan op, Petrus, slag en eet!	",
"	8 Maar ek antwoord: Nooit nie, my Meester, want niks vermeng of besoedeld het ooit in my mond ingegaan nie.	",
"	9 En die Stem het die tweede keer my uit die Hemele geantwoord: Wat die Elohim gesuiwer het, mag jy nie vuil ag nie.	",
"	10 En dit het drie maal gebeur en alles is weer opgetrek in die Hemele.	",
"	11 En dadelik staan daar drie manne voor die huis waar ek in was, wat van Cesaréa na my gestuur was.	",
"	12 En die Gees het vir my gesê dat ek saam met hulle moes gaan sonder om te twyfel. En saam met my het ook hierdie ses broers gegaan, en ons het in die huis van die man ingegaan.	",
"	13 En hy het ons vertel hoe hy die Boodskapper in sy huis sien staan het en vir hom sê: Stuur manne na Joppe en laat vir Simon haal wat ook Petrus genoem word;	",
"	14 hy sal woorde tot jou spreek waardeur jy en jou hele huis gered sal word.	",
"	15 En toe ek begin spreek, het die Gees van die Apartheid op hulle geval soos ook op ons in die begin.	",
"	16 En ek het die Woord van JaHWèshua, die Meester onthou, hoe Hy gesê het: JeHôWganan het in water gewas/gedoop, maar julle sal met die Gees van die Apartheid gewas/gedoop word.	",
"	17 As Elohim dan aan hulle dieselfde gawe gegee het soos aan ons wat in die Meester, JaHWèshua, die Gesalfde geglo het, wie was ek dan, dat ek die Elohim kon weerstaan?	",
"	18 En toe hulle dit hoor, het hulle geswyg en die Elohim vereer en gesê: So het Elohim dan ook aan die [verstrooide] nasies die bekering tot die lewe geskenk.	",
		
		
"	19 DIE wat dan verstrooi was deur die verdrukking wat oor Stéfanus ontstaan het, het die Aarde deurgegaan tot by Fenícië en Ciprus en Antiochíë sonder om tot iemand die woord te spreek, behalwe tot die manne van JeHûWdah alleen.	",
"	20 En daar was sommige van hulle, Cipriese en Cirenése manne, wat in Antiochíë gekom het en met die Helleniste gepraat en die goeie nuus van die Meester JaHWèshua verkondig het.	",
"	21 En die Hand van JaHWeH was met hulle, en ’n groot getal het gelowig geword en hulle tot die Meester bekeer.	",
"	22 En die berig hiervan het die gemeente wat in Jerusalem was, ter ore gekom en hulle het Bárnabas afgestuur om die Aarde deur te gaan tot by Antiochíë.	",
"	23 Toe hy daar kom en die Barmhartigheid van die Elohim sien, was hy bly en het almal vermaan om met hartlike voorneme aan die Meester getrou te bly;	",
"	24 want hy was ’n goeie man en vol van die Gees van die Apartheid en Geloof; en ’n aansienlike skare is aan die Meester toegebring.	",
"	25 Toe vertrek Bárnabas na Tarsus om Saulus te soek, en toe hy hom kry, het hy hom na Antiochíë gebring.	",
"	26 En hulle het ’n hele jaar lank in die gemeente saam vergader en aan ’n aansienlike skare onderwys gegee; en dié volgelinge is in Antiochíë vir die eerste keer Christene genoem.	",
"	27 En in dié dae het daar Profete van Jerusalem na Antiochíë afgekom.	",
"	28 En een van hulle met die naam van Agabus het opgestaan en deur die Gees van die Apartheid te kenne gegee dat daar ’n groot hongersnood oor die hele wêreld sou kom, wat ook gekom het onder keiser Claudius.	",
"	29 En dié volgelinge het besluit dat iedereen van hulle na sy vermoë iets sou stuur tot versorging van die broers wat in JeHûWdah woon.	",
"	30 En dit het hulle ook gedoen en dit deur Bárnabas en Saulus aan die oudstes gestuur.	",

]
},
{
book: 'Handelinge_Van_Die_Apostels',
chapter: '12',
content: [
		
"	1 EN omtrent daardie tyd het koning Herodes sy hande geslaan aan sommige uit die gemeente om hulle kwaad aan te doen.	",
"	2 En hy het Jakobus, die broer van JeHôWganan, met die swaard omgebring.	",
"	3 En toe hy sien dat dit die Jode welgevallig was, het hy verder ook Petrus in hegtenis geneem. En dit was die dae van die Ongesuurde Brode.	",
"	4 Toe hy hom dan gegryp het, het hy hom in die gevangenis gesit en oorgegee aan vier wagte, elkeen van vier soldate, om hom te bewaak, met die bedoeling om hom ná die Pasga voor die volk te bring.	",
"	5 So is Petrus dan in die gevangenis bewaak; maar daar het ’n aanhoudende gebed tot Elohim deur die gemeente vir hom opgegaan.	",
"	6 En toe Herodes hom wou voorbring, het Petrus in daardie nag tussen twee soldate geslaap, met twee kettings geboei, en wagte voor die deur het die gevangenis bewaak.	",
"	7 En meteens staan daar ’n Boodskapper van JaHWeH by hom, en ’n lig skyn in die gevangenis. Toe slaan hy Petrus op die sy, maak hom wakker en sê: Staan gou op! En die boeie het van sy hande afgeval.	",
"	8 En die Boodskapper sê vir hom: Omgord jou en trek jou skoene aan! En hy het dit gedoen. Verder sê hy vir hom: Gooi jou bo-kleed om en volg my!	",
"	9 En hy het uitgegaan en hom gevolg; en hy het nie geweet dat wat deur die Boodskapper plaasgevind het, werklikheid was nie, maar hy het gemeen dat hy ’n gesig sien.	",
"	10 En toe hulle by die eerste en die tweede wag verbygegaan het, kom hulle by die ysterpoort wat na die stad lei, en hy het vanself vir hulle oopgegaan. En hulle het buitekant gekom en een straat ver gegaan, en dadelik het die Boodskapper hom verlaat.	",
"	11 Toe kom Petrus tot homself en sê: Nou weet ek waarlik dat die Elohey Sy Boodskapper gestuur en my gered het uit die hand van Herodes en uit al die verwagtinge van JeHûWdah.	",
"	12 En nadat dit vir hom duidelik geword het, kom hy by die huis van Mirjam, die moeder van JeHôWganan wat ook Markus genoem word, waar baie in die gebed bymekaar was.	",
"	13 En toe Petrus aan die deur van die poort klop, het ’n diensmeisie met die naam van Rhodé gegaan om te hoor wie daar was.	",
"	14 En sy het die stem van Petrus herken en van blydskap die poort nie oopgemaak nie, maar na binne gehardloop en vertel dat Petrus voor die poort staan.	",
"	15 Maar hulle sê vir haar: Jy is van jou verstand af. Maar sy het volgehou dat dit so is. Daarop sê hulle: Dit is sy Boodskapper.	",
"	16 En Petrus het aangehou met klop; en toe hulle oopmaak, sien hulle hom en was verbaas.	",
"	17 Maar hy het hulle met die hand gewink om stil te bly en aan hulle vertel hoe Elohim hom uit die gevangenis uitgelei het. En hy sê: Vertel dit aan Jakobus en die broers. En hy het uitgegaan en na ’n ander plek vertrek.	",
"	18 En toe dit dag geword het, was daar onder die soldate geen kleine opskudding oor wat van Petrus geword het nie.	",
"	19 Daarop het Herodes hom gesoek en nie gekry nie, en die wagte onder verhoor geneem en bevel gegee dat hulle tereggestel moes word. En hy het van JeHûWdah weggegaan na Cesaréa en daar gebly.	",
"	20 En Herodes was verbitterd teen die Tiriërs en Sidóniërs. En hulle het eenparig na hom gekom, en nadat hulle Blastus, die koning se hofdienaar, omgepraat het, vrede gevra, omdat hulle deel van die Aarde onderhoud uit die koning s’n ontvang het.	",
"	21 En op ’n bepaalde dag het Herodes ’n koninklike kleed aangetrek en op die troon gaan sit en hulle toegespreek.	",
"	22 Daarop het die volk hom toegeroep: ’n Stem van ’n Elohim en nie van ’n adamiet nie!	",
"	23 En onmiddellik het ‘n Boodskapper van JaHWeH hom getref, omdat hy die Eer nie aan Elohim gegee het nie; en hy is deur wurms verteer en het gesterwe.	",
"	24 Maar die Woord van Elohim het gegroei en toegeneem.	",

]
}
];
