const hebreërsChapters = [

{
book: 'Hebreërs',
chapter: '1',
content: [


"	1 NADAT Elohim baiekeer en op baie maniere in die ou tyd gespreek het tot die vaders deur die Profete, het HY in hierdie laaste dae tot Ons gespreek deur die Seun	",
"	2 wat HY as Erfgenaam van alles aangestel het, deur wie HY ook die Ewigheid gemaak het.	",
"	3 Hy, wat die verglansing is van SY Glansrykheid en die ewebeeld van SY Wese en alle dinge dra deur die Woord van SY Krag, nadat Hy deur Homself die wassing van Ons oortredinge bewerk het, het gaan sit aan die Regterkant van die MAJESTEIT in die hoogte,	",
"	4 terwyl Hy soveel uitnemender geword het as die Boodskappers namate Hy ’n voortrefliker naam geërf het as hulle.	",
"	5 Want aan wie van die Boodskappers het HY ooit gesê: U is MY Seun, vandag het EK Self U gegenereer? [Psalm 2:7] en weer: EK sal vir Hom ’n Vader wees, en Hy sal vir MY ’n Seun wees? [2 ShemuEl 7:14]	",
"	6 En wanneer HY weer die Eersgeborene in die wêreld inbring, sê HY: En al die Boodskappers van Elohim moet Hom vereer.	",
"	7 En van die Boodskappers sê HY wel: Wat van Sy Boodskappers Geeste maak, Sy dienaars ‘n Verterende Vuur. [Psalm 104:4]	",
"	8 maar van die Seun: U Troon, o El, is tot in alle ewigheid, die Septer van U Koninkryk is ’n regverdige Septer;	",
"	9 U het Geregtigheid lief en haat Ongeregtigheid. Daarom het, o Elohim, U Elohim U gesalf met Vreugde-olie bo U metgeselle; [Psalm 45:7]	",
"	10 en: JaHWeH, in die voortyd het U die Aarde gegrondves en die Hemele is die werk van U Hande. [Psalm 102:25]	",
"	11 Hulle sal vergaan, maar U sal bly; ja, hulle almal sal soos ‘n kleed verslyt,	",
"	12 U verwissel hulle soos ’n kledingstuk, en hulle verdwyn. [Psalm 102:26] Maar U bly dieselfde, en U jare het geen einde nie. [Psalm 102:27]	",
"	13 En aan watter een van die Boodskappers het HY ooit gesê: Sit aan MY regterkant totdat EK U vyande maak ’n Voetbank van U voete? [Psalm 110:1]	",
"	14 Is Hulle nie almal dienende Geeste wat vir diens uitgestuur word ter wille van die wat die Lossing sal beërwe nie?	",

]
},
{
book: 'Hebreërs',
chapter: '2',
content: [
		
"	1 DAAROM moet Ons des te meer ag gee op wat Ons gehoor het, dat Ons nie miskien wegdrywe nie.	",
"	2 Want as die woord deur Boodskappers gespreek, onwankelbaar was, en elke oortreding en ongehoorsaamheid regverdige vergelding ontvang het,	",
"	3 hoe sal Ons ontvlug as Ons so ’n groot Lossing veronagsaam wat, nadat dit eers deur die Meester verkondig is, aan Ons bevestig is deur die wat dit gehoor het,	",
"	4 terwyl Elohim ook nog saam getuig het deur tekens en wonders en allerhande kragtige dade en bedélinge van die Gees van die Apartheid volgens SY wil?	",
"	5 Want aan die Boodskappers het HY die toekomstige wêreld waarvan Ons spreek, nie onderwerp nie;	",
"	6 maar iemand het êrens getuig en gesê: Wat is die adamiet, dat U aan hom dink, of die Seun van die Adam, dat U Hom besoek? [Psalm 8:4]	",
"	7 U het Hom weinig tekort laat kom van die Elohim en Hom met Eer en Glansrykheid gekroon. U laat Hom heers oor die werke van U Hande, [Psalm 8:5]	",
"	8 U het alles onder Sy Voete gestel. [Psalm 8:6] Want in die onderwerping van alle dinge aan Hom het HY niks uitgesonder wat aan Hom nie onderworpe is nie. Maar nou sien Ons nog nie dat alle dinge aan Hom onderwerp is nie;	",
"	9 maar Ons sien Hom, naamlik JaHWèshua, wat weinig minder as die Elohim gemaak is, vanweë die lyde van die Dood met Eer en Glansrykheid gekroon, sodat Hy deur die Barmhartigheid van JaHWeH vir elkeen die dood sou smaak. [Psalm 8:5]	",
"	10 Want dit het Hom betaam, ter wille van Wie alle dinge en deur Wie alle dinge is, om baie kinders na die Glansrykheid te vervolmaak, as die Leidsman van hulle Lossing, self vervolmaak deur lyde . [2 Ezra 2:31]	",
"	11 Want Hy wat Apartheid instel, sowel as hulle wat apart gestel word, is almal uit EEN; om hierdie rede skaam Hy Hom nie om hulle broers te noem nie, [JeHôWganan 20:17, MattithJaHûW 25:40]	",
"	12 wanneer Hy sê: Ek wil U Naam aan My broers vertel, in die midde van die vergadering sal Ek U prys; [Psalm 22:22]	",
"	13 en verder: En ek sal wag op JaHWeH [JeshaJaH 8:17]; en verder: Hier is Ek en die kinders wat JaHWeH My gegee het. [JeshaJaH 8:18]	",
"	14 Aangesien die kinders dan vlees en bloed deelagtig is, het Hy dit ook op dieselfde manier deelagtig geword, sodat Hy deur die Dood hom tot niet kon maak wat mag oor die Dood het - dit is die Satan - [JeshaJaH 25:8]	",
"	15 en almal kon bevry wat hulle hele lewe lank uit vrees vir die Dood aan slawerny onderworpe was.	",
"	16 Want waarlik, Hy bekommer Hom nie oor die Boodskappers nie, maar oor die saad van Abraham bekommer Hy Hom. [JeshaJaH 41:8, 9]	",
"	17 Daarom moes Hy in alle opsigte aan Sy broers gelyk word, sodat Hy ’n barmhartige en getroue Hoëpriester kon wees in die dinge wat in betrekking tot Elohim staan, om die oortredinge van die volk te versoen.	",
"	18 Want deurdat Hy self onder versoeking gely het, kan Hy dié help wat versoek word.	",

]
},
{
book: 'Hebreërs',
chapter: '3',
content: [
		
"	1 DAAROM, broers van Apartheid, deelgenote van die Hemelse roeping, let op die Apostel en Hoëpriester van Ons profesie, die Gesalfde JaHWèshua,	",
"	2 wat getrou was aan HOM wat Hom aangestel het, net soos Moshè ook in sy hele huis.	",
"	3 Want Hy is meer Majesteit waardig geag as Moshè, namate hy wat die Huis gebou het, meer Eer het as die Huis; [ZekarJaH 6:12,13]	",
"	4 want elke huis word deur iemand gebou, maar HY wat alle dinge gebou het, is Elohim.	",
"	5 En Moshè was wel getrou in sy hele huis as ’n dienaar, om te getuig van wat nog gespreek sou word, [Númeri 12:7]	",
"	6 maar die Gesalfde as Seun oor Sy Huis. En Ons is Sy Huis as Ons net die vrymoedigheid en die roem van die hoop tot die einde toe onwrikbaar vashou.	",
"	7 Daarom, soos die Gees van die Apartheid spreek: Vandag as julle Sy Stem hoor,	",
"	8 verhard julle harte nie soos by Mériba (versoeking), soos op die dag van Massa (beproewing) in die wildernis nie, [Psalm 95:8]	",
"	9 waar julle vaders My versoek het, My beproef het, alhoewel hulle My werk vir veertig jaar gesien het. [Psalm 95:9]	",
"	10 Ek ’n afkeer gehad van [hierdie] geslag en gesê: Hulle is ’n volk met ’n dwalende hart, en hulle ken My Weë nie; [Psalm 95:10]	",
"	11 sodat Ek in My Woede gesweer het: Hulle sal in My rus nie ingaan nie. [Psalm 95:11]	",
"	12 Sorg daarvoor, broers, dat daar nie miskien in een van julle ’n besoedelde en wantrouige hart is deurdat hy van die lewende Elohim afvallig word nie.	",
"	13 Maar vermaan mekaar elke dag so lank as dit vandag genoem word, sodat niemand van julle deur die verleiding van die oortredinge verhard word nie.	",
"	14 Want Ons het metgeselle van die Gesalfde geword, as Ons net die begin van Ons vertroue tot die einde toe onwrikbaar vashou;	",
"	15 omdat daar gesê word: Vandag as julle Sy Stem hoor, verhard julle harte nie soos by Mériba (versoeking) nie. [Psalm 95:8]	",
"	16 Wie was dit dan wat gehoor het en Hom versoek het? Was dit nie almal wat onder leiding van Moshè uit Egipte gegaan het nie?	",
"	17 En op wie was Hy veertig jaar lank vertoornd? Was dit nie op die wat gemurmureer het, wie se lyke in die wildernis geval het nie? [Númeri 14:29]	",
"	18 En aan wie het Hy gesweer dat hulle in Sy rus nie sal ingaan nie, veral die wat wantrou. [Psalm 95:11]	",
"	19 En Ons sien dat hulle deur wantroue nie kon ingaan nie. [Psalm 78:22]	",

]
},
{
book: 'Hebreërs',
chapter: '4',
content: [
	
"	1 LAAT Ons dan vrees dat, terwyl die Belofte om in Sy rus in te gaan nog standhou, dit nie miskien sal blyk dat iemand van julle agtergebly het nie. [Psalm 95:11]	",
"	2 Want aan Ons is die goeie nuus ook verkondig net soos aan hulle; maar die prediking van die Woord het hulle nie gebaat nie, omdat dit by die hoorders nie met die Geloof verenig was nie.	",
"	3 Want Ons wat geglo het, gaan die rus in, soos Hy gesê het: Daarom het Ek in My Woede gesweer, hulle sal in My rus nie ingaan nie [Psalm 95:11] - alhoewel Sy werke van die grondlegging van die wêreld af volbring is.	",
"	4 Want Hy het êrens van die sewende dag so gespreek: En Elohim het op die sewende dag van al SY werke gerus;	",
"	5 en nou hier weer: Hulle sal in My rus nie ingaan nie. [Psalm 95:11]	",
"	6 Terwyl dit dan so is dat sommige daar ingaan, en diegene aan wie die Goeie Nuus eers verkondig is, deur ongehoorsaamheid nie ingegaan het nie,	",
"	7 bepaal Hy weer ’n sekere dag, naamlik vandag, as Hy soveel later deur Dawid spreek, soos gesê is: Vandag as julle Sy Stem hoor, verhard julle harte nie. [Psalm 95:7,8]	",
"	8 Want as JeHôWshua aan hulle rus gegee het, sou Hy nie van ’n ander dag daarná spreek nie.	",
"	9 Daar bly dus ’n Sabbatsrus oor vir die volk van Elohim;	",
"	10 want wie in Sy rus ingegaan het, rus ook self van sy werke soos Elohim van SYNE. [Génesis 2:2]	",
"	11 Laat Ons Ons dan beywer om in te gaan in dié rus, sodat niemand in dieselfde voorbeeld van ongehoorsaamheid mag val nie.	",
"	12 Want die Woord van Elohim is lewend en kragtig en skerper as enige tweesnydende swaard, en dring deur tot die skeiding van siel en gees en van gewrigte en murg, en is ’n beoordelaar van die oorlegginge en gedagtes van die hart. [JeshaJaH 49:2 ; JesegiEl 20:37]	",
"	13 En daar is geen skepsel onsigbaar voor Hom nie, maar alles is oop en bloot voor die Oë van Hom met wie Ons te doen het. [Spreuke 15:11]	",
		
		
"	14 TERWYL Ons dan ’n groot Hoëpriester het wat deur die Hemele deurgegaan het, naamlik JaHWèshua, die Seun van Elohim, laat Ons die belydenis vashou.	",
"	15 Want Ons het nie ’n Hoëpriester wat nie met Ons swakhede Medelye kan hê nie, maar een wat in alle opsigte versoek is net soos Ons, maar sonder oortredinge.	",
"	16 Laat Ons dan met vrymoedigheid na die Troon van Barmhartigheid gaan, sodat Ons Barmhartigheid kan verkry en Guns vind om op die regte tyd gehelp te word.	",

]
},
{
book: 'Hebreërs',
chapter: '5',
content: [
		
"	1 WANT elke hoëpriester wat uit die adamiete geneem word, tree ten behoewe van adamiete op in die dinge wat in betrekking tot Elohim staan, om bydraes en slagdiere vir die oortredinge, nader te bring	",
"	2 as een wat kan saamvoel met die onwetendes en dwalendes, omdat hy self ook met swakheid bevange is.	",
"	3 En daarom juis moet hy, net soos vir die volk, so ook homself naderbring vanweë die oortredinge. [Levítikus 4:3]	",
"	4 En niemand neem die waardigheid vir homself nie, maar hy wat deur JaHWeH geroep word, net soos Aäron. [Exodus 28:1]	",
"	5 So het die Gesalfde ook Homself nie verhoog om Hoëpriester te word nie, maar Hy het HOM verhoog wat vir Hom gesê het: U is MY Seun, vandag het EK U gegenereer. [Psalm 2:7]	",
"	6 Soos HY ook op ’n ander plek sê: U is Priester vir ewig volgens die Orde van Melgisédek. [Psalm 110:4]	",
"	7 Hy wat in die dae van Sy Vlees gebede en smekinge met sterk geroep en trane aan HOM nadergebring het wat Hom uit die Dood kon red, en ook verhoor is uit die angs -	",
"	8 Hy, al was Hy die Seun, het gehoorsaamheid geleer uit wat Hy gely het;	",
"	9 en nadat Hy vervolmaak is, het Hy vir almal wat HOM gehoorsaam is, ’n bewerker van ewige Lossing geword	",
"	10 en is deur Elohim genoem ’n Hoëpriester volgens die Orde van Melgisédek; [Psalm 110:4]	",
"	11 waaroor Ons veel te sê het wat swaar is om te verklaar, omdat julle traag geword het om te hoor.	",
"	12 Want hoewel julle vanweë die tyd leraars behoort te wees, het julle weer nodig dat ’n mens julle die eerste beginsels van die Woorde van Elohim moet leer, en julle het weer behoefte aan Melk en nie aan vaste spys nie. [Psalm 131:2]	",
"	13 Want elkeen wat Melk gebruik, is onervare in die Woord van Geregtigheid, omdat hy ’n kind is.	",
"	14 Maar vaste spys is vir hulle wat na volmaaktheid streef, vir die wat geestesvermoëns besit deur die gewoonte geoefen, om die egte van die verdraaide te onderskei.	",

]
},
{
book: 'Hebreërs',
chapter: '6',
content: [
		
"	1 DAAROM moet Ons nie bly by die begin van die prediking aangaande die Gesalfde nie, maar na die volmaaktheid voortgaan sonder om weer die fondament te lê van die bekering uit dooie werke en van die Geloof in Elohim,	",
"	2 van die leer van die wassing/doop en van die handoplegging en van die opstanding van die dode en van die ewige oordeel.	",
"	3 En dit sal Ons doen as die El dit toelaat.	",
"	4 Want dit is onmoontlik om die wat eenmaal verlig geword het en die Hemelse gawe gesmaak en die Gees van die Apartheid deelagtig geword het,	",
"	5 en die suiwer Woord van Elohim gesmaak het en die kragte van die ewigheid wat kom,	",
"	6 en afvallig geword het - om dié weer tot bekering te vernuwe, omdat hulle ten opsigte van hulleself die Seun van die Elohim weer folter en openlik tot skande maak.	",
"	7 Want die Aarde wat die reën indrink wat dikwels op haar val, en nuttige plante voortbring ter wille van hulle vir wie sy ook bewerk word, het deel aan die seën van die Elohim. [Psalm 65:9-11]	",
"	8 Maar as sy dorings en distels oplewer, deug sy nie en is naby die vervloeking - die einde van haar is verbranding.	",
"	9 Maar, geliefdes, Ons is aangaande julle van beter dinge oortuig, dinge wat saamhang met die Lossing, al spreek Ons ook so.	",
"	10 Want die Elohim is nie onregverdig om julle werk te vergeet nie en die liefdearbeid wat julle betoon het vir SY NAAM, omdat julle die Apartes gedien het en nog dien.	",
"	11 Maar Ons verlang dat elkeen van julle dieselfde ywer mag toon om te kom tot die volkome sekerheid van die hoop tot die einde toe;	",
"	12 sodat julle nie traag word nie, maar navolgers van hulle wat deur Geloof en lankmoedigheid Erfgename van die Belofte is. [Handelinge 1:4]	",
		
		
"	13 WANT toe Elohim aan Abraham die Belofte gegee het, het HY, omdat HY by geen meerdere kon sweer nie, by HOMSELF gesweer [Génesis 22:16]	",
"	14 en gesê: Voorwaar, EK sal jou ryklik seën en jou grootliks vermeerder. [Genesis 22:17]	",
"	15 En so het hy die Belofte verkry nadat hy geduldig gewag het.	",
"	16 Want adamiete sweer by een wat meer is, en die eed van bevestiging is vir hulle die einde van alle teëspraak.	",
"	17 Daarom het die Elohim, omdat HY nog kragtiger aan die Erfgename van die Belofte die onveranderlikheid van SY Raad wou toon, haar met ’n Eed gewaarborg;	",
"	18 sodat Ons deur twee onveranderlike dinge, waarin dit onmoontlik is dat die Elohim sou lieg, kragtige bemoediging kan hê, Ons wat ontvlug het, om vas te hou aan die hoop wat voorlê;	",
"	19 en Ons het Hom as ’n Anker van die siel wat veilig en vas is en ingaan tot binnekant die voorhangsel	",
"	20 waar JaHWèshua as voorloper vir Ons ingegaan het, Hy wat volgens die Orde van Melgisédek ’n Hoëpriester geword het vir ewig. [Psalm 110:4]	",

]
},
{
book: 'Hebreërs',
chapter: '7',
content: [
		
"	1 WANT hierdie Melgisédek was koning van Salem, priester van die Hoogste El, wat vir Abraham tegemoetgegaan het by sy terugkeer toe hy die konings verslaan het, en hom geseën het; [Génesis 14:18]	",
"	2 aan wie Abraham ook ’n tiende deel van alles gegee het - hy was in die eerste plek, volgens uitleg, Koning van Geregtigheid en dan ook Koning van Salem, dit is Koning van Vrede; [Openbaring van Henog 23:37]	",
"	3 sonder vader, sonder moeder, sonder geslagsregister, sonder begin van dae of lewens-einde, maar gelykgestel aan die Seun van die Elohim, bly Hy Priester altyddeur.	",
"	4 Let nou op hoe groot hierdie Man was, aan wie selfs Abraham, die aartsvader, ’n tiende van die [sy] beste [goed]gegee het.	",
"	5 Nou het hulle wat uit die seuns van Levi die priesterskap ontvang, wel ’n Gebod om, volgens die Wet, van die volk tiendes te neem, dit is van hulle broers, ofskoon hulle uit die lendene van Abraham voortgekom het;	",
"	6 maar Hy wat nie uit húlle Sy geslagsregister aflei nie, het van Abraham tiendes geneem en die besitter van die beloftes geseën.	",
"	7 Nou word sonder enige teëspraak die mindere deur die meerdere geseën.	",
"	8 En hier neem wel sterflike adamiete tiendes, maar dáár een van wie getuig word dat Hy lewe.	",
"	9 En, om so te sê, het ook Levi wat tiendes ontvang, deur Abraham tiendes gegee; [Númeri 18:21]	",
"	10 want hy was nog in die lendene van sy vader toe Melgisédek hom tegemoet gegaan het.	",
"	11 As daar dan rasegtheid deur die Levitiese priesterskap was - want met die oog daarop het die volk die Wet ontvang - waarom was dit nog nodig dat ’n ander priester moes opstaan volgens die Orde van Melgisédek en dat hy nie volgens die Orde van Aäron genoem word nie?	",
"	12 Want met verandering van die priesterskap kom daar noodsaaklik ook verandering aan die Wet;	",
"	13 omdat Hy met die oog op wie hierdie dinge gesê word, aan ’n ander stam behoort het waaruit niemand die altaar bedien het nie.	",
"	14 Want dit is volkome duidelik dat Onse Meester uit JeHûWdah voortgespruit het, en met betrekking tot hierdie stam het Moshè niks gesê van die priesterskap nie. [Génesis 49:8, 10]	",
"	15 En nog baie duideliker is dit as daar ’n ander priester opstaan na die ewebeeld van Melgisédek,	",
"	16 een wat dit geword het nie kragtens die Wet van ’n vleeslike Gebod nie, maar uit die Krag van die onvernietigbare lewe.	",
"	17 Want HY getuig: U is Priester vir ewig volgens die Orde van Melgisédek. [Psalm 110:4]	",
"	18 Want aan die een kant is daar die opheffing van dié voorafgaande Gebod weens haar swakheid en nutteloosheid,	",
"	19 omdat dié Wet niemand raseg gemaak het nie; maar aan die ander kant kom rasegtheid deur die invoering van ’n beter Hoop waardeur Ons tot die Elohim nader.	",
"	20 En vir sover sy nie sonder eedswering was nie, want hulle het sonder eedswering priesters geword,	",
"	21 maar Hy met eedswering deur die Een wat aan Hom gesê het: JaHWeH het gesweer en dit sal Hom nie berou nie: U is Priester vir ewig volgens die Orde van Melgisédek. [Psalm 110:4]	",
"	22 in sover het JaHWèshua van ’n beter Verbond Borg geword. [Psalm 119:122]	",
"	23 En hulle het wel priesters geword in ’n groot aantal, omdat hulle deur die Dood verhinder is om aan te bly;	",
"	24 maar Hy, omdat Hy vir ewig bly, besit ’n Priesterskap wat nie op ander oorgaan nie.	",
"	25 Daarom kan Hy ook volkome red die wat deur Hom tot Elohim gaan, omdat Hy altyd leef om vir hulle in te tree.	",
"	26 Want so ’n Hoëpriester was vir Ons gepas, een wat gewy, onskuldig, raseg, apart gestel van die oortreders is, en wat hoër as die Hemele geword het;	",
"	27 wat nie elke dag nodig het, soos die hoëpriesters, om eers vir sy eie oortredinge ‘n slagdier te bring en dan vir dié van die volk nie. Want dit het Hy net een maal gedoen toe Hy Homself nadergebring het.	",
"	28 Want die Wet stel as hoëpriesters aan adamiete met gebreke, maar die Woord van die Eedswering wat ná die Wet gekom het, het die Seun vir ewig vervolmaak.	",

]
},
{
book: 'Hebreërs',
chapter: '8',
content: [
		
"	1 DIE hoofsaak nou van wat Ons gesê het, is dít: Ons het so ’n Hoëpriester wat gaan sit het aan die regterkant van die Troon van die Majesteit in die Hemele,	",
"	2 ’n Bediener in die Plek van Apartheid en van die ware Tabernakel wat JaHWeH opgerig het en nie ’n adamiet nie.	",
"	3 Want elke hoëpriester word aangestel om bydraes en slagdiere nader te bring. Daarom moes Hy ook iets hê om nader te bring.	",
"	4 Want as Hy op Aarde was, sou Hy selfs geen priester wees nie, omdat dit die priesters is wat volgens die Wet die bydraes naderbring,	",
"	5 hulle wat ’n afbeeldsel en skaduwee van die Hemelse dinge bedien, soos Moshè ’n bevel van Elohim ontvang het toe hy die Tabernakel sou voltooi; want Hy het gesê: En kyk dat jy hom maak volgens die voorbeeld van hom wat jou op die berg getoon is. [Exodus 25:40]	",
"	6 Maar nou het Hy ’n voortrefliker bediening verkry vir sover Hy ook Middelaar is van ’n beter Verbond wat op beter beloftes Wetlik gegrond is.	",
"	7 Want as daardie eerste een onberispelik was, sou daar nie plek vir ’n tweede gesoek word nie.	",
"	8 Want Hy berispe hulle en sê: Kyk, daar kom dae, spreek JaHWeH, dat Ek met die huis van JisraEl en die huis van JeHûWdah ’n Nuwe Verbond sal sluit, [JirmeJaH 31:31]	",
"	9 nie soos die Verbond wat Ek met hulle vaders gesluit het op dié dag toe Ek hulle hand gegryp het om hulle uit die Aarde van Egipte uit te lei nie - My Verbond wat hulle verbreek het, alhoewel Ék hulle Besitter was, spreek JaHWeH. [JirmeJaH 31:32]	",
"	10 Maar Sy is die Verbond wat Ek ná dié dae met die huis van JisraEl sal sluit, spreek JaHWeH: Ek gee My Wet in hulle binneste en skrywe Haar op hulle hart; en Ek sal vir hulle ‘n Elohim wees, en hulle sal vir My ‘n volk wees. [JeshaJaH 8:16; JirmeJaH 31:33]	",
"	11 En hulle sal nie meer elkeen sy naaste en elkeen sy broer leer nie en sê: Ken JaHWeH; want hulle sal My almal ken, klein en groot onder hulle, spreek JaHWeH, [JirmeJaH 31:34]	",
"	12 want hulle sal My almal ken, klein en groot onder hulle, spreek JaHWeH; want Ek sal hulle ongeregtigheid vergewe en aan hulle oortredinge nie meer dink nie. [JirmeJaH 31:34]	",
"	13 As Hy sê ’n nuwe, het Hy die eerste oud gemaak; en wat oud word en verouder, is naby die verdwyning.	",

]
},
{
book: 'Hebreërs',
chapter: '9',
content: [
		
"	1 SO het dan die eerste sowel Verordeninge vir die diens en aardse Apartheidsplek gehad.	",
"	2 Want die Tabernakel is so ingerig: die eerste, waarin die kandelaar was en die tafel en die toonbrode, wat die Apartheid genoem word; [Exodus 25:30]	",
"	3 en agter die tweede voorhangsel die Tabernakel wat genoem word die Apartgestelde Apartheid, [Exodus 26:33; 31]	",
"	4 waarin ’n goue Wierookbak was en die Ark van die Verbond, rondom heeltemal met goud oortrek, waarin die goue kruik met die manna was en die Staf van Aäron wat gebot het, en die tafels van die Verbond; [Exodus 16:33; 34:29, Númeri 17:8; Deuteronómium 10:5]	",
"	5 en daar bo-op die Gérubs van die Glansrykheid wat die Versoendeksel oorskadu het, waaroor nie nou afsonderlik gespreek kan word nie.	",
"	6 En nadat hierdie dinge so ingerig was, het die priesters wel gedurig in die eerste Tabernakel ingegaan om die dienste te vervul,	",
"	7 maar in die tweede die hoëpriester alleen, een maal in die jaar, nie sonder bloed nie, wat hy naderbring vir homself en vir die oortredinge wat die volk uit onwetendheid begaan het -	",
"	8 waarmee die Gees van die Apartheid dít duidelik maak, dat die Weg na die Apartgestelde Apartheid nog nie geopen is solank as die eerste Tabernakel nog standhou nie.	",
"	9 Hy was ’n beeld met die oog op die teenwoordige tyd waarin daar bydraes en slagdiere nadergebring word, wat hom wat die diens verrig nie raseg kon maak nie, ook nie die siel volmaak nie,	",
"	10 omdat hy net bestaan het in spys en drank en verskillende wassinge en vleeslike verordeninge wat opgelê is tot op die tyd van herstelling.	",
"	11 Maar die Gesalfde, wat opgetree het as Hoëpriester van die toekomstige suiwer dinge, het deur die groter en volmaakter Tabernakel wat nie met hande gemaak is nie, dit wil sê, wat nie aan hierdie skepping behoort nie,	",
"	12 ook nie met die bloed van bokke en kalwers nie, maar met Sy eie Bloed, een maal ingegaan in die Apartgestelde Apartheid en ’n ewige Verlossing teweeggebring.	",
"	13 Want as die bloed van stiere en bokke en die as van ’n vers wat die besoedeldes besprinkel, apart maak tot wassing van die vlees,	",
"	14 hoeveel te meer sal die rassuiwer bloed van die Gesalfde, wat Homself deur die Ewige Gees aan Elohim as rasegte nadergebring het, julle siele suiwer van dooie werke om die Lewende Elohim te dien.	",
"	15 En daarom is Hy Middelaar van ’n Nuwe Verbond, sodat, terwyl daar ’n bloeiing plaasgevind het vir die Verlossing van die oortredinge onder die eerste Verbond, die wat geroepe is, die Belofte van die Ewige Erfenis kan ontvang.	",
"	16 Want waar ’n Verbond is, moet noodsaaklik die dood van die verbondmaker aangekondig word;	",
"	17 want ’n Verbond is geldig by sterfgevalle, aangesien sy nooit van krag is solank as die verbondmaker nog leef nie.	",
"	18 Daarom is ook die eerste nie sonder bloed ingewy nie;	",
"	19 want toe elke Gebod volgens die Wet deur Moshè aan die hele volk aangekondig is, het hy die bloed van die kalwers en bokke saam met water en skarlakenrooi wol en hisop geneem en die Boekrol self en die hele volk besprinkel	",
"	20 en gesê: Dit is die bloed van die Verbond wat JaHWeH met julle gesluit het op grond van al hierdie Woorde. [Exodus 24:8].	",
"	21 En hy het ook die Tabernakel en al die gereedskap van die diens net so met die bloed gesprinkel. [Levítikus 8:19]	",
"	22 En byna alles word met rassuiwer bloed gesuiwer volgens die Wet, en sonder bloedvergieting vind daar geen versoening plaas nie. [Levítikus 17:11]	",
"	23 Dit was dus nodig dat die afbeeldinge van die dinge in die Hemele deur hierdie aanbiedinge gesuiwer moes word, maar die Hemelse dinge self deur beter aanbiedinge as hierdie.	",
"	24 Want die Gesalfde het nie ingegaan in Apartheid met hande gemaak, ’n teëbeeld van die werklike nie, maar in die Hemele self om nou voor die Aangesig van Elohim vir Ons te verskyn;	",
"	25 ook nie om Homself dikwels nader te bring, soos die hoëpriester elke jaar in die Apartgestelde Apartheid ingaan met bloed wat nie sy eie is nie, [Exodus 30:10]	",
"	26 want dan moes Hy dikwels gely het van die grondlegging van die wêreld af. Maar nou het Hy een maal in die voleinding van tyd verskyn om die oortredinge van die Wet weg te neem deur Homself aan te bied.  [Opregte 23:70]	",
"	27 En net soos die adamiete bestem is om een maal te sterwe en daarna die oordeel,	",
"	28 so sal die Gesalfde ook, nadat Hy een maal gebloei is om die oortredinge van baie weg te neem, vir die tweede maal sonder hul oortredinge te verskyn aan die wat Hom verwag tot Lossing. [Psalm 40:12]	",

]
},
{
book: 'Hebreërs',
chapter: '10',
content: [
		
"	1 WANT die Wet, wat ’n afbeelding is van die toekomstige suiwer dinge, nie die beeld self van die dinge nie, kan nooit deur dieselfde rasegte slagdiere wat jaar na jaar gedurig nader gebring word, die wat toetree, tot rasegtheid lei nie.	",
"	2 Anders sou hulle nie opgehou het om hulle nader te bring nie, omdat die wat die diens verrig, nadat hulle een maal skoongewas is, hul siele geen oortredinge meer sou gehad het nie.	",
"	3 Maar [in dié slagdiere] is daar jaar na jaar ’n herinnering aan die oortredinge;	",
"	4 want die bloed van stiere en bokke kan onmoontlik oortredinge wegneem.	",
"	5 Daarom sê Hy, as Hy in die wêreld inkom: Slagdier en aanbiedinge wou U nie hê nie, maar U het vir My ’n Liggaam berei.	",
"	6 Brandoffers vir oortredinge het U nie behaag nie.	",
"	7 Toe het Ek gesê: Kyk, Ek kom - in die Boekrol, is dit van My geskryf - om U wil te doen, o Elohim. [Psalm 40:7]	",
"	8 Nadat Hy hierbo gespreek het: U het geen behae in ‘n slagdier of aanbieding nie; My ore het U vir My geopen; brandoffer vir oortreding het U nie geëis nie - wat volgens die Wet nadergebring word – [Psalm 40:6]	",
"	9 het Hy daarna gesê: Ek het lus, o My Elohey, om U welbehae te doen, [en U Wet is binne-in My ingewande]. [Psalm 40:8] Hy neem die eerste weg om die tweede in te stel.	",
"	10 Deur hierdie wil is Ons apartgestel deur die aanbieding van die Liggaam van JaHWèshua die Gesalfde, net een maal.	",
"	11 En elke priester staan wel dag vir dag om die diens waar te neem en dikwels dieselfde slagdiere te bring wat tog nooit die oortredinge kan wegneem nie;	",
"	12 maar Hy het, nadat Hy een Slagdier vir die oortredinge gebring het, vir altyd gaan sit aan die regterkant van Elohim. [Odes van Salomo 7:10; 20:4]	",
"	13 en wag nou verder totdat Sy vyande gemaak is ’n Voetbank van Sy voete. [Psalm 110:1]	",
"	14 Want deur een aanbieding het Hy vir altyd diegene raseg gemaak wat apartgestel is.	",
"	15 En ook die Gees van die Apartheid gee aan Ons Getuienis;	",
"	16 want nadat Hy tevore gesê het: Sy is die Verbond wat Ek met hulle sal sluit ná dié dae, spreek JaHWeH verder: Ek gee My Wet in hulle binneste en skrywe haar op hulle hart; en Ek sal vir hulle ‘n Elohim wees, en hulle sal vir My ‘n volk wees [JirmeJaH 31:33]	",
"	17 want Ek sal hulle ongeregtigheid vergewe en aan hulle oortredinge nie meer dink nie. [JirmeJaH 31:34]	",
"	18 Waar daar nou vergifnis van hierdie dinge is, is daar geen aanbieding meer vir die oortredinge nie.	",
		
		
"	19 TERWYL Ons dan, broers, vrymoedigheid het om na die Apartheid te gaan deur die bloed van JaHWèshua	",
"	20 op die Nuwe en Lewende Weg wat Hy vir Ons ingewy het deur die voorhangsel heen, dit is Sy vlees, [Exodus 12:7 ; Boodskap van Jakobus 10]	",
"	21 en Ons ’n groot Priester oor die Huis van Elohim het,	",
"	22 laat Ons toetree met ’n ware hart in volle Vertroue en Waarheid, die harte gesuiwer deur besprenkeling van ’n besoedelde siel en die liggaam gewas met skoon water.	",
"	23 Laat Ons die belydenis van die Hoop onwankelbaar vashou, want Hy wat Haar beloof het, is getrou;	",
"	24 en laat Ons op mekaar ag gee om tot liefde en suiwer werke aan te spoor;	",
"	25 en laat Ons Ons onderlinge byeenkoms nie versuim soos sommige die gewoonte het nie, maar laat Ons mekaar vermaan, en dit des te meer namate julle die dag sien nader kom.	",
"	26 Want as Ons opsetlik oortree, nadat Ons die Kennis van die Waarheid ontvang het, bly daar geen aanbieding vir die oortredinge meer oor nie,	",
"	27 maar ’n verskriklike verwagting van oordeel en ’n vuurgloed wat die teëstanders sal verteer.	",
"	28 As iemand die Wet van Moshè verwerp het, sterf hy sonder Ontferming op die getuienis van twee of drie;	",
"	29 hoeveel swaarder straf, dink julle, sal hy verdien wat die Seun van Elohim vertrap het en die Bloed van die Verbond waardeur hy apart gestel is, verbasterd geag, en die Gees van Barmhartigheid beledig het?	",
"	30 Want Ons ken Hom wat gesê het: My kom die wraak toe, Ek sal vergelde, spreek JaHWeH; en weer: JaHWeH sal Sy volk oordeel. [Deuteronómium 32:35, 36]	",
"	31 Vreeslik is dit om te val in die hande van die lewende Elohim.	",
"	32 Maar onthou die vorige dae waarin julle, toe julle verlig geword het, ’n groot lydensworsteling deurstaan het,	",
"	33 gedeeltelik omdat julle deur smaad en verdrukkinge ’n skouspel geword het, gedeeltelik omdat julle deel geword het van die wat in so ’n toestand verkeer het.	",
"	34 Want julle het ook saam met My gevoel in My boeie, en julle het die berowing van julle goed met blydskap aanvaar, omdat julle geweet het dat julle in julself ’n beter en blywende besitting in die Hemele het. [Hooglied 2:9]	",
"	35 Werp dan julle vrymoedigheid, wat ’n groot beloning het, nie weg nie.	",
"	36 Want julle het lydsaamheid nodig, om, nadat julle die wil van Elohim gedoen het, die Belofte te verkry. [JehôWganan 15:26]	",
"	37 Want nog ’n klein tydjie, en Hy wat kom, sal kom en nie versuim nie.	",
"	38 Maar die regverdige sal uit die Geloof lewe; en as hy hom onttrek, het My Siel geen welbehae in hom nie.	",
"	39 Maar by Ons is daar geen onttrekking tot verderf nie, maar Geloof tot behoud van die lewe.	",

]
},
{
book: 'Hebreërs',
chapter: '11',
content: [
		
"	1 DIE Geloof dan is ’n vaste Vertroue op die dinge wat Ons hoop, ’n bewys van die dinge wat Ons nie sien nie. [2 Ezra 7:34]	",
"	2 Want deur Haar het die adamiete van die ou tyd Getuienis ontvang.	",
"	3 Deur die Geloof verstaan Ons dat die ewigheid deur die Woord van Elohim toeberei is, sodat die dinge wat gesien word, nie ontstaan het uit sienlike dinge nie.	",
"	4 Deur die Geloof het Abel ’n aanneemliker eerbewys aan Elohim gebring as Kain, waardeur hy getuienis ontvang het dat hy regverdig was, omdat Elohim oor sy gawes getuienis gegee het; en deur dieselfde Geloof spreek hy nog nadat hy dood is. [Génesis 4:4-5]	",
"	5 Deur die Geloof is Henog weggeneem om die Dood nie te sien nie; en hy is nie gevind nie, omdat Elohim hom weggeneem het; want voor sy wegneming het hy getuienis ontvang dat hy Elohim behaag het.	",
"	6 En sonder Geloof is dit onmoontlik om Elohim te behaag; want hy wat tot Elohim gaan, moet glo dat HY IS en ’n beloner is van die wat Hom soek.	",
"	7 Deur die Geloof het Noag, toe hy ’n waarskuwing ontvang het aangaande wat nog nie gesien was nie, met eerbiedige vrees die Ark gereed gemaak tot verlossing van sy huisgesin, waardeur HY die wêreld veroordeel het en ’n erfgenaam geword het van die Geregtigheid wat volgens die Geloof is.	",
"	8 Deur die Geloof het Abraham, toe hy geroep is, gehoorsaam weggetrek na die plek wat hy as ’n Erfenis sou ontvang; en hy het weggetrek sonder om te weet waar hy sou kom.	",
"	9 Deur die Geloof het hy as vreemdeling gaan woon in die Adamah [die adamiet se Aarde] van Belofte soos in ’n vreemde deel van die Aarde en in tente gewoon met Isak en Jakob, die mede-erfgename van dieselfde Belofte.	",
"	10 Want hy het die Stad verwag wat fondamente het, waarvan Elohim die Boumeester en Oprigter is.	",
"	11 Deur die Geloof het Sarah self ook die Krag ontvang om bevrug te word; en toe sy oor die leeftyd was, het sy gebaar, omdat sy Hom getrou geag het wat dit beloof het.	",
"	12 Daarom is daar ook gebore uit een vader, en hom ’n verstorwene, kinders soos Sterre van die Hemele in menigte en soos die sand aan die strand van die see, wat ontelbaar is.	",
"	13 In die Geloof het hulle almal gesterwe sonder om die beloftes te verkry, maar hulle het Haar uit die verte gesien en geglo en begroet, en het bely dat hulle vreemdelinge en bywoners op Aarde was.	",
"	14 Want die wat sulke dinge sê, verklaar dat hulle ’n vaderland soek.	",
"	15 En as hulle bly dink het aan dié vaderland waaruit hulle weggetrek het, sou hulle geleentheid gehad het om terug te keer.	",
"	16 Maar nou verlang hulle na ’n beter een, sy is ’n Hemelse. Daarom skaam die Elohim HOM nie vir hulle om hulle Elohim genoem te word nie, want HY het vir hulle ’n Stad berei.	",
"	17 Deur die Geloof het Abraham, toe hy op die proef gestel is, Isak nadergebring; ja, hy wat die beloftes ontvang het, het sy eniggeborene opgeneem, [Génesis 22:2]	",
"	18 aan wie gesê is: In Isak sal jou saad genoem word -	",
"	19 want hy het gereken dat Elohim mag het om selfs uit die dode op te wek; daaruit het hy hom ook, om so te spreek, terug ontvang.	",
"	20 Deur die Geloof het Isak vir Jakob en Esau geseën met die oog op die toekoms.	",
"	21 Deur die Geloof het Jakob op sy sterfbed altwee die seuns van JôWsef geseën; en hy het aanbid terwyl hy leun op die knop van sy Staf.	",
"	22 Deur die Geloof het JôWsef aan die einde van sy lewe melding gemaak van die uittog van die kinders van JisraEl en bevel gegee aangaande sy gebeente.	",
"	23 Deur die Geloof is Moshè ná sy geboorte drie maande lank in sy vader se huis weggesteek, omdat hulle gesien het dat die seuntjie mooi was; en hulle het nie die gebod van die koning gevrees nie.	",
"	24 Deur die Geloof het Moshè, toe hy grootgeword het, geweier om die seun van Farao se dogter genoem te word,	",
"	25 omdat hy verkies het om liewer sleg behandel te word saam met die volk van Elohim as om ’n tyd lank die genot van die oortredinge te hê,	",
"	26 en die smaad van die Gesalfde groter rykdom geag het as die skatte van Egipte, want hy het uitgesien na die beloning.	",
"	27 Deur die Geloof het hy Egipte verlaat sonder om die toorn van die koning te vrees, want hy het volgehou soos een wat die Onsienlike sien.	",
"	28 Deur die Geloof het hy die Pasga gehou en die besprenkeling van die bloed, sodat die verderwer hulle eersgeborenes nie sou aanraak nie.	",
"	29 Deur die Geloof het hulle die Rooi See deurgegaan soos oor droë grond, terwyl die Egiptenaars, toe hulle dit probeer, verdrink het.	",
"	30 Deur die Geloof het die mure van Jérigo geval nadat daar sewe dae lank om haar getrek was.	",
"	31 Deur die Geloof het Ragab, die herbergier, nie saam met die wetteloses omgekom nie, omdat sy die spioene in Vrede ontvang het.	",
"	32 En wat sal Ek nog meer sê? Want die tyd sal My ontbreek as Ek van Gídeon, Barak en Simson en Jefta, Dawid en ShemuEl en die Profete sou verhaal,	",
"	33 wat deur die Geloof koninkryke oorweldig het, geregtigheid uitgeoefen, beloftes verkry, bekke van leeus toegestop,	",
"	34 die krag van vuur uitgeblus, die skerpte van die swaard ontvlug, Krag uit swakheid ontvang het, dapper gewees het in die oorlog, leërs van vreemdes op die vlug gedryf het.	",
"	35 Vroue het hulle dode deur opstanding teruggekry, en ander is gefolter en wou geen bevryding aanneem nie, om ’n beter opstanding te kan verkry. [2 Makkabeërs 7:1]	",
"	36 Ander weer het die proef van bespottinge en géselinge deurstaan, ook van boeie en gevangenis.	",
"	37 Hulle is gestenig, in stukke gesaag, versoek, deur die swaard vermoor. Hulle het rondgeloop in skaapvelle en in bokvelle; hulle het gebrek gely, hulle is verdruk, mishandel -	",
"	38 die wêreld was hulle nie werd nie - hulle het in wildernisse rondgedwaal en op berge en in spelonke en skeure in die Aarde.	",
"	39 En alhoewel hulle almal deur die Geloof getuienis ontvang het, het hulle die Belofte nie verkry nie,	",
"	40 omdat Elohim ’n beter Een vir Ons beskik het, sodat hulle volmaaktheid sonder Ons volmaaktheid nie vervolmaak kon word nie.	",

]
},
{
book: 'Hebreërs',
chapter: '12',
content: [
		
"	1 DAAROM dan, terwyl Ons so ’n groot wolk van getuies rondom Ons het, laat Ons ook elke las aflê en die oortredinge wat Ons so maklik omring, en met volharding die wedloop loop wat voor Ons lê,	",
"	2 die oog gevestig op JaHWèshua, die Leidsman en Voleinder van die Geloof, wat vir die Vreugde wat Hom voorgehou is, die folterpaal verdra het, die skande verag het en aan die regterkant van die Troon van Elohim gaan sit het.	",
"	3 Want julle moet ag gee op Hom wat so ’n teëspraak van die oortreders teen Hom verdra het, sodat julle in jul siele nie vermoeid word en verslap nie.	",
"	4 Julle het nog nie so ver as die bloed weerstand gebied in julle stryd teen die oortredinge nie.	",
"	5 En julle het die vermaning heeltemal vergeet wat tot julle as seuns spreek: My seun, ag die Tugtiging van JaHWeH nie gering nie en beswyk nie as jy deur Hom bestraf word nie;	",
"	6 want JaHWeH tugtig hom wat Hy liefhet, en Hy kasty elke seun wat Hy aanneem. [Spreuke 3:11, 12]	",
"	7 As julle die Tugtiging verdra, behandel Elohim julle as seuns; want watter seun is daar wat die vader nie tugtig nie?	",
"	8 Maar as julle sonder Tugtiging is, wat almal deelagtig geword het, dan is julle basters en nie seuns nie.	",
"	9 Verder, Ons het Ons vaders na die vlees as kastyders gehad, en Ons het vir hulle ontsag gehad; moet Ons nie veel meer aan die VADER van die Geeste onderworpe wees en lewe nie?	",
"	10 Want húlle het Ons wel ’n kort tydjie na hulle beste wete getugtig; maar HY tot Ons beswil, sodat Ons SY Apartheid kan deelagtig word.	",
"	11 Nou lyk elke Tugtiging of Sy op die oomblik nie ’n saak van blydskap is nie, maar van droefheid; later lewer Sy egter ’n vredevolle Vrug van Geregtigheid vir die wat deur Haar geoefen is. [Spreuke 4:13]	",
"	12 Daarom, rig die slap hande en die verlamde knieë weer op;	",
"	13 en maak reguit Paaie vir julle voete, sodat wat kreupel is, nie uit lit raak nie, maar liewer gesond gemaak word.	",
"	14 Jaag die Vrede na met al die adamiete en beoefen Apartheid, waarsonder niemand die Meester sal sien nie;	",
"	15 en pas op dat niemand in die Barmhartigheid van JaHWeH agterraak nie; dat geen wortel van bitterheid opskiet en onrus verwek en baie hierdeur besoedel word nie.	",
"	16 Laat niemand ’n homoseksuele hoer wees nie, of ’n apartheidsveragter soos Esau, wat vir één spysgereg sy eersgeboortereg verkoop het.	",
"	17 Want julle weet dat hy, toe hy ook later die seën wou beërwe, verwerp is, want hy het geen geleentheid vir berou gevind nie, al het hy haar met trane vurig begeer.	",
"	18 Want julle het nie gekom by ’n tasbare berg nie en ’n brandende vuur en donkerheid en duisternis en storm	",
"	19 en ramshoring-geklank en die geluid van woorde waarby die hoorders gesmeek het dat hulle geen Woord meer sou toegevoeg word nie -	",
"	20 want hulle kon die Gebod nie verdra nie: selfs as wilde wesens die berg aanraak, moet hulle gestenig word of met ’n pyl neergeskiet word.	",
"	21 En Moshè, so vreeslik was die gesig, het gesê: Ek is verskrik en ek sidder. [Exodus 19:16]	",
"	22 Maar julle het gekom by die Berg van Sion en die Stad van die lewende Elohim, die Hemelse Jerusalem en tienduisende Boodskappers, [Openbaring 14:1-3]	",
"	23 by die feestelike vergadering en die gemeente van eersgeborenes wat in die Hemele opgeskrywe is, en by Elohim, die Regter van almal, en by die geeste van die regverdiges wat vervolmaak is, [Ode van Salomo 33:11]	",
"	24 en by JaHWèshua, die Middelaar van die Nuwe Verbond, en die bloed van die besprenkeling wat van beter dinge spreek as Abel.	",
"	25 Pas op dat julle Hom wat spreek, nie afwys nie; want as húlle nie ontvlug het nie wat Hom afgewys het toe Hy op Aarde ’n waarskuwing gegee het, veel minder Ons wat Ons van Hom afkeer nou dat Hy uit die Hemele spreek.	",
"	26 Toe het Sy Stem die Aarde geskud; maar nou het Hy belowe en gesê: Nog een maal laat Ek nie alleen die Aarde nie, maar ook die Hemele bewe.	",
"	27 En hierdie Woord: nog een maal, wys duidelik op die verandering van die wankelbare dinge as geskape dinge, sodat die onwankelbare kan bly.	",
"	28 Daarom, omdat Ons ’n onwankelbare Koninkryk ontvang, laat Ons dankbaar wees, en so Elohim welbehaaglik dien met eerbied en vrees.	",
"	29 Want Onse Elohey is ’n verterende vuur.	",

]
}
];
