const jubileumChapters = [

{
book: 'Jubileum',
chapter: '1',
content: [

"	1 En dit het in die eerste jaar van die uittog van die JisraEliete uit Egipte gebeur, in die derde maand, op die sestiende dag van die maand, dat Vader met Moshè gespreek het, en gesê: Kom op na My op die Berg, en Ek sal vir jou die twee kliptafels van die Wet en van die Gebod, wat Ek Geskryf het gee, sodat jy hulle kan Onderrig. 	",
"	2 En Moshè het opgegaan na die Berg van Vader, en die Glansrykheid van die Meester het op die Berg Sinai gerus en ‘n Wolk het dit vir ses dae oorskadu. 	",
"	3 En op die sewende dag het Hy vanuit die middel van die Wolk na Moshè geroep; en die Glansrykheid van die Meester het soos ‘n vlammende vuur op die kruin van die Berg gelyk. 	",
"	4 En Moshè was vir veertig dae en veertig nagte op die Berg; En Vader het vir hom die eerste en die laaste dinge geleer, en die verdeling van al die dae van die Wet en van die Getuienis. (:1-:4 = 50:1-:2 + :4) 	",
"	5 En Hy het gesê: Luister noukeurig na elke ding wat Ek jou op hierdie Berg vertel, en skryf dit in ‘n Boek sodat die geslagte wat volg kan sien hoe Ek hulle nie versaak het, weens al die boosheid wat hulle gedoen het in oortreding van die Verbond, wat Ek vandag tussen My en jou, op Berg Sinai vestig, vir al hulle nageslagte nie. 	",
"	6 En so, wanneer al hierdie dinge met hulle gebeur het, sal hulle besef dat Ek Regverdiger as hulle is, in al hulle oordele en dade, en hulle sal erken dat Ek Getrou aan hulle gebly het. (= Rom. 3:3-:4) 	",
"	7 Skryf dan alles neer, wat Ek jou vandag vertel; want Ek weet hoe uitdagend en hardnekkig hulle is, selfs voordat Ek hulle in die Land lei waaroor Ek ‘n eed aan hulle vaders, Abraham, Isak en Jakob, gesweer het, deur te sê: Aan jou nageslagte sal Ek ‘n Land gee, wat vloei met Melk en Heuning. 	",
"	8 En hulle sal eet en versadig wees, en hulle sal hulle tot uitheemse gode wend, wat Magteloos is om hulle uit hul ellende te verlos; en dan sal hierdie Bewys as bewys teen hulle dien. 	",
"	9 Want hulle sal al My Bevele wat Ek hulle gee vergeet en die heidene naboots, hulle onreinheid en hulle skande, en hulle gode aanbid; en Hierdie sal bewys, om ‘n struikelblok vir hulle te wees, ‘n bron van ellende en nood, en ‘n vangstrik. (= O.v.Abr. 29:13 = Jes. 8:14 = Matt. 21:42-:44) 	",
"	10 En baie sal omkom, en andere sal as gevangene geneem en in die hande van die vyand val, omdat hulle My Wet en My Bevele versaak het, en die Feeste van My Verbond en My Sabbatte, en My Rein Aanbiedinge wat Ek vir My, in hul midde, afgesonder het, en My Tabernakel, en My Toevlugsoord wat Ek vir My afgesonder het, in die middel van die Land, om dit ‘n Woonplek vir My Naam te maak. 	",
"	11 En hulle sal berg-altare gewyde-pale en uitgesnede beelde maak, en elkeen sal sy eie uitgesnede beeld aanbid en afdwaal; en hulle sal hul kinders aan bose geeste en al die afgodsbeelde wat hulle in die verkeerdheid van hul harte gemaak het, aanbied. 	",
"	12 En Ek sal Getuies stuur om teen hulle te getuig; maar hulle sal nie luister nie, en hulle sal die Getuies dood en daardie wat die Wet Begeer, vervolg, en hulle sal afskaf en alles verander en doen wat verkeerd is in My oë. 	",
"	13 En Ek sal My aangesig van hulle af wegdraai en hulle aan die heidene oorgee om gevange geneem te word en om beroof,en verslind te word; en Ek sal hulle uit die land uitdryf en hulle onder die heidene verstrooi. 	",
"	14 En hulle sal al My Wette en al My Gebooie en al My Voorskrifte vergeet en afdwaal met betrekking tot Nuwemane en Sabbatte en Feeste en Jubileums en die ander Verordeninge. 	",
"	15 En hierna sal hulle na My toe terugkeer, van onder die heidene met hulle hele hart en met hulle hele siel en met al hulle krag; en Ek sal hulle onder al die heidene bymekaarmaak, en hulle sal My Begeer, en Ek sal My deur hulle laat vind. 	",
"	16 En wanneer hulle My met hulle hele hart en hulle hele siel Begeer, Sal Ek aan hulle ‘n Tydperk van Vrede en Geregtigheid toestaan en hulle afsonder as ‘n Opregte plant, met My hele Hart en My hele Siel; en hulle sal ‘n Seën en nie ‘n vervloeking wees nie, die kop en nie die stert nie. 	",
"	17 En Ek sal My Toevlugsoord in hulle midde bou, en Ek sal by hulle woon, en hulle Vader wees en hulle sal My Volk in Waarheid en Geregtigheid wees. 	",
"	18 En Ek sal hulle nie versaak en ook nie in die steek laat; want Ek is die Meester hulle Vader. 	",
"	19 En Moshè het hom onderwerp en Gebid en gesê: O Meester my Vader, moenie U volk en U Eie Besitting verlaat nie, en laat hulle nie dwaal in die verkeerdheid van hulle harte nie: gee hulle nie oor in die hande van hulle vyande, die heidene nie, en laat hulle nie oor hulle heers en teen U laat sondig nie. 	",
"	20 Laat U Barmhartigheid (Wet), o Meester, oor U volk Waak, en skep in hulle ‘n Opregte Gees; en laat nie die gees van Beliar (Wetteloosheid) oor hulle heers om hulle voor U te beskuldig en hulle van al die Paaie van Geregtigheid af (verlok en) verstrik nie, sodat hulle nie, weg van U Aangesig, vergaan nie. 	",
"	21 Want hulle is U volk en U eie Besitting, wat U met U groot Krag uit die hande van die Egiptenare Verlos het. Skep in hulle ‘n Suiwer hart en ‘n Volmaakte gees, en laat hulle nie in hulle sondes verstrik raak nie, nou of ooit. 	",
"	22 En die Meester het vir Moshè gesê: Ek ken hulle dwarstrekkerigheid, hulle gedagtes en hulle hardnekkigheid, en hulle sal nie gehoorsaam wees totdat hulle hul eie sonde en die sonde van hul vaders erken het nie. 	",
"	23 En hierna sal hulle na My terugkeer in alle Opregtheid en met hulle hele hart en siel; en Ek sal die voorhuid van hulle hart en die voorhuid van die harte van hulle nageslag besny, en Ek sal in hulle ‘n Volmaakte gees skep (Wet = Rom. 8:9-:11) en Ek sal hulle Reinig sodat hulle nie weer van My af sal wegdraai nie, van daardie dag af tot in Ewigheid. 	",
"	24 En hulle sal My en al My Gebooie aankleef, en My Bevele nakom; en Ek sal hulle Vader wees, en hulle sal My Kinders wees. 	",
"	25 En hulle sal almal genoem word: Kinders van die Lewende Vader; en elke Engel en siel sal weet [hulle sal inderdaad weet] dat hiérdie, My Kinders is, en dat Ek in Opregtheid en Geregtigheid hulle Vader is, en dat Ek hulle Liefhet. 	",
"	26 En skryf jy alles neer wat Ek jou op hierdie Berg sê, die eerste en die laaste dinge wat sal gebeur in al die verdelings van die dae, in die Wet en in die Getuienis, en in die weke (Sabbatjare) van die Jubileums tot in Ewigheid, totdat Ek Neerdaal en tot in alle Ewigheid by hulle Woon. 	",
"	27 En Hy het vir die teenwoordige Engel gesê: Skryf vir Moshè die verhaal van die eerste skepping tot die Tyd wanneer My Toevlugsoord tussen hulle Gebou (Jeség. 40:1-47:23 = Jes. 9:6) sal wees tot in alle Ewigheid, 	",
"	28 en die Meester voor die aangesig van almal Verskyn, en almal weet dat Ek die Vader van JisraEl en die Vader van al die seuns van Jakob en Koning op die Berg Sion tot in alle Ewigheid is, en Sion en JeRuSHâLeim sal Gevestig [Volmaak] wees. (:26-:28 = Jhg. 12:34-:36{a}) 	",
"	29 En die teenwoordige Engel, wat gewoonlik voor die laer van JisraEl getrek het, het die tafels van die verdelings van die jare, van die tyd van die skepping van die Wet en van die Getuienis – die tafels, dit is, van die weke van die Jubileums volgens hulle jare, volgens al die getalle van die Jubileums volgens hulle jare, van die dag van die Skepping tot die dag wanneer die hemele en die aarde Hernieu is daarmee saam alle geskape dinge, en hulle hele skepping volgens die Kragte van die Hemel en volgens die hele skepping van die aarde, tot die dag dat die Toevlugsoord van die Meester in JeRuSHâLeim op die Berg Sion Geskep is, en al die Ligdraers Herstel is as instrumente van Genesing en van Vrede en van Seën vir al die Uitverkorenes van JisraEl geneem, en dat dit so mag wees van daardie dag af en verder, vir solank as wat die aarde voortduur. (= Jes. 9:5-:6)	",

]
},
{
book: 'Jubileum',
chapter: '2',
content: [
		
"	1 En die teenwoordige Engel het met Moshè in ooreenstemming met die Meester se Bevel gespreek, en gesê: Skryf die volledige geskiedenis van die Skepping, hoe die Meester Vader al Sy Werke en alles wat Hy Geskep het, op die sesde dag voltooi het, en Sabbat op die sewende dag gehou het, en dit vir alle tye afgesonder het en dit as ‘n Teken van al Sy Werke bepaal het. 	",
"	2 Want op die Eerste dag het Hy die hemele wat daarbo is geskape, en die aarde, en die waters, en elke siel wat Hom Dien – die Engele in Sy teenwoordigheid, en die Engele van Volmaaktheid, en die Engele van die gees van Vuur, en die Engele van die gees van die winde, en die Engele van die gees van die wolke, en van duisternis, en van sneeu, en van hael, en van ryp, en die Engele van die dieptes en van die donders en weerligte, en die Engele van die koue winde en die warm winde en van winter en van lente en herfs en somer, en die siele van Sy skepsele in die hemele en op die aarde en in die hele eindeloosheid, en die diep duisternis, en die lig en die skemer en die oggend en die aand, wat Hy alreeds Voorberei en Beplan het. (= O.v.Gnk. 10:1-:5) 	",
"	3 Daarna het ons Sy Werke gesien, en ons het Hom Geseën en lofliedere vanweë al Sy Werke voor Hom gesing; want op die Eerste dag het Hy sewe groot Werke Geskep. 	",
"	4 En die volgende dag het Hy die koepelvormige oordekking in die middel van die waters geskep, en die waters was op daardie dag verdeel – die helfte daarvan het boontoe gestyg en die helfte daarvan het afgegaan onder die koepelvormige oordekking wat tussen hulle oor die aarde was; en dit was die enigste Werk wat Hy op die Tweede dag gedoen het. 	",
"	5 En op die derde dag het Hy die waters Beveel om van die oppervlakte van die aarde bymekaar te kom op een plek, en die droë land om te verskyn. 	",
"	6 En die waters het so gedoen, net soos Hy dit Beveel het, en dit het van die oppervlakte van die aarde teruggeloop in een plek buite die koepelvormige oordekking, en die droë land het verskyn. 	",
"	7 En op daardie dag het Hy al die seë op hul verskillende versamelplekke Geskape, en al die riviere en die versamelings van die waters in die berge oor die hele aarde, en al die mere, en al die dou van die aarde, en die saad wat gesaai word, en alle plante wat groei, en die bome wat vrug dra, en die bome van die woud, en die tuin van Genoeë in Eden; en al vier hierdie groot werke het Vader op die derde dag Geskep. 	",
"	8 En op die vierde dag het Hy die son en maan en sterre Geskape, en Hy het hulle in die hemel gewelf geplaas om lig op die aarde te gee, om beheer te hê oor dag en nag, en om lig en duisternis te skei. 	",
"	9 En Vader het die son aangestel as ‘n groot teken op die aarde om die dae, weke (Sabbatte) en maande [nuwemaan dae] te merk (aan te dui) en Feeste en jare en weke van jare en Jubileums en al die seisoene van die jare; 	",
"	10 en dit skei lig van duisternis, en is die bron van gesondheid, sodat elke ding wat op aarde spruit en groei, gesond mag wees. Hierdie drie soorte van ligte het Hy op die vierde dag gemaak. 	",
"	11 En op die vyfde dag het Hy groot seemonsters in die dieptes van die waters geskape [hierdie was die eerste lewende wesens [letterlik dinge van vlees] wat deur Sy Hande Geskape was], en al die vis wat in die waters swem, en alle soorte voëls wat vlieg. 	",
"	12 En die son het oor hulle almal verrys om aan hulle gesondheid te gee, oor elke ding wat op die aarde was – alle plante en bome en lewende wesens. Hierdie drie soorte lewende wesens het Hy op die vyfde dag geskape. 	",
"	13 En op die sesde dag het Hy al die wilde diere van die aarde geskape, en al die vee, en elke ding wat op die aarde beweeg. 	",
"	14 En na al hierdie het Hy die Man geskape: Hy het ‘n man en ‘n vrou geskape; en Hy het hom meester gemaak, oor elke ding wat op die aarde is, en in die seë, en oor elke ding wat vlieg, en oor die wilde diere en die vee, en oor elke ding wat op die aarde beweeg, en oor die hele aarde: oor al hierdie het Hy hom meester gemaak. 	",
"	15 En hierdie vier soorte wesens het Hy op die sesde dag geskep. En daar was altesaam twee-en-twintig soorte. (=:23) 	",
"	16 En Hy het al Sy Werke op die sesde dag voltooi – alles wat in die hemele en op die aarde, en in die seë en in die dieptes, en in die lig en in die duisternis, en in elke ding is. 	",
"	17 En Hy het vir ons ‘n groot Teken gegee, die Sabbatdag (die dag van die Sabbatte), dat ons vir ses dae behoort te werk (aanhou werk op die sesde dag), maar die Sabbat onthou van alle werk, op die sewende dag. 	",
"	18 En al die teenwoordige Engele en al die toegewyde Engele, hierdie twee groot ordes – Hy het ons Beveel om die Sabbat saam met Hom in die Hemel en op die aarde te hou. 	",
"	19 En Hy het vir ons gesê: Kyk! Ek sal vir My ‘n Volk uitsonder, ‘n volk uit alle volke, en hulle sal die Sabbatdag hou; en Ek sal hulle as My eie Volk afsonder, en Ek sal hulle Seën: soos wat Ek die Sabbatdag afgesonder het en dit nog as Myne afsonder, netso sal Ek hulle ook Seën en hulle sal My Volk wees en Ek sal hulle Vader wees. 	",
"	20 En Ek het Jakob se nageslag uit die afstammelinge van elke volk gekies [want Ek het hom gesien en hom as My oudste seun gemerk en hom as Myne afgesonder vir altyd]; en Ek sal hulle die Wet van die Sabbatdag leer, dat hulle Sabbat (Sinnebeeld van Koninkryk = Heb. 4:1-:13) op daardie dag sal hou en geen werk doen nie. 	",
"	21 En so het Hy in Dit ‘n Teken geskep dat hulle soos Hy moet wees, (= Matt. 5:48) en dat hulle saam met ons Sabbat op die sewende dag moet hou, en eet en drink en Hom Seën wat alle dinge Geskape het, soos Hy as Sy eie Geseën en afgesonder het, ‘n besondere Volk uit alle volke en dat hulle saam met ons Sabbat behoort te hou, 	",
"	22 en die uitvoering van Sy Bevele behoort vir ewig voor Hom op te styg soos ‘n welriekende vertroostende geur. 	",
"	23 Soos wat daar twee-en-twintig letters (Hebreeuse alfabet), en twee-en-twintig gewyde Boeke, en twee-en-twintig stamvaders van Adam tot Jakob en twee-en-twintig soorte geskape dinge (= :15) voor die sewende dag gemaak was: Is hierdie dag Geseën en afgesonder; en Jakob is ook Geseën en afgesonder; en so is die twee saam afgesonder en Geseën (hierdie een dien saam met daardie een vir afsondering en Seën). 	",
"	24 En vir Jakob en sy nageslag was dit toegestaan dat, hulle altyd die Geseëndes en Reines van die eerste Verbond en Wet behoort te wees, net soos Hy die Sabbat op die sewende dag afgesonder en Geseën het. 	",
"	25 In ses dae het Hy hemel en aarde en alles wat Hy Geskape het, Geskape, en Vader het die sewende dag vir al Sy Werke afgesonder (= Jhg. 5:16-:17): dit is waarom Hy die Bevel gegee het dat wie ookal enige werk daarop doen, sal sterwe, en dat wie dit ookal Besoedel, sal sekerlik sterf. 	",
"	26 En so moet jy die seuns van JisraEl Beveel om hierdie dag waar te neem, dit Rein te hou en geen werk daarop te doen en dit nie Besoedel nie, want dit is meer Verhewe as al die ander dae. 	",
"	27 En wie dit ookal skend sal sekerlik sterf en wie ookal enige werk daarop doen sal sekerlik Ewiglik sterf, sodat JisraEl se seuns hierdie dag mag waarneem in elke geslag en nie uit die land ontwortel word nie; want dit is ‘n afgesonderde dag en ‘n Geseënde dag. 	",
"	28 En elke persoon wat dit waarneem en Sabbat daarop onderhou en geen werk doen nie, sal soos ons, vir altyd Rein en Geseënd wees. (:21 + :28 = Matt. 5:48) 	",
"	29 Proklameer die Wet van hierdie dag aan die seuns van JisraEl en sê vir hulle om Sabbat daarop te hou, en dit nie te versaak deur die fout van hulle harte (begeerte) nie, en dat dit nie Wettig is om enige werk wat onbehoorlik is, of hul eie begeertes te doen nie, of water te trek of enige swaar vrag deur hul hekke in of uit daarop te dra nie, en dat hulle nie daarop enigiets om te eet of te drink behoort voor te berei, wat nie alreeds op die Sesdedag in hulle huise voorberei is nie. (= Jes. 58:13-:14) 	",
"	30 En hulle sal niks van een huis na ‘n ander op daardie dag in of uitneem nie, want daardie dag is meer Verhewe en Geseën as enige Jubileum dag van die Jubileums: dit is waarom ons Sabbat in die Hemele gehou het, voordat dit aan enige sterfling bekendgemaak was, om Sabbat daarop te hou, op die aarde. 	",
"	31 En die Skepper van alle dinge het dit Geseën, maar Hy het nie alle volke en nasies afgesonder om Sabbat daarop te hou nie, (= Amos. 8:11-:14) maar slegs JisraEl: Hulle alleen het Hy op aarde toegelaat om te Eet en te Drink (= Open. 2:7 + Jhg. 6:25-:58) en Sabbat daarop te hou. 	",
"	32 En die Skepper van alle dinge het hierdie dag Geseën, wat Hy vir Seën en Volmaaktheid en Glansrykheid bo alle dae Geskape het. (= Heb. 4:1-:13) 	",
"	33 Hierdie Wet en Verordening was aan JisraEl se seuns as ‘n Wet vir Ewig gegee, vir al hul geslagte.	",

]
},
{
book: 'Jubileum',
chapter: '3',
content: [
		
"	1 En op die ses dae van die tweede week, in ooreenstemming met Vader se Bevel, het ons al die wilde diere na Adam gebring, en al die vee, en al die voëls, en elke ding wat op die aarde beweeg, en elke ding wat in die water swem, volgens hulle soorte, en volgens hulle spesies – die wilde diere op die Eerste dag, die vee op die Tweede dag, die voëls op die Derde dag, alles wat op die aarde beweeg op die Vierde dag, en wat in die water swem op die Vyfde dag. 	",
"	2 En Adam het vir hulle almal name gegee; en wat hy hulle genoem het, daardie was hulle name.	",
"	3 En Adam het hulle almal op hierdie vyf dae gesien, manlik en vroulik, volgens elke soort wat op die aarde was; maar hy was alleen en het geen maat gevind wat soos hy was nie.	",
"	4 En die Meester het vir ons gesê: Dit is nie goed vir die man om alleen te wees nie: laat ons vir hom ‘n maat maak wat soos hy is. 	",
"	5 En die Meester ons Vader het hom diep laat slaap, en hy het geslaap; en Hy het vir die vrou een been tussen sy beendere geneem (en so was die oorsprong van die vrou hierdie rib wat van Adam se beendere geneem was), en Hy het weer die vlees op sy plek opgebou en die vrou gebou. 	",
"	6 En Hy het Adam uit sy slaap wakker gemaak; en hy het wakker geword en op die Sesdedag opgestaan. En Hy het haar na hom toe gebring en hy het haar geken (herken) en vir haar gesê: Hierdie is been van my beendere, En vlees van my vlees: Sy sal my vrou genoem word, Omdat sy vanuit haar man geneem was. 	",
"	7 Dit is waarom man en vrou een is; en dit is waarom die man sy vader en moeder verlaat en met sy vrou verenig, en hulle een vlees word. 	",
"	8 In die eerste week (Sabbatjaar) was Adam Geskape, en die rib – sy vrou: in die tweede week (Sabbatjaar) het Hy haar aan hom getoon; en dit is waarom ‘n Bevel gegee was aan vroue om in hul onreinheid te bly – sewe dae vir ‘n manlike en veertien dae vir ‘n vroulike (kind). 	",
"	9 En nadat Adam veertig dae in die land was waar hy Geskape was, het ons hom in die tuin van Eden gebring om dit te bewerk en te bewaak; maar sy vrou het hulle op die tagtigste dag ingebring (en hierna het sy die tuin van Eden binnegegaan). 	",
"	10 En dit is waarom die Gebod op die Hemelse Tafels Geskryf is aangaande ‘n vrou wat geboorte skenk – as sy ‘n manlike baar, sal sy vir sewe dae in haar onreinheid wag (volgens die eerste week van dae), en dan sal sy ‘n verdere drie-en-dertig dae wag in die bloed van haar suiwering (vir haar bloed om te suiwer), en sy sal niks aanraak wat Rein is of die Gereserveerde Plek binnegaan, totdat sy hierdie dae wat aangewys is in die geval van ‘n manlike kind voltooi het nie. 	",
"	11 Maar in die geval van ‘n vroulike kind sal sy in haar onreinheid veertien dae wag (volgens die eerste twee weke), en dan ‘n verdere ses-en-sestig dae in die bloed van haar suiwering, tagtig dae gesamentlik. 	",
"	12 En wanneer sy hierdie tagtig dae voltooi het, het ons haar in die tuin van Eden gebring; want dit is meer Volmaak as die res van die aarde en elke boom wat daarin geplant is, is Volmaak. (= Luk. 13:6-:9 = Open. 2:7) 	",
"	13 Dit is waarom die Reël neergelê was aangaande ‘n vrou wat ‘n kind baar, hetsy manlik of vroulik, dat sy niks behoort aan te raak wat Rein is nie, ook nie die Gereserveerde Plek binnegaan nie, totdat hierdie dae wat vir ‘n manlike of vroulike kind voorgeskryf is, voltooi is nie. 	",
"	14 Dit is die Wet en die Verordening wat vir JisraEl Neergeskryf was, dat hulle dit altyd moet waarneem. 	",
"	15 En in die eerste week van die eerste Jubileum was Adam en sy vrou in die tuin van Eden vir sewe jaar waar hulle dit bewerk en bewaak het; en ons het vir hom werk gegee om te doen en hom al die besonderhede van tuinboukunde geleer. 	",
"	16 En hy het die tuin bewerk; en hy was naak sonder om dit te weet, en was nie skaam nie. En hy het die tuin teen voëls, wilde diere en beeste beskerm; en hy het die vrugte versamel, geëet, en wat oor was, vir hom en sy vrou eenkant gesit. 	",
"	17 En nadat hy sewe jaar daar voltooi het, presies sewe jaar, in die tweede maand, op die sewentiende dag van die maand, het die slang gekom en die vrou genader; en die slang het vir die vrou gesê: Het Vader julle Beveel en gesê, 	",
"	18 dat julle nie van die vrugte van al die bome van die tuin mag eet nie? En sy het daarop geantwoord: Van al die vrugte van die bome van die tuin het Vader vir ons gesê: Eet; maar van die vrug van die boom in die middel van die tuin, het Vader vir ons gesê: Julle mag daarvan nie eet nie, ook mag julle dit nie aanraak nie: as julle dit doen, sal julle sterf. 	",
"	19 En die slang het vir die vrou gesê: Natuurlik sal julle nie sterf nie: Vader weet dat, op die dag wat julle wel daarvan eet, sal julle oë oopgemaak word, en julle sal soos gode wees en Goed en kwaad ken. 	",
"	20 En die vrou het na die boom gekyk en gesien dat dit welgevallig en aangenaam vir die oog was en dat die vrug daarvan goed was om van te eet, en sy het daarvan geneem, en geëet. (:17-:20 = 12:2o) 	",
"	21 En toe sy haar skaamte met vyeblare bedek het, [met die blare van die genoemde vyeboom. Volgens tradisionele oorlewering was die boom van kennis ‘n vyeboom] het sy daarvan vir Adam gegee, en hy het geëet; en sy oë was geopen, en hy het gesien dat hy naak was. (= :31) 	",
"	22 En hy het vyeblare geneem en dit aanmekaar gewerk, en vir hom ‘n lendekleed gemaak, en sy skaamte bedek. 	",
"	23 En Vader het die slang vervloek en was vir ewig kwaad daarvoor. 	",
"	24 En Hy was kwaad vir die vrou, omdat sy na die slang geluister en geëet het; en Hy het vir haar gesê: Ek sal jou taak en pyne vermeerder: In droefheid sal jy kinders baar. Op jou man sal jy vertrou. En hy sal jou gesagvoerder wees. 	",
"	25 En vir Adam het Hy gesê: Omdat jy na jou vrou geluister het, En van die boom geëet het, waarvan Ek jou Beveel het om nie te eet nie, Vervloek sal die grond wees ter oorsake van jou: Dorings en distels sal dit vir jou voortbring, En jy sal jou brood eet deur die sweet van jou voorkop, Totdat jy na die aarde terugkeer waaruit jy geneem was; Want jy is grond en na grond sal jy terugkeer. 	",
"	26 En Hy het vir hulle mantels uit vel gemaak en hulle beklee, en hulle uit die tuin van Eden gestuur.	",
"	27 En op die dag wat Adam uit die tuin gegaan het, het hy wierook, gomhars, storaks, en speserye as ‘n voedselaanbieding van aangename geur aangebied; en so het hy elke dag in die oggend met sonsopgang gedoen, van die dag af dat hy sy skaamte bedek het. 	",
"	28 En op daardie dag het die bekke van al die wilde diere en die vee en die voëls, en van alles wat loop of beweeg was gesluit, sodat hulle nie meer kon praat [want tot op daardie oomblik het hulle almal met mekaar in ‘n algemene taal gepraat]. 	",
"	29 En Hy het uit die Tuin van Eden al die wesens wat daarin was, uitgestuur; en hulle was verstrooi na die plekke wat vir hulle natuur geskik was, volgens hulle geaardheid en spesie. 30 En alleenlik Adam, as uitgesonder onder al die wilde diere en beeste, het Hy rede gegee om sy skaamte te bedek. Wilde diere skaamte nie bedek...? 	",
"	31 Dit is waarom dit op die Hemelse Tafels Beskryf dat, al daardie wat bekend is met die oordele van die Wet, hulle skaamte moet bedek en hulle nie ontbloot soos die heidene hulle ontbloot nie. 	",
"	32 En Adam en sy vrou het op die dag van die nuwemaan van die vierde maand uit die tuin van Eden gegaan; en hulle in die land van Elda gevestig [ in die land van hulle skepping]. 33 En Adam het sy vrou Gawwah genoem. 	",
"	34 En hulle het nie ‘n seun gehad voor die eerste Jubileum; en hierna het hy gemeenskap met haar gehad. 	",
"	35 En hy het die land bewerk, soos wat hy in die tuin van Eden geleer was.	",


]
},
{
book: 'Jubileum',
chapter: '4',
content: [
		
"	1 En in die derde week van die tweede Jubileum het sy geboorte aan Kain geskenk, en in die vierde het sy geboorte aan HaaBeL (Abel) geskenk, en in die vyfde het sy geboorte geskenk aan haar dogter Awan. 	",
"	2 En in die eerste week van die derde Jubileum het Kain vir HaaBeL (Abel) gedood omdat Vader HaaBeL (Abel) se aanbieding aanvaar het, maar syne nie. 	",
"	3 En hy het hom in die ope gedood; en sy bloed het uit die grond tot die Hemel geroep, hom van moord aangekla. 	",
"	4 En die Meester het Kain bestraf vanweë die moord op Haabel (Abel), en hom ‘n voortvlugtige op die aarde gemaak as gevolg van sy broer se bloed; en Hy het hom op die aarde vervloek. 	",
"	5 En dit is waarom dit op die Hemelse Tafels Geskryf is, vervloek is die man wat ‘n ander man tref in boosheid, en laat almal wat dit gesien of gehoor het, Sê: Âmein; en die man wat dit gesien het en dit nie geopenbaar het nie, laat hom so vervloek wees soos die ander. 	",
"	6 En dit is waarom, wanneer ons voor die Meester ons Vader kom, rapporteer ons al die sonde wat in die hemel en op die aarde gepleeg is, en in lig en duisternis, orals. 	",
"	7 En Adam en sy vrou het oor HaaBeL (Abel) vir vier weke van jare gerou. En in die vierde jaar van die vyfde week het hulle geesdrif vir die lewe teruggekeer; en Adam het weereens met sy vrou gemeenskap gehad, en sy het vir hom ‘n seun gebaar, en hy het hom Set genoem — want hy het gesê: Vader het vir ons ‘n ander seun op aarde gegee in die plek van HaaBeL (Abel), omdat Kain hom gedood het. 	",
"	8 En in die sesde week het hy sy dogter Azura verwek. En Kain het sy suster Awan as sy vrou geneem, en sy het Henoh vir hom gebaar, aan die einde van die vierde Jubileum. 	",
"	9 En in die eerste jaar van die eerste week van die vyfde Jubileum, was huise op aarde gebou; en Kain het ‘n stad gebou en dit na sy seun Henoh vernoem. 	",
"	10 En Adam het gemeenskap met sy vrou Gawwah gehad, en sy het vir hom nog nege kinders gebaar. 	",
"	11 En in die vyfde week van die vyfde Jubileum het Set sy suster Azura as vrou geneem, en in die vierde jaar van die sesde week het sy Enos vir hom gebaar. 	",
"	12 Hy was die eerste op aarde om die Meester in Naam aan te roep. 	",
"	13 En in die sewende Jubileum, in die derde week het Enos sy suster Noam as sy vrou geneem, en sy het vir hom in die derde jaar van die vyfde week ‘n seun gebaar, en hy het hom Kenan genoem. 	",
"	14 En teen die einde van die agste Jubileum het Kenan sy suster Mualeleth as sy vrou geneem, en sy het vir hom in die negende Jubileum ‘n seun gebaar [in die eerste week, in die derde jaar van daardie week], en hy het hom Mahalalel genoem. 	",
"	15 En in die tweede week van die tiende Jubileum het Mahalalel, Dinah as sy vrou geneem, die dogter van Barakiel, sy vader se broer [suster] se dogter, en sy het vir hom in die derde week gebaar, in die sesde jaar, en hy het hom Jared genoem; en in sy dae het die Engele van die Meester [daardie wat Wagters genoem was] na die aarde gekom om manne te leer, wat Goed en Reg op aarde was. 	",
"	16 En in die elfde Jubileum het Jared ‘n vrou geneem in die vierde week van hierdie Jubileum, en haar naam was Berakhah, die dogter van Rasuel, ‘n dogter van sy vader se broer [suster], en sy het vir hom in die vyfde week ‘n seun gebaar, in die vierde jaar van die Jubileum, en hy het hom GaNoWK (Henog) genoem. 	",
"	17 En hy was die eerste op aarde onder manne gebore, om te leer skryf en om Kennis en Wysheid te bekom; en hy het in ‘n Boek, besonderhede van die tekens van die hemel volgens die Orde van hulle maande neergeskryf, sodat manne die seisoene van die jare kan ken volgens die Orde van hulle verskillende maande. 	",
"	18 En hy was die eerste om ‘n Getuienis te skryf; en hy het die seuns van Adam gewaarsku oor wat in die toekomende geslagte op die aarde sou gebeur, en die weke van die Jubileums uiteengesit, en die dae van die jare bekendgemaak, en die maande in orde geplaas, en die Sabbatte van die jare uiteengesit net soos ons (die Engele) dit aan hom bekendgemaak het., 	",
"	19 En wat was en wat sal wees het hy in ‘n droombeeld in sy slaap gesien, net soos wat dit met die seuns van Adam in elke geslag sal gebeur, tot die dag van Oordeel: het hy Gesien en alles daarvan Geweet; en hy het sy testament geskryf, en dit as ‘n testament op aarde gelaat vir al die seuns van Adam van elke geslag. 	",
"	20 En in die twaalfde Jubileum, in die sewende week — daarvan, het hy ‘n vrou geneem, en haar naam was Edni, die dogter van Danel, sy vader se broer [suster], en in die sesde jaar van daardie week, het sy vir hom ‘n seun gebaar, en hy het hom Metúsalag genoem. 	",
"	21 En hy was by Vader se Engele vir hierdie ses Jubileum jare, en hulle het hom alles op aarde, en die hemele getoon, en die kragte van die son; en hy het alles neergeskryf. 	",
"	22 En hy het getuienis teen die Wagters ontbloot, wat met die dogters van Adamiete gesondig het — want hierdie het begin om huwelike met die dogters van die Adamiete te sluit, en hulleself so verontreinig; en GaNoWK (Henog) het getuienis teen hulle almal ontbloot. 	",
"	23 En hy was van die seuns van Adam af weggeneem, en ons het hom met majesteit en eer in die Tuin van Eden ingelei; en daar skryf hy die Veroordeling en Oordele van die wêreld neer, en al die seuns van Adam se sondes. 	",
"	24 Dit is waarom GaNoWK (Henog) van die vloed weerhou is. En as gevolg van hom (sy Getuienis) het Vader die water van die vloed oor die hele Land van Eden gebring; (= 5:26) want hy was daar gevestig as ‘n Teken, om Getuienis teen al die seuns van Adam te gee, en ‘n Register van al die dade, van al die geslagte tot die Dag van Oordeel te hou. 	",
"	25 En hy het die wierook van die Gereserveerde Plek op die Berg gebrand, wat voor die Meester aanvaarbaar is. 	",
"	26 Want die Meester het vier Volmaakte Plekke op aarde — die Tuin van Eden, die Berg van die ooste, hierdie Berg waarop jy vandag is (Berg Sinai), en die Berg Sion, wat in die Nuwe Skepping afgesonder sal wees vir die Reiniging van die aarde: daardeur sal die aarde Gesuiwer word van al sy skuld en onsuiwerheid, in elke Suksesvolle geslag. 	",
"	27 en in die veertiende Jubileum het Metúsalag ‘n vrou, Ednah, die dogter van Azariel, sy vader se broer [dogter] geneem, in die derde week, in die eerste jaar van hierdie week, en hy het ‘n seun verkry, en hom Lameg genoem. 	",
"	28 En in die vyftiende Jubileum, in die derde week, het Lameg ‘n vrou geneem, en haar naam was Betenos, die dogter van Barachel, sy vader se broer [dogter]; en in hierdie week het sy vir hom ‘n seun gebaar, en hy het hom Noag genoem, en gesê: Die een wat my in my probleme en al my werk sal vertroos, en die grond wat die Meester Vervloek het. 	",
"	29 En teen die einde van die negentiende Jubileum, in die sewende week, in die sesde jaar daarvan, het Adam gesterf; en al sy kinders het hom in die land waar hy geskape was, begrawe [ en hy was die eerste op aarde om begrawe te word]. 	",
"	30 En hy was sewentig jaar minder as ‘n duisend; want in die Testament van die Hemele is ‘n duisend jaar soos een dag, en dit verduidelik waarom dit oor die boom van kennis geskryf is, op die dag wat jy daarvan eet, sal jy sterf. Hy het dus nie die jare van hierdie dag voltooi nie, maar gedurende die dag gesterf. (Hierdie vers is niks anders as ‘n oorskrywer se eie siening nie, want die dag wat Adam van die “vrugte” geëet het, was hy uit die Paradys gewerp, gesterf — weg van die teenwoordigheid van Vader — en van daar af poog alle Adamiete om deur aanbiedinge {dade van Geregtigheid} weer die Guns van Vader te wen, en JaHshua het daardie Pad vir ons kom illustreer, sodat ons weer in die Paradys, Vader se teenwoordigheid, opgeneem kan word = Efés. 2:1-:10) 	",
"	31 Na hom, teen die einde van hierdie Jubileum, was Kain gedood, in dieselfde jaar: het sy huis op hom geval en hy het binne in die huis gesterf en was deur die klippe daarvan gedood; want met ‘n klip het hy HaaBeL (Abel) gedood, en deur ‘n soortgelyke vergelding was hy deur ‘n klip gedood. (= Opreg. 1:25 = Opreg. 2:23-:31) 	",
"	32 Daar is ‘n Reël omtrent hierdie, in die Hemelse Tafels: Met die voorwerp waarmee een man ‘n ander man dood, met dieselfde voorwerp sal hy gedood word (= Matt. 26:52): as hy ‘n man ‘n bepaalde besering aangedoen het, sal dieselfde besering hom aangedoen word. (= Matt. 5:38 = Lev. 24:19-:20) 	",
"	33 En in die vyf-en-twintigste Jubileum het Noag ‘n vrou geneem, en haar naam was Emzara, die dogter van Rakeel, sy vader se broer [dogter], in die eerste jaar, in die vyfde week; en in die derde jaar daarvan het sy Sem vir hom gebaar, in die vyfde jaar daarvan het sy Gam vir hom gebaar, en in die eerste jaar van die sesde week het sy Jafet vir hom gebaar.	",


]
},
{
book: 'Jubileum',
chapter: '5',
content: [
		
"	1 En dit het gebeur, toe die seuns van Adam op die aarde begin vermeerder het, en dogters vir hulle gebore was, dat in die eerste jaar van hierdie Jubileum, die Engele van Vader na hulle gekyk en gesien het dat hulle mooi was; en het vir hulle vroue geneem, soveel as wat hulle wou hê. 	",
"	2 En hulle het vir hulle seuns gebaar wat reuse was. En Wetteloosheid het op die aarde vermeerder, en die lewenswyse van elke skepsel het eenders korrup geword — Adamiete, vee, wilde diere en voëls, elke ding wat op aarde leef: Almal van hulle se weë was korrup en die hele Natuurlike Orde; en hulle het begin om die een die ander te verslind. En Wetteloosheid het op die aarde toegeneem, en die gedagtes en neigings van die Adamiet was nooit enigiets anders as boos nie. 	",
"	3 En Vader het na die aarde gekyk en gesien, dit was korrup: die hele Natuurlike Orde was korrup; en alle skepsels op aarde het, in Sy Oë, elke soort boosheid, gedoen.	",
"	4 En Hy het gesê: Hy sal die Adamiet en alle vlees wat Hy op die aarde Geskape het, vernietig. 	",
"	5 Noag het alleen Guns by die Meester gevind. 	",
"	6 En teen die Engele wat Hy na die aarde gestuur het, was Sy Toorn so groot dat Hy hulle van hulle gesagsgebied ontwortel het en ons Beveel het om hulle in die dieptes van die aarde gevange te hou; en kyk, hulle is daar in gevangenis en word in ‘n aparte plek gehou. 	",
"	7 En teen hulle seuns het ‘n Gebod van Hom uitgegaan, dat hulle deur die swaard gedood moes word, en van onder die Hemel verwyder word. 	",
"	8 En ‘n Stem het van Hom af uitgegaan, en gesê: My Gees sal nie vir altyd in die Adamiet bly nie; want hulle is ook vleeslik (verleibaar), en hulle leeftyd sal honderd-en-twintig jaar wees. 	",
"	9 En Hy het die Swaard onder hulle gestuur, sodat hulle mekaar moes dood; en hulle het begin om mekaar te dood, totdat almal van hulle deur die Swaard geval en van die aarde vernietig was. 	",
"	10 En hulle vaders was getuies van hulle vernietiging; en hierna was hulle vir ewig gevange geneem in die dieptes van die aarde, tot die Groot Oordeelsdag, wanneer Vonnis oor daardie wie se leefwyse en gedagtes, in die Oë van die Meester, korrup was. 	",
"	11 En Hy sal almal van hulle, van hulle plekke vernietig, en nie een sal oorbly wat Hy nie sal Oordeel, volgens die verdienste van hulle Wetteloosheid nie. 	",
"	12 En Hy sal ‘n Nuwe en Regverdige Natuur vir al Sy Werke Formeer, sodat hulle in hulle Natuur nooit weer sal sondig nie, maar almal altyd Regverdig sal wees, elkeen in sy soort. (= I Jhg. 3:1-:12) 	",
"	13 En die Oordeel van elkeen is bepaal en op die Hemelse Tafels geskryf, en daar is geen Ongeregtigheid daarin nie: almal wat van die Pad wat vir hulle uitgemerk is om te volg, verdwaal en dit nie volg nie — Oordeel is vir hulle neergeskryf, vir elke skepsel en vir elke soort skepsel. 	",
"	14 En daar is niks in die Hemel of aarde, of in Lig of duisternis, of in die doderyk of in die diepte, of in die plek van duisternis, wat nie Geoordeel sal word nie; en al hulle Oordele is Bepaal en Neergeskryf en Gegraveer. (= Jhg. 8:8 = Jir. 17:13) 	",
"	15 Uit elke oogpunt sal Hy hulle Oordeel, die grootse man as ‘n groot man, die klein man (nederige) as ‘n klein man, en elkeen volgens sy manier van lewe. 	",
"	16 En Hy is nie een om die persoon in ag te neem nie, Hy is ook nie een wat omkoopgeskenke sal aanneem nie, wanneer Hy sê dat Hy Vonnis oor elkeen sal uitspreek: as iemand Hom enigiets op die aarde sou gee, sou Hy nie aandag gee aan die omkoopgeskenk of aan die persoon van enigiemand, Hy sou ook nie enigiets uit sy hande aanneem nie; want Hy is ‘n Regverdige Regter. 	",
"	17 En aangaande die seuns van JisraEl was dit Geskryf en Bepaal, as hulle in Geregtigheid berou het, sal Hy al hulle oortredinge vergewe en hulle sonde kwytskeld. (= Jeség. 18:21-:23) 	",
"	18 Dit is Geskryf en Bepaal dat Hy eenmaal elke jaar Genade sal toon, aan al daardie wat berou het oor al hulle sonde wat hulle onopsetlik gedoen het. 	",
"	19 En wat al daardie betref wie se lewe en gedagtes voor die vloed korrup geword het, was aan geen man Genade betoon, behalwe Noag: Genade was aan hom, sowel as sy seuns betoon, wie Vader van die waters van die vloed gered het ter wille van hom; want sy hart was Regverdig in al sy weë en sy lewe ooreenkomstig met wat Hy Beveel het, en hy het op geen wyse afgedwaal van die pad wat vir hom Uitgemerk was nie. 	",
"	20 En die Meester het gesê Hy sou elke ding op die droë land vernietig, Adamiet en vee, wilde diere en voëls, en elke ding wat op die aarde beweeg. 	",
"	21 En Hy het Noag Beveel om ‘n ark te bou, sodat Hy hom van die waters van die vloed kon red. 	",
"	22 En Noag het die ark gebou volgens al die besonderhede soos Hy hom Beveel het, in die sewe-en-twintigste1 Jubileum van jare, in die vyfde week in die vyfde jaar. 1Charles egter, ooreenkomstig met die Samaritaanse Kronieke en met die ondersteuning van die datums aan die einde van hoofstuk 4. Alle manuskripte verklaar “twee-en-twintig” 	",
"	23 En hy het in die sesde jaar daarvan ingegaan, in die tweede maand, vanaf die nuwemaan van die tweede maand tot op die sestiende dag daarvan. En hy en alles wat ons vir hom gebring het, het in die ark gegaan; en die Meester het dit van buite toegemaak, op die aand van die sewentiende. 	",
"	24 En die Meester het sewe vloedhekke van die hemel oopgemaak, en die mondings van die fonteine van die groot afgrond (sewe mondings in getal). 	",
"	25 En die vloedhekke het begin om vir veertig dae en veertig nagte water uit die hemel te giet, en die fonteine van die afgrond het ook waters opgestuur, totdat die hele wêreld vol water was. 	",
"	26 En die waters het oor die aarde vermeerder: vyftien el hoër as die hoogste berge het die waters gestyg, en die ark was bokant die aarde opgelig en het op die oppervlakte van die waters gedryf. 	",
"	27 En die water het vir vyf maande op die oppervlakte van die aarde gebly — vir ‘n honderd-en-vyftig dae. 	",
"	28 En die ark het gaan gestrand op die top van Lubar, een van die berge van Ararat. 	",
"	29 En in die vierde maand was die fonteine van die groot afgrond uitgeput en die vloedhekke van die hemel was bedwing; en op die nuwemaan van die sewende maand was al die mondings van die afgronde van die aarde geopen, en die water het begin afdaal in die bodemlose dieptes. 	",
"	30 En op die nuwe maan van die tiende maand was die kruine van die berge sigbaar; en op die nuwemaan van die eerste maand het die aarde sigbaar geword. 	",
"	31 En die waters het in die vyfde week op die hoër dele van die aarde opgedroog, in die sewende jaar daarvan; en op die sewentiende dag van die tweede maand was die aarde droog. 	",
"	32 En op die sewe-en-twintigste dag daarvan, het Hy die ark oopgemaak, en die wilde diere en beeste en voëls en elke bewegende ding laat uitgaan.	",

]
},
{
book: 'Jubileum',
chapter: '6',
content: [
		
"	1 En op die nuwemaan [tiende dag] van die derde maand het hy uit die ark gegaan en op daardie berg [daardie land] ‘n altaar gebou. 	",
"	2 En hy het versoening vir die aarde gedoen, en ‘n boklam geneem en deur die bloed versoening gedoen vir al die skuld van die aarde; want alles daarop was vernietig, afgesien van wat saam met Noag in die ark was. 	",
"	3 En hy het die vet daarvan op die altaar gesit; en hy het ‘n os geneem, en ‘n bokram, en ‘n skaap, en boklammers en sout, en ‘n tortelduif, en jong duiwe, en dit as ‘n geheel op die altaar aangebied, en ‘n aanbieding met olie gemeng daaroor uitgegiet. en wyn gesprinkel en wierook oor alles gestrooi, en ‘n welriekende geur gemaak, aanneemlik vir die Meester. 	",
"	4 En die Meester het die welriekende geur geruik; en Hy het met hom ‘n Verbond gesluit, dat daar nooit weer ‘n vloed sal wees om die aarde te vernietig nie, dat terwyl die aarde bestaan, saaityd en oestyd nooit sou eindig nie, en dat koue en hitte, somer en winter, en dag en nag, nie hulle Orde sou verander of ooit ophou nie. 	",
"	5 En Hy het vir Noag gesê: Wees vrugbaar en vermeerder op die aarde, vermeerder in getal daarop, en wees ‘n Seën daarop. Ek sal die vrees en skrik op jou inspireer in elke ding op aarde en in die see. 	",
"	6 En kyk, Ek gee al die wilde diere en voëls en die vee op aarde, en die vis in die waters — dit is, alle dinge: soos Ek eens aan jou die groen plante gegee het, gee Ek jou nou alle dinge om te eet. 	",
"	7 Maar jy mag nie vlees eet met die lewe nog daarin eet nie — dit is, die bloed [want die lewe van alle vlees is in die bloed], sodat jou eie bloed nie geëis word nie. Van elke Adamiet, van elke dier [elke een], sal Ek die bloed van die Adamiet eis. 	",
"	8 Wie ookal die bloed van die Adamiet vergiet, deur die Adamiet sal sy bloed vergiet word; want Hy het die Adamiet na die Beeld van Vader gemaak. 	",
"	9 En wees julle vrugbaar en vermeerder op die aarde. 	",
"	10 En Noag en sy seuns het gesweer dat hulle geen bloed in enige vlees sou eet nie; en in hierdie maand het hy ‘n Ewige Verbond voor die Meester Vader gesluit, vir elke geslag van die aarde. 	",
"	11 Dit was om hierdie rede dat Hy (Vader) in hierdie maand ook vir jou (Moshè) gesê het om ‘n Verbond met die seuns van JisraEl op die berg met ‘n eed te sluit, en om bloed oor hulle te sprenkel om die Voorwaardes van die Verbond te bekragtig, wat die Meester vir Ewig met hulle gesluit het. 	",
"	12 En hierdie Bepaling is daar Geskryf vir julle om voortdurend waar te neem, naamlik, dat julle nooit enige bloed van wilde diere of voëls of vee behoort te eet nie, vir solank as die aarde bestaan; en enigeen wat die bloed van wilde diere, of vee, of voëls ter eniger tyd eet, hy en sy nageslag sal uit die land ontwortel word. 	",
"	13 Beveel die seuns van JisraEl, om nooit enigsins enige bloed te eet nie, sodat hulle name en hulle nageslag voortdurend voor die Meester ons Vader mag wees. 	",
"	14 En vir hierdie Wet is daar geen tydsbeperking nie: dit is vir Ewig. Hulle sal dit in elke geslag waarneem, sodat hulle elke dag gereeld, om hulle onthalwe, met bloed voor die altaar versoening kan doen: Hulle sal in die oggend en in die aand, ewigdurend voor die Meester, om hulle onthalwe, vergewing begeer, dat hulle dit kan onderhou en nie ontwortel word nie. 	",
"	15 En Hy het vir Noag en sy seuns ‘n Teken gegee, dat daar nooit weer op die aarde ‘n vloed sou wees nie.	",
"	16 Hy het Sy Boog in die wolk gestel as ‘n Teken van die Ewige Verbond, dat daar nooit weer ‘n vloed op die aarde sou wees om dit te vernietig nie. 	",
"	17 Dit is waarom dit bepaal en op die Hemelse Tafels Geskryf is, dat hulle die Fees van die weke in hierdie maand, een maal per jaar sou vier — Om die Verbond dus elke jaar te hernieu. 	",
"	18 En hierdie hele Fees was altyd in die Hemel gevier, van die dag van Skepping, tot op die dae van Noag [vir ses-en-twintig Jubileums en vyf weke van jare]; en Noag en sy seuns het dit vir sewe Jubileums en ‘n week van jare gehou, tot op die dag van Noag se dood, maar na Noag se dood het sy seuns korrup geword, en tot op die dae van Abraham bloed geëet. 	",
"	19 Nogtans het Abraham dit gehou, en Isak en Jakob en sy kinders het dit gehou, tot op julle dae; maar in julle dae het die seuns van JisraEl dit vergeet, totdat Ek dit by hierdie berg met hulle Herstel het. 	",
"	20 Beveel dus die kinders van JisraEl, om hierdie Fees in elke geslag te hou, as ‘n bindende Bevel op hulle: Op een dag [op die Eerste dag van die week] in die jaar, in hierdie maand, sal hulle die Fees vier. 	",
"	21 Dit is die Fees van weke en die Fees van Eerste Vrugte, ‘n tweevoudige en dubbele Fees: vier dit dan soos julle geleer was, volgens wat Geskryf en Gegraveer is, wat dit betref. 	",
"	22 Want Ek het in die Boek van die Eerste Wet Geskryf, wat Ek vir julle Geskryf het, dat julle dit op die aangewese tyd behoort te vier, op een dag van die jaar, en Ek het aan julle die besonderhede van die Fees se aanbiedinge verduidelik, sodat die seuns van JisraEl dit kan onthou en dit in elke geslag kan vier, in hierdie maand, op een dag, elke jaar. 	",
"	23 En op die nuwemaan van die eerste maand, en op die nuwemaan in die vierde maand, en op die nuwemaan in die sewende maand, en op die nuwemaan van die tiende maand is die dae van herinnering, ook feestelike dae, wat die vier verdelings van die jaar aandui: hierdie is Geskryf en Bepaal as ‘n Bewys vir Ewig. (= Gnk. 75:1-:2) 	",
"	24 En Noag het ook hierdie dae gehou en as Feeste bepaal vir die komende geslagte vir Ewig, sodat dit vir hom ‘n herdenking geword het. 	",
"	25 Op die nuwemaan van die eerste maand was hy aangesê om vir hom ‘n ark te bou, en die aarde was op daardie dag weer droog, en hy het die venster van die ark oopgemaak en die aarde gesien: 26 op die nuwemaan van die vierde maand was die mondings van die dieptes van die afgrond onder, toegemaak: op die nuwemaan van die sewende maand was die monding van die dieptes van die aarde geopen, en die waters het begin om daarin af te daal; 	",
"	27 en op die nuwemaan van die tiende maand was die kruine van die berge sigbaar, en Noag was verheug. 	",
"	28 So was dit dat hy dit waargeneem en as Feeste bepaal het, as ‘n Gedenkteken vir Ewig; en so is die Feeste bepaal. 	",
"	29 En dit is op die Hemelse Tafels Geskryf: daar is ‘n tussenpose van dertien weke tussen elke Fees en die volgende een, van die eerste tot die tweede, van die tweede tot die derde, en van die derde tot die vierde. 	",
"	30 En al die dae van die Bevel is twee-en-vyftig weke van dae, en saam maak dit ‘n volle jaar: Aldus is dit op die Hemelse Tafels Gegraveer en Bepaal. 	",
"	31 En geen jaar oorskry dit ooit. 	",
"	32 Beveel dus die seuns van JisraEl, om die jare te hou volgens hierdie berekening — driehonderd-vier-en-sestig dae; en hierdie sal ‘n volledige jaar voltooi. En hulle sal nie die tye van die dae van die jaar of die tye van die dae van die Feeste verander nie [want elke ding moet op sy vasgestelde plek volg]; en hulle sal nie een dag weglaat of enige Fees oorslaan nie. 	",
"	33 Maar as hulle die korrekte orde verontagsaam en nalaat om dit te onderhou, soos Hy dit Beveel het, dan sal al hulle seisoene buite orde raak en die volgorde van die jaar sal versteur wees. 	",
"	34 Nogtans sal al die seuns van JisraEl vergeet en onkundig wees ten opsigte van die voortgang van die jare [en sal nie die pad van die jare vind nie]: Hulle sal nuwemaan en Fees en Sabbat vergeet, en op die manier fouteer, wat die orde van die jare betref. 	",
"	35 Want ek weet, en ek sê julle nou, en dit is nie iets wat ek my verbeel het nie; want die Boek lê Geskryf voor my, en op die Hemelse Tafels is die verdeling van die dae Bepaal, sodat hulle nie die Feeste van die Verbond sou vergeet en wandel volgens die feeste van die heidene nie, en hulleself gelykstaande mislei en onkundig betoon. 	",
"	36 Daar sal daardie wees wat versigtig waarnemings van die maan sal maak [ten spyte van die feit dat dit die seisoene omverwerp en van jaar tot jaar tien dae te vroeg verskyn]. 	",
"	37 Aldus sal die jare vir hulle heeltemal verkeerd uitwerk: hulle sal die dag van Getuienis ‘n dag van veragting maak, en ‘n gewone dag ‘n Feesdag; en hulle sal al die dae deurmekaar maak, die Afgesonderde met die gewone, en die gewone met die Afgesonderde, en fouteer aangaande die maande en Sabbatte en Feeste en Jubileums. 	",
"	38 Dit is waarom ek vir jou hierdie Gebod en plegtige waarskuwing gee, sodat jy dit aan hulle kan oordra; want na jou dood sal jou seuns alles omverwerp deur nie die lengte van die jaar net driehonderd-vier-en-sestig dae te maak nie, en so sal hulle verkeerd doen aangaande die nuwemane en seisoene en Sabbatte en Feeste; en hulle sal alle soorte vleis met die bloed steeds daarin eet.	",

]
},
{
book: 'Jubileum',
chapter: '7',
content: [
		
"	1 En in die sewende week van hierdie Jubileum, in die eerste jaar daarvan, het Noag ‘n wingerd op die berg wat Lubar genoem word, geplant, waarop die ark gestrand het [een van die Ararat berge]; en dit het vrug in die vierde jaar geproduseer, en hy het die vrugte opgepas en dit in hierdie jaar bymekaar gemaak, in die sewende maand. 	",
"	2 En hy het wyn daarvan gemaak en dit in ‘n houer geplaas en dit tot die vyfde jaar bewaar, tot die eerste dag van die nuwemaan van die eerste maand.µˆô.o 	",
"	3 En hy het hierdie Feesdag met vreugde gevier; en hy het ‘n Volledige aanbieding aan die Meester gebied — een jong os, een ram, sewe skape [elk ‘n jaar oud], en ‘n bokram, om daarmee vir hom en sy seuns versoening te doen. 	",
"	4 En hy het die boklam eerste voorberei, en van die bloed op die vleis, op die altaar wat hy gemaak het, geplaas, en al die vet het hy op die altaar neergelê, waar hy die Volledige-aanbieding aangebied het; en so het hy ook met die os gedoen, en die ram en die skape, en hy het al hulle vlees op die altaar neergelê. 	",
"	5 En hy het al hulle aanbiedinge, gemeng met olie, daarop geplaas. En daarna het hy wyn op die vuur wat hy vooraf op die altaar gemaak het, gesprinkel, en wierook op die altaar gesit, en ‘n welriekende geur, aanneemlik vir die Meester sy Vader gemaak. 	",
"	6 En hy was verheug en het van hierdie wyn met vreugde gedrink, hy en sy kinders. 	",
"	7 En dit was aand, en hy het in sy tent gegaan en in ‘n dronk bedwelming gaan lê, en aan die slaap geraak; en hy het naak in sy tent gelê en slaap. 	",
"	8 En Gam het sy vader Noag naak gesien, en uitgegaan en sy twee broers vertel. 	",
"	9 En Sem het sy mantel geneem en opgestaan, hy en Jafet, en hulle het die mantel op hulle skouers geplaas en met hul gesigte na agter gedraai, hulle vader se skaamte bedek. (:8-:9 = Lev. 18:7-:8) 	",
"	10 En Noag het uit sy slaap wakker geword en uitgevind wat sy jonger seun hom aangedoen het; en hy het sy seun vervloek, en gesê: Vervloek is Kanaän: ‘n Dienskneg en slaaf sal hy vir sy broers wees. (= Opreg. 73:35) 	",
"	11 En hy het Sem Geseën, en gesê: Geseënd is die Meester Vader van Sem, En Kanaän sal sy dienskneg wees: 	",
"	12 Vader sal vir Jafet ‘n ruim land gee; En Vader sal in die woning van Sem Bly, (= Jhg. 14:19-:23) En Kanaän sal sy dienskneg wees. 	",
"	13 En Gam het uitgevind dat sy vader sy jonger seun vervloek het, en hy was ontevrede omdat hy sy seun vervloek het; En hy het van sy vader geskei, hy en sy seuns saam met hom — Kus en Mitzrajim en Put [Mestrem en Fud] en Kanaän. 	",
"	14 En Hy het vir hom ‘n stad gebou en dit na sy vrou vernoem, Naeltamauk. 	",
"	15 En Jafet het dit gesien, en was afgunstig op sy broer, en hy het ook vir hom ‘n stad gebou en dit na sy vrou vernoem, Adataneses. 	",
"	16 En Sem het saam met sy vader Noag gewoon; en hy het ‘n stad onder sy vader se gesag by die berg gebou, en ook hy het dit na sy vrou vernoem, Sedeqatelebab. 	",
"	17 En kyk, hierdie drie stede is naby die berg Lubar. Sedeqatelebab aan die oostekant van die berg gerig, Naeltamauk aan die suide, en Adataneses aan die westekant. 	",
"	18 En hierdie is die seuns van Sem — Elam en Assur en Arpagsad [gebore, twee jaar na die vloed] en Aram en Lud: die seuns van Jafet — Gomer en Magog en Madai en Jawan, Tubal en Meseg en Tiras. Hierdie is die seuns van Noag. 	",
"	20 En in die agt-en-twintigste Jubileum het Noag begin om sy kleinseuns te Onderrig in die Voorskrifte en Wette, en in al die Verordeninge wat hy geken het; en hy het sy seuns vermaan om te doen wat reg is, om die skaamte van hul vlees te bedek, om hulle Skepper te Seën, om vader en moeder te eer, om elkeen sy naaste Lief te hê, en om hulle te weerhou van hoerery en onreinheid en alle ongeregtigheid. 	",
"	21 Want dit was as gevolg van hierdie drie dinge, het Noag vir hulle gesê, dat die vloed oor die aarde gekom het — as gevolg van die owerspel van die Wagters, wat, teenstrydig met die Wet van hulle Natuur, vurig verlang het na die dogters van Adam en vir hulle vroue geneem het, na hulle keuse: dit was die begin van onreinheid. 	",
"	22 En hulle het seuns gebaar, die Nefilim, en hulle het almal met mekaar getwis, en hulle het die een die ander verslind: die reus het die Nefilim gedood, die Nefilim het die Eljo gedood, en die Eljo die Adamsgeslag, en een Adamiet ‘n ander Adamiet. (= Gnk. 7:1-:6) 	",
"	23 En elkeen het homself verkoop om te doen wat verkeerd was en om baie bloed te vergiet; en die aarde was met ongeregtigheid gevul. 	",
"	24 En hierna het hulle teen die wilde diere en voëls en elke ding wat op die aarde beweeg en loop gesondig; en baie bloed was op die aarde vergiet, en al die Adamiete se neigings en begeertes was na wat nutteloos was, en het voortdurend gesondig. 	",
"	25 En die Meester het alles op die aarde vernietig, as gevolg van die boosheid van hulle dade; en as gevolg van die bloed wat hulle op die aarde vergiet het, het Hy alles vernietig. 	",
"	26 En ons het oorgebly, ek en julle, my seuns, en elke ding wat saam met ons in die ark ingegaan het. En kyk, ek kan julle werke voor my sien, dat julle nie die Weg van Geregtigheid volg nie, want julle het begin om die pad na verdelging te betree: julle skei van mekaar en is afgunstig op mekaar, en so gebeur dit, my seuns, dat julle nie in harmonie leef nie, elkeen van julle met sy broer. 	",
"	27 Ek kan sien die demone het begin met hulle verleiding tussen julle en julle kinders; (= Jak. 1:12-:14) en ek is bevrees oor julle, dat julle na my dood, Adamiete se bloed op die aarde sal vergiet, en dat julle ook van die aarde vernietig sal word. 	",
"	28 Want wie ookal die Adamiet se bloed vergiet, en wie ookal die bloed van enige lewende skepsel eet, sal altesaam van die aarde vernietig word. 	",
"	29 En geen Adamiet wat bloed eet sal op die aarde oorbly nie, of wat die bloed van die Adamiet vergiet, daar sal ook nie vir hom enige afstammeling of nageslag onder die hemel gelaat word nie; want hulle sal na Doderyk toe gaan, en hulle sal na die plek van straf afgaan, en hulle sal almal verwyder word na die duisternis van die diepte deur ‘n gewelddadige dood. 	",
"	30 Daar mag geen bloed op julle gesien word, van enige van die bloed wat vergiet is, wanneer julle enige dier, of vee, of voël op die aarde dood nie; en doen dan wat Reg is, en bedek wat op die aarde vergiet is. 	",
"	31 En julle mag nie soos die Adamiet wees wat vlees met bloed nog daarin eet nie, en wees versigtig dat niemand in julle teenwoordigheid bloed eet nie: bedek die bloed (= Rom. 3:24), want so was ek Beveel om julle en julle kinders en die hele Adamsgeslag te Onderrig. 	",
"	32 Moet nooit toelaat dat die siel saam met die vlees geëet word nie (ongehoorsaamheid = Jak. 1:12), sodat jou bloed (waarin jou siel is) nie deur enige skepsel (vleeslikheid), wat dit op die aarde giet (verlei is = Jak. 1:14), opgeëis word nie (tweede dood = Jak. 1:15). (= Judas. 1:11 + Deut. 34:4 + Heb. 3:5 + Ex. 34:7) (:31-:32 = Rom. 3:25-:26) 	",
"	33 Want die aarde sal nie Gereinig wees van die bloed wat daarop vergiet is nie: slegs deur die bloed van hom wat dit vergiet het, sal die aarde gesuiwer word, deur al die geslagte heen. (= Jeség. 3:17-:21 = Gen. 9:5-:6 = I Jhg. 5:5-:8) 	",
"	34 En nou, my kinders, luister: Handel Regverdig en doen wat Reg is, sodat julle in Geregtigheid oor die hele aarde geplant word, en julle roem voor my Vader verhef word, wat ons van die waters van die vloed gered het. 	",
"	35 En kyk julle sal vir julle stede gaan bou, en julle sal daarin plant, al die plante wat daar op die aarde is, en ook alle bome wat vrugte dra. 	",
"	36 Vir drie jaar mag die vrugte van alles wat geëet kan word, nie versamel word nie; en in die vierde jaar mag die vrugte ingesamel word, en hulle sal die Eerstelingvrugte aanbied, aanvaarbaar voor die Allerhoogste Vader, wat hemel en aarde en alle dinge Geskape het. Laat hulle dit aanbied, besprinkel met die Eerste wyn en die olie, as Eerstelingvrugte op die altaar van die Meester, wat dit ontvang; en wat oorbly, laat die Diensknegte van die huis van die Meester voor die altaar eet, wat dit ontvang. 	",
"	37 En laat die land in die sewende jaar braak lê, sodat julle dit in Geregtigheid en Eerlikheid laat braak lê; en julle sal Regverdig wees, en al julle boorde sal volgens Ritueel Suiwer wees. 	",
"	38 Want so het die vader van julle vader, GaNoWK sy seun Matusalag beveel, en Matusalag, sy seun Lameg, en Lameg het my beveel om alles te onderhou wat sy vaders hom beveel het. 	",
"	39 En ek gee julle ook ‘n bevel, my seuns. soos GaNoWK sy seun in die eerste Jubileum beveel het: terwyl hy nog gelewe het, die sewende in sy geslag, hy het sy seun en sy kleinseuns beveel en Onderrig tot die dag van sy dood.	",


]
},
{
book: 'Jubileum',
chapter: '8',
content: [
		
"	1 In die nege-en-twintigste Jubileum, in die eerste week, in die begin daarvan, het Arpagsad ‘n vrou geneem, en haar naam was Rasuejah, die dogter van Susan, Elam se dogter; en sy het vir hom ‘n seun gebaar, in die derde jaar van hierdie week, en hy het hom Kainam genoem. 	",
"	2 En die seun het grootgeword, en sy vader het hom uit die Boeke geleer; en hy het gaan kyk na ‘n plek waar hy ‘n stad kon stig. 	",
"	3 En hy het op ‘n geskrif afgekom wat sommige manne van die outyd op ‘n rots gegraveer het, en hy het gelees wat daarop geskryf was en dit uitgelê; en hy het as gevolg daarvan gesondig, want dit het die lering van die Wagters bevat, in ooreenstemming met wat hulle gebruik het, om die voorspellings van die son, maan en sterre en al die tekens van die hemel waar te neem. 	",
"	4 En hy het dit neergeskryf en niks daaromtrent gesê nie; want hy was bang om Noag daarvan te vertel, vir ingeval hy vir hom kwaad sou wees as gevolg daarvan. 	",
"	5 En in die dertigste Jubileum, in die tweede week, in die eerste jaar daarvan, het hy ‘n vrou geneem, en haar naam was Melka, die dogter van Abadai, Jafet se seun; en in die vierde jaar het sy vir hom ‘n seun gebaar, en hy het hom Shelah genoem, want hy het gesê: Waarlik, ek was gestuur. 	",
"	6 En Shelah het grootgeword en ‘n vrou geneem, en haar naam was Muak, die dogter van Kesed, sy vader se broer: dit was in die een-en-dertigste Jubileum, in die vyfde week, in die eerste jaar daarvan. 	",
"	7 En sy het vir hom ‘n seun in die vyfde jaar daarvan gebaar, en hy het hom Eber genoem; en hy het ‘n vrou geneem, en haar naam was Azurad, die dogter van Nimrod – in die twee-en-dertigste Jubileum, in die sewende week, in die derde jaar daarvan. 	",
"	8 En in die sesde jaar daarvan, het sy vir hom ‘n seun gebaar, en hy het hom Peleg genoem, want in die dae toe hy gebore was, het Noag se seuns begin om die aarde onder hulle te verdeel [dit is waarom hy hom Peleg genoem het]. 	",
"	9 En hulle het dit (sonder die medewete van Noag, onwettig: :11) in die geheim onder mekaar verdeel, en hulle het Noag daarvan vertel. 	",
"	10 En dit was in die begin van die drie-en-dertigste Jubileum dat hulle die aarde in drie dele verdeel het, een deel vir Sem en een vir Gam en een vir Jafet, in ooreenstemming met elkeen se erfdeel, in die eerste jaar, van die eerste week, terwyl een van ons, wat na hulle gestuur was, by hulle was. 	",
"	11 En hy het sy seuns geroep, en hulle het na hom toe gekom, hulle en hulle kinders; en hy het die aarde deur loting in persele opgedeel (:18 + 20), na wat elkeen van sy drie seuns behoort te hê, en hulle het hul hande uitgestrek en hul loot van hul vader Noag, se skoot geneem. 	",
"	12 En Sem het as sy loot getrek, die middel van die aarde, om dit te neem as sy vaderlike erfdeel en sy seuns se vaderlike erfdeel vir ewig – van die middel van die bergreeks van Rafa, van die monding van die rivier Tina af; en sy deel gaan weswaarts in die middel van hierdie rivier en brei uit sovêr as die water van die afgronde, waaruit hierdie rivier ontstaan en sy water in die see van Miot giet, en hierdie rivier vloei in die groot see [en alles wat ten noorde is, is Jafet s’n en alles ten suide daarvan behoort aan Sem]. 	",
"	13 En dit brei sovêr as Karaso uit – dit is in die hart van die tong wat suid kyk. 	",
"	14 En sy deel brei langs die groot see uit, in ‘n reguit lyn tot dit die weste bereik van die tong wat suid kyk; want hierdie see word die tong van die Egiptiese see genoem. 	",
"	15 En dit draai van hier suidwaarts, na die mond van die groot see, op die strande van die waters; en dit brei uit na die weste van Afra sovêr as die waters van die rivier Gihon, en na die suide van die waters van Gihon, na die banke van hierdie rivier. 	",
"	16 en dit brei na die ooste uit, sovêr as die tuin van Eden, na die suide daarvan, [na die suide] en van die ooste van die hele land van Eden en van die hele ooste, en dit draai na die ooste en gaan voort tot dit die ooste van die berg wat Rafa genoem word bereik, en dit gaan af na die bank van die monding van die rivier Tina.1 1 Daar is duidelik geografiese verwarring in hierdie vers. Charles het voorgestel om “noord” vir “suid” te lees [en ook “wes” vir “oos” in die sinsdeel “en dit draai na die ooste”]. In latere Etiohopiese tradisie, en in sommige hoofstukke van Jubileum, was die woorde van “noord” en “suid” gereeld teenoorgestelde betekenisse gegee. 	",
"	17 Hierdie deel het deur die lot op Sem en sy seuns geval, as ‘n ewige besitting vir sy nakomelinge vir ewig. 	",
"	18 En Noag was verheug dat hierdie deel op Sem en sy seuns geval het, en hy het alles onthou wat hy met sy mond geuiter het in sy Profesie; want hy het gesê: Geseënd sal wees, die Meester Vader van Sem, En mag die Meester woon in die wonings van Sem. 	",
"	19 En hy het geweet dat die tuin van Eden die Volmaakte van Volmaaktheid is, en die Meester se Woonplek, en die Berg Sinai die middel van die woestyn, en die berg Sion die middel van die nawel van die aarde is: hierdie drie was geskape as Gereserveerde Plekke wat teenoor mekaar staan. 	",
"	20 En hy het die Vader van die vaders Geseën, wat die Meester se Woord in sy mond gegee het, selfs die Meester vir Ewig. 	",
"	21 En hy het geweet dat Sem en sy seuns vir Ewig Geseën is – die hele Land van Eden en die hele land van die Rooi-See, en die hele land van die ooste, en Indië, en Edom en die berge daarvan, en die hele land van Basor en die hele land van Líbanon en die eilande van Caphtor, en al die berge van Senir en Amana, en die berge van Assur in die noorde, en die hele land van Elam, Assur, en Babel, en Susa, en Media, en al die berge van Ararat, en die hele streek oorkant die see, wat noordwaarts van die berge van Assur is, ‘n geseënde en uitgestrekte land, en alles wat daarin is, is baie goed. 	",
"	22 En Gam het die tweede deel getrek – wat suidwaarts, anderkant die Gihon lê, na die regterkant van die Tuin; en dit strek na die suide sovêr as al die gloeiende berge; en dit strek weswaarts na die see van Atel en nog vêrder tot dit die see Mauk [dit is die see waarin alles wat tot niet gaan wegsink] bereik. 	",
"	23 En dit gaan noordwaarts tot die grense van Gadir en uit na die kus van die waters van die see, na die waters van die groot see, tot dit die rivier Gihon bereik, en die rivier Gihon gaan voort tot dit die regterkant van die Tuin van Eden bereik. 	",
"	24 En dit is die land wat in die verdeling aan Gam deur die lot toegeval het, wat hy vir ewig moes beset, hy en sy seuns, van geslag tot geslag, vir ewig. 	",
"	25 En Jafet het die derde deel getrek – wat anderkant die rivier Tina lê, na die noorde van sy waters se uitloop; en dit strek na die noordooste na die hele streek van Gog en na die hele land oos daarvan. 	",
"	26 En dit strek noordwaarts sovêr as die berg Qelt en na die see van Mauk; en verder tot die ooste van Gadir, sovêr as die streek van die waters van die see. 	",
"	27 En vêrder tot dit die weste van Fara [Fera Of Fereg] bereik, en keer terug na Aferag [Afreg]; en dit strek ooswaarts na die waters van die see van Mauk. 	",
"	28 En in die noordoostelike rigting strek dit na die streek van die rivier Tina tot dit die grens van die waters in die rigting van die berg Rafa bereik; en dan keer dit terug na die noorde. 	",
"	29 Dit is die land wat tot Jafet en sy seuns geval het as hulle deel om te behou as hulle vaderlike erfdeel, geslag na geslag, vir ewig – vyf groot eilande, en ‘n groot stuk land in die noorde. 	",
"	30 Maar dit is koud. Gam se land is warm. En Sem se land in nie warm of koud nie, maar ‘n mengsel van koue en hitte.	",

]
},
{
book: 'Jubileum',
chapter: '9',
content: [
		
"	1 En Gam het sy land onder sy seuns verdeel; en die eerste deel het aan Kuwsh toegeval – dit is die oostelike deel, en aan sy weste was Mitzrajim, en aan sy weste was Put, en aan sy weste was Kanaän, en aan sy weste die see. 	",
"	2 En Sem het ook sy land onder sy seuns verdeel; en die eerste deel het Elam en sy seuns toegeval – wat oos van die rivier Tigris lê tot aan die ooste, die hele land van Indië, en die kus van die Rooi-See, en die waters van Dedan, en al die berge van Mebri en Ela [Matzbara en Elam], en die hele land Susa, en alles wat aan die kant van Pharnak is tot aan die Rooi-See en die rivier Tina. 	",
"	3 En die tweede deel het op Assur geval – die hele land van Assur en Ninevé en Sínear tot by die grens van Indië en dit gaan op na die rivier Wadafa. 	",
"	4 En die derde deel het op Arpagsad geval – die hele land van die streek van die Chaldeërs tot die ooste van die Eufraat, wat aan die Rooi-See grens. en al die waters van die woestyn naby die tong van die see wat na Egipte uitstrek, die hele land van Líbanon en Senir en Amana tot by die grens van die Eufraat. 5 En die vierde deel het op Aram geval – die hele land van Mesopotamië tussen die Tigris en die Eufraat tot aan die noorde van die Chaldeërs, na waar dit die berge van Assur en die land van Ararat bereik. 6 En die vyfde deel het op Lud geval – die berge van Assur en alles wat aan hulle behoort tot dit die groot see bereik, en tot dit die ooste van sy broer Assur bereik. 	",
"	5 En Jafet het ook die land van sy vaderlike erfdeel onder sy seuns verdeel. 	",
"	6 En die eerste deel het op Gomer geval – wat na die ooste lê, van die noordekant na die rivier Tina. En in die noorde het daar tot Magog geval die hele noordelike binneland, tot dit die see van Mauk bereik. 	",
"	7 En tot Madai het as sy deel geval, om te beset, wat wes van sy twee broers lê tot by die eilande en die kusdele van die eilande. 	",
"	8 En die vierde deel het tot Jawan geval – Al die eilande na die grens van Lud. 	",
"	9 En die vyfde deel het tot Tubal geval – wat in die middel van die tong lê wat strek in die rigting van die grens van Lud se deel, sovêr as die tweede tong, sovêr as die streek anderkant die tweede tong, tot by die derde tong. 	",
"	10 En die sesde deel het op Meseg geval – die hele streek anderkant die derde tong tot by die ooste van Gadir. 	",
"	11 En die sewende deel het op Tiras geval – vier groot eilande in die middel van die see, wat strek tot by Gam se deel.[En die eilande van Kamaturi het deur die lot op die seuns van Arpagsad as deel van sy vaderlike erfdeel geval.] 	",
"	12 Op die manier het Noag se seuns hulle lande onder hulle seuns verdeel, in die teenwoordigheid van hulle vader, Noag; en hy het hulle almal deur ‘n eed gebind, ‘n vloek op elkeen geplaas wat probeer om, wat hom nie toegeval het nie, te buit. 	",
"	13 En hulle het almal gesê: Laat dit so wees, laat dit so wees, vir hulle en hulle seuns vir ewig, in elke geslag tot die dag van Oordeel, wanneer die Meester Vader hulle sal Oordeel met Swaard en Vuur vir al hulle onreinhede en die Wetteloosheid van hulle misdade, waarmee hulle die aarde gevul het – met oortreding en onreinheid en hoerery en sonde.	",

]
},
{
book: 'Jubileum',
chapter: '10',
content: [
		
"	1 En in die derde week van hierdie Jubileum het die onrein demone begin om die kinders van Noag se seuns op die verkeerde pad te lei en om hulle te mislei en te vernietig. (= Jak. 1:12-:15) 	",
"	2 En Noag se seuns het na hulle vader Noag gekom en hom vertel van die demone wat sy kleinseuns mislei en verblind en dood. 	",
"	3 En hy het tot die Meester sy Vader gebid, en gesê: Vader van die siele van die hele Adamsgeslag, wat Barmhartigheid aan my getoon het, En wat vir my en my seuns uit die water van die vloed gered het, En het my nie verlaat om tot niet te gaan soos wat U gedoen het aan die seuns wat tot vernietiging verdoem was; Want U Genade oor my was baie groot, En groot was U Barmhartigheid oor my siel. Laat U Genade oor my seuns, opgehemel word, En laat Wettelose geeste nie oor hulle heers En hulle van die aarde vernietig nie. 	",
"	4 Maar sal U my en my seuns Seën, dat ons vrugbaar mag wees, vermeerder, en die aarde vul. 5 En U weet wat U Wagters, die vaders van hierdie geeste, in my dag gedoen het; en wat hierdie geeste betref wat nou lewendig is, neem hulle gevange en bewaar hulle veilig in die plek van straf, en laat hulle nie vernietiging oor U dienskneg se seuns bring nie, my Vader, want hierdie is kwaadwillig, en geskep met die doel om te vernietig. 	",
"	5 En laat hulle geen heerskappy oor die siel van die lewende hê nie, want U alleen weet hoe om met hulle natuur te handel; en laat hulle geen mag oor die seuns van Geregtigheid hê nie, nie nou of ooit nie. 	",
"	6 En die Meester ons Vader het ons Beveel om hulle almal te bind. 	",
"	7 En Mastema, die hoof van die geeste, het gekom, en gesê: O Meester, Skepper, laat sommige van hulle voor my oorbly, en laat hulle luister na wat ek sê en alles doen wat ek vir hulle sê; want as sommige nie vir my gelaat word nie, sal ek nie in staat wees om oor Adamiete die mag uit te oefen wat ek wil nie; want hierdie is bestem vir verdorwenheid en om te laat afdwaal volgens my oordeel (siening), want groot is die Wetteloosheid van die Adamiet. (= Matt. 13:13-:15) 	",
"	8 En Hy het gesê: Laat ‘n tiende van hulle vir hom oorbly, en laat nege tiendes afgaan in die plek van straf. 	",
"	9 En Hy het een van ons Beveel om vir Noag al die middele teen hulle te leer [want Hy het geweet dat hulle nie Opregte lewens sou leef nie, ook nie eers probeer om te doen wat Reg is nie (= Deut. 31:16-:18)]. 	",
"	10 En ons het gedoen soos Hy ons Beveel het: al die kwaadwilliges en boosaardiges het ons in die plek van straf gevange gehou, en ‘n tiende het ons as agente van straf onder Satan op die aarde gelaat. (:8-:11 = 15:31) 	",
"	11 En ons het aan Noag al die middele teen hulle siektes verduidelik, (= Deut. 28:1-:14) saam met hulle bose uitwerkings, (= Deut. 28:15-:68) en hoe om hulle met die Bome van die aarde te genees. (= Open. 22:2) 	",
"	12 En Noag het alles in ‘n boek geskryf, soos ons hom Onderrig het, met betrekking tot elke soort geneesmiddel: so was die bose geeste daarvan weerhou om skade aan die seuns van Noag te doen. (= Deut. 6:1-:25 = Ps. 91:1-:16) 	",
"	13 En hy het alles wat hy geskryf het vir Sem, sy oudste seun gegee; want hy het hom bo al sy seuns die liefste gehad. (:12-:14 = 15:32 = 19:27-:29) 	",
"	14 En Noag het gesterf, en is by sy vaders op die berg Lubar in die land van Ararat begrawe. 	",
"	15 Hy het negehonderd-en-vyftig jaar oud geword – negentien Jubileums, twee weke en vyf jare. 	",
"	16 En in sy lewe op aarde het hy alle sterflike Adamiete oortref in die verwerwing van Volmaakte Regverdigheid, behalwe GaNoWK; want GaNoWK het ‘n spesiale amp gehad, om ‘n Getuie vir die wêreld se geslagte te wees, en om al die dade van elke geslag, tot op die Dag van Oordeel te rapporteer. 	",
"	17 En in die drie-en-dertigste Jubileum, in die eerste jaar, van die tweede week, het Peleg ‘n vrou geneem, wie se naam Lomna was, die dogter van Shinar; en sy het vir hom ‘n seun in die vierde jaar van hierdie week gebaar, en hy het hom Reu [boos] genoem, want, het hy gesê: Kyk, die seuns van Adam het sondig geword deur hulle Wettelose doel om ‘n stad en ‘n toring in die land van Sínear te bou. 	",
"	18 [Want hulle het die land Ararat verlaat en ooswaarts na Sínear beweeg; en in sy dae het hulle die stad en die toring gebou, en gesê: Kom laat ons daardeur opgaan na die Hemel.] 	",
"	19 En hulle het begin om te bou; en in die vierde week het hulle stene in die vuur gebak, en die stene het vir hulle as klippe gedien; en die klei waarmee hulle dit geheg het was asfalt, wat uit die see en uit die fonteine van die land van Sínear kom. 	",
"	20 En hulle het drie-en-veertig jaar daaraan gebou: hulle het dit uitsluitlik van stene gebou [elke steen was dertien el wyd, en die hoogte daarvan ‘n derde van die wydte]: die algehele hoogte was vyfduisend-vierhonderd-drie-en-dertig, en twee palms, en die lente van een muur was dertien stadiums, en van die ander, dertig stadiums. 	",
"	21 En die Meester ons Vader het vir ons gesê: Kyk, hulle is een volk: hulle het begin om dit te doen, en nou sal hulle nie ophou nie. Kom, laat ons neerdaal en hulle tongval verwar, sodat hulle mekaar nie kan verstaan nie, en in stede en nasies versprei wees, en dus geen gemeenskaplike doel hê, tot die Dag van Oordeel nie. 	",
"	22 En die Meester het neergedaal, en ons het saam met Hom neergedaal, om die stad en die toring te ondersoek, wat die seuns van die Adamiete gebou het. 	",
"	23 En Hy het al hulle tongvalle verwar, met die gevolg dat hulle mekaar se spraak nie langer verstaan het nie, en opgehou het om die stad en toring te bou. 	",
"	24 Dit is waarom die hele land van Sínear Babel genoem word, omdat die Meester alle manne se tongvalle daar verwar het; en van daar af was hulle na hulle verskillende stede versprei, elkeen volgens sy taal en sy nasie. 	",
"	25 En die Meester het ‘n geweldige wind teen die toring gestuur wat dit met die grond gelykgemaak het [die ligging is tussen Assur en Babilon in die land van Sínear], en hulle het dit, “Mislukking” genoem. 	",
"	26 Dit was in die vierde week van die eerste jaar, aan die begin daarvan, in die vier-en-dertigste Jubileum, dat hulle uit die land Sínear verdryf was. 	",
"	27 En Gam en sy seuns het na die land gegaan, wat vir hom eenkant gesit is, wat volgens die lot op hom geval het, as sy deel, in die land van die suide. 	",
"	28 En Kanaän het die land van Líbanon gesien tot by die rivier van Egipte, dat dit baie goed was, en het nie gegaan na die land wat op hom, in die weste by die see geval het nie, maar hom in die land van Líbanon, tussen die Jordaan gebied en die see gevestig. 	",
"	29 En sy vader Gam, Kus en Mitzrajim, sy broers, het vir hom gesê: Jy het jou in ‘n land, wat nie joune is nie, gevestig en wat nie deur die lot op ons geval het nie. Moet dit nie doen nie. As jy dit doen, sal jy en jou seuns verminder word tot vernietiging in die land en ‘n Vloek oor jou bring, as gevolg van jou opstandige optrede; want jy het as ‘n rebel gevestig, en deur opstand sal jou kinders verminder word tot vernietiging en jy sal vir ewig ontwortel wees. 	",
"	30 Moenie op Sem se erfdeel indring nie, want dit het deur die lot op Sem en sy seuns geval. 	",
"	31 Vervloek is jy en meer vervloek sal jy wees as al die seuns van Noag, as gevolg van die vloek waardeur ons, ons met ‘n eed in die teenwoordigheid van die Volmaakte Prins gebind het, en in die teenwoordigheid van ons vader Noag. 	",
"	32 Maar hy het hom nie aan hulle gesteur nie en hom in die land van Líbanon gaan vestig, Van Hamat tot die ingang van Mitzrajim (Egipte), hy en sy seuns, tot op hierdie dag. 	",
"	33 Dit is waarom hierdie land Kanaän genoem word. (:28-:34 = Gen. 15:16-:21) 	",
"	34 En Jafet en sy seuns het na die see toe gegaan en hulle in die land wat aan hulle toegeken was gevestig; en Madai het na die land by die see gekyk, en was nie daarmee tevrede nie, en hy het ‘n deel by Elam, Assur en Arpagsad, sy vrou se broer, gebedel en hom in die land Médië, naby sy vrou se broer, gevestig, tot op hierdie dag. 	",
"	35 En hulle het die plek waar hy en sy seuns gevestig was, Médië, na die naam van hulle vader Madai, genoem.	",

]
},
{
book: 'Jubileum',
chapter: '11',
content: [
		
"	1 En in die vyf-en-dertigste Jubileum, in die derde week, in die eerste jaar daarvan, het Reu ‘n vrou geneem, en haar naam was Ora, die dogter van Ur, die seun van Gesed; en sy het vir hom ‘n seun gebaar, en hy het hom Serug genoem, in die sewende jaar van hierdie week, in hierdie Jubileum. 	",
"	2 En Noag se seuns het begin om onder mekaar oorlog te maak, om die een die ander gevange te neem, en om mekaar te dood, en om die bloed van die Adamiet op die aarde te vergiet, en om bloed te eet, en om versterkte stede, mure en torings te bou; en sekere indiwidue het begin om hulself bo die ander te verhef en hulself as konings te kroon, en om in oorlog uit te gaan — volk teen volk, nasie teen nasie en stad teen stad. En almal van hulle het begin om boosheid te beoefen, om wapens te verkry, en om hulle seuns te leer om te veg; en hulle het begin om beslag op stede te lê, en om mans en vroue as slawe te verkoop. 	",
"	3 En Ur, die seun van Gesed, het die stad Era (Ara — Ur) van die Chaldeërs gebou, en dit na homself en sy vader, vernoem. 	",
"	4 En manne het vir hulle afbeeldinge van gegote metaal gemaak en elke man het sy beeld wat hy vir hom gegiet het, aanbid; en hulle het ook begin om gesnede beelde te maak, en onrein figure. En kwaadwillige geeste het hulle aangemoedig en hulle verlei (= Jak. 1:13-:14), sodat hulle in alle soorte sonde en onreinheid bevredig geraak het. (= Jak. 1:15) 	",
"	5 En die prins Mastema het hom daarvoor beywer om al hierdie dinge te doen, en hy het die geeste onder sy beheer as agente uitgestuur om alle soorte verkeerde dinge en sonde te doen, en alle soorte oortredinge, om te korrupteer en te vernietig, en om bloed op die aarde te vergiet. (= Jeség. 3:18-:21) 	",
"	6 Dus het hulle Serug, Seruk genoem (draai en verdraai), want almal het weggedraai na alle soorte sonde en oortredinge. 	",
"	7 En hy het grootgeword en in Ur van die Chaldeërs gewoon, naby sy vrou se moeder se vader, en hy het idole aanbid; en hy het in die ses-en-dertigste Jubileum, in die vyfde week, in die eerste jaar daarvan ‘n vrou geneem, en haar naam was Milka, die dogter van Heber, sy vader se broer se dogter. 	",
"	8 En sy het Nahor, in die eerste jaar van hierdie week, vir hom gebaar; en hy het grootgeword en in Ur van die Chaldeërs gewoon, en sy vader het hom in die leerstellings van die Chaldeërs opgelei, hoe om te wiggel en die toekoms deur die tekens van die hemel (sterre) te voorspel. 	",
"	9 En in die sewe-en-dertigste Jubileum, in die sesde week, in die eerste jaar daarvan, het hy ‘n vrou geneem, en haar naam was Iskah, die dogter van Mestag van die Chaldeërs. 	",
"	10 En sy het Tera in die sewende jaar van hierdie week gebaar. 	",
"	11 En die prins Mastema het rawe (kraaie) en ander voëls gestuur om die saad wat in die land gesaai was op te vreet, met die doel om die land te vernietig en die Adamiete van die vrug van hul arbeid te beroof: voordat hulle die saad kon inploeg, het die rawe dit van die oppervlakte van die grond opgepik. 	",
"	12 En dit is waarom hy hom Tera genoem het, omdat die rawe en die ander voëls hulle behoeftig gemaak en hulle saad opgevreet het. 	",
"	13 En die jare het vrugteloos geword, as gevolg van die voëls, en hulle het al die vrugte in die bome opgevreet: dit was slegs met groot moeite dat hulle enige van die aarde se vrugte in daardie dae kon red. (:11-:13 = Deut. 28:15-:68) 	",
"	14 En in hierdie nege-en-dertigste Jubileum, in die tweede week, in die eerste jaar, het Tera ‘n vrou geneem, die dogter van Abram, sy vader se suster se dogter. 	",
"	15 En in die sewende jaar van hierdie week het sy vir hom ‘n seun gebaar, en hy het hom Abram genoem, na sy moeder se vader (want hy het gesterf voordat sy dogter met ‘n seun swanger geword het). 	",
"	16 En die kind het begin om die foute van die aarde te verstaan, hoe almal agter gesnede beelde en onreinheid afgedwaal het; en sy vader het hom geleer om te skryf. 	",
"	17 En toe hy twee weke van jare oud was, het hy hom van sy vader afgeskei, sodat hy nie idole saam met hom kon aanbid nie; en hy het begin om tot die Skepper van alle dinge te bid, dat Hy hom van die foute van die Adamsgeslag mag Red, en dat dit nie sy lot sou wees om agter die onreine en vernederende aan te verdwaal nie. 	",
"	18 En die saaityd het aangebreek, om op die lande te saai, en almal het saam uitgegaan om hulle saad teen die rawe te beskerm; en Abram het saam met hulle uitgegaan [en hy was ‘n knaap van veertien]. 	",
"	19 En ‘n wolk van rawe het gekom om die saad op te vreet; en Abram het hulle tegemoetgehardloop voordat hulle op die grond kon gaan sit en hy het op hulle geskree voordat hulle op die grond gaan sit het om die saad op te vreet, en gesê: Bly weg, gaan terug na waar julle vandaan gekom het. En hulle het omgedraai en weggegaan. 	",
"	20 En hy het dit sewentig keer daardie dag aan die wolk van rawe gedoen; en nie ‘n enkele raaf het op die akkers waar Abram was, gaan sit nie. 	",
"	21 En almal wat saam met hom in die lande was het hom gesien uitroep en hoe al die rawe terugdraai; en sy roem het deur die hele land van die Chaldeërs versprei. 	",
"	22 En al daardie wat daardie jaar wou saai, het na hom toe gekom, en hy het saam met hulle gegaan totdat die saaityd verby was; en hulle het hulle lande gesaai, en daardie jaar het hulle graan in oorvloed huis toe gebring, en hulle kon tot versadiging eet. 	",
"	23 En in die eerste jaar van die vyfde week, het Abram bevele aan die skrynwerkers, wat die landbougereedskap gemaak het, gegee, en hulle het ‘n houer, bo die grondvlak, op die voorkant van die ploegraam gemaak, om die saad in te sit; die saad het daarvandaan op die ploegskaar geval en was in die grond verberg; dus was hulle nie meer bang vir die rawe nie. 	",
"	24 En hulle het houers soos hierdie gemaak, wat bo die grondvlak, op al die rame van die ploeë was; en hulle het die hele land besaai en bewerk, presies soos Abram vir hulle gesê het, en hulle was nie meer deur die voëls verskrik nie.	",

]
},
{
book: 'Jubileum',
chapter: '12',
content: [
		
"	1 En dit het in die sesde week gebeur, in die sewende jaar daarvan, dat Abram met Tera sy vader gespreek, en gesê het: 	",
"	2 Vader! En hy het geantwoord: Kyk, hier is ek my seun. En hy het gesê: Wat se wins of voordeel verkry ons uit daardie idole wat u aanbid en waarvoor u, u neerbuig? 	",
"	3 Want daar is geen Gees in hulle nie: Hulle is stom goed wat ons net lei om foute te maak, moet hulle dus nie aanbid nie. 	",
"	4 Aanbid die Vader van die Hemel, wat reën en dou op die aarde laat neerdaal, en wat alles op die aarde doen, en wat alles deur Sy Woord Geskep het, en alle lewe is uit Hom. 	",
"	5 Waarom aanbid u dinge wat geen Gees in hulle het nie, want dit is die handewerk van manne? U dra dit op u skouers, en u ontvang geen hulp daarvan nie. Dit bring eerder groot skande oor daardie wat dit maak, en mislei die gemoed (emosie) van daardie wat dit aanbid, moet dus nie hierdie goed aanbid nie. 	",
"	6 En sy vader het vir hom gesê: Ek weet dit ook, my seun; maar wat sal ek doen met ‘n volk wat my gedwing het om hulle te dien? 	",
"	7 As ek vir hulle die Waarheid vertel, sal hulle my dood; want hulle kleef daaraan (die idole) om dit te aanbid en te eer. 	",
"	8 Bly stil, my seun, vir ingeval hulle jou dood. En hy het dieselfde vir sy twee broers gesê, en hulle was vir hom kwaad, hy het dus niks meer gesê nie. 	",
"	9 En in die veertigste Jubileum, in die tweede week, in die sewende jaar daarvan, het Abram ‘n vrou geneem, en haar naam was Sarai (Sora), sy vader se dogter; en sy het sy vrou geword. 	",
"	10 En Haran, sy broer, het ‘n vrou in die derde jaar van die derde week geneem; en sy het vir hom in die sewende jaar van hierdie week ‘n seun gebaar, en hy het hom Lot genoem. 	",
"	11 En sy ander broer, Nahor, het ook ‘n vrou geneem. 	",
"	12 En in die sestigste jaar van Abram se lewe, dit is, in die vierde week, in die vierde jaar daarvan, het Abram in die nag opgestaan, en die huis van die idole aan die brand gesteek, en hy het alles wat in die huis was verbrand; niemand het daarvan geweet nie. 	",
"	13 En hulle het in die nag opgestaan en probeer om hulle gode uit die vuur te red. 	",
"	14 En Haran het ingestorm om hulle te red, maar die vlamme het hom oorweldig, en hy was in die vuur verbrand, en het in Ur van die Chaldeërs in die teenwoordigheid van sy vader Tera gesterf; hulle het hom in Ur van die Chaldeërs begrawe. 	",
"	15 En Tera het Ur van die Chaldeërs verlaat, hy en sy seuns, en het na die land van Líbanon, en die land van Kanaän getrek, en hom in die land van Haran gevestig; en Abram het saam met Tera, sy vader, twee weke van jare in Haran gewoon. 	",
"	16 En in die sesde week, in die vyfde jaar daarvan, het Abram die hele nag van die nuwemaan, van die sewende maand opgebly, om die sterre van die aand tot die môre toe waar te neem, met die doel om uit te vind hoe die reën daardie jaar sou val; en hy was alleen terwyl hy gesit en waargeneem het. 	",
"	17 En ‘n gedagte het by hom opgekom, en hy het gesê: Al die tekens van die sterre, en die tekens van die maan en son, is in die Hand van die Meester. 	",
"	18 Waarom sal ek dan by hulle navra doen? As dit Sy Wil is, laat Hy dit in die aand en die môre reën, en as dit Sy Wil is, weerhou Hy die reën; alle dinge is in Sy Hand. 	",
"	19 En hy het daardie nag gebid, en gesê: My Vader, Vader die Allerhoogste, U alleen is vir my ‘n Vader: U het alle dinge Geskape, en alle dinge wat is, is die Werk van U Hande; en U en U Heerskappy het ek verkies. 	",
"	20 Bevry my van die bose geeste wat heerskappy oor die gedagtes en gevoelens (emosie) van die Adamiete het, en laat hulle my nie van U af verlei nie, my Vader; vestig my en my nageslag vir ewig, dat ons nie nou of vir Ewig afdwaal nie. (= Jak. 1:13-:16) 	",
"	21 En ek vra U, moet ek na Ur van die Chaldeërs terugkeer, na daardie wat my smeek om na hulle terug te keer? Of moet ek eerder op hierdie plek bly? Help U Dienskneg om te kies, wat ookal die Regte Pad voor U is, en laat ek nie in die fout van my hart (vleeslike begeerte = Rom. 8:5-:8) wandel nie, o my Vader. 	",
"	22 En toe hy klaar gepraat en gebid het, en kyk, die Woord van die Meester was deur my (die Engel) na hom toe gestuur, wat sê: Verlaat jou land en jou bloedverwante en jou vader se huis, en gaan na ‘n land wat Ek jou sal toon; Ek sal jou ‘n groot en talryke nasie maak. 	",
"	23 En Ek sal jou Seën en jou naam groot maak, en jy sal op die aarde Geseënd wees, en in (een met – Jhg. 17:20-:23) jou sal alle vaders van die aarde Geseënd wees; Ek sal daardie Seën wat jou seën en daardie vervloek wat jou vervloek. 	",
"	24 En Ek sal vir jou ‘n Vader wees, en vir jou seun, en vir jou kleinkind, en vir al jou nageslagte: wees nie bevrees nie: van nou af, en vir Ewig, is Ek jou Vader. 	",
"	25 En die Meester Vader het vir my (Engel) gesê: Open sy mond en sy ore, sodat hy kan hoor en met sy mond praat, die Taal wat Geopenbaar sal word [want dit was nooit deur Adamiete gespreek, sedert die dag van die val van die toring van Babel nie]. 	",
"	26 En ek het sy mond en sy ore en sy lippe Geopen, en ek het in Hebreeus met hom begin praat – die Taal van sy Familie (Moedertaal kennis — Gelykenisse — spreek in Tale). 	",
"	27 En hy het sy vader se Boeke geneem, wat in Hebreeus geskryf was, en dit oorgeskryf en van daar af begin om dit te bestudeer, en ek het aan hom alles verduidelik wat hy nie kon verstaan nie; hy het dit gedurende die ses reënerige maande bestudeer. (:26-:27 = Gnk. 82:1-:3) 	",
"	28 En dit het in die sewende jaar van die sesde week gebeur, dat hy met sy vader gespreek, en vir hom gesê het dat hy Haran wou verlaat, om na die land van Kanaän te gaan, dit te bespied en na hom terug te keer. 	",
"	29 En Tera sy vader het vir hom gesê: Gaan in Vrede: mag die Ewige Vader jou Pad Reguit maak, en die Meester met jou wees, en jou teen alle boosheid Beskerm, en aan jou Genade, Barmhartigheid en Guns verleen, teenoor daardie wat jou sien, en mag geen man mag oor jou hê om jou te Beseer nie: gaan in Vrede. 	",
"	30 En as dit vir jou na ‘n aangename land lyk, en geskik om in te vestig, kom dan terug en kom haal my: neem Lot nou saam met jou, jou broer Haran se seun, en behandel hom asof hy jou eie is; en die Meester sal met jou wees. 	",
"	31 En laat jou ander broer Nahor hier by my bly, totdat jy in vrede terugkom, en dan kan ons almal saam met jou gaan.	",

]
},
{
book: 'Jubileum',
chapter: '13',
content: [
		
"	1 En Abram het van Haran af vertrek en sy vrou Sarai en Lot, sy broer Haran se seun, na die land van Kanaän geneem; en hy het by Assur gekom en rondgedwaal, totdat hy by Sigem gekom en hom daar naby ‘n hoë Eikeboom gevestig het. 	",
"	2 En hy het gekyk, en gesien, dat die land baie aangenaam was, van die ingang van Hamat tot by die hoë Eikeboom. 	",
"	3 En die Meester het vir hom gesê: Aan jou en jou nageslag sal Ek hierdie land gee. 	",
"	4 En hy het daar ‘n altaar gebou en op dit ‘n Volledige aanbieding aan die Meester aangebied wat aan hom Verskyn het. 	",
"	5 En van daar af het hy vêrder na die Bergland [oos van BetEl] gegaan, met BetEl aan die westekant en Ai aan die oostekant; en daar het hy sy tent opgeslaan. 	",
"	6 En hy het gekyk, en gesien, die land was ruim en baie goed, en alles het daar gegroei — wingerde en vye en granate, eike en without (waterhout), terpentyn- en olyfbome, en seders en sipresse en wierookbome (of dadelpalms), en al die bome van die platteland; en daar was water in die Bergland. 	",
"	7 En hy het die Meester Geseën, wat hom uit Ur van die Chaldeërs uitgelei en na hierdie land gebring het. 	",
"	8 en dit het in die eerste jaar gebeur, in die sewende week, op die nuwemaan van die eerste maand, dat hy daar ‘n altaar op die berg gebou en die Meester aangeroep het: U is my Vader, die Ewige Vader. 9 En hy het ‘n Volledige aanbieding op die altaar vir die Meester aangebied, sodat Hy met hom mag wees en hom al die dae van sy lewe nie sou verlaat nie. 	",
"	9 En hy het van daar af suidwaarts verder gegaan en by Hebron aangekom [Hebron was in daardie tyd gebou]; en hy het twee jaar daar gebly. En hy het van daar af na die land van die suide, na Belot gegaan. 	",
"	10 En daar was hongersnood in die land; Abram het in die derde jaar van die week Egipte binnegegaan, en vyf jaar in Egipte gewoon, voordat sy vrou van hom afgeskeur was. 	",
"	11 [Tanais is in daardie tyd in Egipte gebou — sewe jaar na Hebron.] 	",
"	12 En dit het gebeur, toe Farao vir Sarai, Abram se vrou, gevat het, dat die Meester Farao en sy hele huishouding met ernstige siektes getref het, as gevolg van Sarai, Abram se vrou. 	",
"	13 En Abram was hooggeag as gevolg van sy besittings aan skape, beeste, esels, perde, kamele, manlike en vroulike slawe en ‘n oorvloed van silwer en goud; en Lot, sy broer se seun, was ook welaf. 	",
"	14 En Farao het Sarai, Abram se vrou, teruggegee, en hom uit die land Mitzrajim (Egipte) gestuur; en hy het op die weggegaan na die plek waar hy sy tent aan die begin opgeslaan het, na die plek van die altaar, met Ai aan die oostekant en BetEl aan die westekant. En hy het die Meester sy Vader Geseën, wat hom in Vrede teruggebring het. 	",
"	15 En dit het in die een-en-veertigste Jubileum, in die derde jaar van die eerste week gebeur, dat hy na hierdie plek teruggekeer en daar ‘n Volledige aanbieding aangebied het, en hy het die Meester in Naam aangeroep, en gesê: U is die Allerhoogste Vader, my Vader vir Ewig en Ewig. 	",
"	16 En in die vierde jaar van hierdie week het Lot van hom geskei; en Lot het hom in Sodom gevestig [en die manne van Sodom was groot sondaars]. 	",
"	17 En dit het hom gegrief dat sy broer se seun van hom geskei het; want hy het geen kinders gehad nie. 	",
"	18 In daardie jaar, toe Lot gevange geneem was, het die Meester met Abram gespreek [nadat Lot van hom geskei het] in die vierde jaar van hierdie week, en vir hom gesê: Kyk op van die plek waar jy woon, noordwaarts en suidwaarts en weswaarts en ooswaarts. 	",
"	19 Want die hele land wat jy kan sien sal Ek vir jou en jou nageslag, vir Ewig gee, en Ek sal jou nageslag soos die sand van die see maak: Selfs al sou ‘n man die stof van die aarde kon tel, sal jou nageslag nie getel kan word nie. 	",
"	20 Staan op, loop deur die lengte en breedte van die land, en kyk na die hele land; want aan jou nageslag sal Ek dit gee. En Abram het na Hebron gegaan en hom daar gevestig. 	",
"	21 en in hierdie jaar het Kedar-Laomer, koning van Elam, en Amrafel, koning van Sínear, en Ariog, koning van Selasar, en Tergal, koning van nasies gekom, en die koning van Gomorra gedood; en die koning van Sodom het gevlug, en baie het gewond in die vallei van Siddim, by die Soutsee [woestynland], geval. 	",
"	22 En hulle het Sodom en Adam en Zeboim verower en hulle het Lot, Abram se broerskind, met al sy besittings, ook gevange geneem, en hulle het sovêr as Dan gegaan. 	",
"	23 En ‘n vlugteling het gekom, en vir Abram gesê, dat sy broerskind gevange geneem was. 	",
"	24 En hy het die diensknegte van sy huishouding bewapen· · vir Abram, — [Die bestaande teks, wat deur bykans alle manuskripte oorgedra word, maak geen sin nie. Charles veronderstel dat, alhoewel daar geen direkte bewys in die manuskripte daarvoor is nie, is daar eintlik ‘n leemte hier en dat die oorspronklike teks Abram se najaging van die vier konings beskryf, sy aanval op hulle, sy herowering van die buit, en sy ontmoeting met Melgisédek — soos in Gen. 14:14-:20. Die geskrif van een manuskrip egter, met ‘n klein verandering van die woord wat as “bewapen” vertaal is, slaag daarin om tenminste enige duidelikheid te gee met: en sy huishoudelike diensknegte het versoening vir Abram gedoen.] — en vir sy nageslagte, die eerste tiende vir die Meester; en die Meester het dit as ‘n Reël vir alle tye bepaal, dat hulle dit vir die Priesters behoort te gee, wat voor Hom dien, dat dit vir ewig hulle s’n behoort te wees. 	",
"	25 En vir hierdie Wet is daar geen tydsbeperking nie; want Hy het dit bepaal in elke geslag dat hulle aan die Meester ‘n tiende van alles behoort te gee, van saad en wyn en olie en beeste en skape. 	",
"	26 En Hy het dit vir Sy Priesters gegee om te eet en drink in vreugde voor Hom. 	",
"	27 En die koning van Sodom het gekom, voor hom neergebuig, en gesê: Ons meester Abram, vergun ons die volk wat u gered het, maar laat die buit u s’n wees. 	",
"	28 En Abram het vir hom gesê: Ek hef my hande op na die Allerhoogste Vader met ‘n eed, dat ek niks sal neem wat joune is nie, sodat jy nie kan sê: Ek het Abram ryk gemaak nie: ek sal net neem wat die jongmanne geëet het, en die deel van die manne wat saam met my gegaan het — Aunan, Eschol, en Mamre. Hierdie sal hulle deel kry.	",

]
},
{
book: 'Jubileum',
chapter: '14',
content: [
		
"	1 En na hierdie dinge, in die vierde jaar van hierdie week, op die nuwemaan van die derde maand, het die Woord van die Meester tot Abram in ‘n droom gekom, en gesê: Wees nie bevrees nie, Abram: Ek is jou Verdediger, en jou Beloning sal inderdaad groot wees. 	",
"	2 En hy het gesê: Meester, Meester, wat sal U my gee, aangesien ek geen kinders het nie, en die seun van Maseq, my slavin se seun, Eliëzer van Damaskus, sal my erfgenaam wees: vir my het U geen kinders gegee nie. 	",
"	3 En Hy het vir hom gesê: Hierdie man sal nie jou erfgenaam wees nie, maar jou eie seun sal jou erfgenaam wees. 	",
"	4 En hy het hom na buite geneem en vir hom gesê: Kyk op na die hemel en tel die sterre van die hemel, as jy hulle kan tel. 	",
"	5 En hy het na die hemel opgekyk en die sterre beskou; en Hy het vir hom gesê: So sal jou nageslag wees.	",
"	6 En hy het in die Meester geglo; en dit was vir hom as Geregtigheid gereken. 	",
"	7 En Hy het vir hom gesê: Ek is die Meester wat jou uit Ur van die Chaldeërs gebring het, om die land van die Kanaäniete vir jou as ‘n ewige besitting te gee, en om jou Vader en jou nageslag na jou se Vader te wees. 	",
"	8 En hy het gesê: Meester, Meester, hoe sal ek weet dat ek dit sal erf? 	",
"	9 En Hy het vir hom gesê: Bring vir My ‘n driejarige vers, en ‘n bok van drie jaar oud, en ‘n skaap van drie jaar oud, en ‘n tortelduif, en ‘n jong duif. 	",
"	10 En hy het al hierdie in die middel van die maand geneem, terwyl hy by die Eik van Mamre, naby Hebron gewoon het. 	",
"	11 En hy het daar ‘n altaar gebou en dit alles aangebied; en hy het die bloed op die altaar gegiet en elkeen in twee gedeel, en die stukke teenoor mekaar uitgelê; maar die voëls het hy nie in twee gedeel nie. 	",
"	12 En roofvoëls het op die stukke neergedaal; en Abram het hulle verwilder, en wou nie toelaat dat die voëls dit aanraak nie. 	",
"	13 En dit het gebeur, terwyl die son ondergaan, dat ‘n droomtoestand oor Abram gekom het; en kyk, ‘n verskrikking van die donker het oor hom gekom, en ‘n Stem het vir Abram gesê: Weet verseker dat jou nageslag vreemdelinge in ‘n vreemde land sal wees, en hulle sal daar tot slawerny verneder word, vir vierhonderd jaar. 	",
"	14 Maar Ek sal die nasie wat hulle slawe maak, Oordeel, en daarna sal hulle met baie besittings uitkom. 	",
"	15 Jy sal in Vrede na jou vaders gaan en in goeie ouderdom begrawe word. 	",
"	16 En in die vierde geslag sal hulle hierheen terugkom; want die Amoriete sal tot dan nog nie vir Straf gereed wees nie. 	",
"	17 En hy het wakker geword en opgestaan: die son het ondergegaan; en daar was ‘n vlam, en kyk, ‘n rokende konfoor, en ‘n vuurvlam het tussen die stukke deurgegaan. 	",
"	18 En op daardie dag het die Meester met Abram ‘n Verbond gesluit, wat lui: Aan jou nageslag sal Ek hierdie land gee, van die rivier van Egipte, tot die Groot-Rivier, die rivier Eufraat — die Keniete, die Kenessiete, Kadmoniete, Ferisiete, en die Nefilim, die Pakoriete, en die Hewiete, en die Amoriete, en die Kanaäniete, en die Girgasiete, en die Jebusiete. (:16-:18 = Gen. 15:16-:21) 	",
"	19 En daardie dag het verbygegaan, en Abram het die stukke aangebied en die voëls en hulle graanaanbiedinge en hulle drankaanbiedinge, en die vuur het dit verteer. 	",
"	20 En op daardie dag het ons (Engele) ‘n verbond met Abram gesluit, net soos wat ons met Noag in hierdie maand ‘n verbond gesluit het; en Abram het die Feesdag hernieu, (laat herleef) en dit vir Ewig vir hom so gereël. 	",
"	21 En Abram was verheug en het alles vir sy vrou	",

]
}
];
