const juditChapters = [

{
book: 'Judit',
chapter: '1',
content: [

"	1 IN die twaalfde jaar van die koningskap van Nebukadnésar, wat oor die Assiriërs geregeer het in Ninevé die groot stad, en in die dae van Arpagsad wat in Ekbatana koning van die Mediërs gewees het -	",
"	2 dit is hy wat naby Ekbatana in ‘n kring mure gebou het uit gekapte klippe wat drie voorarm breed en ses voorarm lank was; en die hoogte van die muurwerk het hy sewentig voorarm gemaak en die breedte daarvan vyftig voorarm;	",
"	3 by die poorte daarvan het hy torings gebou met ‘n hoogte van honderd voorarm, terwyl hy die fondamente na die mure se kant toe sestig voorarm breed gemaak het;	",
"	4 die poorte daarvan het hy wagpoorte gemaak tot ‘n hoogte van sewentig voorarm en met ‘n breedte van veertig voorarm vir die uitvalle van sy berede mag en van die geledere van sy voetknegte -	",
"	5 in daardie dae het koning Nebukadnésar oorlog gevoer teen koning Arpagsad op die groot vlakte; sy is die vlakte in die landstreek Rágaoe.	",
"	6 Teen hom het al die bewoners van die Bergland saamgekom en al die wat by die Eufraat woon en by die Tigris en die Hidasyes, onder die aanvoering van Arfog, die koning van die Elamiete. En baie volke het saamgekom in die slagorde van die kinders van die Ehaldoe.	",
"	7 Toe het koning Nebukadnésar van Assirië boodskappers gestuur na al die inwoners van Persis en na almal wat na die weste woon, na die bewoners van Cilícië en Damáskus en die Libanon en die Anti-Libanon, en na al die bewoners in die kusgebied,	",
"	8 en na die nasies van die Karmel en van Gílead en van Opper-Galiléa en van die groot Esdrelonvlakte,	",
"	9 na almal in Samaría en in die stede van haar, en na die wat oorkant die Jordaan is tot Jerusalem en Bet-Anot en EIísa en Kádes en by die spruit van Egipte, en Tapnes en Raämses en die hele Aarde van Gosen	",
"	10 tot bo Tanis en Memfis, en na al die bewoners van Egipte sover soos die grense van Kush.	",
"	11 Maar al die bewoners van die hele grondgebied het die oproep van koning Nebukadnésar van Assirië geminag; en hulle het nie met hom saamgekom vir die stryd nie, omdat hulle hom nie gevrees het nie en hy vir hulle maar net een man gewees het. En hulle het sy gesante met leë hande in oneer weggestuur.	",
"	12 Toe het Nebukadnésar baie toornig geword op daardie hele gebied, en hy het gesweer by sy troon en sy koningskap om die hele grondgebied van Cilícië en Damaskéne en Sírië uit te roei met sy swaard, eweas al die bewoners van die Aarde van Moab en die kinders van Ammon en die hele Hebreeuse grondgebied, en al die bewoners van Egipte sover soos die grense van die twee mere.	",
"	13 En hy het hom met sy leërmag teenoor koning Arpagsad opgestel in die sewentiende jaar; en hy was sterk in sy stryd en het die hele leër van Arpagsad en sy perde en sy waens vernietig.	",
"	14 Hy het sy stede oormeester en na Ekbatana getrek; hy het die torings oorweldig en die strate van haar geplunder en sy roem tot skande gemaak.	",
"	15 Arpagsad het hy in die berge van Ragaoe gevange geneem en hom met sy werpspiese doodgesteek en hom verdelg tot vandag.	",
"	16 Toe het hy na Ninevé teruggekeer, hyself en die hele bont menigte en sy baie groot skare van krygsmanne. Daar het hy ligsinnig en losbandig geleef, hyself en die leërmag, vir ‘n tyd van honderd-en-twintig dae.	",

]
},
{
book: 'Judit',
chapter: '2',
content: [
		
"	1 IN die agtiende jaar, op die twee-en-twintigste dag van die eerste maand, is in die huis van koning Nebukadnésar van Assirië besluit om die hele grondgebied te straf soos hy gesê het.	",
"	2 Hy het al sy edeles en al sy owerstes saamgeroep en met hulle sy geheime raad gehou en die hele besoedeling van die Aarde met eie mond meegedeel.	",
"	3 Hulle het geoordeel om alle vlees uit te roei - dit is die wat nie gevolg gegee het aan die woord van sy mond nie.	",
"	4 En nadat hy die vergadering gesluit het, het koning Nebukadnésar van Assirië Holofernes ontbied, wat die opper- bevelhebber van sy leër en die tweede na homself was. En hy sê vir hom:	",
"	5 Dit sê die groot koning, die meester van die hele Aarde: Kyk, jy moet wegtrek van voor my aangesig, en jy moet met jou saamneem manne wat op hulle eie krag vertrou - honderd-en-twintig duisend voetknegte en ‘n menigte perde saam met twaalf-duisend ruiters.	",
"	6 Jy moet uittrek vir ‘n ontmoeting met die hele Aarde in die weste, omdat hulle nie geluister het na die woord van my mond nie.	",
"	7 Jy moet hulle laat weet om grond en water in gereedheid te hou, omdat ek in my toorn teen hulle sal uittrek en die hele aangesig van die Aarde sal bedek met die voete van my leër en hulle aan plundering sal oorgee.	",
"	8 Hulle gewondes sal hulle dale vol maak, en elke spruit en rivier sal vol wees deur hulle lyke en oorloop.	",
"	9 Hulle gevangenes sal ek wegvoer na die versterkte plekke van die hele Aarde.	",
"	10 Maar jy, trek weg; neem eerstens al hulle Aarde vir my in besit, en die wat hulleself aan jou oorgee, moet jy vir my bewaar tot die dag van hulle ondervraging.	",
"	11 Laat jou oog die wat ongehoorsaam is egter nie ontsien nie; lewer hulle in die hele Aarde oor aan die dood en die plundering.	",
"	12 By my lewe en die mag van my koningskap! Ek het gespreek, en ek sal dit volbring deur my hand.	",
"	13 Wat betref jouself: vergeet nie een van jou meester se woorde nie, maar volbring hulle tot die laaste een, soos ek jou dit beveel het, en versuim nie om dit te doen nie.	",
"	14 Holofernes het toe van voor die aangesig van sy meester weggegaan en al die owerstes en bevelhebbers en leiers van die leër van Assur opgeroep.	",
"	15 En hy het uitgesoekte manne in slagordes ingedeel, soos sy meester hom beveel het: twaalf tienduisendtalle voetknegte en twaalfduisend boogskutters op perde;	",
"	16 en hy het hulle ingedeel op die wyse waarop ‘n menigte krygsvolk ingedeel word.	",
"	17 Hy het ook kamele en esels en muilesels vir hulle uitrusting aangeskaf, ‘n baie groot aantal; en verder tallose skape en beeste en bokke vir hulle voedsel,	",
"	18 en vir elke man ‘n oorvloed van koring, en ‘n groot hoeveelheid goud en silwer uit die huis van die koning.	",
"	19 Toe het hy weggetrek, hy self en sy hele leërmag, om voor koning Nebukadnésar in die oorlog te gaan, en om die hele aangesig van die Aarde na die weste te bedek met sy waens en ruiters en uitgesoekte voetknegte.	",
"	20 En ‘n bont menigte, so talryk soos sprinkane en soos die sand van die Aarde, het met hulle saamgegaan, wat vanweë hulle menigte ontelbaar was.	",
"	21 Vanaf Ninevé het hulle drie dagmarse deur die vlakte van Bet-Ketilal afgelê, en aan die anderkant van Bet-Ketilal het hulle laer getrek naby die berge aan die linkerkant van Opper-Cilícië.	",
"	22 Daarna het hy sy hele leërmag, sy voetknegte en ruiters en waens, geneem en vandaar na die bergland getrek.	",
"	23 Hy het Put en Lud verwoes en al die kinders van Résef uitgeplunder en die kinders van Jismael wat naby die woestyn woon, suidelik van die Aarde van die Hetiete.	",
"	24 Vervolgens het hy langs die Eufraat getrek en deur Mesopotamië gegaan en al die stede en hoogtes langs die Abronaspruit verwoes tot naby die see.	",
"	25 Die grondgebied van Cilícië het hy in besit geneem, en sy teenstanders het hy almal vernietig; en vervolgens het hy na die Aarde van Jafet getrek, wat suidelik geleë is teenoor Arabië.	",
"	26 Toe het hy al die kinders van Mídian van alkante ingesluit en vervolgens hulle tente aan die brand gesteek en hulle veestapel geroof.	",
"	27 Hy het na die vlakte van Damaskus afgedaal in die dae van die koringoes; hy het al hulle grond aan die brand gesteek, hulle troppe kleinvee en beeste gedood, hulle stede geplunder, hulle vlaktes gefynkam, en al hulle jong manne met die punt van die swaard doodgemaak.	",
"	28 En vrees en skrik vir hom het al die bewoners van die kusstreek oorval, dit is hulle wat in Sidon en in Tirus woon en in Sihor en Akko, en al die inwoners van Jábneël en Asdod en Askaton. Hulle is met ‘n groot angs vir hom vervul.	",

]
},
{
book: 'Judit',
chapter: '3',
content: [
		
"	1 TOE het hulle boodskappers na hom gestuur met vredeliewende woorde, om te sê:	",
"	2 Kyk, ons, die diensknegte van die groot koning Nebukadnésar, val neer voor u. Maak met ons soos dit die beste is voor u aangesig.	",
"	3 Aanskou ons plase en al ons grond en die hele vlakte met koring en die kleinvee en die beeste en al ons tentdorpe: sy staan oop voor u. Maak daarmee soos dit u sal behaag.	",
"	4 Kyk, ook ons stede en hulle inwoners is u slawe. Kom, en bejeën hulle soos dit goed is in u oë.	",
"	5 En die manne het by Holofernes gekom en aan hom berig gegee ooreenkomstig hierdie woorde.	",
"	6 Toe het hy na die kusgebied afgedaal, hy en sy leër; en hy het die stede wat hoog gelê het, beset en daaruit uitgesoekte manne as hulptroepe saamgeneem.	",
"	7 Hulle het hom toe ontvang, hierdie en al die bewoners van die naburige gebied, met kranse en reisange en keteltromme.	",
"	8 Maar hy het hulle hele Aarde verwoes en hulle Asherahs omgekap; want hy het die opdrag gekry om al die gode van die Aarde uit te roei, sodat al die nasies alleen Nebukadnésar sou aanbid, en sodat al hulle tonge en stamme hom tot god sou uitroep.	",
"	9 En hy het teenoor Esdrelon gekom, naby Dotan wat teenoor die groot vlakte van JeHûWdah lê.	",
"	10 Tussen Géba en Skitópolis het hy toe laer getrek. Hy het daar ‘n maand gebly om die hele uitrusting van sy leër te versamel.	",

]
},
{
book: 'Judit',
chapter: '4',
content: [
		
"	1 EN die kinders van JisraEl wat in JeHûWdah woon, het alles gehoor wat Holofernes, die opperbevelhebber van koning Nebukadnésar van Assirië, gedoen het, en hoe hy al hulle tempels geplunder en verwoes het.	",
"	2 En hulle het vreeslik beangs geword voor sy aangesig en hulle bekommer oor Jerusalem en die Huis van JaHWeH, hulle Elohey,	",
"	3 omdat hulle maar onlangs uit die ballingskap teruggekeer het, en die hele volk van JeHûWdah net ‘n kort tydjie gelede herstel het, en die gereedskap en die brandofferaltaar en die Tempel self na die besoedeling opnuut gewy was.	",
"	4 Toe het hulle boodskappers gestuur na die hele grensgebied van Samaría, en na Kona, en na Bet-Horon, en na Jíbleam, en na Jérigo, en na Hoba, en na Hasor, en na die Salemvlakte.	",
"	5 En hulle het al die hoë bergtoppe vantevore beset, en hulle het die dorpe wat daar lê met mure versterk, en hulle het voedselvoorrade opgeslaan, om voor- berei te wees vir die oorlog, want hulle het hulle lande net ‘n kort tydjie vantevore geoes.	",
"	6 En die opperpriester JeHôWjakim, wat in daardie dae in Jerusalem was, het geskryf na die inwoners van Betoël en Bet-Místeh, wat teenoor Esdrelon lê en voor die vlakte wat naby Dotan is.	",
"	7 Hy het hulle gesê om die bergpasse te beset, omdat daarlangs die toegang na JeHûWdah, is, en omdat dit vir hulle maklik sou wees om die wat opruk voor te keer, want dit is te nou vir twee manne wat tegelyk wil deurgaan.	",
"	8 En die kinders van JisraEl het gedoen wat die opperpriester JeHôWjakim en die oudstes van die hele volk JisraEl wat in Jerusalem woon, aan hulle beveel het.	",
"	9 Toe het die hele JisraEl met groot aandrang luid geroep na hulle Elohey, en hulle het hulle met groot toewyding verootmoedig.	",
"	10 Hulle en hulle vroue en hulle kinders en hulle besittings, saam met elke bywoner en huurling en slaaf onder hulle, het hulle lendes met ‘n boetekleed omgord.	",
"	11 En van JisraEl het elke man en vrou en kind wat in Jerusalem woon, neergeval voor die Tempel; hulle het as op hulle hoofde gestrooi en hulle het hulle boeteklere geskeur voor die Aangesig van JaHWeH.	",
"	12 Ook het hulle die brandofferaltaar met ‘n boetekleed bedek, en hulle het eendragtig met aandrang na die Elohey van JisraEl geroep om hulle besittings nie aan plundering oor te gee nie, hulle vroue nie aan roof nie, die stede van hulle erfdeel nie aan verwoesting nie, en die Apartheids-plek nie aan die besoedeling en die beskamende leedvermaak van die nasies nie.	",
"	13 En JaHWeH het hulle geroep gehoor en hulle verdrukking gesien. En die volk het baie dae gevas in die hele JeHûWdah en Jerusalem voor die Apartheidsplek van die Almagtige JaHWeH.	",
"	14 En JeHôWjakim, die opperpriester, en al die priesters wat voor die Aangesig van JaHWeH staan, en die wat vir JaHWeH die dienswerk verrig, het met ‘n boetekleed om hulle lendes sonder ophouding die brandoffers opgedra en die gebede en die vrywillige gawes van die volk.	",
"	15 Daar was selfs as op hulle hoofdoeke; en hulle het uit alle mag na JaHWeH bly roep om die hele huis van JisraEl in goedheid te aanskou.	",

]
},
{
book: 'Judit',
chapter: '5',
content: [
		
"	1 TOE het Holofernes, die opperbevelhebber van die leër van Assur, ver- neem dat die kinders van JisraEl hulle vir die oorlog voorberei het, dat hulle die bergpasse afgesluit het, en dat hulle elke hoë bergtop omring het met mure en dat hulle in die vlaktes versperrings aangebring het.	",
"	2 En hy het baie woedend geword, en hy het al die leiers van Moab ontbied, eweas die aanvoerders van Ammon en al die goewerneurs van die kus-gebied;	",
"	3 en hy sê toe vir hulle: Verklaar my nou, kinders van Kanaän, watter volk is dit wat in die bergland woon? In watter stede woon hulle? Hoe groot is hulle leërmag? Waarin bestaan hulle krag en sterkte? Watter koning heers oor hulle en voer hulle leër aan?	",
"	4 Waarom is hulle die enigste bewoners in die weste wat dit onderneem om my nie tegemoet te kom nie?	",
"	5 Toe het Agior, die aanvoerder van al die kinders van Ammon, gesê: Laat my meester luister na die woord uit die mond van sy dienskneg, en ek sal u die waarheid meedeel omtrent daardie volk wat naby u in daardie bergland woon; en uit die mond van u dienskneg sal geen onwaarheid kom nie.	",
"	6 Hierdie volk is afstammelinge van Chaldeërs.	",
"	7 Maar hulle het hulle eers as vreem- delinge in Mesopotamië gaan vestig, omdat hulle nie die gode van hulle vaders wou dien wat in die Aarde van die Chaldeërs gewoon het nie.	",
"	8 Want hulle het die pad van hulle ouers verlaat en die Elohey van die Hemele gaan vereer, wat hulle as die enigste Elohim erken. Toe het hulle van die aangesig van hulle gode weggetrek en na Mesopotamië gegaan en daar baie dae gebly.	",
"	9 Maar toe sê hulle Elohey dat hulle moet ophou om bywoners te wees en na die Aarde van Kanaän gaan. Hulle het daar gaan woon, en het baie ryk geword aan goud en silwer en vee.	",
"	10 Vervolgens het hulle na Egipte afgesak, omdat daar oor die hele Aarde van Kanaän ‘n hongersnood gekom het; en hulle was daar bywoners so lank as hulle voedsel gevind het. Hulle het daar tot ‘n groot menigte geword, sodat hulle afstam- melinge ontelbaar was.	",
"	11 Maar die koning van Egipte het hulle weerstaan, en hy het hulle op ‘n slinkse wyse oorwin deur harde arbeid en die maak van bakstene; hy het hulle verneder en tot slawe gemaak.	",
"	12 Maar hulle het na hulle Elohey geroep, en Hy het die hele Aarde van Egipte geslaan met plae waaraan geen ontkoming gewees het nie. Toe het die Egiptenare hulle uitgedryf van hulle aangesig.	",
"	13 Hulle Elohey het die Riet See [Skelf See] voor hulle droog gemaak,	",
"	14 en Hy het hulle gelei op die pad van Sinai en Kades-Barnéa; en hulle het al die woestynbewoners uitgedryf.	",
"	15 Hulle het gaan woon in die Aarde van die Amoriete en hulle het al die Hesboniete verdelg deur hulle krag.	",
"	16 Voor hulle aangesig het hulle die Kanaäniet verdrywe asook die Feresiet en die Jebusiet en die Hewiet en al die Girgasiete, en hulle het daar baie dae gewoon.	",
"	17 En so lank as hulle nie oortree het voor die Aangesig van hulle Elohey nie, het hulle voorspoed gehad, omdat die Elohey wat ongeregtigheid haat, met hulle gewees het.	",
"	18 Maar toe hulle afgewyk het van die Weg wat Hy vir hulle bepaal het, is hulle baie swaar geslaan in baie oorloë en is hulle in ballingskap weggevoer na ‘n vreemde deel van die Aarde; en die Huis van hulle Elohey is te gronde gerig, en hulle stede is deur die vyande in besit geneem.	",
"	19 Toe het hulle egter teruggekeer na hulle Elohey, en hulle het teruggekom uit die verstrooiing waarin hulle verstrooi is. Hulle het Jerusalem, waar hulle Apartheidsplek is, teruggekry, en hulle het die bergland bevolk, omdat sy leeg was.	",
"	20 En nou, my gebieder en meester, as daar tog skuld van ongeregtigheid onder hierdie volk is en hulle oortree teen hulle Elohey, dan sal ons dit raaksien, omdat dit vir hulle ‘n hindernis is, en sal ons opruk en hulle oorwin.	",
"	21 Maar as daar geen skuld van ongeregtigheid onder hulle mense is nie, gaan dan weg, sodat JaHWeH hulle Elohey hulle nie beskerm en ons tot skande maak voor die hele Aarde nie.	",
"	22 Toe Agior ophou met hierdie woorde te sê, het al die volk wat rondom die tent staan, begin mor; en Holofernes se aanvoerders en al die bewoners van die kusgebied en van Moab het gesê dat hulle hom sal vermoor:	",
"	23 Ons sal ons geen vrees laat aanja vir die kinders van JisraEl nie. Want, kyk, dit is ‘n volk sonder die mag en die krag vir ‘n gedugte leër.	",
"	24 Laat ons daarom opruk; hulle sal ‘n prooi vir u hele leër wees, meester Holofernes!	",

]
},
{
book: 'Judit',
chapter: '6',
content: [
		
"	1 TOE die geraas van die manne in die kring van die vergadering ophou, het Holofernes, die opperbevelhebber van die leër van Assur, voor die hele menigte vreemdelinge vir Agior en vir al die kinders van Moab gesê:	",
"	2 Wie is jy, Agior, en wie is die huurlinge van Efraim, dat jy onder ons geprofeteer het soos netnou en dat jy sê om nie teen die geslag van JisraEl oorlog te voer nie omdat hulle Elohey hulle sal beskerm? En wie is elohim behalwe Nebukadnésar? Dit is hy wat sy leër stuur en wat hulle sal uitroei van die aangesig van die Aarde, sonder dat hulle Elohey hulle sal bewaar.	",
"	3 Want ons, sy diensknegte, sal hulle soos een man neerslaan. En hulle sal nie aan die krag van ons perde weerstand bied nie.	",
"	4 Ons sal hulle daar verbrand, en hulle berge sal dronk word van hulle bloed en hulle vlaktes sal gevul word met hulle lyke en selfs die spore van hulle voete sal nie standhou voor ons aangesig nie, maar deur vernietiging weggevee word, verklaar koning Nebukadnésar, die heerser van die hele Aarde. Want hy het gesê dat sy woorde nie verydel moet word nie.	",
"	5 En jy, Agior, huurling van Ammon, omdat jy hierdie woorde gepraat het op die dag van jou ongeregtigheid, sal jy vanaf vandag my aangesig nie meer sien nie, totdat ek wraak neem op die geslag van die wat uit Egipte gekom het.	",
"	6 Dan sal die swaard van my leër en die menigte van my diensbares jou sy deursteek. Jy sal onder hulle slae val, wanneer ek kom.	",
"	7 Want my slawe sal jou wegvoer na die gebergte, en hulle sal jou by een van die dorpe in die bergpasse bring;	",
"	8 En jy sal nie omkom voordat jy saam met hulle uitgeroei gaan word nie.	",
"	9 Maar as jy in jou hart verwag dat hulle nie oorwin word nie, toon dan nie ‘n ingevalle gesig nie. Ek het gepraat, en niks van wat ek sê, sal misluk nie.	",
"	10 Toe het Holofernes aan sy slawe wat by hom in die tent is, beveel om Agior saam te neem en hom na Betoel te bring en hom oor te lewer in die hande van die kinders van JisraEl.	",
"	11 En sy slawe het hom saamgeneem en uit die laer na die vlakte weggevoer; en van die vlakte het hulle in die berge gegaan en verby die fonteine gekom wat onder Betoel is.	",
"	12 Toe die manne van die Stad op die top van die berg hulle gewaar, het hulle hulle wapens opgeneem en uit die Stad op die top van die berg geloop; en al die slingeraars het verhinder dat hulle hoër klim deur hulle met klippe te gooi.	",
"	13 Maar hulle het onder teen die berg weggeskuil en Agior vasgebind, en hulle het hom by die voet van die berg agtergelaat en weggegaan na hulle meester.	",
"	14 Toe het die kinders van JisraEl uit hulle Stad afgekom en by hom gaan staan; hulle het hom losgemaak en hom toe na Betoel gebring en voor die owerstes gelei.	",
"	15 In daardie dae was dit UzziJaH, die seun van Míga, uit die stam van Simeon; en Abris, die seun van GotóniEl; en Samri, die seun van MelgiEl.	",
"	16 En hulle het al die oudstes van die Stad bymekaar geroep, en al hulle jongelinge en vroue het na die byeenkoms gekom, en hulle het Agior in die midde van hulle hele volk geplaas; en UzziJaH het hom gevra wat hom oorgekom het.	",
"	17 En hy het as antwoord aan hulle al die woorde oorgebring van Holofernes se raad, en al wat hy self gesê het te midde van die owerstes van die kinders van Assur, en Holofernes se grootpraat teen die huis van JisraEl.	",
"	18 Toe het die volk neergekniel en Elohim aanbid en na Elohim geroep:	",
"	19 O, JaHWeH, Elohey van die Hemele, kyk neer op hulle vermetelheid en ontferm U oor die vernedering van ons geslag. Aanskou op daardie dag die aangesig van hulle wat aan U toegewy is.	",
"	20 En hulle het Agior getroos en hom baie geprys.	",
"	21 Toe het UzziJaH hom van die vergadering saamgeneem na sy huis, en aan die oudstes het hy gegee om te drink. En daardie hele nag het hulle die Elohey van JisraEl om hulp geroep.	",

]
},
{
book: 'Judit',
chapter: '7',
content: [
		
"	1 DIE volgende dag het Holofernes bevel gegee aan sy hele leër en aan al die volk wat as hulptroepe by hom aangesluit het, om op te trek na Betoel en die bergpasse te beset, en om die oorlog teen die kinders van JisraEl te voer.	",
"	2 Op daardie dag het al die soldate dan ook opgetrek. En hulle leërmag het bestaan uit sewentigduisend voetknegte en twaalfduisend ruiters, behalwe nog die uitrusting en die manne wat saamgeloop het met hulle - ‘n geweldig groot menigte.	",
"	3 Nie ver van Betoel nie het hulle naby die fontein laer getrek; en hulle was uitgesprei in die breedte sover soos Dotan en Jibleam, en in die lengte van Betoel tot naby Jókneam, wat teenoor Esdrelon geleë is.	",
"	4 Toe die kinders van JisraEl hulle menigte sien, het hulle baie bevrees geword en hulle het vir mekaar gesê: Nou oorstroom hulle die aangesig van die hele Aarde, en nòg die bergtoppe, nòg die dale, nòg die heuwels sal hulle gewig kan dra.	",
"	5 En elkeen van hulle het sy wapens opgeneem, en hulle het op die poorte vure aangesteek en daardie hele nag waggehou.	",
"	6 Die volgende dag het Holofernes sy hele ruitery uitgelei tot voor die oë van die kinders van JisraEl wat in Betoel gewees het.	",
"	7 Ook het hy die toegangsweë na hulle Stad in oënskou geneem, na die fonteine gaan kyk en hulle in besit geneem; hy het wagposte van krygsmanne daarby geplaas en daarna weer teruggegaan na sy manskappe.	",
"	8 Toe het al die owerstes van die kinders van Esau en al die leiers van die volk van Moab en die bevelhebbers van die kusgebied na hom toe gekom, en hulle het gesê:	",
"	9 Laat ons gebieder luister na ‘n plan waardeur u leër geen verliese sal ly nie.	",
"	10 Hierdie volk van die kinders van JisraEl vertrou nie op hulle spiese nie, maar op die hoogtes van die berge waarop hulle woon, omdat dit nie maklik is om op die toppe van hulle berge te klim nie.	",
"	11 Nou dan, gebieder, veg nie met hulle in die gebruiklike slagorde nie, en nie een enkele man van u leër sal sneuwel nie.	",
"	12 Bly in u kamp en spaar elke man van u troepemag, maar laat u manskappe net die fontein beset hou wat uit die voet van die berg stroom,	",
"	13 want daarvandaan kry al die inwoners van Betoel hulle water. Die dors sal hulle swak maak, sodat hulle hulle Stad oorgee. Ons en ons volk sal op die naburige bergtoppe klim en daar laer om wag te hou, sodat nie een man die Stad kan verlaat nie.	",
"	14 Hulle sal versmag in hulle nood, hulleself en hulle vroue en hulle kinders; en nog voordat die swaard hulle kan tref, sal hulle dood rondlê in die strate van hulle woonplek.	",
"	15 Dan sal u hulle vergeld met ‘n smartlike vergelding vir die feit dat hulle opgestaan het en nie u aangesig in vrede gesoek het nie.	",
"	16 Hulle plan het Holofernes en al sy ondergeskiktes geval; en hy het hulle beveel om te maak soos hulle gesê het.	",
"	17 ‘n Afdeling van die kinders van Ammon het toe weggetrek, en saam met hulle nog vyfduisend kinders van Assur wat hulle in die dal gelaer het en wat die spruite en Fonteine van die kinders van JisraEl beset het.	",
"	18 Maar die kinders van Esau en die kinders van Ammon het self opgeklim en in die bergland teenoor Dotan laer getrek. En hulle het van hulle manskappe na die suide en na die ooste gestuur teenoor Ekrebel, naby Ehoes, wat by die Mogmoerspruit geleë is. En die res van die leër van die Assiriërs het in die vlakte gelaer, en hulle het die hele aangesig van die land bedek; en hulle tente en uitrusting is in ‘n baie groot menigte opgeslaan, en daar was vreeslik baie van hulle.	",
"	19 Die kinders van JisraEl het toe na JaHWeH, hulle Elohey geroep, omdat hulle harte neerslagtig geword het deur die feit dat die vyande hulle ingesluit het, sodat daar geen ontkoming uit hulle midde is nie.	",
"	20 Die hele laer van Assur, die voetknegte en die strydwaens en die ruiters, het so gedurende vier-en-dertig dae die beleg volgehou; en die watervoorraad het al die inwoners van Betoel in die steek gelaat.	",
"	21 Die waterputte het leeg geword, en daar was nie water om selfs een dag genoeg te drink nie, omdat hulle afgemete hoeveelhede gegee het om te drink.	",
"	22 En die klein kindertjies het lusteloos geword; en die vroue en jongelinge het verswak deur die dors en het in die strate van die Stad en in die openinge van die deure geval, want daar was geen krag in hulle oor nie.	",
"	23 Toe het die hele bevolking by UzziJaH en die stadsbestuurders bymekaar gekom, die jongelinge en die vroue en die kinders en met ‘n groot stem het hulle geroep. En teenoor al die oudstes het hulle gesê:	",
"	24 Laat JaHWeH regter wees tussen u en ons, want u het ons ‘n groot onreg aangedoen deur nie op ‘n vredeliewende wyse met die kinders van Assur te praat nie.	",
"	25 Nou is daar niemand om ons te help nie, want JaHWeH het ons verkoop in hulle hande, omdat ons voor hulle oë deur dors en groot gebrek omkom.	",
"	26 Nou dan, roep hulle en gee die hele Stad as buit oor aan die manskappe van Holofernes en aan sy hele leër;	",
"	27 want dit is beter vir ons om hulle buit te word. Dan sal ons hulle slawe wees en ons bly lewe. En ons sal nie met eie oë die dood aanskou van ons klein kindertjies en hoe ons vroue en kinders die gees gee nie.	",
"	28 Ons roep tot getuie die Hemele en die Aarde en JaHWeH onse Elohey van ons vaders. Hy straf ons vanweë ons eie oortredinge en die oortredinge van ons vaders, as u nie vandag nog handel ooreenkomstig ons versoek nie.	",
"	29 En almal het gelyklik in die midde van die vergadering geweeklaag, en met ‘n groot stem het hulle geroep na JaHWeH, hulle Elohey.	",
"	30 Toe het UzziJaH vir hulle gesê: Hou goeie moed, broers! Laat ons nog vyf dae langer uithou waarin JaHWeH, onse Elohey Sy Ontferming na ons kan toekeer, want Hy sal ons nie volkome verlaat nie.	",
"	31 As hulle verbygaan sonder dat daar hulp vir ons kom, sal ek ooreenkomstig julle versoek handel.	",
"	32 Toe het hy die volk weggestuur, elkeen na sy wagpos; en hulle het weer na die mure en die poorte van hulle Stad gegaan. En hulle het hulle vroue en kinders na hulle huise gestuur. En hulle was baie bedruk in die Stad.	",

]
},
{
book: 'Judit',
chapter: '8',
content: [
		
"	1 IN daardie dae is dit ook verneem deur Judit, die dogter van Merái, die seun van UzziJaH, die seun van JôWsef, die seun van OsiEl, die seun van ElkiJaH die seun van GanánJaH, die seun van Gideon, die seun van Refaïm, die seun van Agítob, die seun van Eli, die seun van HilkiJaH, die seun van Elíab, die seun van NatánaEl, die seun van SelumiEl, die seun van Surísaddai, die seun van JisraEl.	",
"	2 Haar man was Manasse, van haar eie stam en geslag, wat tydens ‘n oes van die gars gesterf het.	",
"	3 Want terwyl hy op die vlakte toesig hou op die gerwebinders, het die warmte sy hoof getref. Hy het op sy bed gaan lê, maar in sy eie stad Betoel het hy gesterf, en hulle het hom begrawe in die Aarde tussen Dotan en Jibleam.	",
"	4 En Judit was al drie jaar en vier maande ‘n weduwee in haar huis gewees.	",
"	5 Sy het vir haar op die dak van haar huis ‘n tent gemaak, en sy het haar lendes met ‘n boetekleed omgord, en sy was altyd aangetrek in die kleed van haar weduweeskap.	",
"	6 En al die dae van haar weduweeskap het sy gevas, uitge-sonder op die Sabbat en met die maandsvernuwing en op die Fees- en Jubeldae van die Huis van JisraEl.	",
"	7 Sy was besonder mooi van gestalte en skoon om te aanskou. Verder het Manasse, haar man, aan haar goud en silwer en slawe en slavinne en vee en grond nagelaat, en sy het dit in die oog gehou.	",
"	8 Daar was ook niemand wat behoefte gehad het aan ‘n woord van afkeuring nie, want sy het JaHWeH gevrees.	",
"	9 Sy het verneem van die bevolking se bose woorde tot die owerste omdat hulle bedruk gevoel het deur die gebrek aan water. Ook het Judit al die woorde verneem wat UzziJaH vir hulle gesê het - dat hy hulle belowe het om na vyf dae die Stad oor te gee aan die Assiriërs.	",
"	10 En sy het haar kamerbediende wat oor al haar diensbares toesig hou, gestuur en Abris en Samri, die oudstes van die Stad, geroep.	",
"	11 Hulle het na haar toe gegaan, en sy het vir hulle gesê: Luister na my, owerstes van die inwoners van Betoel! Want dit is nie ‘n goeie woord wat julle vandag voor die volk gepraat het nie, toe julle daardie eed sweer, wat julle tussen Elohim en julleself uitgespreek het, toe julle sê dat julle die Stad aan ons vyande sal oorgee as JaHWeH julle binne daardie tyd nie te hulp kom nie.	",
"	12 Nou dan, wie is julle wat Elohim vandag versoek, en wat julle bo Elohim plaas in die midde van die seuns van die Adam?	",
"	13 Want julle is nou besig om die Almagtige JaHWeH na te vors, en tog sal julle tot in ewigheid niks weet nie.	",
"	14 Want die diepte van ‘n adamiet se hart kan julle nie peil nie, en die gedagtes van sy gees kan julle nie vat nie. Maar hoe kan julle dan wel Elohim begryp, wat hierdie dinge gemaak het, en hoe kan julle dan Sy Wysheid verstaan en Sy rede begryp? Nooit, broers! En vertoorn nie JaHWeH, onse Elohey nie!	",
"	15 Want ook wanneer Hy ons nie binne hierdie vyf dae wil help nie, dan besit Hy tog nog die mag om ons in soveel dae soos Hy wil, te beskerm of uit te roei voor die aangesig van ons vyande.	",
"	16 En julle, moenie die Raadsbesluite van JaHWeH, onse Elohey afdwing nie, want JaHWeH laat Hom nie soos ‘n adamiet dreig of soos ‘n seun van adam ‘n dagverdeling voorskryf nie.	",
"	17 Laat ons daarom, terwyl ons Sy uitredding afwag, Hom roep om ons te help; en Hy sal ons stem verneem, wanneer dit Hom behaag.	",
"	18 Want Hy het nie opgestaan om ons geslag te straf nie, want daar is vandag nòg ‘n stam, nòg ‘n geslag, nòg ‘n volk, nòg ‘n Stad van ons, wat gode vereer wat deur mensehande gemaak is, soos dit in vroeër dae wel die geval gewees het.	",
"	19 Daarom was ons vaders oorgelewer aan die swaard en die plundering en was hulle diep verneder in die aangesig van ons vyande.	",
"	20 Maar ons, ons ken nie ‘n ander Elohey as Hom nie; en daarom hoop ons dat Hy ons nie sal oorsien nie; selfs nie vanweë ons geslag nie.	",
"	21 Want as ons oorweldig word, sal ook die hele JeHûWdah oorweldig word, en dan sal ook ons Apartheidsplek geplunder word; en daardie besoedeling sal Hy op ons bloed wreek.	",
"	22 En die moord op ons broers en die verowering van die Aarde en die verwoesting van ons Erfdeel sal Hy laat neerkom op ons hoof by die nasies, wie se slawe ons daar sal wees; en ons sal ‘n ergernis en ‘n spot wees vir die wat ons gekoop het.	",
"	23 Want ons diensbaarheid sal nie reggemaak word tot ons voordeel nie, maar JaHWeH, onse Elohey sal dit ‘n skande vir ons laat wees.	",
"	24 Nou dan, broers, laat ons toon aan ons broers dat hulle lewe van ons afhang, en dat die Apartheid en die Tempel en die altaar op ons steun.	",
"	25 Laat ons by al hierdie dinge JaHWeH, onse Elohey dank, wat ons op die proef stel net soos ons vaders.	",
"	26 Gedenk wat Hy met Abraham gedoen het, en waarin Hy Isak beproef het, en wat Jakob oorkom het in Mesopotamië van Sirië, toe hy die skape oppas van Laban, die broer van sy moeder.	",
"	27 Want soos Hy hulle gelouter het om hulle harte te beproef, so is Hy nie besig om ons te bestraf nie; maar JaHWeH slaan die wat Hom soek, om hulle te waarsku.	",
"	28 Toe sê UzziJaH vir haar: Alles wat jy sê, het jy in die suiwerheid van jou hart gepraat; en daar is niemand wat jou woorde sal bestry nie.	",
"	29 Want jou wysheid blyk nie van vandag nie; inteendeel, die hele volk ken jou verstandigheid reeds sedert die begin van jou dae, omdat jou hart reg is.	",
"	30 Maar omdat die volk versmag van dors, het hulle ons gedwing om te doen soos ons vir hulle gesê het en om ons onder ‘n eed te plaas, wat ons nie sal breek nie.	",
"	31 Nou dan, bid vir ons, omdat jy ‘n vrou is wat Elohim vrees; en JaHWeH sal reën stuur om ons putte vol te maak; en ons sal nie meer verswak nie.	",
"	32 Toe sê Judit vir hulle: Luister na my; ek gaan ‘n daad doen wat die kinders van ons geslag aangaan in lengte van dae.	",
"	33 Gaan julle vannag by die poort staan, dan sal ek uitgaan saam met my kamerbediende; en in die dae, na verloop waarvan julle gesê het om die Stad aan ons vyande oor te gee, sal JaHWeH neersien op JisraEl deur my hand.	",
"	34 En julle moet nie wil uitvind wat ek gaan maak nie, want ek sal dit nie vir julle sê nie, totdat ek voltooi het wat ek van plan is om te doen.	",
"	35 Toe sê UzziJaH en die owerstes vir haar: Gaan in vrede, en mag JaHWeH jou Elohey met jou wees om ons vyande te straf.	",
"	36 En hulle het die tent verlaat en na hulle poste gegaan.	",

]
},
{
book: 'Judit',
chapter: '9',
content: [
		
"	1 JUDIT het neergeval op haar aangesig en as op haar hoof gestrooi en die boetekleed wat sy dra, ontbloot: Dit was presies die uur dat in Jerusalem die aandaanbieding in die Huis van JaHWeH gebring word: En met ‘n groot stem het Judit na JaHWeH geroep en gesê:	",
"	2 O, JaHWeH, die Elohey van my vader Simeon, aan wie U ‘n swaard in sy hand gegee het vir die bestraffing van die vreemdelinge wat die skoot van ‘n maagd geopen het tot besoedeling; wat haar heup ontbloot het tot beskaming, en wat haar skoot geskend het vir skande. Want ofskoon U gesê het: Dit sal nie so wees nie, het hulle dit tog gedoen.	",
"	3 Vanweë hierdie dinge het U hulle leiers aan die dood prysgegee; en aan die bloed het U hulle leërstede oorgegee, waarop sy vir hulle bedrog beswyk het en hulle self mislei is; en oor die heersers het U slawe aangestel as heersers op hulle trone.	",
"	4 U het hulle vroue as buit gegee en hulle dogters om as ballinge weggevoer te word; en hulle besit het U gegee om as buit verdeel te word deur U geliefde seuns, wat in ywer vir U geywer het, en wat gewalg het van die besoedeling van hulle bloed en na U om hulp geroep het. My El, my El! Luister na my wat weduwee is.	",
"	5 U het die dinge gewerk wat daarvoor gebeur het, en daardie dinge self, en ook: die dinge wat daarna gebeur het. U beplan wat nou gebeur, en dit wat nog sal gebeur. En dit wat U beplan, gebeur ook.	",
"	6 En die dinge wat U besluit het, kom na U toe en sê: Kyk, hier is ons. Want al U Weë is geskik, en U oordeel is in voorsienigheid.	",
"	7 En kyk, die Assiriërs is vervul van hulle leërmag, en hulle verhoog hulle oor perd en ruiter; hulle is vermetel deur die arm van hulle voetknegte; hulle vertrou op skild, werpspies, boog en slinger; tog weet hulle nie dat U JaHWeH is wat oorloë kan laat misluk nie.	",
"	8 JaHWeH is U Naam: U breek hulle sterkte deur U Krag en U verneder hulle krag deur U Woede. Want hulle het besluit om U Apartheid te skend, om die Tempel van die rus van U roemryke Naam te besoedel, en om die horing van U altaar met yster af te kap.	",
"	9 Aanskou hulle vermetelheid; bring U Woede op hulle hoofde; gee in die hand van my wat weduwee is die Krag wat ek oorweeg het.	",
"	10 Tref die slaaf deur die bedrog van my lippe by die heerser, en die heerser ter wille van sy bediende. Breek hulle trots deur die hand van ‘n vrou.	",
"	11 Want U Krag bestaan nie in ‘n groot menigte nie; U mag is nie geleë in krygsmanne nie. U is ‘n El van nederiges, U is ‘n helper van die wat min is, U is ‘n bystand vir swakkes, ‘n Beskermer van verworpelinge, ‘n Redder van wanhopiges	",
"	12 Ja, U is die Elohey van my vader, en die Elohey van die Erfdeel van JisraEl, die Elohey van Hemele en Aarde, Skepper van die waters, Koning van die hele skepping. Luister na my smeking!	",
"	13 Laat my woord en bedrog dié verwond en gesel wat kwaad beoog teen U Verbond en U Woning van Apartheid en die kruin van Sion en die Huis waar U kinders woon.	",
"	14 En leer U hele volk en elke stam om tog in te sien dat U, JaHWeH, die Elohey van alle Krag en mag is, en dat geen ander die volk van JisraEl beskerm nie, behalwe U.	",

]
},
{
book: 'Judit',
chapter: '10',
content: [
		
"	1 NADAT sy opgehou het om te roep na die Elohey van JisraEl en al daardie woorde gesê het,	",
"	2 het sy opgestaan van die plek waar sy neergeval het, en sy het haar kamerbediende geroep en afgeklim na haar huis, waarin sy slegs op die Sabbatdag en die Feeste vertoef het.	",
"	3 Toe het sy die boetekleed wat sy dra, uitgetrek en die klere van haar weduweeskap afgelê; sy het haar liggaam met water gewas en met dik mirre gesalf; sy het die hare van haar hoof gekam en daarop ‘n hoofversiersel gesit; en sy het haar feesklere aangetrek waarmee sy haar getooi het in die dae toe haar man Manasse nog geleef het.	",
"	4 Sy het sandale aan haar voete gesit en voetringe, armbande, vingerringe, oorversiersels en al haar sieraad; en sy het haar besonder fraai gemaak om die oë te bedrieg van al die manne wat haar mag gewaar.	",
"	5 En aan haar kamerbediende het sy ‘n sak wyn gegee en ‘n kruik olyfolie; sy het ook ‘n reissak volgemaak met gars, gedroogde vrugte en goeie brode; en sy het haar sak toegebind en vir haar bediende opgelê.	",
"	6 Toe het hulle na die stadspoort van Betoel gegaan en daar het hulle UzziJaH gevind, wat vir haar staan en wag, en die oudstes van die Stad, Abris en Samri.	",
"	7 Terstond nadat hulle haar gewaar het en sien dat haar gesig anders lyk en ook die kleding wat sy aangetrek het, het hulle met bewondering na haar buitengewone groot skoonheid gekyk; en hulle het vir haar gesê: [2 Ezra 7:26]	",
"	8 Mag die Elohey van ons vaders aan jou Sy Guns bewys; mag Hy jou planne laat slaag tot verhoging van die kinders van JisraEl en tot verheffing van Jerusalem. Toe het hulle JaHWeH aanbid en gesê:	",
"	9 'Beveel dat die stadspoort oopgemaak word vir my, dan sal ek uitgaan om die planne uit te voer waaroor julle met my gepraat het.' En hulle het aan die jong manne bevel gegee dat die poort vir haar oopgemaak word, soos sy gesê het.	",
"	10 En hulle het dit gedoen. Toe het Judit uitgegaan, sy en haar diensmeisie wat by haar was. En die manne van die Stad het haar agternagekyk tot die plek waar sy van die berg afklim en in die vlakte gaan; en toe het hulle haar nie meer gesien nie.	",
"	11 Hulle het reguit geloop oor die vlakte, toe ‘n brandwag van die Assiriërs haar aantref.	",
"	12 Hy het haar voorgekeer en ondervra: Van watter volk is jy? Waar kom jy vandaan? Waarheen gaan jy? En sy het gesê: Ek is ‘n dogter van die Hebreërs en ek is besig om van hulle weg te loop, omdat hulle sekerlik aan julle tot spys gegee sal word.	",
"	13 Maar ek gaan tot voor Holofernes, die opperbevelhebber van julle leërmag om hom ‘n ware boodskap te bring; en voor sy aangesig sal ek hom ‘n weg wys wat hy moet volg om die hele bergland te onderwerp, sonder dat sy manskappe gewond of gedood word.	",
"	14 Terstond toe die manne haar woord hoor en haar voorkoms opmerk - want sy het vir hulle wonderlik gelyk deur haar buitengewone skoonheid,- het hulle vir haar gesê:	",
"	15 Jy het jou lewe gered deur jou verlange om af te klim tot voor die aangesig van ons bevelhebber. Nou dan, gaan na sy tent, en van ons af sal hulle jou begelei, totdat hulle jou in sy hande oordra.	",
"	16 En wanneer jy voor hom staan, wees dan nie bevrees in jou hart nie, maar deel hom jou boodskap mee, en hy sal jou goed doen.	",
"	17 En hulle het uit hulle midde honderd manskappe gekies, wat saamgegaan het met haar en haar kamerbediende, en hulle het haar by die tent van Holofernes gebring.	",
"	18 In die hele laer het daar toe ‘n sameloop ontstaan, want haar verskyning het deur geroep na die tente bekend geword. Hulle het gekom en haar omring, soos sy daar buitekant Holofernes se tent staan, totdat hulle hom berig gegee het oor haar.	",
"	19 En hulle was vol bewondering vir haar skoonheid en hulle het die kinders van JisraEl bewonder om haar ontwil. Hulle het vir mekaar gesê: Wie sal hierdie volk verag wat sodanige vroue in sy midde het? Dit is dan ook nie reg om ook maar een van hulle manne te laat oorbly nie, want as hulle vrygelaat word, kan hulle deur verleiding die hele Aarde onderwerp.	",
"	20 Toe het Holofernes se tentgenote en al sy dienare na buite gekom en haar in die tent gebring.	",
"	21 Holofernes het self op sy rusbed gelê onder ‘n muskietnet, wat versier is met koningsblou en goud en smarag en kosbare stene wat daaraan vasgewerk is.	",
"	22 En hulle het hom berig gegee oor haar, en hy het uitgegaan na die voorvertrek, terwyl silwer lampe voor hom vooruitgedra is.	",
"	23 En toe Judit voor hom en sy dienare kom, het almal haar bewonder vanweë die skoonheid van haar voorkoms. En sy het neergeval op haar aangesig en hom gehuldig; en sy dienare het haar opgerig.	",

]
},
{
book: 'Judit',
chapter: '11',
content: [
		
"	1 TOE sê Holofernes vir haar: Hou goeie moed, vrou, en wees nie be- vrees in jou hart nie! Ek het nog geen mens kwaad berokken wat bereid is om Nebukadnésar, die koning van die hele Aarde, te dien nie.	",
"	2 Nou dan, jou volk wat in die bergland woon: as hulle my nie sou geminag het nie, dan sou ek my spies nie teen hulle opgeneem het nie. Maar hulle het dit self oor hulle gebring.	",
"	3 Maar sê jy nou vir my waarom jy van hulle af weggeloop het en na ons toe gekom het. Jy is nou veilig. Hou goeie moed; hierdie nag sal jy lewe, en ook in die toekoms.	",
"	4 Want daar is niemand wat jou onreg sal aandoen nie, maar wel wat jou sal goeddoen, soos die geval is met almal wat onderdane is van my meester, koning Nebukadnésar.	",
"	5 Toe sê Judit vir hom: Neem die woorde aan van u dienares, en laat u slavin praat voor u aangesig; ek sal in hierdie nag aan my meester geen leuen meedeel nie.	",
"	6 As u die woorde van u slavin opvolg, sal Elohim u onderneming laat slaag; en my meester sal die voltooiing van sy werke nie ontgaan nie.	",
"	7 Want soos Nebukadnésar, die koning van die hele Aarde leef, so leef ook die mag van hom wat u gestuur het vir die tugtiging van elke lewende wese; omdat nie alleen die mense hom deur u onderdanig is nie, maar ook die wilde diere van die veld en die vee en die voëls van die Hemele, deur u krag leef vir Nebukadnésar en sy hele huis.	",
"	8 Want ons het verneem van u wysheid en van die werke van u gees; en aan die hele Aarde het dit bekend geword dat in ‘n oorlog alleen u dapper is in die hele koninkryk en kragtig in kennis en bewonderenswaardig in veldtogte.	",
"	9 Nou dan, die woord wat Agior in u raadsvergadering gesê het. Ons het sy woorde gehoor, omdat die manne van Betoel hom sy lewe laat hou het en hy aan hulle alles meegedeel het wat hy vir u gesê het.	",
"	10 Daarom, meester en gebieder, gaan nie agteloos by sy woorde verby nie, maar bewaar hulle in u hart, want dit is die waarheid. Ons geslag word nie gestraf en die swaard vermag niks teen hulle nie, as hulle nie oortree teen hulle Elohey nie.	",
"	11 Nietemin, laat my meester nie neerslagtig en verydel voel nie: die Dood sal oor hulle kom, want ‘n oortreding het hulle oormeester, waardeur hulle hulle Elohey sal vertoorn, wanneer hulle hierdie ongerymdheid doen.	",
"	12 Want omdat hulle voedsel opgeraak het en al die water skaars geword het, het hulle dit oorweeg om die hand te slaan aan daardie vee en aan al die dinge wat hulle Elohey deur Sy Wette beveel het om nie te eet nie; en hulle het tot die verkwisting besluit.	",
"	13 En selfs omtrent die eerstelinge van die koring en die tiendes van die wyn en van die olie, wat hulle as gawes afsonder vir die priesters wat in Jerusalem voor die Aangesig van onse Elohey staan, het hulle geoordeel om dit oop te maak; en dit is dinge waaraan niemand van die gewone volk met sy hande mag raak nie.	",
"	14 En omdat die inwoners van Jerusalem dieselfde dinge gedoen het, het hulle manne daarheen gestuur wat hulle gerusgestel het met die ontheffing deur die raad van oudstes.	",
"	15 En as dit sal wees dat hulle inderdaad doen soos vir hulle gesê is, dan word hulle nog op dieselfde dag aan u oorgelewer tot hulle ondergang.	",
"	16 Daarom het ek, u dienares, toe ek al daardie dinge sien, van hulle af weggehardloop; en Elohim het my gestuur om met u dinge te doen waaroor die hele Aarde verbaas sal wees, en almal wat dit hoor.	",
"	17 Want u dienares vrees JaHWeH en dien die Elohey van die Hemele bedags en snags. Ek sal nou bly by u, my meester, maar u dienares sal in die nag uitgaan na die kloof, en dan sal ek tot JaHWeH bid; en Hy sal vir my sê wanneer hulle hulle oortredinge gedoen het.",
"	18 En ek sal dan vir u kom sê, sodat u saam met u hele leër kan uittrek, sonder dat daar iemand van hulle is wat u kan weerstaan.	",
"	19 En ek sal u deur die midde van JeHûWdah tot by Jerusalem lei en u troon dan in die midde van haar sit; en u sal hulle lei soos skape wat sonder herder is, en selfs sal daar geen hond wees wat vir u blaf nie. Want hierdie dinge is aan my gesê en meegedeel deur middel van my voorkennis, en ek is gestuur om u van haar berig te gee.	",
"	20 Haar woorde het behaag aan Holofernes en aan al sy ondergeskiktes, en hulle het hulle verbaas oor haar wysheid. En hulle het gesê:	",
"	21 Daar bestaan nie nog so ‘n vrou van die een Einde van die Aarde tot die ander met so ‘n skoonheid in haar voorkoms en wysheid in haar woorde nie.	",
"	22 En Holofernes het vir haar gesê: Elohim het reg gedoen deur jou voor jou volk vooruit te stuur om ‘n krag te wees in ons hande, maar die ondergang vir hulle wat my meester verag het.	",
"	23 Nou dan, jou voorkoms is fraai en jou woorde is reg. Wanneer jy daarom doen soos jy gesê het, sal jou Elohey ook my Elohey wees, en dan sal jy woon in die huis van koning Nebukadnésar, en jy sal beroemd wees oor die hele Aarde.	",

]
},
{
book: 'Judit',
chapter: '12',
content: [
		
"	1 EN hy het beveel om haar te bring na die plek waar hy sy silwer kosbaarhede opgeslaan het, en hy het opdrag gegee om op te dien van sy eie smaaklike geregte en van sy eie wyn om te drink.	",
"	2 Toe sê Judit: Ek sal nie daarvan eet nie, sodat dit geen oorsaak van oortreding kan word nie; maar ek sal van die voedsel eet wat ek saamgebring het.	",
"	3 En Holofernes sê vir haar: Maar as die voedsel wat jy by jou het, opgeraak het, waarvandaan sal ons dan soortgelyke dinge kry om aan jou te gee? Want daar is niemand van jou volk by ons nie.	",
"	4 Toe sê Judit weer vir hom: U siel sal lewe, my meester, want u slavin sal die dinge wat ek saamgebring het, nie verbruik het nie, voordat JaHWeH deur my hand doen wat Hy besluit het.	",
"	5 En Holofernes se dienaars het haar na die tent gelei, en sy het geslaap tot middernag. Teen die môrewake het sy opgestaan,	",
"	6 en sy het na Holofernes gestuur en gesê: Laat my meester beveel dat dit aan sy slavin toegestaan word om buitekant te gaan bid.	",
"	7 En Holofernes het aan die lyfwag beveel om haar nie te belet nie. En sy het drie dae in die laer gebly, en snags het sy uitgegaan na die kloof van Betoel en binne die laer by die fontein gebad.	",
"	8 Terwyl sy weer opgaan, het sy JaHWeH die Elohey van JisraEl gebid om haar weg te rig na die verhoging van die kinders van haar volk.	",
"	9 En sy het binnegegaan in haar tent en suiwer gebly, totdat sy teen die aand van haar voedsel geneem het.	",
"	10 Daarna, op die vierde dag, het Holofernes alleen vir sy slawe ‘n drinkgelag aangerig, maar hy het nie een van die gebruiklike gaste uitgenooi nie.	",
"	11 En vir Bagoas, die ontmande wat al sy besittings beheer het, het hy gesê: Gaan nou na die Hebreeuse vrou wat by jou is, en oorreed haar om na ons toe te kom en saam met ons te eet en te drink.	",
"	12 Want kyk, dit is ‘n skande voor ons aangesig as ons so ‘n vrou laat weggaan, sonder dat ons omgang gehad het met haar; want as ons haar nie verlok nie, sal hulle oor ons lag.	",
"	13 En Bagoas het Holofernes verlaat en by haar binnegegaan, en hy het gesê: Laat die jong dogter, wat so fraai is, nie langer wag om na my meester toe te gaan nie en voor sy aangesig geëer te word en saam met ons in vrolikheid wyn te drink en vandag soos een van die dogters van die kinders van Assur te word wat in die huis van Nebukadnésar inwoon.	",
"	14 Toe sê Judit vir hom: En wie is ek, sodat ek my meester sal teenspreek? Alles wat in sy oë die beste is, sal ek my haas om te doen; en dit sal vir my ‘n vreugde wees tot die oomblik van my dood.	",
"	15 En sy het opgestaan en haar versier met klere en allerlei vroulike opsmuk. Haar slavin het vooruitgegaan en op die Aarde voor Holofernes vir haar die skaapvag uitgesprei wat sy vir haar daaglikse gebruik by Bagoas gekry het, om daarop te lê en eet.	",
"	16 En Judit het binnegegaan en gaan lê; en Holofernes se hart het oor haar ontvlam en sy siel is geskok, want hy het baie begeer om met haar gemeenskap te hê; en hy het na ‘n gunstige oomblik gesoek om haar te verlei sedert die dag waarop hy haar gesien het.	",
"	17 En Holofernes het vir haar gesê: Drink dan, en wees vrolik saam met ons.	",
"	18 Toe sê Judit: Ek sal drink, meester, omdat my lewe vandag meer geëer is as in al die ander dae van my bestaan.	",
"	19 En sy het geneem en voor hom geëet en gedrink van die dinge wat haar slavin toeberei het.	",
"	20 En Holofernes het hom in haar verlustig, en hy het buitengewoon veel wyn gedrink; soveel soos hy nog nooit op een dag sedert sy geboorte gedrink het nie.	",

]
},
{
book: 'Judit',
chapter: '13',
content: [
		
"	1 TOE dit laat word, het sy slawe haastig geword om weg te gaan. En Bagoas het die tent buitekant toegesluit, en hy het die bystanders buite die aangesig van sy meester gesluit; en hulle het weggegaan na hulle rusplekke, want hulle was almal moeg, omdat die drank te veel geword het vir hulle.	",
"	2 Judit is alleen in die tent agtergelaat, terwyl Holofernes vooroor op sy rusbed geval het; en die wyn was rondom hom uitgegiet.	",
"	3 En Judit het vir haar slavin gesê om buitekant haar slaapvertrek te staan en wag, totdat sy uitkom soos elke dag; want sy het gesê dat sy sou uitgaan vir haar gebed, en ook met Bagoas het sy ooreenkomstig hierdie afspraak gepraat.	",
"	4 En almal het weggegaan, en niemand, van klein tot groot, het in die slaapvertrek agtergebly nie. En Judit het by sy rusbed gaan staan en het in haar hart gesê: JaHWeH, El Almagtig, sien in hierdie uur neer op die werke van my hande tot verhoging van Jerusalem.	",
"	5 Want nou is die geskikte oomblik om U Erfdeel vas te hou en my plan uit te voer tot vernietiging van die vyande wat teenoor ons staan.	",
"	6 Toe het sy na die bedstang naby Holofernes se hoof gegaan en sy swaard daarvan afgehaak.	",
"	7 En sy het nader aan die bed gegaan en die hare van sy hoof vasgegryp en gesê: Gee my Krag, JaHWeH, Elohey van JisraEl, op hierdie dag!	",
"	8 En met al haar krag het sy twee keer op sy nek geslaan en sy hoof van sy liggaam gekap.	",
"	9 Toe het sy die liggaam van die bed gewentel en die muskietnet van die style losgetrek; en terstond daarna het sy uitgegaan en aan haar bediende die hoof van Holofernes oorhandig.	",
"	10 En sy het hom in die sak van haar voedsel gesit. En hulle twee het uitgegaan, net soos hulle gewoonte gewees het wanneer hulle gaan bid het. En hulle het deur die kamp gegaan en verby daardie kloof geloop en op die berg van Betoel geklim en so die stadspoorte genader.	",
"	11 En op ‘n afstand het Judit vir die poortwagters geroep: Maak oop! Maak oop die Poort! JaHWeH, onse Elohey is met ons om JisraEl weer kragtig en sterk te maak teen die vyande, soos Hy vandag gedoen het.	",
"	12 Toe die manne van die Stad haar stem hoor, het hulle haastig van die stadspoort na onder gekom en hulle het die oudstes van die Stad geroep.	",
"	13 En almal, van klein tot groot, het hulle saamgestroom, omdat sy teen hulle verwagting gekom het. En hulle het die Poort oopgemaak en hulle binne gelaat; en hulle het vuur geneem om lig te maak, en hulle het in ‘n kring rondom hulle gaan staan.	",
"	14 Toe het sy met ‘n groot stem vir hulle gesê: Loof JaHWeH! Loof! Loof JaHWeH, wat Sy Ontferming nie afgewend het van die huis van JisraEl nie, maar wat ons vyande in hierdie nag deur my hand verslaan het.	",
"	15 En sy het die hoof uit die sak geneem, en terwyl sy hom aan hulle wys, het sy gesê: Kyk, dit is die hoof van Holofernes, die opperbevelhebber van die leërmag van Assur; en kyk, hier is die muskietnet waarin hy gelê het in sy dronkenskap. JaHWeH het hom geslaan deur die hand van ‘n vrou.	",
"	16 Mag JaHWeH leef wat my beskerm het op my weg, waarop ek gewandel het; omdat my aangesig hom mislei het na sy ondergang, en hy nie met my oortree het tot besoedeling en skande nie.	",
"	17 En die hele bevolking was baie verbaas, en hulle het neergebuig en JaHWeH aanbid en eenparig gesê: Geseën is U, onse Elohey, wat op hierdie dag die vyande van U volk vernietig het.	",
"	18 En UzziJaH het vir haar gesê: Geseën is jy, dogter, deur die Hoogste El bo al die vroue op die Aarde; en geseën is JaHWeH die Elohey, Skepper van die Hemele en die Aarde, wat jou gelei het tot die onthoofding van die opper-bevelhebber van ons vyande.	",
"	19 Want jou hoop sal nie wyk uit die harte van die mense wat die Krag van Elohim gedenk tot in ewigheid nie.	",
"	20 En mag Elohim dit aan jou vergeld tot ‘n voortdurende verhoging deur neer te sien op jou tot Verlossing; want jy het jou lewe nie ontsien vanweë die vernedering van ons volk nie, maar jy het ons ondergang voorkom tot uitredding deur te wandel voor die Aangesig van onse Elohey. En die hele bevolking het gesê: Mag dit so wees! Mag dit so wees!	",

]
},
{
book: 'Judit',
chapter: '14',
content: [
		
"	1 TOE sê Judit vir hulle: Luister na my, broers! Neem hierdie hoof en hang dit aan die borswering van julle mure.	",
"	2 En wanneer dit so ver is dat die rooidag sigbaar word en die son uitkom oor die Aarde, neem dan almal julle wapens op en laat al die krygsmanne uit die poort uittrek. Stel ook ‘n bevelhebber oor hulle aan; en daal af na die vlakte asof julle na die wagpos van die kinders van Assur gaan, maar julle moet nie klaar afklim nie.	",
"	3 Hulle sal dan na hulle wapens gryp en na hulle laer gaan en die bevelhebbers van die leër van Assur wakker maak. Daarna sal hulle saamstroom na die tent van Holofernes en hom nie kry nie. Vrees sal hulle oormeester, en voor julle aangesig sal hulle op die vlug slaan.	",
"	4 Dan moet julle en al die bewoners van die hele landstreek van JeHûWdah hulle agtervolg en neerslaan op hulle paaie.	",
"	5 Maar voordat dit gebeur, roep julle vir my Agior, die Ammoniet, sodat hy diegene kan sien en uitken wat die huis van JisraEl geminag het, en hoe hy tot sy ondergang na ons uitgestuur is.	",
"	6 En hulle het Agior uit die huis van UzziJaH ontbied. En toe hy kom en die hoof van Holofernes sien in die hand van een van die manne in die volksmenigte, het hy op sy aangesig neergeval en sy asem verloor.	",
"	7 Nadat hulle hom opgehelp het, het hy by die voete van Judit neergekniel en voor haar neergebuig en gesê: Geseën is jy in al die woontente van JeHûWdah en onder elke volk; die wat jou naam sal hoor, sal verbaas wees.	",
"	8 Nou dan, vertel my watter dinge jy in hierdie dae gedoen het. En Judit het hom in die midde van die volk alles meegedeel wat sy gedoen het, vanaf die dag waarop sy weggegaan het tot die oomblik waarop sy nou vir hulle praat.	",
"	9 En toe sy ophou met praat, het die volk met ‘n groot stem geroep, en hulle het in hulle Stad uiting gegee aan hulle blydskap.	",
"	10 En toe Agior alles sien wat die Elohey van JisraEl gewerk het, het hy hartstogtelik in JaHWeH geglo; hy is aan die vlees van sy voorhuid besny en by die huis van JisraEl ingelyf tot vandag toe.	",
"	11 En op die tyd dat die rooidag aanbreek, het hulle die hoof van Holofernes aan die stadsmuur gehang; elke man het sy wapens opgeneem, en in afdelinge het hulle uitgetrek met die toegangspaaie van die berg.	",
"	12 Toe die kinders van Assur hulle gewaar, het hulle berig gegee aan hulle owerstes, wat weer na die bevelhebbers gegaan het en na die hoofmanne oor duisend en na die opperbevelhebbers.	",
"	13 En nadat hulle by die tent van Holofernes gekom het, het hulle vir diegene wat al sy besittings opgepas het, gesê: Maak ons meester wakker, want die slawe waag dit om af te klim na ons toe en te veg, om so hulle verdelging tegemoet te gaan.	",
"	14 Bagoas het ingegaan en op die gordyn van die tent geslaan, omdat hy gemeen het dat hy saam met Judit slaap.	",
"	15 Maar toe hy niks hoor nie, het hy die gordyn oopgeskuif en in die slaapvertrek binnegegaan en hom dood aangetref, soos hy by die drumpel lê en met sy hoof van sy liggaam gekap.	",
"	16 Hy het hard geskreeu met gejammer en gesug en kragtige uitroepe; en hy het sy klere geskeur.	",
"	17 Vervolgens het hy in die tent binnegegaan waar Judit vertoef het, maar hy het haar nie gevind nie. Toe het hy na die menigte buitekant gehardloop en geskreeu:	",
"	18 Gewetenloos het hulle gehandel, die slawe! Een vrou van die Hebreërs het skande gebring oor die huis van koning Nebukadnésar. Want kyk, Holofernes lê op die grond , en hy het nie ‘n hoof nie.	",
"	19 En die bevelhebbers van die leër van Assur wat hierdie woorde hoor, het hulle klere geskeur, en ‘n groot vrees het hulle oormeester, sodat daar in die midde van die laer ‘n geroep en ‘n baie heftige geskreeu ontstaan.	",

]
},
{
book: 'Judit',
chapter: '15',
content: [
		
"	1 EN toe die wat nog in die tente is hoor wat gebeur het, het dit hulle baie ontstel.	",
"	2 En angs en vrees het hulle oormeester, sodat niemand nog by die man langsaan hom gebly het nie; maar in dieselfde toestand het hulle uiteen gespat en met elke pad van die vlakte en die bergland weggevlug.	",
"	3 En die wat hulle laers rondom Betoel in die bergland het, het ook op die vlug geslaan. En toe het die kinders van JisraEl, elke strydbare man uit hulle midde, hulle agternagesit.	",
"	4 En UzziJaH het na Bet-Místeh en Beba en Hoba en Kola en die hele grondgebied van JisraEl manne gestuur om te boodskap wat gebeur het, sodat almal die vyande sou agtervolg totdat hulle uitgeroei is.	",
"	5 En toe die kinders van JisraEl dit verneem, het hulle eensgesind die vyande agternagesit en hulle geslaan tot by Hoba. Ook uit Jerusalem het hulle gekom en uit die hele bergland, omdat ook aan hulle berig gegee is wat in die laer van hulle vyande plaasgevind het. En die in Gilead en die in Galilea het hulle deur ‘n groot slag oorvleuel, totdat hulle by die stad en die grondgebied van Damaskus gekom het.	",
"	6 En die inwoners van Betoel wat agtergebly het, het na die laer van Assur gehardloop en hulle geplunder en ‘n baie ryk buit ingesamel.	",
"	7 En toe die kinders van JisraEl terugkom van die slagting, het hulle die oorskot in besit geneem; en die dorpe en plase van die bergland en die vlakte het ryk aan buit geword, want daar was ‘n baie groot hoeveelheid gewees.	",
"	8 En JeHôWjakim, die hoëpriester, en die oudstes van die kinders van JisraEl wat in Jerusalem woon, het gekom om die weldade te sien wat JaHWeH aan JisraEl gedoen het, en ook om Judit te sien en met haar te praat oor die vrede.	",
"	9 Toe hulle by haar aankom, het almal eenparig haar geprys en vir haar gesê: Jy is die verhoging van Jerusalem! Jy is die groot trots van JisraEl! Jy is die roem van ons geslag!	",
"	10 Al hierdie dinge het jy met eie hand gedoen. Jy het goeie dinge vir JisraEl gedoen, en Elohim het jou daarvoor uitgekies. Wees geseën van die Almagtige JaHWeH tot in ewigheid. En die volk het gesê: Mag dit so wees!	",
"	11 En die hele volk het dertig dae lank die laer geplunder. Aan Judit het hulle die tent van Holofernes gegee en al sy silwerwerk en rusbeddens en skottels en al die vaatwerk. En sy het dit geneem en op haar muilesel gesit, en sy het haar waens ingespan en dit daarop gedoen.	",
"	12 En al die vroue van JisraEl het gekom om haar te sien; en hulle het haar geprys, en hulle het uit hulle midde vir haar ‘n koor gevorm. En sy het takke in haar hande geneem en gegee aan die vroue wat by haar is.	",
"	13 Toe het hulle Olyfkranse opgesit, sy en die wat saam met haar is. En sy het voor die hele volk vooruitgegaan in ‘n reidans as leidster van die vrouens; en al die mans van JisraEl het in hulle wapenrusting en met kranse om, agterna gekom en lofliedere gesing.	",
"	14 In die midde van die hele JisraEl het Judit toe hierdie lofsang aangehef, en die hele volk het hierdie danklied nagesing.	",

]
},
{
book: 'Judit',
chapter: '16',
content: [
		
"	1 EN Judit het gesê: Hef aan ‘n lied vir my Elohey met tamboeryne, loof JaHWeH met simbale; begelei Hom met psalmsing en lofprysing, verhoog en prys Sy Naam!	",
"	2 Want JaHWeH is onse Elohey wat ‘n oorlog beslis; Hy het my na Sy laer in die midde van die volk gebring uit die hande van my vervolgers.	",
"	3 Assur het uit die berge van die noorde gekom; hy het gekom met sy geweldige leër, en hulle menigte het die bergstrome teengehou, en hulle perde het die heuwels bedek.	",
"	4 Hy het gesê dat hy my grond aan die brand steek, en my jonkmans sal dood met sy swaard, en my suiglinge sal werp op die Aarde, en my kinders sal weggee as buit, en my maagde hulle eer sal ontneem.	",
"	5 Maar die Almagtige JaHWeH het hulle verjaag deur die hand van ‘n vrou.	",
"	6 Want hulle leier het nie geval deur die hand van ‘n jonkman, en nie seuns van helde het hom verslaan, en ook nie groot reuse het hom gedood nie; maar Judit, Merari se dogter, het hom verlam deur die skoonheid van haar gelaat.	",
"	7 Haar weduweekleed het sy afgelê tot verhoging van wie swaar leef in JisraEl; haar gesig het sy gesalf met die olie uit mirre.	",
"	8 Haar hare het sy gebind met ‘n hoofsieraad; ‘n linnekleed trek sy aan tot misleiding.	",
"	9 Haar sandaal het sy oë gebuit, haar skoonheid sy gees gevang; maar die swaard het deur sy nek gegaan.	",
"	10 Die Perse het gehuiwer voor haar durf, en Mediërs is verwar deur haar moed.	",
"	11 Toe het my verdruktes ‘n geskreeu laat weerklink; en my swakkes, vol angs en verwarring, het luid hulle stemme verhef en hulle vyand verwilder.	",
"	12 Deursteek is hulle soos die seuns van ontugtige vroue, en gekwes soos kinders van swerfsters; hulle het geval deur die slagorde van my Meester.	",
"	13 ‘n Nuwe lied sal ek sing voor my Elohey: JaHWeH, U is groot en geëer, wonderbaarlik is U in U Krag en onoorwinlik.	",
"	14 U hele skepping moet U vereer, want U het gespreek en hulle het ontstaan; U het U Gees gestuur en Sy het ‘n Huis gebou; daar is niemand wat U stem kan weerstaan nie.	",
"	15 Want berge word uit hulle grondveste geskud soos water, en rotse smelt voor U Aanblik soos was; maar U is goedgunstig vir die wat U vrees.	",
"	16 Al die reukwerk is te min vir ‘n soet reuk tot U, en al die vet is nie voldoende vir U brandoffer nie; maar hy wat JaHWeH vrees, is vir altyd groot.	",
"	17 Wee die nasies wat teenoor my volk kom staan; die Almagtige JaHWeH straf hulle op die dag van Sy oordeel; Hy gee hulle vlees aan die vuur en die wurms, sodat hulle ewig sal weeklaag in smart.	",
		
"	18 TOE hulle in Jerusalem kom, het hulle JaHWeH aanbid. En nadat die volk gewas is, het hulle brandoffers opgedra asook vrywillige gawes en geloftegawes.	",
"	19 En Judit het al die gebruiksvoorwerpe van Holofernes, wat die volk aan haar gegee het, opgedra; en ook die muskietnet wat sy vir haar self uit sy slaapvertrek geneem het, het sy as ‘n gawe aan JaHWeH gegee.	",
"	20 En drie maande lank was die volk in Jerusalem vrolik voor die aangesig van die Apartheidsplek, terwyl Judit in hulle midde gebly het.	",
"	21 Na hierdie dae het elkeen weer afgereis na sy erfdeel; en Judit het teruggekeer na Betoel en by haar besittings gebly, en sy was in haar tyd baie geëer in die hele Aarde.	",
"	22 Baie mans het haar begeer, maar nie een het haar beken gedurende al die dae van haar lewe vanaf die dag waarop haar man Manasse gesterf het en by sy volk versamel is nie.	",
"	23 En sy het baie toegeneem in grootheid, en sy het in die huis van haar man die ouderdom van honderd-en-vyf jaar bereik. Aan haar kamerbediende het sy die vryheid gegee; en sy het in Betoel gesterf, en hulle het haar begrawe in die grot van haar man Manasse.	",
"	24 En die huis van JisraEl het sewe dae rou bedryf oor haar. Haar besittings het sy voor haar dood verdeel onder al die naasbestaandes van haar man Manasse en die naasbestaandes uit haar eie geslag.	",
"	25 In die dae van Judit en nog lank daarna was daar niemand wat die kinders van JisraEl nog vrees aangeja het nie.	",

]
}

];
