const klaagliedere_van_jeremiaChapters = [

{
book: 'Klaagliedere_van_Jeremia',
chapter: '1',
content: [

"	1 [ae Alef.] AG, hoe verlate sit die Stad wat vol mense was! Sy het soos ’n weduwee geword, Sy wat magtig was onder die nasies; die prinses onder die provinsies het dwangarbeid verrig.	",
"	2 [B Bet.] Bitterlik ween Sy snags - Haar trane oor Haar wange! Sy het geen Trooster onder al Haar liefhebbers nie; al Haar vriende het verraad gepleeg teen Haar, Haar vyande geword.	",
"	3 [G:Ghimel.] JeHûWdah is ontvolk deur ellende en deur sware diensbaarheid; sy sit onder die nasies, sonder om ’n rusplek te vind; al haar vervolgers het haar ingehaal tussen die engtes in.	",
"	4 [D’ Dalet.] Die Weë na Sion treur, omdat daar geen feesgangers is nie; al Haar poorte lê woes, Haar priesters sug, Haar maagde is bedroef, en Sy het dit bitter.	",
"	5 [h Hé.] Haar teëstanders het die oorhand gekry, Haar vyande lewe rustig; want JaHWeH het Haar droefheid aangedoen vanweë die menigte van Haar oortredinge; Haar kinders het in gevangenskap gegaan voor die teëstander uit.	",
"	6 [w” Waw.] En van die Dogter van Sion het gewyk al Haar grootsheid; Haar vorste het geword soos takbokke wat geen weiveld vind nie en kragteloos heengegaan het voor die vervolger uit.	",
"	7 [zÉ Zajin.] Jerusalem dink, in die dae van Haar ellende en Haar omswerwinge, aan al Haar kosbaarhede wat gewees het van die dae van die voortyd af. Toe Haar volk deur die hand van die teëstander geval het en daar vir Haar geen helper was nie, het die teëstanders Haar aanskou, hulle het gelag oor Haar uitwissing.	",
"	8 [je Get.] Jerusalem het swaar oortree, daarom het Sy ’n voorwerp van afsku geword; almal wat Haar geëer het, verag Haar, omdat hulle Haar naaktheid gesien het; Sy self sug en het Haar weggedraai.	",
"	9 [fu Tet.] Haar besoedeling kleef aan Haar some, Sy het aan Haar einde nie gedink nie, en Sy het wonderbaarlik gesink, sonder dat Sy ’n Trooster het. Sien My ellende aan, JaHWeH, want die vyand hou hom groot.	",
"	10 [y Jod.] Die teëstander het sy hand uitgesteek na al Haar kosbaarhede; ja, Sy het gesien hoedat nasies in Haar Apartheidsplek ingekom het, van wie U bevel gegee het dat hulle in U vergadering nie mag kom nie. [Deuteronómium 23:2]	",
"	11 [K Kaf.] Haar hele volk sug, hulle soek Brood, hulle het hul kosbaarhede vir voedsel gegee, om hul siel te verkwik. Aanskou, JaHWeH, en merk op dat Ek ’n veragte geword het.	",
"	12 [l¿ Lamed.] Raak dit julle nie, julle almal wat met die pad verbygaan? Aanskou en kyk of daar ’n smart is soos My smart wat My aangedoen is, waarmee JaHWeH My bedroef het op die dag van Sy brandende Woede.	",
"	13 [mi Mem.] Uit die hoogte het Hy Vuur gestuur in My gebeente en dit oorweldig, Hy het ’n net voor My voet uitgesprei, Hy het My agteruit laat wyk, Hy het My woes gemaak, die hele dag ellendig.	",
"	14 [nI Noen.] Die juk van My oortredinge is vasgebind deur Sy Hand, sy is saamgevleg, sy het op My nek gekom, sy het My krag laat struikel. My Meester het My oorgegee in die hande van een teen wie ek geen teëstand kon bied nie.	",
"	15 [si Samek.] My Meester het al My magtiges binne-in My verwerp, Hy het teen My ’n feestyd uitgeroep om My jongmanne te verbreek; My Meester het die parskuip getrap vir die Maagd, die Dogter van JeHûWdah.	",
"	16 [[ Ajin.] Daarom ween Ek, My oog, My oog loop af in water, want ver van My is die Trooster wat My Siel verkwik; My kinders is verbyster, omdat die vyand die oorhand het.	",
"	17 [Pe Pé.] Sion brei Haar hande uit, Sy het geen Trooster nie; JaHWeH het die wat rondom hom was, teen Jakob ontbied as Sy teëstanders; Jerusalem het in hul midde geword soos ‘n vrou wat menstrueer.	",
"	18 [x’ Tzadé.] Regverdig is Hy, JaHWeH, want Ek het gerebelleer teen Sy Mond. Hoor tog, alle volke, en aanskou My smart; My maagde en My jongmanne het in gevangenskap gegaan.	",
"	19 [q Kof.] Ek het geroep na My liefhebbers - hulle het My in die steek gelaat; My priesters en My oudstes het in die Stad beswyk toe hulle voedsel vir hulle gesoek het om hulle siel te verkwik.	",
"	20 [r Resj.] Aanskou, JaHWeH, hoe benoud Ek is, My ingewande is in beroering, My Hart draai om in My binneste, want Ek was baie rebels; buitekant het die swaard berowe, binnekant is dit die pes. [Hooglied 11:6]	",
"	21 [v Sjin.] Hulle hoor dat Ek sug, Ek het geen Trooster nie; al My vyande hoor van My besoedeling, hulle is bly dat U dit gedoen het. U laat die dag kom wat U uitgeroep het, dat hulle kan wees soos Ek, [Klaagliedere 4:13]	",
"	22 [T Taw.] dat al hulle besoedeling voor U Aangesig kom; en doen aan hulle soos U aan My gedoen het vanweë al My oortredinge, want My versugtinge is baie, en My Hart is krank.	",

]
},
{
book: 'Klaagliedere_van_Jeremia',
chapter: '2',
content: [
		
"	1 [ae Alef.] AG, hoe het my Meester in Sy Toorn die Dogter van Sion met ‘n donker wolk oordek! Hy het die Sieraad van JisraEl uit die Hemele op die Aarde neergewerp en nie gedink aan die Voetbank van Sy voete op die dag van Sy Toorn nie. [1 Kronieke 28:2; Openbaring van Henog 8:8; 2 Ezra 6:4 ; Hooglied 11:5]	",
"	2 [Bi Bet.] My Meester het al die woonplekke van Jakob sonder verskoning verslind; in Sy Grimmigheid het Hy die vestings van die Dogter van JeHûWdah verwoes, op die Aarde gewerp, die koninkryk en haar vorste vermeng.	",
"	3 [G Ghimel.] Hy het in gloeiende Toorn elke horing van JisraEl afgekap; Hy het Sy Regterhand teruggetrek voor die vyand, en in Jakob het Hy gebrand soos ’n vuurvlam wat rondom verteer.	",
"	4 [D Dalet.] Hy het Sy boog gespan soos ’n vyand, Hy staan met Sy Regterhand soos ’n teëstander en het gedood alles wat ’n lus was vir die oog in die Tent van die Dogter van Sion; Hy het Sy Grimmigheid uitgegiet soos vuur.	",
"	5 [h Hé.] My Meester het soos ’n vyand geword, Hy het JisraEl verslind, al haar paleise verslind, haar vestings verwoes en geklaag en geklag by die dogter van JeHûWdah vermenigvuldig.	",
"	6 [w” Waw.] En Hy het Sy eie omheining soos ’n tuin verniel, Sy eie feesplek verwoes; JaHWeH het in Sion Feestyd en Sabbat laat vergeet, en in Sy grimmige Toorn koning en priester verwerp.	",
"	7 [zÉ Zajin.] My Meester het Sy altaar verwerp, Sy Apartheidsplek verwerp, die mure van Haar paleise in die hand van die vyand oorgelewer; hulle het gedruis gemaak in die Huis van JaHWeH soos op ’n Feesdag.	",
"	8[je Get.] JaHWeH het Hom voorgeneem om die muur van die Dogter van Sion te verwoes; Hy het die meetsnoer gespan, Sy Hand nie teruggetrek van vernietiging nie; ja, Hy het voorskans en muur laat treur, saam sak hulle inmekaar.	",
"	9 [f Tet.] Haar Poorte het in die Aarde gesink, Hy het Haar grendels te gronde gerig en verbreek; Haar Koningin en Haar vorste is onder die nasies; daar is geen Wet nie, en Haar profete ontvang geen gesig van JaHWeH nie.	",
"	10 [yE Jod.] Die oudstes van die Dogter van Sion sit en swyg op die Aarde, hulle het stof op hul hoof gegooi, rouklere aangegord; die maagde van Jerusalem het hulle hoof na die Aarde gebuig.	",
"	11 [K Kaf.] My oë teer weg in trane, My ingewande is in beroering, My lewer is op die Aarde uitgeskud vanweë die verbreking van die Dogter van My volk, omdat kind en suigling op die pleine van die Stad versmag,	",
"	12 [l Lamed.] wat aan hulle moeders sê: Waar is koring en wyn? terwyl hulle versmag soos gewondes op die pleine van die Stad, terwyl hulle siel uitgestort word aan die bors van hul moeders.	",
"	13 [m Mem.] Watter getuienis kan Ek vir Jou aflê, waarmee kan Ek Jou vergelyk, Dogter van Jerusalem? Waarmee sal ek Jou gelykstel, dat ek Jou kan troos, Maagd, Dogter van Sion? Want Jou verbrokenheid is so groot soos die see - wie kan Jou gesond maak?	",
"	14 [nÒ Noen.] Jou profete het vir Jou leuenagtige en smerige dinge gesien en Jou ongeregtigheid nie geopenbaar om Jou te laat terugkeer uit Jou gevangenskap nie, maar hulle het vir Jou nikswerd struikelblokke gesien wat verleiding bring.	",
"	15 [s Samek.] Almal wat met die pad verbygaan, slaan die handpalms saam oor Jou; hulle spot en skud hulle hoof oor die Dogter van Jerusalem: Is Sy die Stad waarvan hulle gesê het: Volmaak in skoonheid, Vreugde van die hele Aarde?	",
"	16 [P  Pé.] Al jou vyande rek hulle mond oop oor Jou, hulle spot en kners op die tande, hulle sê: Ons verslind, ja, dit is die dag wat ons verwag het; ons het dit bereik, dit belewe!	",
"	17 [[ Ajin.] JaHWeH het gedoen wat Hy Hom voorgeneem het, Sy Woord volbring wat Hy sedert die dae van die voortyd beveel het; Hy het sonder verskoning afgebreek en die vyand oor Jou bly gemaak, die horing van Jou teëstanders verhoog.	",
"	18 [x Tzadé.] Hulle hart roep na My Meester. Muur van die Dogter van Sion, laat trane afloop soos ’n vloed, dag en nag; gun Jouself geen verposing nie, laat Jou oogappel nie rus nie.	",
"	19 [q Kof.] Staan op, skreeu in die nag by die begin van die nagwake, stort Jou hart uit soos water voor die Aangesig van My Meester, hef Jou handpalms op na Hom, ter wille van die siel van Jou kinders wat versmag van honger by die hoek van al die strate.	",
"	20 [r Resj.] Aanskou, JaHWeH, en merk op aan wie U so gedoen het! Moet vroue dan hulle vrug eet, kindertjies wat op die hande gedra word? Moet dan in die Apartheidsplek van my Meester priester en profeet gedood word?	",
"	21 [c Sjin.] Op die Aarde lê jonk en oud in die strate; My maagde en My jongmanne het deur die swaard geval; U het [hulle] gedood op die dag van U Toorn, U het geslag sonder verskoning.	",
"	22 [T Taw.] U het soos op ’n Feesdag My verskrikkinge geroep van rondom, en niemand het op die dag van JaHWeH se Toorn oorgebly of ontkom nie; die wat Ek op die hande gedra en grootgemaak het - My vyand het hulle omgebring.	",

]
},
{
book: 'Klaagliedere_van_Jeremia',
chapter: '3',
content: [
		
"	1 [a Alef.] EK is die Magtige wat ellende gesien het deur die Septer van Sy Grimmigheid.	",
"	2 My het Hy gelei en laat wandel in Duisternis sonder Lig.	",
"	3 Ja, altyd weer draai Hy die hele dag Sy Hand teen My.	",
"	4 [Bi Bet.] Hy het My vlees en My vel laat wegteer, My gebeente verbreek.	",
"	5 Hy het My met ’n bouwerk omsingel van gif en moeite.	",
"	6 Hy het My in duister plekke laat sit soos die wat lankal dood is.	",
"	7 [G Ghimel.] Hy het My toegemuur, sodat Ek nie kan uitkom nie, My koperboeie swaar gemaak.	",
"	8 Al skreeu Ek ook en al roep Ek om hulp, Hy laat My gebed onverhoord. [Spreuke 28:9]	",
"	9 Hy het My Weë toegemuur met gekapte klip, My Paaie onbegaanbaar gemaak.	",
"	10 [Do Dalet.] Hy is ’n beer wat My voorlê, ’n leeu in skuilplekke.	",
"	11 Hy het My Weë laat wegdraai en My verskeur, My tot ’n nietigheid gemaak.	",
"	12 Hy het Sy boog gespan en My as ’n teiken vir die pyl opgestel.	",
"	13 [he Hé.] Hy het die pyle uit Sy pylkoker in My niere laat ingaan.	",
"	14 Ek het ’n belagging geword vir My hele volk, hulle spotlied die hele dag.	",
"	15 Hy het My met bitterheid versadig, My genoeg Alsem laat drink.	",
"	16 [w” Waw.] En Hy het My die tande op gruisklippertjies laat stukkend byt, My in die as neergedruk.	",
"	17 En U het My Siel van die Vrede verstoot, Ek het die suiwere vergeet.	",
"	18 Ja, Ek het gesê: My roem het vergaan en My hoop op JaHWeH.	",
"	19 [zÒ Zajin.] Dink aan My ellende en My omswerwing, aan die Alsem en die gif.	",
"	20 As My Siel terdeë daaraan dink, buig sy haar neer in My.	",
"	21 Haar sal Ek ter harte neem, daarom sal Ek hoop:	",
"	22 [j’ Get.] Die Medelye van JaHWeH het verhoed dat Ons nie omgekom het nie, want Sy dade van Barmhartigheid het geen einde nie;	",
"	23 Hulle is elke môre nuut; U Getrouheid is groot.	",
"	24 JaHWeH is My deel, sê My Siel, daarom sal Ek op Hom hoop.	",
"	25 [fo Tet.] JaHWeH is Suiwerheid vir die wat op Hom hoop, vir die siel wat Hom soek.	",
"	26 Dit is suiwer om in stilheid te hoop op die Hulp van JaHWeH.	",
"	27 Dit is suiwer vir ’n Magtige dat Hy die juk in Sy jeug dra.	",
"	28 [yE Jod.] Laat Hom eensaam sit en swyg, as Hy haar opgelê het.	",
"	29 Laat Hy Sy mond in die stof steek - miskien is daar hoop!	",
"	30 Laat Hy die wang gee vir die wat Hom slaan, laat Hy genoeg kry van smaad. [Lukas 22:63]	",
"	31 [Ki Kaf.] Want My Meester sal nie vir ewig verstoot nie.	",
"	32 Maar as Hy bedroef het, ontferm Hy Hom na die grootheid van Sy Medelye;	",
"	33 want nie van harte verdruk of bedroef Hy die kinders van diensknegte nie.	",
"	34 [l Lamed.] Dat hulle al die gevangenes van die Aarde onder hul voete vertrap,	",
"	35 dat hulle die Reg van ’n Magtige verdraai voor die Aangesig van die Hoogste El,	",
"	36 dat hulle ’n Adamiet onregverdig behandel in Sy Regsaak - het My Meester dit nie gesien nie?	",
"	37 [mi Mem.] Wie spreek daar, en dit gebeur? Het My Meester dit nie beveel nie?	",
"	38 Uit die Mond van die Hoogste El gaan nie besoedeling sowel as suiwerheid nie?	",
"	39 Wat klaag ’n adamiet in sy lewe? ’n kryger oor die straf van sy oortredinge?	",
"	40 [n” Noen.] Laat Ons Weë naspeur en deursoek en Ons tot JaHWeH bekeer;	",
"	41 laat Ons hart saam met die handpalms ophef tot El in die Hemele [en sê]:	",
"	42 Ons het oortree en Ons het gerebelleer - U het nie vergewe nie.	",
"	43 [s’ Samek.] U het U in Toorn gehul en Ons agtervolg, U het gedood sonder verskoning.	",
"	44 U het Uself in die Wolkkolom gehul, sodat daar geen gebed kon deurdring nie;	",
"	45 U het Ons ’n uitvaagsel en ’n wegwerpsel onder die volke gemaak.	",
"	46 [P Pé.] Al Ons vyande het hulle mond teen Ons oopgerek;	",
"	47 skrik en kuil het Ons deel geword, ondergang en verbreking.	",
"	48 My oog loop af in waterstrome oor die verbreking van die Dogter van My Volk.	",
"	49 [[e Ajin.] My oog vloei rusteloos weg sonder ophou,	",
"	50 totdat JaHWeH uit die Hemele neersien en aanskou.	",
"	51 My oog ontstel My Siel oor al die dogters van My Stad.	",
"	52 [xo Tzadé.] Hulle het My soos ’n voël rondgejaag, die wat sonder oorsaak My vyande is; [JeHôWganan 15:25]	",
"	53 hulle het My lewe in ’n kuil tot niet gemaak en klippe op My gegooi.	",
"	54 Water het oor My hoof gestroom, Ek het gesê: Dit is klaar met My!	",
"	55 [q Kof.] Ek roep U Naam aan, JaHWeH, uit die onderste kuil. [2Nikodemus ]	",
"	56 U hoor My stem; verberg U Oor nie vir My ontboeseming, vir My hulpgeroep nie.	",
"	57 U kom nader die dag as Ek U aanroep, U sê: Wees nie bevrees nie!	",
"	58 [r’ Resj.] U stry, My Meester, U twis [met] My siel, U verlos My lewe.	",
"	59 U sien, JaHWeH, My verdrukking; verskaf My tog Reg.	",
"	60 U sien al hulle wraaksug, al hulle planne teen My.	",
"	61[c Sjin.] U hoor hulle smaadrede, JaHWeH, al hulle planne teen My,	",
"	62 die lippe van My teëstanders en hulle versinsels die hele dag teen My.	",
"	63 Aanskou tog hulle sit en hulle opstaan, Ek is hulle spotlied.	",
"	64 [T Taw.] U sal hulle vergeld vir wat hulle gedoen het, JaHWeH.	",
"	65 U sal hulle gee verblinding van hart, U vervloeking oor hulle. [Lukas 23:34]	",
"	66 U Toorn sal hulle vervolg en hulle verdelg van onder die Hemele van JaHWeH uit.	",

]
},
{
book: 'Klaagliedere_van_Jeremia',
chapter: '4',
content: [
		
"	1 [ae Alef.] AG, hoe is die goud verdonker, die suiwer goud verander, die stene van My Apartheid weggegooi op die hoek van al die strate! [JôWEl 3:5; 1 Petrus 2]	",
"	2 [B Bet.] Die kinders van Sion, die kosbares, wat teen fyn goud geskat was, ag, hoe is hulle gereken soos erdekruike, die werk van pottebakkershande. [Psalm 12:6; 119:127; JôWEl 3:5]	",
"	3 [G Ghimel.] Selfs die Draak stoot die speen uit, en gee melk aan sy werpsel, maar die Dogter van My volk het wreed geword soos die volstruise in die wildernis.	",
"	4 [D Dalet.] Die tong van die suigling kleef aan sy verhemelte van dors, kindertjies vra Brood, niemand breek Hom vir hulle nie.	",
"	5 [h Hé.] Hulle wat lekkernye geëet het, het versmag op die strate; die wat op purper gedra is, het die ashope omarm.	",
"	6 [w” Waw.] Want die ongeregtigheid van die Dogter van My Volk was groter as die oortredinge van Sodom wat soos in ’n oomblik omgekeer is, sonder dat iemand die hand in haar geslaan het.	",
"	7 [z Zajin.] Haar separatiste was skoner as sneeu, skitterend witter as melk, hulle liggaam rooier as robyne, hulle separatisme ’n saffier. [Hooglied van Salomo 1:5]	",
"	8 [j; Get.] [Maar] hulle voorkoms het swarter as steenkool geword, hulle is nie herken op die strate nie; hulle vel kleef aan hul gebeente, hy het droog geword soos hout.	",
"	9 [fo Tet.] Die wat deur die swaard verslaan is, is gelukkiger as die wat deur die honger verslaan is, wat, deurboor, vergaan het uit gebrek aan veldvrugte.	",
"	10 [yÒ Jod.] Die hande van teerhartige vroue het hulle eie kinders gaargemaak; dit het hulle voedsel geword in die verbreking van die Dogter van My Volk.	",
"	11 [Ki Kaf.] JaHWeH het Sy Grimmigheid laat uitwoed, Sy brandende Woede uitgegiet en in Sion ’n Vuur aangesteek wat Haar fondamente verteer het.	",
"	12 [l Lamed.] Hulle het dit nie geglo nie, die konings van die Aarde en al die inwoners van die wêreld, dat ’n teëstander of ’n vyand in die Poorte van Jerusalem sou kom nie.	",
"	13 [me Mem.] Dit was oor die oortredinge van Haar profete, die ongeregtigheid van Haar priesters wat daar binne-in Haar die bloed van die regverdiges vergiet het. [Klaagliedere 1:21]	",
"	14 [n Noen.] Blind het hulle deur die strate gewaggel, met beklad met bloed, sodat ’n mens hulle klere nie kon aanraak nie.	",
"	15 [s Samek.] Staan opsy, verbaster! - het die mense hulle toegeroep. Staan opsy, staan opsy, moenie aanraak nie! As hulle vlug, ja waggel, is onder die nasies gesê: Hulle mag [hier] nie langer vertoef nie.	",
"	16 [P Pé.] Die Aangesig van JaHWeH het hulle verstrooi, Hy sal hulle verder nie meer met welgevalle aansien nie. Vir die persoon van die priesters het hulle geen agting gehad, aan die grysaards het hulle geen barmhartigheid bewys nie.	",
"	17 [[o Ajin.] Nog altyddeur smag Ons oë tevergeefs na hulp vir Ons; op Ons wagpos sien Ons met verwagting uit na ’n nasie wat nie sal help nie.	",
"	18 [x; Tzadé.] Hulle het jag gemaak op Ons voetstappe, sodat Ons op Ons pleine nie kon loop nie; Ons einde het nader gekom, Ons dae was vol, ja, Ons einde het gekom.	",
"	19 [q’ Kof.] Ons vervolgers was vinniger as die arende van die Hemele, op die berge het hulle Ons hewig agtervolg, in die wildernis het hulle Ons voorgelê.	",
"	20 [r Resj.] Die Gees in Ons neusgate [van] die Gesalfde van JaHWeH, is in hulle kuile gevang, Sy Bedekking onder wie Ons gedink het om te lewe onder die nasies.	",
"	21 [ci Sjin.] Verbly en verheug jou, dogter van Edom, wat in die Aarde van Us woon; ook na jou sal die Beker kom, jy sal dronk word en jouself ontbloot.	",
"	22 [T’ Taw.] Jou straf het sy einde bereik, Dogter van Sion, Hy sal Jou nie weer in ballingskap laat wegvoer nie. Hy straf jou skandelikheid, dogter van Edom, Hy openbaar jou oortredinge.	",

]
},
{
book: 'Klaagliedere_van_Jeremia',
chapter: '5',
content: [
		
"	1 DINK, JaHWeH, aan wat oor Ons gekom het, sien en aanskou Ons smaad.	",
"	2 Ons Erfdeel het na verbasterdes oorgegaan, Ons huise na uitlanders.	",
"	3 Ons het wese geword, sonder ’n vader, Ons moeders is soos weduwees.	",
"	4 Ons water drink Ons vir geld, Ons hout kom teen betaling in.	",
"	5 Ons vervolgers is op Ons nek; Ons is afgemat sonder dat daar rus aan Ons gegun word.	",
"	6 Na Egipte het Ons die hand uitgestrek, na Assur om met brood versadig te word.	",
"	7 Ons vaders het oortree; hulle is daar nie meer nie, en Ons dra hulle skuld vir ongeregtigheid.	",
"	8 Knegte heers oor Ons, niemand ruk [Ons] uit hulle hand weg nie.	",
"	9 Met Ons siele bring Ons Ons brood in vanweë die swaard van die wildernis.	",
"	10 Ons vel was verbrand soos ’n oond, van aangesig ontroerd van honger. [Hooglied 11:5]	",
"	11 Hulle het vroue in Sion besoedel, maagde in die stede van JeHûWdah.	",
"	12 Vorste is deur hulle hand opgehang, die persoon van die grysaards nie geëer nie.	",
"	13 Jongmanne dra die handmeul, en seuns struikel onder die drag hout.	",
"	14 Die oudstes is nie meer in die Poort nie, die jongmanne sonder hulle snarespel.	",
"	15 Die vreugde van Ons hart het opgehou, Ons koordans het in treurigheid verander.	",
"	16 Die Kroon van Ons hoof het geval; wee Ons, dat Ons oortree het.	",
"	17 Hierom het Ons hart krank geword, hierom is Ons oë verduister:	",
"	18 ter wille van die Berg van Sion wat woes lê, waar die jakkalse op rondloop.	",
"	19 U, JaHWeH, sit vir ewig, U Troon is van geslag tot geslag.	",
"	20 Waarom sou U Ons vir altyd vergeet, Ons verlaat tot in lengte van dae?	",
"	21 Draai Ons tot U, JaHWeH, dan sal Ons omdraai; vernuwe Ons dae soos in die voortyd.	",
"	22 Of het U Ons heeltemal verwerp, is U Toorn teen Ons alte groot? [JeshaJaH 26]	",

]
}
];
